obj = {
"	1	":{"character":"	リンリン感激パンダくんち！	","letter": "	Linlin's thrilled panda!	", "pinyin":"	りんりんかんげきぱんだくんち！	"},																			
"	2	":{"character":"	お花こちらでよろしいでしょうか	","letter": "	Flowers here, please.	", "pinyin":"	おはなこちらでよろしいでしょうか	"},																			
"	3	":{"character":"	ははいそれでお願いします	","letter": "	Yes, please!	", "pinyin":"	ははいそれでおねがいします	"},																			
"	4	":{"character":"	またいらしてくださいね	","letter": "	Please come again!	", "pinyin":"	またいらしてくださいね	"},																			
"	5	":{"character":"	はい！	","letter": "	Yes!	", "pinyin":"	はい！	"},																			
"	6	":{"character":"	かっこいいよね	","letter": "	He's so cool!	", "pinyin":"	かっこいいよね	"},																			
"	7	":{"character":"	パンダくん	","letter": "	Panda!	", "pinyin":"	ぱんだくん	"},																			
"	8	":{"character":"	バイトお疲れはいこれ	","letter": "	Good job!	", "pinyin":"	ばいとおつかれはいこれ	"},																			
"	9	":{"character":"	まぁもらっておくけど	","letter": "	I'll take it.	", "pinyin":"	まぁもらっておくけど	"},																			
"	10	":{"character":"	そんじゃお疲れ	","letter": "	Well, good night.	", "pinyin":"	そんじゃおつかれ	"},																			
"	11	":{"character":"	パンダくんつれないな	","letter": "	Panda, you're so boring.	", "pinyin":"	ぱんだくんつれないな	"},																			
"	12	":{"character":"	あ～パンダくん仲よくなりたいのに	","letter": "	I want to be friends with you, Panda.	", "pinyin":"	あ～ぱんだくんなかよくなりたいのに	"},																			
"	13	":{"character":"	大丈夫きっと仲よくなれるよ	","letter": "	Don't worry, I'm sure we'll get along.	", "pinyin":"	だいじょうぶきっとなかよくなれるよ	"},																			
"	14	":{"character":"	そうだよね	","letter": "	I'm sure we will.	", "pinyin":"	そうだよね	"},																			
"	15	":{"character":"	もちろんさ	","letter": "	Of course we will.	", "pinyin":"	もちろんさ	"},																			
"	16	":{"character":"	パンダ最高！	","letter": "	I love pandas!	", "pinyin":"	ぱんださいこう！	"},																			
"	17	":{"character":"	はいフローリストリンリンです	","letter": "	Yes, I'm Florist Lynn Lynn.	", "pinyin":"	はいふろーりすとりんりんです	"},																			
"	18	":{"character":"	竹をメインにしたアレンジですか	","letter": "	You want to use bamboo as the main element of the arrangement?	", "pinyin":"	たけをめいんにしたあれんじですか	"},																			
"	19	":{"character":"	はいできますよ	","letter": "	Yes, we can do that.	", "pinyin":"	はいできますよ	"},																			
"	20	":{"character":"	でお届けはどちらまで	","letter": "	And where do you deliver it?	", "pinyin":"	でおとどけはどちらまで	"},																			
"	21	":{"character":"	リンリンてさ困った人だよね	","letter": "	You're a real pain in the ass, Ling Ling Ling, aren't you?	", "pinyin":"	りんりんてさこまったひとだよね	"},																			
"	22	":{"character":"	リンリンて	","letter": "	Ling Ling...	", "pinyin":"	りんりんて	"},																			
"	23	":{"character":"	花屋さんの	","letter": "	The florist.	", "pinyin":"	はなやさんの	"},																			
"	24	":{"character":"	そう僕が通りかかるたびにさ	","letter": "	Yeah, every time I pass by.	", "pinyin":"	そうぼくがとおりかかるたびにさ	"},																			
"	25	":{"character":"	あげる	","letter": "	I give them to you.	", "pinyin":"	あげる	"},																			
"	26	":{"character":"	好きでしょ	","letter": "	You like it, don't you?	", "pinyin":"	すきでしょ	"},																			
"	27	":{"character":"	パンダってかわいいよね	","letter": "	Pandas are cute.	", "pinyin":"	ぱんだってかわいいよね	"},																			
"	28	":{"character":"	いい人じゃない	","letter": "	He's a nice guy.	", "pinyin":"	いいひとじゃない	"},																			
"	29	":{"character":"	あれ？でもでも	","letter": "	What's that? But...	", "pinyin":"	あれ？でもでも	"},																			
"	30	":{"character":"	くれるパンダグッズだって趣味悪いし	","letter": "	Even the panda stuff they give you is in poor taste.	", "pinyin":"	くれるぱんだぐっずだってしゅみわるいし	"},																			
"	31	":{"character":"	こんなのとか	","letter": "	Like this.	", "pinyin":"	こんなのとか	"},																			
"	32	":{"character":"	わ～かわいい！	","letter": "	It's so cute!	", "pinyin":"	わ～かわいい！	"},																			
"	33	":{"character":"	え～そうかな	","letter": "	I wonder if it is...	", "pinyin":"	え～そうかな	"},																			
"	34	":{"character":"	じゃあ笹子さんにあげれば	","letter": "	Then give it to Sasako.	", "pinyin":"	じゃあささごさんにあげれば	"},																			
"	35	":{"character":"	あげないよ	","letter": "	I won't give it to her.	", "pinyin":"	あげないよ	"},																			
"	36	":{"character":"	気に入ってるじゃない	","letter": "	She likes it.	", "pinyin":"	きにいってるじゃない	"},																			
"	37	":{"character":"	リンリンてホント困った人だから	","letter": "	You're such a pain in the ass.	", "pinyin":"	りんりんてほんとこまったひとだから	"},																			
"	38	":{"character":"	今頃パンダくんの家に行ってたりして	","letter": "	She's probably at Panda's right now.	", "pinyin":"	いまごろぱんだくんのいえにいってたりして	"},																			
"	39	":{"character":"	やめてよ	","letter": "	Stop it.	", "pinyin":"	やめてよ	"},																			
"	40	":{"character":"	パンダくんちだよ	","letter": "	I'm at Panda's house.	", "pinyin":"	ぱんだくんちだよ	"},																			
"	41	":{"character":"	お花をお届けにあがりました	","letter": "	I'm here to deliver flowers.	", "pinyin":"	おはなをおとどけにあがりました	"},																			
"	42	":{"character":"	パンダくんは…	","letter": "	Where's Panda?	", "pinyin":"	ぱんだくんは…	"},																			
"	43	":{"character":"	この時間はしろくまカフェかな	","letter": "	I wonder if he's at the Shirokuma Cafe this time of night.	", "pinyin":"	このじかんはしろくまかふぇかな	"},																			
"	44	":{"character":"	どうもご苦労様です	","letter": "	Thank you very much.	", "pinyin":"	どうもごくろうさまです	"},																			
"	45	":{"character":"	どうしました？	","letter": "	What's up?	", "pinyin":"	どうしました？	"},																			
"	46	":{"character":"	パンダだパンダママだ	","letter": "	It's a panda.	", "pinyin":"	ぱんだだぱんだままだ	"},																			
"	47	":{"character":"	あねぇ	","letter": "	Hey, there.	", "pinyin":"	あねぇ	"},																			
"	48	":{"character":"	はい	","letter": "	Yes, ma'am.	", "pinyin":"	はい	"},																			
"	49	":{"character":"	お代は別に払うから部屋の竹も活け直してもらえないかしら	","letter": "	I'll pay you separately, but I'd like you to rearrange the bamboo in my room.	", "pinyin":"	おだいはべつにはらうからへやのたけもいけなおしてもらえないかしら	"},																			
"	50	":{"character":"	お家に上がっていいんですか！	","letter": "	Can I come in?	", "pinyin":"	おうちにあがっていいんですか！	"},																			
"	51	":{"character":"	リンリンのパンダ好きは相当なものらしいよ	","letter": "	I heard Linlin's love for pandas is considerable.	", "pinyin":"	りんりんのぱんだずきはそうとうなものらしいよ	"},																			
"	52	":{"character":"	パンダグッズもかなり集めてるそうですよ	","letter": "	I hear he collects a lot of panda goods.	", "pinyin":"	ぱんだぐっずもかなりあつめてるそうですよ	"},																			
"	53	":{"character":"	花屋じゃなくてパンダグッズ屋やればよかったのに	","letter": "	You should've opened a panda goods shop instead of a flower shop.	", "pinyin":"	はなやじゃなくてぱんだぐっずややればよかったのに	"},																			
"	54	":{"character":"	事情があるんだよ	","letter": "	I have my reasons.	", "pinyin":"	じじょうがあるんだよ	"},																			
"	55	":{"character":"	どんな？	","letter": "	What kind?	", "pinyin":"	どんな？	"},																			
"	56	":{"character":"	若き日のリンリンがパンダグッズを集めるため世界を旅していた頃	","letter": "	When the young Linlin was traveling the world to collect panda goods.	", "pinyin":"	わかきひのりんりんがぱんだぐっずをあつめるためせかいをたびしていたころ	"},																			
"	57	":{"character":"	とある事件に巻き込まれ…	","letter": "	He got caught up in an incident...	", "pinyin":"	とあるじけんにまきこまれ…	"},																			
"	58	":{"character":"	嘘ですね	","letter": "	You're lying.	", "pinyin":"	うそですね	"},																			
"	59	":{"character":"	うん	","letter": "	Yes, it is.	", "pinyin":"	うん	"},																			
"	60	":{"character":"	何で嘘つくの？	","letter": "	Why are you lying?	", "pinyin":"	なんでうそつくの？	"},																			
"	61	":{"character":"	ささやかな嘘であなたの味気ない日常に彩りを	","letter": "	A little lie to add a little color to your dull life.	", "pinyin":"	ささやかなうそであなたのあじけないにちじょうにいろどりを	"},																			
"	62	":{"character":"	味気ない日常で悪かったね	","letter": "	I'm sorry it's so boring.	", "pinyin":"	あじけないにちじょうでわるかったね	"},																			
"	63	":{"character":"	もうリンリンの話はいいよ	","letter": "	Enough with the 'Lynn Lynn' talk.	", "pinyin":"	もうりんりんのはなしはいいよ	"},																			
"	64	":{"character":"	よしいかがです？	","letter": "	Okay, how do you like it?	", "pinyin":"	よしいかがです？	"},																			
"	65	":{"character":"	まぁステキ！	","letter": "	Oh, my God, it's beautiful!	", "pinyin":"	まぁすてき！	"},																			
"	66	":{"character":"	今お代を払うわ	","letter": "	I'll pay for it.	", "pinyin":"	いまおだいをはらうわ	"},																			
"	67	":{"character":"	ちょっと待っててね	","letter": "	I'll be back in a minute.	", "pinyin":"	ちょっとまっててね	"},																			
"	68	":{"character":"	ここでパンダくんが暮らしているんだな	","letter": "	So this is where Mr. Panda lives.	", "pinyin":"	ここでぱんだくんがくらしているんだな	"},																			
"	69	":{"character":"	かわいい	","letter": "	Cute.	", "pinyin":"	かわいい	"},																			
"	70	":{"character":"	こんにちは	","letter": "	Hello, there.	", "pinyin":"	こんにちは	"},																			
"	71	":{"character":"	ママがお茶どうぞって	","letter": "	Mommy says have some tea.	", "pinyin":"	ままがおちゃどうぞって	"},																			
"	72	":{"character":"	パンダだパンダ妹だ	","letter": "	A panda... a panda sister.	", "pinyin":"	ぱんだだぱんだいもうとだ	"},																			
"	73	":{"character":"	ここに置いとくね	","letter": "	I'll just leave it here.	", "pinyin":"	ここにおいとくね	"},																			
"	74	":{"character":"	ありがとう…えっと…	","letter": "	Thank you for... um...	", "pinyin":"	ありがとう…えっと…	"},																			
"	75	":{"character":"	メイメイって呼んで	","letter": "	Call me Mei Mei.	", "pinyin":"	めいめいってよんで	"},																			
"	76	":{"character":"	あなたリンリンでしょ？	","letter": "	You're Ling Ling, right?	", "pinyin":"	あなたりんりんでしょ？	"},																			
"	77	":{"character":"	僕のこと知ってるんだ？	","letter": "	You know who I am?	", "pinyin":"	ぼくのことしってるんだ？	"},																			
"	78	":{"character":"	イケメン花屋って街じゃ有名よ	","letter": "	You're famous in town for being a good-looking florist.	", "pinyin":"	いけめんはなやってまちじゃゆうめいよ	"},																			
"	79	":{"character":"	そうらしいね	","letter": "	So I've heard.	", "pinyin":"	そうらしいね	"},																			
"	80	":{"character":"	否定しないのね…	","letter": "	You don't deny it.	", "pinyin":"	ひていしないのね…	"},																			
"	81	":{"character":"	でも…私の好みじゃないわね	","letter": "	But... you're not my type.	", "pinyin":"	でも…わたしのこのみじゃないわね	"},																			
"	82	":{"character":"	ちょっと痩せすぎ	","letter": "	You're a little too skinny.	", "pinyin":"	ちょっとやせすぎ	"},																			
"	83	":{"character":"	まあいいわちょっと遊んであげる	","letter": "	Well, I don't care. I'm going to play with you.	", "pinyin":"	まあいいわちょっとあそんであげる	"},																			
"	84	":{"character":"	鬼ごっこね	","letter": "	Tag.	", "pinyin":"	おにごっこね	"},																			
"	85	":{"character":"	ああごめんお店があるから帰らないと	","letter": "	Oh, sorry, I have to go back to the store.	", "pinyin":"	ああごめんおみせがあるからかえらないと	"},																			
"	86	":{"character":"	リンリンさんお待たせ	","letter": "	Hey, Ling Ling.	", "pinyin":"	りんりんさんおまたせ	"},																			
"	87	":{"character":"	あら？	","letter": "	Hey, what's up?	", "pinyin":"	あら？	"},																			
"	88	":{"character":"	待て！	","letter": "	Wait!	", "pinyin":"	まて！	"},																			
"	89	":{"character":"	パンダを追いかける…	","letter": "	Chasing pandas...	", "pinyin":"	ぱんだをおいかける…	"},																			
"	90	":{"character":"	パンダと回る…	","letter": "	Spinning with the panda...	", "pinyin":"	ぱんだとまわる…	"},																			
"	91	":{"character":"	パンダと転がる…	","letter": "	Rolling with the panda...	", "pinyin":"	ぱんだところがる…	"},																			
"	92	":{"character":"	なんて幸せな時間なんだ…	","letter": "	What a happy time...	", "pinyin":"	なんてしあわせなじかんなんだ…	"},																			
"	93	":{"character":"	次はかくれんぼね	","letter": "	Hide and seek...	", "pinyin":"	つぎはかくれんぼね	"},																			
"	94	":{"character":"	パンダとかくれんぼ…	","letter": "	Hide and seek with panda...	", "pinyin":"	ぱんだとかくれんぼ…	"},																			
"	95	":{"character":"	１２…	","letter": "	12...	", "pinyin":"	１２…	"},																			
"	96	":{"character":"	リンリンさん案外タフね	","letter": "	You're tougher than I thought, Linlin.	", "pinyin":"	りんりんさんあんがいたふね	"},																			
"	97	":{"character":"	お～いどこだい？	","letter": "	Hey, where are you?	", "pinyin":"	お～いどこだい？	"},																			
"	98	":{"character":"	店に戻らないで遊んでていいのか？	","letter": "	You sure you don't want to go back to the store?	", "pinyin":"	みせにもどらないであそんでていいのか？	"},																			
"	99	":{"character":"	いい！	","letter": "	No, I'm a panda!	", "pinyin":"	いい！	"},																			
"	100	":{"character":"	だってパンダなんだも～ん！	","letter": "	Because I'm a panda!	", "pinyin":"	だってぱんだなんだも～ん！	"},																			
"	101	":{"character":"	見つけた！	","letter": "	I found it!	", "pinyin":"	みつけた！	"},																			
"	102	":{"character":"	何奴？	","letter": "	What is it?	", "pinyin":"	どいつ？	"},																			
"	103	":{"character":"	どうしたの？	","letter": "	What's going on?	", "pinyin":"	どうしたの？	"},																			
"	104	":{"character":"	あっお爺ちゃん何やってるの？	","letter": "	Oh, Grandpa, what are you doing?	", "pinyin":"	あっおじいちゃんなにやってるの？	"},																			
"	105	":{"character":"	お爺ちゃん？	","letter": "	Grandpa?	", "pinyin":"	おじいちゃん？	"},																			
"	106	":{"character":"	曲者め	","letter": "	You're a wacko.	", "pinyin":"	くせものめ	"},																			
"	107	":{"character":"	違うわよリンリンはお花屋さんよ	","letter": "	No, no, no, Linlin's a florist.	", "pinyin":"	ちがうわよりんりんはおはなやさんよ	"},																			
"	108	":{"character":"	ニチニチコレコーニチ…	","letter": "	Nich nich nich nich kollektich...	", "pinyin":"	にちにちこれこーにち…	"},																			
"	109	":{"character":"	ジョージョーシャクリョーセーコートーテー…	","letter": "	Joe Joe Shakuryo sei kootei...	", "pinyin":"	じょーじょーしゃくりょーせーこーとーてー…	"},																			
"	110	":{"character":"	都合が悪くなるとすぐとぼけるんだから	","letter": "	You're always blurting it out when things go wrong.	", "pinyin":"	つごうがわるくなるとすぐとぼけるんだから	"},																			
"	111	":{"character":"	アオゾラチューシャ…	","letter": "	Aozora Chucha...	", "pinyin":"	あおぞらちゅーしゃ…	"},																			
"	112	":{"character":"	パンダ…だ…	","letter": "	Panda...	", "pinyin":"	ぱんだ…だ…	"},																			
"	113	":{"character":"	パンダお爺ちゃんの太極拳…だ…	","letter": "	Grandpa Panda's tai chi...	", "pinyin":"	ぱんだおじいちゃんのたいきょくけん…だ…	"},																			
"	114	":{"character":"	というわけで	","letter": "	So...	", "pinyin":"	というわけで	"},																			
"	115	":{"character":"	彼はパンダグッズ屋ではなく	","letter": "	He is not a panda goods shop	", "pinyin":"	かれはぱんだぐっずやではなく	"},																			
"	116	":{"character":"	花屋を営むこととなりました	","letter": "	He is now a florist...	", "pinyin":"	はなやをいとなむこととなりました	"},																			
"	117	":{"character":"	悲しすぎる…	","letter": "	Too sad...	", "pinyin":"	かなしすぎる…	"},																			
"	118	":{"character":"	ホラ話とわかってても涙が止まらない…	","letter": "	I can't stop crying even though I know it's just a tall tale...	", "pinyin":"	ほらはなしとわかっててもなみだがとまらない…	"},																			
"	119	":{"character":"	思わずリンリンに優しくしちゃいそうだよ	","letter": "	I can't help but be nice to Linlin	", "pinyin":"	おもわずりんりんにやさしくしちゃいそうだよ	"},																			
"	120	":{"character":"	事情があるんだよ	","letter": "	There's a reason.	", "pinyin":"	じじょうがあるんだよ	"},																			
"	121	":{"character":"	それはあの眩しくも世知辛い国でのことだった	","letter": "	It was in that dazzling but bitter country...	", "pinyin":"	それはあのまぶしくもせちがらいくにでのことだった	"},																			
"	122	":{"character":"	いやさすがにもういい	","letter": "	No, that's enough.	", "pinyin":"	いやさすがにもういい	"},																			
"	123	":{"character":"	あっ…あれ？ここは…	","letter": "	Ah...what is it? This place is...	", "pinyin":"	あっ…あれ？ここは…	"},																			
"	124	":{"character":"	イテテ…あっそうか	","letter": "	I see...	", "pinyin":"	いてて…あっそうか	"},																			
"	125	":{"character":"	パンダくんちに配達に来てそれで…	","letter": "	I came to Panda's house to make a delivery...	", "pinyin":"	ぱんだくんちにはいたつにきてそれで…	"},																			
"	126	":{"character":"	まいったな…早く店に帰らなきゃ	","letter": "	I've got to get back to the store.	", "pinyin":"	まいったな…はやくみせにかえらなきゃ	"},																			
"	127	":{"character":"	こ…これはパンダくんの…	","letter": "	This is Panda's...	", "pinyin":"	こ…これはぱんだくんの…	"},																			
"	128	":{"character":"	もしかしてこの部屋は…	","letter": "	Could this be...	", "pinyin":"	もしかしてこのへやは…	"},																			
"	129	":{"character":"	パンダくんの部屋？	","letter": "	Panda's room?	", "pinyin":"	ぱんだくんのへや？	"},																			
"	130	":{"character":"	パンダくんのベッド…パンダくんのパンダクッション	","letter": "	Panda-kun's bed... panda cushion...	", "pinyin":"	ぱんだくんのべっど…ぱんだくんのぱんだくっしょん	"},																			
"	131	":{"character":"	パンダくんのパンダスリッパ！パンダくんのシール…	","letter": "	Panda-kun's panda slippers! Panda-kun's stickers...	", "pinyin":"	ぱんだくんのぱんだすりっぱ！ぱんだくんのしーる…	"},																			
"	132	":{"character":"	あっ…これ僕があげたプレゼント	","letter": "	Oh... this is the present I gave you.	", "pinyin":"	あっ…これぼくがあげたぷれぜんと	"},																			
"	133	":{"character":"	なんだよ…大事にしてくれてるじゃん	","letter": "	What... you're taking good care of it.	", "pinyin":"	なんだよ…だいじにしてくれてるじゃん	"},																			
"	134	":{"character":"	うぉ～！仔パンダ！！	","letter": "	Wow~! A little panda!	", "pinyin":"	うぉ～！こぱんだ！！	"},																			
"	135	":{"character":"	うぉ～！超かわいい！！	","letter": "	Wow~! It's so cute!	", "pinyin":"	うぉ～！ちょうかわいい！！	"},																			
"	136	":{"character":"	さ…触りたい	","letter": "	I want to touch it.	", "pinyin":"	さ…さわりたい	"},																			
"	137	":{"character":"	ダメだよそれは観賞用だよ	","letter": "	No, no, no, that's just for show.	", "pinyin":"	だめだよそれはかんしょうようだよ	"},																			
"	138	":{"character":"	くれるの？	","letter": "	Can I have it?	", "pinyin":"	くれるの？	"},																			
"	139	":{"character":"	かわいい！	","letter": "	So cute!	", "pinyin":"	かわいい！	"},																			
"	140	":{"character":"	お目覚め？ごめんなさいね	","letter": "	Are you awake? I'm sorry.	", "pinyin":"	おめざめ？ごめんなさいね	"},																			
"	141	":{"character":"	うちのお爺ちゃんが…あら？	","letter": "	My grandpa... oh?	", "pinyin":"	うちのおじいちゃんが…あら？	"},																			
"	142	":{"character":"	ありがとう！おいしいな	","letter": "	Oh, thank you! This is delicious.	", "pinyin":"	ありがとう！おいしいな	"},																			
"	143	":{"character":"	リンリン！？それ観賞用よ	","letter": "	Ling Ling! That's just for decoration.	", "pinyin":"	りんりん！？それかんしょうようよ	"},																			
"	144	":{"character":"	っていうか笹食べるの？	","letter": "	I mean, do you eat the bamboos?	", "pinyin":"	っていうかささたべるの？	"},																			
"	145	":{"character":"	えぇ状況しだいでは	","letter": "	Yes, depending on the situation.	", "pinyin":"	えぇじょうきょうしだいでは	"},																			
"	146	":{"character":"	まぁ止めないけど…	","letter": "	Well, I won't stop you.	", "pinyin":"	まぁとめないけど…	"},																			
"	147	":{"character":"	あの…お花代まだお支払いしてなかったでしょ？	","letter": "	I mean... you haven't paid for the flowers yet, have you?	", "pinyin":"	あの…おはなだいまだおしはらいしてなかったでしょ？	"},																			
"	148	":{"character":"	お代はいらないので仔パンダ抱っこさせてください！	","letter": "	I don't want to pay for the flowers, just let me hold the panda cub.	", "pinyin":"	おだいはいらないのでこぱんだだっこさせてください！	"},																			
"	149	":{"character":"	いいけど…	","letter": "	Okay, but...	", "pinyin":"	いいけど…	"},																			
"	150	":{"character":"	ちゃんと払うわよ	","letter": "	I'll pay you.	", "pinyin":"	ちゃんとはらうわよ	"},																			
"	151	":{"character":"	あら…ごめんなさい	","letter": "	Oh, I'm sorry.	", "pinyin":"	あら…ごめんなさい	"},																			
"	152	":{"character":"	うちの子人見知りで…	","letter": "	My baby is shy.	", "pinyin":"	うちのこひとみしりで…	"},																			
"	153	":{"character":"	幸せです！	","letter": "	I'm so happy.	", "pinyin":"	しあわせです！	"},																			
"	154	":{"character":"	お花こちらでよろしいでしょうか？	","letter": "	May I have the flowers here?	", "pinyin":"	おはなこちらでよろしいでしょうか？	"},																			
"	155	":{"character":"	厘太郎さんどうしたのかしら？	","letter": "	Rintaro, what's wrong?	", "pinyin":"	りんたろうさんどうしたのかしら？	"},																			
"	156	":{"character":"	傷だらけね	","letter": "	You're all scratched up.	", "pinyin":"	きずだらけね	"},																			
"	157	":{"character":"	パンダママさんや妹ちゃんとは仲よくなれたんだ	","letter": "	He got along well with his mommy and sister.	", "pinyin":"	ぱんだままさんやいもうとちゃんとはなかよくなれたんだ	"},																			
"	158	":{"character":"	今度はパンダお爺ちゃんと仔パンダちゃんたち…	","letter": "	And now Grandpa Panda and the little pandas...	", "pinyin":"	こんどはぱんだおじいちゃんとこぱんだちゃんたち…	"},																			
"	159	":{"character":"	そしていずれは…	","letter": "	And eventually...	", "pinyin":"	そしていずれは…	"},																			
"	160	":{"character":"	ねぇねぇ半田さん	","letter": "	Hey, hey, Mr. Handa.	", "pinyin":"	ねぇねぇはんでんさん	"},																			
"	161	":{"character":"	今日帰りにさ…	","letter": "	I was just on my way home today...	", "pinyin":"	きょうかえりにさ…	"},																			
"	162	":{"character":"	今日はダメ！用事あるの	","letter": "	Not today! I have something to do.	", "pinyin":"	きょうはだめ！ようじあるの	"},																			
"	163	":{"character":"	ちょっとくらいいいじゃん	","letter": "	Why don't you come over for a bit?	", "pinyin":"	ちょっとくらいいいじゃん	"},																			
"	164	":{"character":"	彼女もいないし暇でしょ？	","letter": "	You don't have a girlfriend and you're not busy.	", "pinyin":"	かのじょもいないしひまでしょ？	"},																			
"	165	":{"character":"	もう…パンダくんより女の子に追いかけられたいよ	","letter": "	I'd rather be chased by a girl than a panda.	", "pinyin":"	もう…ぱんだくんよりおんなのこにおいかけられたいよ	"},																			
"	166	":{"character":"	あ～っ！ひどい	","letter": "	Oh, no! That's terrible.	", "pinyin":"	あ～っ！ひどい	"},																			
"	167	":{"character":"	パンダくんよりだと！？	","letter": "	More than a panda?	", "pinyin":"	ぱんだくんよりだと！？	"},																			
"	168	":{"character":"	うらやましい！	","letter": "	I'm jealous!	", "pinyin":"	うらやましい！	"},																			
"	169	":{"character":"	何か視線を感じるんだけど…	","letter": "	I can feel her eyes on me...	", "pinyin":"	なにかしせんをかんじるんだけど…	"},																			
"	170	":{"character":"	そう？	","letter": "	Yeah?	", "pinyin":"	そう？	"},																			
"	171	":{"character":"	ペンギンさんの告白	","letter": "	Penguin's confession.	", "pinyin":"	ぺんぎんさんのこくはく	"},																			
"	172	":{"character":"	クロワッサンもいけるね	","letter": "	Croissants would work too.	", "pinyin":"	くろわっさんもいけるね	"},																			
"	173	":{"character":"	これに竹の葉を練りこんだらもっとおいしくなるんじゃない？	","letter": "	Wouldn't it taste even better if you kneaded bamboo leaves into this?	", "pinyin":"	これにたけのはをねりこんだらもっとおいしくなるんじゃない？	"},																			
"	174	":{"character":"	それはどうかな？	","letter": "	I don't know about that.	", "pinyin":"	それはどうかな？	"},																			
"	175	":{"character":"	それよりパンダあんぱんっていうのがあるみたいだよ	","letter": "	I heard there's something called panda anpan.	", "pinyin":"	それよりぱんだあんぱんっていうのがあるみたいだよ	"},																			
"	176	":{"character":"	本当？	","letter": "	Really?	", "pinyin":"	ほんとう？	"},																			
"	177	":{"character":"	ねぇペンギンさん次はそのパンダあんぱんを…	","letter": "	Hey, Penguin, can we try the Panda Anpan next time?	", "pinyin":"	ねぇぺんぎんさんつぎはそのぱんだあんぱんを…	"},																			
"	178	":{"character":"	あぁもう…	","letter": "	Oh, no...	", "pinyin":"	あぁもう…	"},																			
"	179	":{"character":"	僕は別にパンを買うためにパン屋さんに行ってるわけじゃないんだよ！	","letter": "	I don't go to the bakery to buy bread!	", "pinyin":"	ぼくはべつにぱんをかうためにぱんやさんにいってるわけじゃないんだよ！	"},																			
"	180	":{"character":"	ペン子さんを…その…	","letter": "	I want to ask Penko-san out on a...	", "pinyin":"	ぺんごさんを…その…	"},																			
"	181	":{"character":"	デートに誘いたいんだよ…	","letter": "	I want to ask her out on a date...	", "pinyin":"	でーとにさそいたいんだよ…	"},																			
"	182	":{"character":"	知ってるよそんなの	","letter": "	I know that.	", "pinyin":"	しってるよそんなの	"},																			
"	183	":{"character":"	でも結局いつもパンを買って帰ってくるだけじゃない	","letter": "	But you always end up just buying bread	", "pinyin":"	でもけっきょくいつもぱんをかってかえってくるだけじゃない	"},																			
"	184	":{"character":"	だって…	","letter": "	Because...	", "pinyin":"	だって…	"},																			
"	185	":{"character":"	いっそ告白しちゃったらどうです？	","letter": "	Why don't you just confess your feelings to her?	", "pinyin":"	いっそこくはくしちゃったらどうです？	"},																			
"	186	":{"character":"	そ…そんな！	","letter": "	Oh, no!	", "pinyin":"	そ…そんな！	"},																			
"	187	":{"character":"	小さな１歩を恐れるときは	","letter": "	When you're afraid to take a small step	", "pinyin":"	ちいさな１ほをおそれるときは	"},																			
"	188	":{"character":"	大きな１歩を踏み出すときである	","letter": "	It's time to take a big step forward.	", "pinyin":"	おおきな１ほをふみだすときである	"},																			
"	189	":{"character":"	フランスの古い格言だよ	","letter": "	It's an old French saying.	", "pinyin":"	ふらんすのふるいかくげんだよ	"},																			
"	190	":{"character":"	大きな１歩を踏み出すとき…	","letter": "	When you take the first big step...	", "pinyin":"	おおきな１ほをふみだすとき…	"},																			
"	191	":{"character":"	ウソだけど	","letter": "	That's a lie.	", "pinyin":"	うそだけど	"},																			
"	192	":{"character":"	小さな１歩	","letter": "	One small step.	", "pinyin":"	ちいさな１ほ	"},																			
"	193	":{"character":"	大きな１歩…	","letter": "	One big step...	", "pinyin":"	おおきな１ほ…	"},																			
"	194	":{"character":"	決めた！僕はやるよ	","letter": "	I've made up my mind! I'm gonna do it.	", "pinyin":"	きめた！ぼくはやるよ	"},																			
"	195	":{"character":"	やるってまさか…	","letter": "	You don't mean...	", "pinyin":"	やるってまさか…	"},																			
"	196	":{"character":"	ペン子さんに告白する！	","letter": "	I'm going to confess to Penko-san!	", "pinyin":"	ぺんごさんにこくはくする！	"},																			
"	197	":{"character":"	告白？	","letter": "	Confess?	", "pinyin":"	こくはく？	"},																			
"	198	":{"character":"	ごめん！今の僕はダジャレにつきあってる暇はないの	","letter": "	Sorry! I don't have time for puns right now.	", "pinyin":"	ごめん！いまのぼくはだじゃれにつきあってるひまはないの	"},																			
"	199	":{"character":"	早速行ってくるよ！	","letter": "	I'll be right there!	", "pinyin":"	さっそくいってくるよ！	"},																			
"	200	":{"character":"	行っちゃった…	","letter": "	He's gone...	", "pinyin":"	いっちゃった…	"},																			
"	201	":{"character":"	ヒャッハー！	","letter": "	Hooray!	", "pinyin":"	ひゃっはー！	"},																			
"	202	":{"character":"	それは極悪？	","letter": "	That's evil?	", "pinyin":"	それはごくあく？	"},																			
"	203	":{"character":"	でもどうやって言おう？	","letter": "	But how do I say it?	", "pinyin":"	でもどうやっていおう？	"},																			
"	204	":{"character":"	ノープランなの？	","letter": "	You have no plan?	", "pinyin":"	のーぷらんなの？	"},																			
"	205	":{"character":"	当たり前でしょ！	","letter": "	Of course not!	", "pinyin":"	あたりまえでしょ！	"},																			
"	206	":{"character":"	さっき思い立ったんだから	","letter": "	It just came to me a while ago.	", "pinyin":"	さっきおもいたったんだから	"},																			
"	207	":{"character":"	どうしたらいいかな？	","letter": "	What should I do?	", "pinyin":"	どうしたらいいかな？	"},																			
"	208	":{"character":"	例えばクジャクは羽を広げて愛の告白をするよね	","letter": "	For example, peacocks spread their wings to confess their love, right?	", "pinyin":"	たとえばくじゃくははねをひろげてあいのこくはくをするよね	"},																			
"	209	":{"character":"	なるほど！	","letter": "	I see!	", "pinyin":"	なるほど！	"},																			
"	210	":{"character":"	こんな感じ？	","letter": "	Like this?	", "pinyin":"	こんなかんじ？	"},																			
"	211	":{"character":"	地味だね	","letter": "	That's plain.	", "pinyin":"	じみだね	"},																			
"	212	":{"character":"	じゃあ…他には！？	","letter": "	Then... what else?	", "pinyin":"	じゃあ…ほかには！？	"},																			
"	213	":{"character":"	グンカンドリは赤いノド袋を膨らますらしいよ	","letter": "	I heard that the Ginkandori inflates its red throat pouch.	", "pinyin":"	ぐんかんどりはあかいのどぶくろをふくらますらしいよ	"},																			
"	214	":{"character":"	あんまり変わりませんね	","letter": "	It doesn't look much different.	", "pinyin":"	あんまりかわりませんね	"},																			
"	215	":{"character":"	もっと膨らまないの？	","letter": "	Can't it be inflated more?	", "pinyin":"	もっとふくらまないの？	"},																			
"	216	":{"character":"	リクガメは甲羅アタック噛みつきマウントだよ	","letter": "	The tortoise is a shell-attacking, biting mount.	", "pinyin":"	りくがめはこうらあたっくかみつきまうんとだよ	"},																			
"	217	":{"character":"	え～プロレス？	","letter": "	Wrestling?	", "pinyin":"	え～ぷろれす？	"},																			
"	218	":{"character":"	噛みつきは反則じゃないんですか？	","letter": "	Isn't biting illegal?	", "pinyin":"	かみつきははんそくじゃないんですか？	"},																			
"	219	":{"character":"	ワルだねかっこいい！	","letter": "	You're so cool!	", "pinyin":"	わるだねかっこいい！	"},																			
"	220	":{"character":"	あれ？でもペンギンさん甲羅ないよ	","letter": "	Huh? But penguins don't have shells.	", "pinyin":"	あれ？でもぺんぎんさんこうらないよ	"},																			
"	221	":{"character":"	お皿付けたら？	","letter": "	Why don't you put a plate on it?	", "pinyin":"	おさらつけたら？	"},																			
"	222	":{"character":"	カッパ？	","letter": "	Kappa?	", "pinyin":"	かっぱ？	"},																			
"	223	":{"character":"	カッパってなんて言って告白するの？	","letter": "	What do you say to a kappa?	", "pinyin":"	かっぱってなんていってこくはくするの？	"},																			
"	224	":{"character":"	ちょっと！まじめに考えてよ！	","letter": "	Oh, come on! Seriously, think about it!	", "pinyin":"	ちょっと！まじめにかんがえてよ！	"},																			
"	225	":{"character":"	はぁ…もうどうしていいかわからないよ	","letter": "	I don't know what to do anymore.	", "pinyin":"	はぁ…もうどうしていいかわからないよ	"},																			
"	226	":{"character":"	最悪だ世界の終わりだ	","letter": "	It's the end of the world!	", "pinyin":"	さいあくだせかいのおわりだ	"},																			
"	227	":{"character":"	や…やっぱり好きですってシンプルなのがいちばんですよ	","letter": "	I think a simple 'I love you' is the best.	", "pinyin":"	や…やっぱりすきですってしんぷるなのがいちばんですよ	"},																			
"	228	":{"character":"	あからさますぎない？	","letter": "	Isn't it too obvious?	", "pinyin":"	あからさますぎない？	"},																			
"	229	":{"character":"	それじゃあ好きってバレちゃうよ～！	","letter": "	Then they'll know you like them!	", "pinyin":"	それじゃあすきってばれちゃうよ～！	"},																			
"	230	":{"character":"	告白するんじゃないんですか？	","letter": "	Aren't you going to confess?	", "pinyin":"	こくはくするんじゃないんですか？	"},																			
"	231	":{"character":"	はっ…そうだった	","letter": "	Oh... that's right.	", "pinyin":"	はっ…そうだった	"},																			
"	232	":{"character":"	わかったシンプルに頑張るよ	","letter": "	Okay, I'll try to keep it simple.	", "pinyin":"	わかったしんぷるにがんばるよ	"},																			
"	233	":{"character":"	それじゃあ行こうか	","letter": "	Well then, let's go.	", "pinyin":"	それじゃあいこうか	"},																			
"	234	":{"character":"	ついてくる気！？	","letter": "	You're following me!	", "pinyin":"	ついてくるき！？	"},																			
"	235	":{"character":"	昔の武将はこう言った	","letter": "	An old warlord once said.	", "pinyin":"	むかしのぶしょうはこういった	"},																			
"	236	":{"character":"	１本の矢なら折れるが３本の矢なら折れないと	","letter": "	One arrow will break, but three arrows will not.	", "pinyin":"	１ぽんのやならおれるが３ぼんのやならおれないと	"},																			
"	237	":{"character":"	え～っと…三人寄れば文殊の知恵	","letter": "	Let's see... three arrows make a wise man.	", "pinyin":"	え～っと…さんにんよればもんじゅのちえ	"},																			
"	238	":{"character":"	モンキーの知恵？	","letter": "	Monkey wisdom?	", "pinyin":"	もんきーのちえ？	"},																			
"	239	":{"character":"	それじゃあ猿知恵になっちゃうよ	","letter": "	That would be monkey wisdom.	", "pinyin":"	それじゃあさるぢえになっちゃうよ	"},																			
"	240	":{"character":"	一人で大丈夫だから来ないでね！	","letter": "	I'm fine on my own, so don't come here!	", "pinyin":"	ひとりでだいじょうぶだからこないでね！	"},																			
"	241	":{"character":"	うまくいくといいですね	","letter": "	I hope it works out.	", "pinyin":"	うまくいくといいですね	"},																			
"	242	":{"character":"	あ…あれ？	","letter": "	Oh...what?	", "pinyin":"	あ…あれ？	"},																			
"	243	":{"character":"	す…好きです！	","letter": "	I like you!	", "pinyin":"	す…すきです！	"},																			
"	244	":{"character":"	これ受け取ってください	","letter": "	Please take this.	", "pinyin":"	これうけとってください	"},																			
"	245	":{"character":"	よ～し…言える！言えるぞ！	","letter": "	Okay, I can say it! I can say it!	", "pinyin":"	よ～し…いえる！いえるぞ！	"},																			
"	246	":{"character":"	行くぞ…よし行くぞ！	","letter": "	Let's go... okay, let's go!	", "pinyin":"	いくぞ…よしいくぞ！	"},																			
"	247	":{"character":"	す…好きです！これ受け取ってください！	","letter": "	I love you! Please take this!	", "pinyin":"	す…すきです！これうけとってください！	"},																			
"	248	":{"character":"	よし！	","letter": "	Yes!	", "pinyin":"	よし！	"},																			
"	249	":{"character":"	す…好きですペン子さん！	","letter": "	I love you, Penko!	", "pinyin":"	す…すきですぺんごさん！	"},																			
"	250	":{"character":"	これ受け取ってください！	","letter": "	Please take this!	", "pinyin":"	これうけとってください！	"},																			
"	251	":{"character":"	す…好きです！	","letter": "	I love you!	", "pinyin":"	す…すきです！	"},																			
"	252	":{"character":"	好きですこれ受け取ってください！	","letter": "	Please accept this!	", "pinyin":"	すきですこれうけとってください！	"},																			
"	253	":{"character":"	あれ何？何かのおまじない？	","letter": "	What is that? Is it a spell?	", "pinyin":"	あれなに？なにかのおまじない？	"},																			
"	254	":{"character":"	恋する者は	","letter": "	Those in love	", "pinyin":"	こいするものは	"},																			
"	255	":{"character":"	それが意味のない行為だとしても幾度となく繰り返してしまう	","letter": "	Even if it's a meaningless act, it's repeated over and over again.	", "pinyin":"	それがいみのないこういだとしてもいくどとなくくりかえしてしまう	"},																			
"	256	":{"character":"	また古い格言？	","letter": "	Another old saying?	", "pinyin":"	またふるいかくげん？	"},																			
"	257	":{"character":"	ううんいずれペンギンさんが作る未来の格言	","letter": "	No, it's just a saying that Penguin will make up in the future.	", "pinyin":"	ううんいずれぺんぎんさんがつくるみらいのかくげん	"},																			
"	258	":{"character":"	やっぱり僕に告白なんてムリなのかなぁ…	","letter": "	I wonder if it's impossible for me to confess my love to her...	", "pinyin":"	やっぱりぼくにこくはくなんてむりなのかなぁ…	"},																			
"	259	":{"character":"	もし彼女が僕の愛を受け入れてくれたら…	","letter": "	If she accepts my love...	", "pinyin":"	もしかのじょがぼくのあいをうけいれてくれたら…	"},																			
"	260	":{"character":"	嬉しいよペン子さん	","letter": "	I'd be so happy, Penko!	", "pinyin":"	うれしいよぺんごさん	"},																			
"	261	":{"character":"	嬉しいよペン子さん！	","letter": "	I'm so happy, Penko!	", "pinyin":"	うれしいよぺんごさん！	"},																			
"	262	":{"character":"	おいしいよペン子さん！	","letter": "	It's delicious, Penko!	", "pinyin":"	おいしいよぺんごさん！	"},																			
"	263	":{"character":"	嬉しいよ…イテッ！	","letter": "	I'm so happy... ouch!	", "pinyin":"	うれしいよ…いてっ！	"},																			
"	264	":{"character":"	あ…しまった！	","letter": "	Oh, no!	", "pinyin":"	あ…しまった！	"},																			
"	265	":{"character":"	いけないいけない夢の世界に浸ってしまった	","letter": "	I shouldn't, I shouldn't, I've fallen into a dream world!	", "pinyin":"	いけないいけないゆめのせかいにひたってしまった	"},																			
"	266	":{"character":"	でも夢が現実になる可能性はある！	","letter": "	But there's a chance that dream can become reality!	", "pinyin":"	でもゆめがげんじつになるかのうせいはある！	"},																			
"	267	":{"character":"	そのためにも頑張らなくっちゃ！	","letter": "	I have to work hard for that!	", "pinyin":"	そのためにもがんばらなくっちゃ！	"},																			
"	268	":{"character":"	あ～よかった行ったよ	","letter": "	Oh, thank goodness it's gone!	", "pinyin":"	あ～よかったいったよ	"},																			
"	269	":{"character":"	うんよかった	","letter": "	I'm so glad!	", "pinyin":"	うんよかった	"},																			
"	270	":{"character":"	僕は言う言うよ！	","letter": "	I'll tell you what I'll tell you!	", "pinyin":"	ぼくはいういうよ！	"},																			
"	271	":{"character":"	ペン子さ…	","letter": "	Penko...	", "pinyin":"	ぺんごさ…	"},																			
"	272	":{"character":"	ペンギンさんなかなか起きないね	","letter": "	Penguins don't wake up very often.	", "pinyin":"	ぺんぎんさんなかなかおきないね	"},																			
"	273	":{"character":"	もう帰ろうかな	","letter": "	I think I'd better go home.	", "pinyin":"	もうかえろうかな	"},																			
"	274	":{"character":"	あれ？僕…	","letter": "	What? I'm...	", "pinyin":"	あれ？ぼく…	"},																			
"	275	":{"character":"	そうだ！ペン子さんに告白！	","letter": "	That's it! Confess to Penko-san!	", "pinyin":"	そうだ！ぺんごさんにこくはく！	"},																			
"	276	":{"character":"	でも今日はやっぱやめとこうかな	","letter": "	But maybe I shouldn't do that today.	", "pinyin":"	でもこんにちはやっぱやめとこうかな	"},																			
"	277	":{"character":"	なんか空回りしてる感じだし…	","letter": "	I feel like I'm spinning my wheels...	", "pinyin":"	なんかからまわりしてるかんじだし…	"},																			
"	278	":{"character":"	いや！思い立ったが吉日！	","letter": "	No! The first day I think of it is the best day of the week!	", "pinyin":"	いや！おもいたったがきちじつ！	"},																			
"	279	":{"character":"	けどなぁなんか調子悪い気もするしな…	","letter": "	But... I feel like I'm not doing well...	", "pinyin":"	けどなぁなんかちょうしわるいきもするしな…	"},																			
"	280	":{"character":"	いやいやそんなこと言ってちゃダメだ！	","letter": "	No, no, no, don't say that!	", "pinyin":"	いやいやそんなこといってちゃだめだ！	"},																			
"	281	":{"character":"	でもなぁ…	","letter": "	But...	", "pinyin":"	でもなぁ…	"},																			
"	282	":{"character":"	ねぇまだ？	","letter": "	Hey, where are you?	", "pinyin":"	ねぇまだ？	"},																			
"	283	":{"character":"	待ちくたびれたよ	","letter": "	I'm tired of waiting.	", "pinyin":"	まちくたびれたよ	"},																			
"	284	":{"character":"	えっ！？なんで２人ともいるの？	","letter": "	What? Why are you both here?	", "pinyin":"	えっ！？なんで２にんともいるの？	"},																			
"	285	":{"character":"	来ないでって言ったのに！	","letter": "	I told you not to come!	", "pinyin":"	こないでっていったのに！	"},																			
"	286	":{"character":"	早くしてよ僕もうお腹すいたよ	","letter": "	Hurry up, I'm hungry.	", "pinyin":"	はやくしてよぼくもうおなかすいたよ	"},																			
"	287	":{"character":"	知らないよ！	","letter": "	I don't know!	", "pinyin":"	しらないよ！	"},																			
"	288	":{"character":"	しないの？告白	","letter": "	You don't? Confession.	", "pinyin":"	しないの？こくはく	"},																			
"	289	":{"character":"	そ…それは…	","letter": "	Well... that's...	", "pinyin":"	そ…それは…	"},																			
"	290	":{"character":"	古きローマの詩人は言った	","letter": "	As the old Roman poet said.	", "pinyin":"	ふるきろーまのしじんはいった	"},																			
"	291	":{"character":"	幸運と愛は勇者とともにあり	","letter": "	Fortune and love are with the brave.	", "pinyin":"	こううんとあいはゆうしゃとともにあり	"},																			
"	292	":{"character":"	勇者とともに？	","letter": "	With the brave?	", "pinyin":"	ゆうしゃとともに？	"},																			
"	293	":{"character":"	幸運も愛もその勇者って人のところにあるってことだね	","letter": "	You mean that luck and love are with that brave man.	", "pinyin":"	こううんもあいもそのゆうしゃってひとのところにあるってことだね	"},																			
"	294	":{"character":"	今から行こう	","letter": "	Let's go now!	", "pinyin":"	いまからいこう	"},																			
"	295	":{"character":"	行くのはペン子さんのところ！	","letter": "	We're going to Penko's!	", "pinyin":"	いくのはぺんごさんのところ！	"},																			
"	296	":{"character":"	そうなの？	","letter": "	Really?	", "pinyin":"	そうなの？	"},																			
"	297	":{"character":"	よ～しいくぞ！	","letter": "	Okay, let's go!	", "pinyin":"	よ～しいくぞ！	"},																			
"	298	":{"character":"	…って２人ともついてこないで！	","letter": "	Don't you two follow me!	", "pinyin":"	…って２にんともついてこないで！	"},																			
"	299	":{"character":"	言うぞ言うぞ！	","letter": "	I'll tell you! I'll tell you!	", "pinyin":"	いうぞいうぞ！	"},																			
"	300	":{"character":"	なんでいざっていうとき邪魔するの！？	","letter": "	Why are you interrupting me when I need you?	", "pinyin":"	なんでいざっていうときじゃまするの！？	"},																			
"	301	":{"character":"	パンダあんパンが気になっちゃって	","letter": "	I'm just worried about the panda buns.	", "pinyin":"	ぱんだあんぱんがきになっちゃって	"},																			
"	302	":{"character":"	わかったよ！買ってきてあげるよ！	","letter": "	I'll get you some! I'll get you some!	", "pinyin":"	わかったよ！かってきてあげるよ！	"},																			
"	303	":{"character":"	だから帰ってよ！ほら帰って帰って！	","letter": "	So go home! Go home!	", "pinyin":"	だからかえってよ！ほらかえってかえって！	"},																			
"	304	":{"character":"	あの…	","letter": "	Um...	", "pinyin":"	あの…	"},																			
"	305	":{"character":"	あっあの…	","letter": "	Oh, um...	", "pinyin":"	あっあの…	"},																			
"	306	":{"character":"	大丈夫かな？ペンギンさん	","letter": "	Are you okay? Hey, Penguin.	", "pinyin":"	だいじょうぶかな？ぺんぎんさん	"},																			
"	307	":{"character":"	お～い！	","letter": "	Hey!	", "pinyin":"	お～い！	"},																			
"	308	":{"character":"	やった！やったよ～！	","letter": "	I did it! We did it!	", "pinyin":"	やった！やったよ～！	"},																			
"	309	":{"character":"	おめでとうペンギンさん	","letter": "	Congratulations, Penguin!	", "pinyin":"	おめでとうぺんぎんさん	"},																			
"	310	":{"character":"	へぇ～じゃあうまくいったんですね	","letter": "	Well, I guess it all worked out.	", "pinyin":"	へぇ～じゃあうまくいったんですね	"},																			
"	311	":{"character":"	いやぁホントまいっちゃう	","letter": "	I'm really blown away!	", "pinyin":"	いやぁほんとまいっちゃう	"},																			
"	312	":{"character":"	それでペン子さんは何て？	","letter": "	So, what did Penko say?	", "pinyin":"	それでぺんごさんはなんて？	"},																			
"	313	":{"character":"	うん？知りたい？	","letter": "	You want to know? You want to know?	", "pinyin":"	うん？しりたい？	"},																			
"	314	":{"character":"	もう詳しく教えてくださいよ	","letter": "	Please tell me more!	", "pinyin":"	もうくわしくおしえてくださいよ	"},																			
"	315	":{"character":"	実はねペン子さん僕の顔を覚えててくれたみたいでね	","letter": "	Actually, Penko-san seems to have remembered my face.	", "pinyin":"	じつはねぺんごさんぼくのかおをおぼえててくれたみたいでね	"},																			
"	316	":{"character":"	「よかったらどうぞ」ってこれ！	","letter": "	He said, 'Here you go, if you like.'	", "pinyin":"	「よかったらどうぞ」ってこれ！	"},																			
"	317	":{"character":"	なんとサービス券もらったの！	","letter": "	What a gift! I got a service coupon!	", "pinyin":"	なんとさーびすけんもらったの！	"},																			
"	318	":{"character":"	ちょっと多めにって３枚も	","letter": "	I got three coupons, just to have a little extra!	", "pinyin":"	ちょっとおおめにって３まいも	"},																			
"	319	":{"character":"	ねっサービス券をサービスだよ！	","letter": "	Service coupons for free!	", "pinyin":"	ねっさーびすけんをさーびすだよ！	"},																			
"	320	":{"character":"	あの…告白は？	","letter": "	What about your confession?	", "pinyin":"	あの…こくはくは？	"},																			
"	321	":{"character":"	それどころじゃないよ！	","letter": "	I'm not here for that!	", "pinyin":"	それどころじゃないよ！	"},																			
"	322	":{"character":"	なんと受け取るときにちょっと手が触れちゃったんだよ	","letter": "	I just touched them when I was getting them!	", "pinyin":"	なんとうけとるときにちょっとてがさわれちゃったんだよ	"},																			
"	323	":{"character":"	どうしようもう手洗わない！	","letter": "	I'm not going to wash my hands!	", "pinyin":"	どうしようもうてあらわない！	"},																			
"	324	":{"character":"	洗えないよ！洗いたくないよ！	","letter": "	I can't wash my hands! I don't want to!	", "pinyin":"	あらえないよ！あらいたくないよ！	"},																			
"	325	":{"character":"	１枚のサービス券はサービス券だが	","letter": "	One service ticket is a service ticket.	", "pinyin":"	１まいのさーびすけんはさーびすけんだが	"},																			
"	326	":{"character":"	３枚なら…やっぱりサービス券だ	","letter": "	But three... is still a service coupon.	", "pinyin":"	３まいなら…やっぱりさーびすけんだ	"},																			
"	327	":{"character":"	それを言っちゃダメですよ	","letter": "	You can't say that.	", "pinyin":"	それをいっちゃだめですよ	"},																			
"	328	":{"character":"	パンダくん聞いてる？	","letter": "	Panda, are you listening to me?	", "pinyin":"	ぱんだくんきいてる？	"},																			
"	329	":{"character":"	聞いてるよ	","letter": "	I'm listening.	", "pinyin":"	きいてるよ	"},																			
"	330	":{"character":"	笹子さんほら！	","letter": "	Sasago!	", "pinyin":"	ささごさんほら！	"},																			
"	331	":{"character":"	もう幸せ！	","letter": "	I'm so happy!	", "pinyin":"	もうしあわせ！	"},																			
"	332	":{"character":"	ペンギンさんペンギンさんペンギンさん	","letter": "	Penguin! Penguin! Penguin!	", "pinyin":"	ぺんぎんさんぺんぎんさんぺんぎんさん	"},																			
"	333	":{"character":"	いつもは二回呼ぶのに今日はどうしたの？	","letter": "	You usually call me twice, but what's wrong with you today?	", "pinyin":"	いつもはにかいよぶのにきょうはどうしたの？	"},																			
"	334	":{"character":"	どうもしないよ	","letter": "	Nothing.	", "pinyin":"	どうもしないよ	"},																			
"	335	":{"character":"	ペンギンさんとの退屈な時間に少しだけでも刺激が欲しかったんだよ	","letter": "	I just wanted a little excitement in my boring time with Mr. Penguin.	", "pinyin":"	ぺんぎんさんとのたいくつなじかんにすこしだけでもしげきがほしかったんだよ	"},																			
"	336	":{"character":"	君結構言うね	","letter": "	You say that a lot.	", "pinyin":"	きみけっこういうね	"},																			
"	337	":{"character":"	ペンギンさんといるとどうして退屈するか考えてみようよ	","letter": "	Let's see if you can figure out why you're so bored with Mr. Penguin.	", "pinyin":"	ぺんぎんさんといるとどうしてたいくつするかかんがえてみようよ	"},																			
"	338	":{"character":"	いいよそれは白熊君終わって	","letter": "	Okay, polar bear, you're done.	", "pinyin":"	いいよそれはしろくまくんおわって	"},																			
"	339	":{"character":"	次回のしろくまカフェは	","letter": "	Next time at the Shirokuma Cafe.	", "pinyin":"	じかいのしろくまかふぇは	"},																			
"	340	":{"character":"	30秒に縮小してお送りします	","letter": "	I'm going to cut it down to 30 seconds.	", "pinyin":"	30びょうにしゅくしょうしておおくりします	"},																			
"	341	":{"character":"	30分やろう	","letter": "	Let's do 30 minutes.	", "pinyin":"	30ふんやろう	"},																			
"	342	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}