obj = {
"	1	":{"character":"	スマフォに夢中	","letter": "	Crazy about smartphones	", "pinyin":"	すまふぉにむちゅう	"},																			
"	2	":{"character":"	ねぇシロクマくん	","letter": "	Hey, Polar Bear.	", "pinyin":"	ねぇしろくまくん	"},																			
"	3	":{"character":"	それ楽しい？(^^)	","letter": "	Is that fun? (^^)	", "pinyin":"	それたのしい？(^^)	"},																			
"	4	":{"character":"	そういう時もあるね	","letter": "	Sometimes it is.	", "pinyin":"	そういうときもあるね	"},																			
"	5	":{"character":"	どんな時？	","letter": "	What kind of times?	", "pinyin":"	どんなとき？	"},																			
"	6	":{"character":"	こんなのが折れた時	","letter": "	When something like this breaks.	", "pinyin":"	こんなのがおれたとき	"},																			
"	7	":{"character":"	おぉ～！(*^▽^*)	","letter": "	Oh, wow! (*^▽^*)	", "pinyin":"	おぉ～！(*^▽^*)	"},																			
"	8	":{"character":"	シロクマだね	","letter": "	It's a polar bear.	", "pinyin":"	しろくまだね	"},																			
"	9	":{"character":"	ねぇどうやったの？	","letter": "	Hey, how did you do that?	", "pinyin":"	ねぇどうやったの？	"},																			
"	10	":{"character":"	秘密(#^.^#)	","letter": "	It's a secret. ^#)	", "pinyin":"	ひみつ(#^.^#)	"},																			
"	11	":{"character":"	器用だね	","letter": "	You're so handy.	", "pinyin":"	きようだね	"},																			
"	12	":{"character":"	写真撮っていいかな？	","letter": "	Can I take a picture?	", "pinyin":"	しゃしんとっていいかな？	"},																			
"	13	":{"character":"	写真？カメラ持ってるんだ？	","letter": "	A picture? You have a camera?	", "pinyin":"	しゃしん？かめらもってるんだ？	"},																			
"	14	":{"character":"	カメラっていうかさ…	","letter": "	It's a camera, it's a...	", "pinyin":"	かめらっていうかさ…	"},																			
"	15	":{"character":"	買ったんだスマフォ	","letter": "	I got a phone.	", "pinyin":"	かったんだすまふぉ	"},																			
"	16	":{"character":"	なに？スマフォって	","letter": "	A what? What's a phone?	", "pinyin":"	なに？すまふぉって	"},																			
"	17	":{"character":"	それはす巻き	","letter": "	That's a cigarette roll.	", "pinyin":"	それはすまき	"},																			
"	18	":{"character":"	それはちまき	","letter": "	That's a headband	", "pinyin":"	それはちまき	"},																			
"	19	":{"character":"	はちまき	","letter": "	A cigar	", "pinyin":"	はちまき	"},																			
"	20	":{"character":"	葉巻	","letter": "	Cigar	", "pinyin":"	はまき	"},																			
"	21	":{"character":"	ハマチ！	","letter": "	Hamachi!	", "pinyin":"	はまち！	"},																			
"	22	":{"character":"	キムチ！	","letter": "	Kimchi!	", "pinyin":"	きむち！	"},																			
"	23	":{"character":"	スマフォだよ！スマフォ！(-_-;)	","letter": "	It's a phone! Smart phone! (-_-;)	", "pinyin":"	すまふぉだよ！すまふぉ！(-_-;)	"},																			
"	24	":{"character":"	スマートフォン携帯電話の一種だよ	","letter": "	It's a smart phone. It's a kind of cell phone.	", "pinyin":"	すまーとふぉんけいたいでんわのいっしゅだよ	"},																			
"	25	":{"character":"	あっ！ペンギンさんそれがスマートフォンですか？	","letter": "	Ah! Penguin, is that a smart phone?	", "pinyin":"	あっ！ぺんぎんさんそれがすまーとふぉんですか？	"},																			
"	26	":{"character":"	私もよく知らないんですよね	","letter": "	I don't know much about it myself.	", "pinyin":"	わたしもよくしらないんですよね	"},																			
"	27	":{"character":"	え？笹子さんも？	","letter": "	Eh? Sasago-san?	", "pinyin":"	え？ささごさんも？	"},																			
"	28	":{"character":"	何ができるんですか？	","letter": "	What does it do?	", "pinyin":"	なにができるんですか？	"},																			
"	29	":{"character":"	いろいろ便利だよアプリも多いし	","letter": "	It's convenient in many ways, and there are many apps.	", "pinyin":"	いろいろべんりだよあぷりもおおいし	"},																			
"	30	":{"character":"	地図とかも見られますしね	","letter": "	You can look at maps and stuff.	", "pinyin":"	ちずとかもみられますしね	"},																			
"	31	":{"character":"	ネットだって見られるんだよほら	","letter": "	You can even look at the Internet.	", "pinyin":"	ねっとだってみられるんだよほら	"},																			
"	32	":{"character":"	なんか小さくて字読みづらくないですか？	","letter": "	Isn't it hard to read?	", "pinyin":"	なんかちいさくてじよみづらくないですか？	"},																			
"	33	":{"character":"	そんなことないよこういう時はねこうするの	","letter": "	It's not like that.	", "pinyin":"	そんなことないよこういうときはねこうするの	"},																			
"	34	":{"character":"	パンチ操作って言ってね	","letter": "	It's called punching.	", "pinyin":"	ぱんちそうさっていってね	"},																			
"	35	":{"character":"	叩くんですか？	","letter": "	You punch it?	", "pinyin":"	たたくんですか？	"},																			
"	36	":{"character":"	違うよ	","letter": "	No, no.	", "pinyin":"	ちがうよ	"},																			
"	37	":{"character":"	ピンチ操作じゃないですか？	","letter": "	Pinch operation?	", "pinyin":"	ぴんちそうさじゃないですか？	"},																			
"	38	":{"character":"	似たようなもんでしょ	","letter": "	It's the same thing.	", "pinyin":"	にたようなもんでしょ	"},																			
"	39	":{"character":"	そうですか	","letter": "	I see.	", "pinyin":"	そうですか	"},																			
"	40	":{"character":"	そうだよ	","letter": "	Yes, it is.	", "pinyin":"	そうだよ	"},																			
"	41	":{"character":"	いい？笹子さん見てて…	","letter": "	May I? Sasago, watch this...	", "pinyin":"	いい？ささごさんみてて…	"},																			
"	42	":{"character":"	よっ…(｀・ω・´)	","letter": "	Yo... (Translator's note)	", "pinyin":"	よっ…(｀・ω・´)	"},																			
"	43	":{"character":"	本当にそれ便利なんですか？	","letter": "	Are you sure that's convenient?	", "pinyin":"	ほんとうにそれべんりなんですか？	"},																			
"	44	":{"character":"	便利だってば！	","letter": "	Convenient!	", "pinyin":"	べんりだってば！	"},																			
"	45	":{"character":"	え～とこうやって…	","letter": "	Let's see... like this...	", "pinyin":"	え～とこうやって…	"},																			
"	46	":{"character":"	そのうち簡単に操作できるようになるよ	","letter": "	You'll be able to operate it easily soon.	", "pinyin":"	そのうちかんたんにそうさできるようになるよ	"},																			
"	47	":{"character":"	あれ？シロクマくんも持ってたの？	","letter": "	Huh? You have one too, Polar Bear?	", "pinyin":"	あれ？しろくまくんももってたの？	"},																			
"	48	":{"character":"	まぁね見てて	","letter": "	Well, watch this.	", "pinyin":"	まぁねみてて	"},																			
"	49	":{"character":"	こうやるの	","letter": "	Watch this.	", "pinyin":"	こうやるの	"},																			
"	50	":{"character":"	あぁ～かっこいい！(m´・ω・｀)m	","letter": "	Oh, that's so cool! (It's so cool!	", "pinyin":"	あぁ～かっこいい！(m´・ω・｀)m	"},																			
"	51	":{"character":"	シロクマさん器用ですね	","letter": "	You're very dexterous, Polar Bear.	", "pinyin":"	しろくまさんきようですね	"},																			
"	52	":{"character":"	それほどでもアヤメの花折ってみた	","letter": "	Not so much... but I broke the iris flower.	", "pinyin":"	それほどでもあやめのはなおってみた	"},																			
"	53	":{"character":"	すご～い！	","letter": "	Amazing!	", "pinyin":"	すご～い！	"},																			
"	54	":{"character":"	ほんと器用ですね！	","letter": "	You really are dexterous!	", "pinyin":"	ほんときようですね！	"},																			
"	55	":{"character":"	よ～しこうやって…	","letter": "	Okay, like this...	", "pinyin":"	よ～しこうやって…	"},																			
"	56	":{"character":"	えい！それ！(・∀・)	","letter": "	Yes! That's it! (Holy shit!)	", "pinyin":"	えい！それ！(・∀・)	"},																			
"	57	":{"character":"	駄目だ…	","letter": "	No...	", "pinyin":"	だめだ…	"},																			
"	58	":{"character":"	まぁ慣れですよ慣れ	","letter": "	Well, you get used to it.	", "pinyin":"	まぁなれですよなれ	"},																			
"	59	":{"character":"	なんか上から目線	","letter": "	You're talking from a high place.	", "pinyin":"	なんかうえからめせん	"},																			
"	60	":{"character":"	僕もスマフォですし	","letter": "	I'm on a smartphone too.	", "pinyin":"	ぼくもすまふぉですし	"},																			
"	61	":{"character":"	えっそうなの？	","letter": "	Oh, really?	", "pinyin":"	えっそうなの？	"},																			
"	62	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},																			
"	63	":{"character":"	ラマさんそういう君こそ上手に操作できるの？	","letter": "	Llama, you're the one who's good at it, right?	", "pinyin":"	らまさんそういうきみこそじょうずにそうさできるの？	"},																			
"	64	":{"character":"	もちろんですよ見ててください	","letter": "	Of course I can, just watch.	", "pinyin":"	もちろんですよみててください	"},																			
"	65	":{"character":"	おぉ～(ﾉﾟοﾟ)ﾉすごい！なんて柔軟な発想！	","letter": "	Oh, wow! What a flexible idea!	", "pinyin":"	おぉ～(の゜おみくろん゜)のすごい！なんてじゅうなんなはっそう！	"},																			
"	66	":{"character":"	そうか…わぁ…	","letter": "	I see... wow...	", "pinyin":"	そうか…わぁ…	"},																			
"	67	":{"character":"	あっプロフ交換します？	","letter": "	Do you want to exchange profiles?	", "pinyin":"	あっぷろふこうかんします？	"},																			
"	68	":{"character":"	するする	","letter": "	I'll do it.	", "pinyin":"	するする	"},																			
"	69	":{"character":"	お勧めの便利なアプリ知ってるよ	","letter": "	I know an app you might find useful.	", "pinyin":"	おすすめのべんりなあぷりしってるよ	"},																			
"	70	":{"character":"	え？なになに？教えて！	","letter": "	What? What's that? Tell me!	", "pinyin":"	え？なになに？おしえて！	"},																			
"	71	":{"character":"	やっぱ時代はスマフォだよね	","letter": "	The age of smartphones is here to stay, isn't it?	", "pinyin":"	やっぱじだいはすまふぉだよね	"},																			
"	72	":{"character":"	そうなの？	","letter": "	Is that so?	", "pinyin":"	そうなの？	"},																			
"	73	":{"character":"	そうだよ	","letter": "	Yes, it is.	", "pinyin":"	そうだよ	"},																			
"	74	":{"character":"	スマフォがあるとすっごく便利なんだから	","letter": "	It's so convenient to have a smartphone.	", "pinyin":"	すまふぉがあるとすっごくべんりなんだから	"},																			
"	75	":{"character":"	どんなふうに？	","letter": "	In what way?	", "pinyin":"	どんなふうに？	"},																			
"	76	":{"character":"	えっとね…	","letter": "	Well...	", "pinyin":"	えっとね…	"},																			
"	77	":{"character":"	画面をちまちま触って操作したり…	","letter": "	Touching and manipulating the screen...	", "pinyin":"	がめんをちまちまさわってそうさしたり…	"},																			
"	78	":{"character":"	なめたり…	","letter": "	Licking it...	", "pinyin":"	なめたり…	"},																			
"	79	":{"character":"	くちばしでつついたり…	","letter": "	Poke it with your beak...	", "pinyin":"	くちばしでつついたり…	"},																			
"	80	":{"character":"	そんでもって字がすっごく小さくて	","letter": "	And the letters are so small	", "pinyin":"	そんでもってじがすっごくちいさくて	"},																			
"	81	":{"character":"	読みづらいんだよ	","letter": "	It's hard to read.	", "pinyin":"	よみづらいんだよ	"},																			
"	82	":{"character":"	便利なの？それ	","letter": "	Is it convenient? That's...	", "pinyin":"	べんりなの？それ	"},																			
"	83	":{"character":"	あれ？	","letter": "	What's that?	", "pinyin":"	あれ？	"},																			
"	84	":{"character":"	とにかく外で働いてるパンダがケータイ持ってないなんて	","letter": "	Anyway, Panda who works outside doesn't have a cell phone.	", "pinyin":"	とにかくそとではたらいてるぱんだがけーたいもってないなんて	"},																			
"	85	":{"character":"	駄目だよ困るよ(/ω＼)	","letter": "	It's a problem.	", "pinyin":"	だめだよこまるよ(/ω＼)	"},																			
"	86	":{"character":"	別に困らないわよ	","letter": "	It doesn't bother me.	", "pinyin":"	べつにこまらないわよ	"},																			
"	87	":{"character":"	いらないでしょ	","letter": "	You don't need it.	", "pinyin":"	いらないでしょ	"},																			
"	88	":{"character":"	それだと困るなぁ	","letter": "	That's not good.	", "pinyin":"	それだとこまるなぁ	"},																			
"	89	":{"character":"	何が？	","letter": "	What's that?	", "pinyin":"	なにが？	"},																			
"	90	":{"character":"	ほらケータイあると何かあったときに便利だよ	","letter": "	You know, a cell phone is handy in case something happens.	", "pinyin":"	ほらけーたいあるとなにかあったときにべんりだよ	"},																			
"	91	":{"character":"	何かあったときね…	","letter": "	If something happens...	", "pinyin":"	なにかあったときね…	"},																			
"	92	":{"character":"	ねぇキッチンのバルサミコ酢がきれちゃったの	","letter": "	Hey, we're out of balsamic vinegar in the kitchen.	", "pinyin":"	ねぇきっちんのばるさみこすがきれちゃったの	"},																			
"	93	":{"character":"	バイト帰りに買ってきてくれる？	","letter": "	Can you pick some up on your way home from work?	", "pinyin":"	ばいとがえりにかってきてくれる？	"},																			
"	94	":{"character":"	うんいいよ	","letter": "	Yeah, sure.	", "pinyin":"	うんいいよ	"},																			
"	95	":{"character":"	便利じゃない！(＾ｖ＾)	","letter": "	It's so convenient! (Yes, it's very convenient.)	", "pinyin":"	べんりじゃない！(＾ｖ＾)	"},																			
"	96	":{"character":"	いいわよ買ってあげる	","letter": "	Sure, I'll buy some for you.	", "pinyin":"	いいわよかってあげる	"},																			
"	97	":{"character":"	やった～！Ｖ（=＾0＾=）ｖ	","letter": "	Yay!	", "pinyin":"	やった～！Ｖ（=＾0＾=）ｖ	"},																			
"	98	":{"character":"	ほら見て見て～	","letter": "	Look, look, look!	", "pinyin":"	ほらみてみて～	"},																			
"	99	":{"character":"	何ですか？	","letter": "	What is it?	", "pinyin":"	なんですか？	"},																			
"	100	":{"character":"	この前撮った写真待ち受けにしてみたんだ	","letter": "	I made the picture I took the other day into a standby.	", "pinyin":"	このまえとったしゃしんまちうけにしてみたんだ	"},																			
"	101	":{"character":"	へぇ～今日は折り紙折らないんですか？	","letter": "	Oh, you're not going to fold origami today?	", "pinyin":"	へぇ～きょうはおりがみおらないんですか？	"},																			
"	102	":{"character":"	えっ？気が向いたら	","letter": "	What? When I feel like it.	", "pinyin":"	えっ？きがむいたら	"},																			
"	103	":{"character":"	そっちの感想！？(;ﾟДﾟ)!	","letter": "	What do you think of that one? (;ppp)!	", "pinyin":"	そっちのかんそう！？(;゜Д゜)!	"},																			
"	104	":{"character":"	こんにちは～	","letter": "	Hello~!	", "pinyin":"	こんにちは～	"},																			
"	105	":{"character":"	いらっしゃい	","letter": "	Welcome!	", "pinyin":"	いらっしゃい	"},																			
"	106	":{"character":"	パンダくん嬉しそうだね	","letter": "	Panda, you look so happy!	", "pinyin":"	ぱんだくんうれしそうだね	"},																			
"	107	":{"character":"	実はさぁ…	","letter": "	Actually...	", "pinyin":"	じつはさぁ…	"},																			
"	108	":{"character":"	ジャーン！	","letter": "	Ta-da!	", "pinyin":"	じゃーん！	"},																			
"	109	":{"character":"	あぁそれ！	","letter": "	That's it!	", "pinyin":"	あぁそれ！	"},																			
"	110	":{"character":"	パンダカバーのスマフォだよ！	","letter": "	It's a phone with a panda cover!	", "pinyin":"	ぱんだかばーのすまふぉだよ！	"},																			
"	111	":{"character":"	かわいいね！(#^.^#)	","letter": "	So cute! (#^. ^#)	", "pinyin":"	かわいいね！(#^.^#)	"},																			
"	112	":{"character":"	いいでしょう～見つけるの苦労したんだよ	","letter": "	I had a hard time finding it.	", "pinyin":"	いいでしょう～みつけるのくろうしたんだよ	"},																			
"	113	":{"character":"	どう？スマフォ	","letter": "	What do you think? Smartphone.	", "pinyin":"	どう？すまふぉ	"},																			
"	114	":{"character":"	やっぱり便利だよね	","letter": "	It's so convenient, isn't it?	", "pinyin":"	やっぱりべんりだよね	"},																			
"	115	":{"character":"	ほら好きな時にいつだって天気予報も見られるしね	","letter": "	You can check the weather forecast whenever you want.	", "pinyin":"	ほらすきなときにいつだっててんきよほうもみられるしね	"},																			
"	116	":{"character":"	地図も見られるから迷子にならなくて済むし	","letter": "	You can look at a map so you don't get lost.	", "pinyin":"	ちずもみられるからまいごにならなくてすむし	"},																			
"	117	":{"character":"	頭にのせてバランス感覚もみがけるし	","letter": "	And you can put it on your head to learn how to balance.	", "pinyin":"	あたまにのせてばらんすかんかくもみがけるし	"},																			
"	118	":{"character":"	それスマフォの使い方じゃないけどね	","letter": "	That's not how you use a smartphone, though.	", "pinyin":"	それすまふぉのつかいかたじゃないけどね	"},																			
"	119	":{"character":"	でもペンギンさんより使いこなしてませんか？	","letter": "	But don't you use it more than Penguin?	", "pinyin":"	でもぺんぎんさんよりつかいこなしてませんか？	"},																			
"	120	":{"character":"	ぼ僕だって待ち受けかえてるし	","letter": "	I've changed my phone's faceplate.	", "pinyin":"	ぼぼくだってまちうけかえてるし	"},																			
"	121	":{"character":"	他にも…	","letter": "	I also...	", "pinyin":"	ほかにも…	"},																			
"	122	":{"character":"	写真を撮ったり	","letter": "	I can take pictures.	", "pinyin":"	しゃしんをとったり	"},																			
"	123	":{"character":"	音楽だって聴けるしね	","letter": "	I can even listen to music.	", "pinyin":"	おんがくだってきけるしね	"},																			
"	124	":{"character":"	あ…あ…(;ﾟДﾟ)!	","letter": "	Oh... oh... oh... oh... oh... oh... oh... oh... oh... oh... oh... oh... oh...	", "pinyin":"	あ…あ…(;゜Д゜)!	"},																			
"	125	":{"character":"	だ大丈夫だよパンダくん	","letter": "	It's okay, Panda.	", "pinyin":"	だだいじょうぶだよぱんだくん	"},																			
"	126	":{"character":"	壊れたのはカバーだけみたい	","letter": "	It looks like the cover is the only thing that broke.	", "pinyin":"	こわれたのはかばーだけみたい	"},																			
"	127	":{"character":"	だって	","letter": "	I'm sure it's fine.	", "pinyin":"	だって	"},																			
"	128	":{"character":"	だから元気出して	","letter": "	So cheer up!	", "pinyin":"	だからげんきだして	"},																			
"	129	":{"character":"	スマフォが無事でよかったです	","letter": "	I'm glad your phone is okay.	", "pinyin":"	すまふぉがぶじでよかったです	"},																			
"	130	":{"character":"	はいパンダくん	","letter": "	Hey, Panda.	", "pinyin":"	はいぱんだくん	"},																			
"	131	":{"character":"	僕にとって…スマフォはパンダカバーのおまけだから	","letter": "	For me... the phone is just an extra panda cover.	", "pinyin":"	ぼくにとって…すまふぉはぱんだかばーのおまけだから	"},																			
"	132	":{"character":"	あらちょっとスマホはどうしたの？スマホは	","letter": "	Oh, hey, what happened to your phone? Where's my phone?	", "pinyin":"	あらちょっとすまほはどうしたの？すまほは	"},																			
"	133	":{"character":"	さっき電話したのよ	","letter": "	I just called you.	", "pinyin":"	さっきでんわしたのよ	"},																			
"	134	":{"character":"	ねぇ聞こえてる？	","letter": "	Hey, can you hear me?	", "pinyin":"	ねぇきこえてる？	"},																			
"	135	":{"character":"	バルサミコ酢よバールーサーミーコー酢！	","letter": "	It's balsamic vinegar.	", "pinyin":"	ばるさみこすよばーるーさーみーこーす！	"},																			
"	136	":{"character":"	この電話はお客様の都合により出られません	","letter": "	This call is being held for your convenience.	", "pinyin":"	このでんわはおきゃくさまのつごうによりでられません	"},																			
"	137	":{"character":"	えっ？	","letter": "	What?	", "pinyin":"	えっ？	"},																			
"	138	":{"character":"	ちっとも便利じゃないわねスマホ	","letter": "	That's not very convenient.	", "pinyin":"	ちっともべんりじゃないわねすまほ	"},																			
"	139	":{"character":"	あのさスマートフォンなんだからスマホじゃなくてスマフォだよ	","letter": "	You know, it's a smartphone, not a smart phone.	", "pinyin":"	あのさすまーとふぉんなんだからすまほじゃなくてすまふぉだよ	"},																			
"	140	":{"character":"	どっちだっていいじゃない	","letter": "	It doesn't matter which one it is.	", "pinyin":"	どっちだっていいじゃない	"},																			
"	141	":{"character":"	こんにちは～(=゜ω゜)ノ	","letter": "	Hello~!	", "pinyin":"	こんにちは～(=゜ω゜)の	"},																			
"	142	":{"character":"	シロクマくんいつものお願い	","letter": "	Polar bear... the usual request.	", "pinyin":"	しろくまくんいつものおねがい	"},																			
"	143	":{"character":"	パンダくんひょっとして立ち直った？	","letter": "	Panda, are you back on your feet by any chance?	", "pinyin":"	ぱんだくんひょっとしてたちなおった？	"},																			
"	144	":{"character":"	何が？	","letter": "	What?	", "pinyin":"	なにが？	"},																			
"	145	":{"character":"	心配した僕がバカだったよ	","letter": "	I was a fool to worry about you.	", "pinyin":"	しんぱいしたぼくがばかだったよ	"},																			
"	146	":{"character":"	パンダくんのスマフォここにあるからね	","letter": "	I've got your phone right here.	", "pinyin":"	ぱんだくんのすまふぉここにあるからね	"},																			
"	147	":{"character":"	あぁスマフォならもういいんだ	","letter": "	Oh, I don't need a phone anymore.	", "pinyin":"	あぁすまふぉならもういいんだ	"},																			
"	148	":{"character":"	強がり？	","letter": "	You think I'm tough?	", "pinyin":"	つよがり？	"},																			
"	149	":{"character":"	本気だってパンダじゃないし	","letter": "	I'm not a panda.	", "pinyin":"	ほんきだってぱんだじゃないし	"},																			
"	150	":{"character":"	えっ？せっかく買ったんだから大事に使ったら？	","letter": "	What? You bought it. Why don't you take good care of it?	", "pinyin":"	えっ？せっかくかったんだからだいじにつかったら？	"},																			
"	151	":{"character":"	パンダくんこれ見てスマフォのケース	","letter": "	Panda, look at this phone case.	", "pinyin":"	ぱんだくんこれみてすまふぉのけーす	"},																			
"	152	":{"character":"	こんなの折ってみた	","letter": "	I folded it like this.	", "pinyin":"	こんなのおってみた	"},																			
"	153	":{"character":"	あっパンダだ～！	","letter": "	Oh, it's a panda!	", "pinyin":"	あっぱんだだ～！	"},																			
"	154	":{"character":"	これなら紙だから割れないね	","letter": "	It's paper, so it won't break.	", "pinyin":"	これならかみだからわれないね	"},																			
"	155	":{"character":"	よかったですね	","letter": "	That's great!	", "pinyin":"	よかったですね	"},																			
"	156	":{"character":"	シロクマさんさすが！	","letter": "	Polar bear, you're the best!	", "pinyin":"	しろくまさんさすが！	"},																			
"	157	":{"character":"	フフッやっぱりパンダは最高だね	","letter": "	Pandas are the best!	", "pinyin":"	ふふっやっぱりぱんだはさいこうだね	"},																			
"	158	":{"character":"	わくわくドライブレッスン	","letter": "	Exciting driving lesson!	", "pinyin":"	わくわくどらいぶれっすん	"},																			
"	159	":{"character":"	はぁ～	","letter": "	Oh, no!	", "pinyin":"	はぁ～	"},																			
"	160	":{"character":"	どうしたのペンギンさん食あたり？	","letter": "	What's the matter, Penguin, food poisoning?	", "pinyin":"	どうしたのぺんぎんさんしょくあたり？	"},																			
"	161	":{"character":"	そんなんじゃないよ	","letter": "	It's nothing like that!	", "pinyin":"	そんなんじゃないよ	"},																			
"	162	":{"character":"	ペン子さんのことですよね	","letter": "	You mean Penko-san, right?	", "pinyin":"	ぺんごさんのことですよね	"},																			
"	163	":{"character":"	違うよ今教習所に通っててそれで…	","letter": "	No, I'm going to driving school now, and...	", "pinyin":"	ちがうよいまきょうしゅうじょにとおっててそれで…	"},																			
"	164	":{"character":"	車の免許取るんだって	","letter": "	He's getting his driver's license.	", "pinyin":"	くるまのめんきょとるんだって	"},																			
"	165	":{"character":"	どうして急に？(・∀・(・∀・(・∀・*)	","letter": "	Why all of a sudden? (Holy shit!	", "pinyin":"	どうしてきゅうに？(・∀・(・∀・(・∀・*)	"},																			
"	166	":{"character":"	ペン子さんをドライブに誘いたいみたい	","letter": "	She wants to take Penko-san for a drive.	", "pinyin":"	ぺんごさんをどらいぶにさそいたいみたい	"},																			
"	167	":{"character":"	どうしてそれを？	","letter": "	How did you know about that?	", "pinyin":"	どうしてそれを？	"},																			
"	168	":{"character":"	ブログに書いてありましたよ	","letter": "	I read it on your blog	", "pinyin":"	ぶろぐにかいてありましたよ	"},																			
"	169	":{"character":"	あ～ペン子さんペン子さんあなたと行きたい海辺のドライブ	","letter": "	Oh, Penko-san, Penko-san I want to go with you for a drive by the sea	", "pinyin":"	あ～ぺんごさんぺんごさんあなたといきたいうみべのどらいぶ	"},																			
"	170	":{"character":"	僕は通うよ教習所	","letter": "	I'm going to the driving school	", "pinyin":"	ぼくはかようよきょうしゅうじょ	"},																			
"	171	":{"character":"	人の日記勝手に読まないでよ！(#`O′)	","letter": "	Don't read my diary without my permission! (#`O′)	", "pinyin":"	ひとのにっきかってによまないでよ！(#`O′)	"},																			
"	172	":{"character":"	いやブログってそういうものだし	","letter": "	No, that's what a blog is for.	", "pinyin":"	いやぶろぐってそういうものだし	"},																			
"	173	":{"character":"	読まれたくないなら非公開にした方がいいですよ	","letter": "	If you don't want people to read it, you should make it private.	", "pinyin":"	よまれたくないならひこうかいにしたほうがいいですよ	"},																			
"	174	":{"character":"	教習所大変なんですか？	","letter": "	Is it hard to go to driving school?	", "pinyin":"	きょうしゅうじょたいへんなんですか？	"},																			
"	175	":{"character":"	結構	","letter": "	It's not that hard.	", "pinyin":"	けっこう	"},																			
"	176	":{"character":"	車の運転ってそんなに難しいの？	","letter": "	Is it that hard to drive a car?	", "pinyin":"	くるまのうんてんってそんなにむずかしいの？	"},																			
"	177	":{"character":"	まあね教えてくれる教官は厳しいし	","letter": "	Well, the instructors are very strict.	", "pinyin":"	まあねおしえてくれるきょうかんはきびしいし	"},																			
"	178	":{"character":"	今日も縦列駐車ができなくってさ	","letter": "	I couldn't parallel park today.	", "pinyin":"	きょうもじゅうれつちゅうしゃができなくってさ	"},																			
"	179	":{"character":"	最初は難しいよね縦列駐車	","letter": "	Parallel parking is hard at first.	", "pinyin":"	さいしょはむずかしいよねじゅうれつちゅうしゃ	"},																			
"	180	":{"character":"	だよね	","letter": "	I know, right?	", "pinyin":"	だよね	"},																			
"	181	":{"character":"	縦列駐車？	","letter": "	Parallel parking?	", "pinyin":"	じゅうれつちゅうしゃ？	"},																			
"	182	":{"character":"	１０列駐車？	","letter": "	Ten-row parking?	", "pinyin":"	１０れつちゅうしゃ？	"},																			
"	183	":{"character":"	１０列注射？	","letter": "	Ten rows of injections?	", "pinyin":"	１０れつちゅうしゃ？	"},																			
"	184	":{"character":"	１０列カチューシャ？	","letter": "	Ten rows of cutlery?	", "pinyin":"	１０れつかちゅーしゃ？	"},																			
"	185	":{"character":"	１０列チュ～？	","letter": "	10 rows of chews?	", "pinyin":"	１０れつちゅ～？	"},																			
"	186	":{"character":"	じゃあ明日１１時に集合ね	","letter": "	I'll see you tomorrow at 11:00.	", "pinyin":"	じゃああした１１じにしゅうごうね	"},																			
"	187	":{"character":"	もう聞いてなかったの？	","letter": "	Didn't you hear already?	", "pinyin":"	もうきいてなかったの？	"},																			
"	188	":{"character":"	勉強に行くの	","letter": "	I'm going to study.	", "pinyin":"	べんきょうにいくの	"},																			
"	189	":{"character":"	そうなの？	","letter": "	Really?	", "pinyin":"	そうなの？	"},																			
"	190	":{"character":"	シロクマさんにペンギンさんが運転のコツを教えてもらうんですよ	","letter": "	Polar bears teach penguins how to drive.	", "pinyin":"	しろくまさんにぺんぎんさんがうんてんのこつをおしえてもらうんですよ	"},																			
"	191	":{"character":"	パンダくんどうせ暇でしょ？	","letter": "	You're not busy anyway, are you, panda?	", "pinyin":"	ぱんだくんどうせひまでしょ？	"},																			
"	192	":{"character":"	ゴロゴロするのに忙しいよ(*￣∇￣)ノ	","letter": "	I'm busy romping around.	", "pinyin":"	ごろごろするのにいそがしいよ(*￣∇￣)の	"},																			
"	193	":{"character":"	それって暇じゃないの？まあいいや	","letter": "	Isn't that not free time? Well, okay...	", "pinyin":"	それってひまじゃないの？まあいいや	"},																			
"	194	":{"character":"	じゃあやめとく？ドライブ	","letter": "	So you don't want to do that? Let's go for a drive.	", "pinyin":"	じゃあやめとく？どらいぶ	"},																			
"	195	":{"character":"	え？ドライブなの？行くよ	","letter": "	What? You're going for a drive? I'm going.	", "pinyin":"	え？どらいぶなの？いくよ	"},																			
"	196	":{"character":"	もうじゃあ明日カフェの前ね	","letter": "	I'll see you tomorrow in front of the cafe.	", "pinyin":"	もうじゃああしたかふぇのまえね	"},																			
"	197	":{"character":"	うん	","letter": "	Okay.	", "pinyin":"	うん	"},																			
"	198	":{"character":"	パンダくんまだかな？	","letter": "	Where's Mr. Panda?	", "pinyin":"	ぱんだくんまだかな？	"},																			
"	199	":{"character":"	呼びに行こうか？	","letter": "	You want me to go get him?	", "pinyin":"	よびにいこうか？	"},																			
"	200	":{"character":"	そのうち来るよ	","letter": "	He'll be here soon.	", "pinyin":"	そのうちくるよ	"},																			
"	201	":{"character":"	おはよう	","letter": "	Good morning.	", "pinyin":"	おはよう	"},																			
"	202	":{"character":"	遅いよパンダくん	","letter": "	You're late, panda.	", "pinyin":"	おそいよぱんだくん	"},																			
"	203	":{"character":"	え？何その竹は？	","letter": "	What? What's with the bamboo?	", "pinyin":"	え？なにそのたけは？	"},																			
"	204	":{"character":"	ドライブにおやつは必要だよ	","letter": "	You need a snack for the drive.	", "pinyin":"	どらいぶにおやつはひつようだよ	"},																			
"	205	":{"character":"	みんなの分も持ってきたからね	","letter": "	I brought enough for everyone.	", "pinyin":"	みんなのぶんももってきたからね	"},																			
"	206	":{"character":"	いやいらないから	","letter": "	No, I don't want any.	", "pinyin":"	いやいらないから	"},																			
"	207	":{"character":"	それパンダくんだけのおやつだし	","letter": "	That's just for you, Panda.	", "pinyin":"	それぱんだくんだけのおやつだし	"},																			
"	208	":{"character":"	おやつ	","letter": "	Snacks?	", "pinyin":"	おやつ	"},																			
"	209	":{"character":"	それはこたつ	","letter": "	That's a kotatsu	", "pinyin":"	それはこたつ	"},																			
"	210	":{"character":"	それは脚立	","letter": "	That's a stepladder	", "pinyin":"	それはきゃたつ	"},																			
"	211	":{"character":"	それはキャベツ	","letter": "	That's cabbage.	", "pinyin":"	それはきゃべつ	"},																			
"	212	":{"character":"	いいから出発しようよ	","letter": "	Let's just get going.	", "pinyin":"	いいからしゅっぱつしようよ	"},																			
"	213	":{"character":"	ラマさんは？	","letter": "	Where's Lamar?	", "pinyin":"	らまさんは？	"},																			
"	214	":{"character":"	動物園のバイトだって	","letter": "	He's working at the zoo.	", "pinyin":"	どうぶつえんのばいとだって	"},																			
"	215	":{"character":"	じゃあシロクマくん頼むね	","letter": "	Polar bear, then?	", "pinyin":"	じゃあしろくまくんたのむね	"},																			
"	216	":{"character":"	後部座席って微妙だよね	","letter": "	The back seat's not very comfortable, is it?	", "pinyin":"	こうぶざせきってびみょうだよね	"},																			
"	217	":{"character":"	寝っ転がるには狭いしさ	","letter": "	It's too small to lie down.	", "pinyin":"	ねっころがるにはせまいしさ	"},																			
"	218	":{"character":"	パンダくんちゃんと座って	","letter": "	Panda, you sit in the back seat.	", "pinyin":"	ぱんだくんちゃんとすわって	"},																			
"	219	":{"character":"	じゃあ行くよ	","letter": "	Okay, I'm going.	", "pinyin":"	じゃあいくよ	"},																			
"	220	":{"character":"	お～さすが発車からして上手だね和ヾ(≧O≦)〃	","letter": "	You're really good at starting the car, aren't you?	", "pinyin":"	お～さすがはっしゃからしてじょうずだねわヾ(≧O≦)〃	"},																			
"	221	":{"character":"	それほどでも	","letter": "	Not so much.	", "pinyin":"	それほどでも	"},																			
"	222	":{"character":"	ねぇコツは？コツ	","letter": "	Hey, any tips? Tips?	", "pinyin":"	ねぇこつは？こつ	"},																			
"	223	":{"character":"	そうだねグッときたらピッとしてゴー！	","letter": "	When you get a good feeling, you just click it and go!	", "pinyin":"	そうだねぐっときたらぴっとしてごー！	"},																			
"	224	":{"character":"	って感じ	","letter": "	That's it!	", "pinyin":"	ってかんじ	"},																			
"	225	":{"character":"	抽象的だなよくわかんないよ(o´∀｀o)	","letter": "	I don't know, that's a bit abstract.	", "pinyin":"	ちゅうしょうてきだなよくわかんないよ(o´∀｀o)	"},																			
"	226	":{"character":"	ペンギンさん	","letter": "	Penguin.	", "pinyin":"	ぺんぎんさん	"},																			
"	227	":{"character":"	なに？	","letter": "	What's that?	", "pinyin":"	なに？	"},																			
"	228	":{"character":"	つるしたタイヤにジャレるみたいな感じだよたぶん	","letter": "	It's like jerking a tire on a swing, I guess.	", "pinyin":"	つるしたたいやにじゃれるみたいなかんじだよたぶん	"},																			
"	229	":{"character":"	ますますわかんないから	","letter": "	I'm getting more and more confused.	", "pinyin":"	ますますわかんないから	"},																			
"	230	":{"character":"	でどこに行く？	","letter": "	So where are you going?	", "pinyin":"	でどこにいく？	"},																			
"	231	":{"character":"	山とか？	","letter": "	The mountains?	", "pinyin":"	やまとか？	"},																			
"	232	":{"character":"	笹がいっぱい生えてそうな	","letter": "	There's a lot of bamboo grass.	", "pinyin":"	ささがいっぱいはえてそうな	"},																			
"	233	":{"character":"	その辺でいいよ	","letter": "	I'm fine with that.	", "pinyin":"	そのへんでいいよ	"},																			
"	234	":{"character":"	今日はシロクマくんの運転技術を僕が勉強するドライブなんだからね	","letter": "	We're going for a drive today so I can study your driving skills, Polar Bear.	", "pinyin":"	きょうはしろくまくんのうんてんぎじゅつをぼくがべんきょうするどらいぶなんだからね	"},																			
"	235	":{"character":"	シロクマくん免許はいつ取ったの？	","letter": "	When did you get your license, polar bear?	", "pinyin":"	しろくまくんめんきょはいつとったの？	"},																			
"	236	":{"character":"	大人になってから	","letter": "	When I grew up.	", "pinyin":"	おとなになってから	"},																			
"	237	":{"character":"	いやそうじゃなくてさ	","letter": "	No, I mean...	", "pinyin":"	いやそうじゃなくてさ	"},																			
"	238	":{"character":"	終わりました	","letter": "	I'm done.	", "pinyin":"	おわりました	"},																			
"	239	":{"character":"	ご苦労さまでした	","letter": "	Thank you for your hard work.	", "pinyin":"	ごくろうさまでした	"},																			
"	240	":{"character":"	笹の葉？	","letter": "	Bamboo grass leaf?	", "pinyin":"	ささのは？	"},																			
"	241	":{"character":"	こんにちはパンダくん	","letter": "	Hello, panda.	", "pinyin":"	こんにちはぱんだくん	"},																			
"	242	":{"character":"	ん？	","letter": "	Hmm?	", "pinyin":"	ん？	"},																			
"	243	":{"character":"	お出かけ？	","letter": "	Going out?	", "pinyin":"	おでかけ？	"},																			
"	244	":{"character":"	おやつ中	","letter": "	Snack time	", "pinyin":"	おやつちゅう	"},																			
"	245	":{"character":"	バイバ～イ！ヾ(￣▽￣)~	","letter": "	Bye bye! Bye bye!	", "pinyin":"	ばいば～い！ヾ(￣▽￣)~	"},																			
"	246	":{"character":"	あ～あなんかお腹減っちゃったね	","letter": "	Oh, I'm so hungry.	", "pinyin":"	あ～あなんかおなかへっちゃったね	"},																			
"	247	":{"character":"	今笹食べてたじゃない	","letter": "	You just ate some bamboo grass!	", "pinyin":"	いまささたべてたじゃない	"},																			
"	248	":{"character":"	あっ！あそこ行こうよ！	","letter": "	Oh! Let's go there!	", "pinyin":"	あっ！あそこいこうよ！	"},																			
"	249	":{"character":"	いらっしゃいませご注文はお決まりですか？	","letter": "	Welcome, what would you like to order?	", "pinyin":"	いらっしゃいませごちゅうもんはおきまりですか？	"},																			
"	250	":{"character":"	笹か竹ください	","letter": "	Bamboo or bamboo, please!	", "pinyin":"	ささかたけください	"},																			
"	251	":{"character":"	申し訳ありません当店のメニューにはございません	","letter": "	Sorry, we don't have that on the menu.	", "pinyin":"	もうしわけありませんとうてんのめにゅーにはございません	"},																			
"	252	":{"character":"	また来ます	","letter": "	I'll be back.	", "pinyin":"	またきます	"},																			
"	253	":{"character":"	いらっしゃいませご注文はお決まりですか？	","letter": "	What would you like to order?	", "pinyin":"	いらっしゃいませごちゅうもんはおきまりですか？	"},																			
"	254	":{"character":"	フィッシュバーガーフィッシュ生で	","letter": "	Fishburger fish, raw fish, please.	", "pinyin":"	ふぃっしゅばーがーふぃっしゅなまで	"},																			
"	255	":{"character":"	申し訳ありません当店のメニューにはございません	","letter": "	Sorry, we don't have that on the menu.	", "pinyin":"	もうしわけありませんとうてんのめにゅーにはございません	"},																			
"	256	":{"character":"	また来ます	","letter": "	We'll be back.	", "pinyin":"	またきます	"},																			
"	257	":{"character":"	いらっしゃいませご注文はお決まりですか？	","letter": "	Welcome, what would you like to order?	", "pinyin":"	いらっしゃいませごちゅうもんはおきまりですか？	"},																			
"	258	":{"character":"	いいボケが思いつかないので	","letter": "	I can't think of a good one.	", "pinyin":"	いいぼけがおもいつかないので	"},																			
"	259	":{"character":"	また来ます	","letter": "	I'll be back.	", "pinyin":"	またきます	"},																			
"	260	":{"character":"	あのお客様！	","letter": "	That customer!	", "pinyin":"	あのおきゃくさま！	"},																			
"	261	":{"character":"	いらっしゃいませ	","letter": "	Welcome!	", "pinyin":"	いらっしゃいませ	"},																			
"	262	":{"character":"	だからフィッシュバーガーセットでいいじゃない	","letter": "	So, why don't you just order the fish burger set?	", "pinyin":"	だからふぃっしゅばーがーせっとでいいじゃない	"},																			
"	263	":{"character":"	レタスバーガーセットがいいよ	","letter": "	I want the lettuce burger set.	", "pinyin":"	れたすばーがーせっとがいいよ	"},																			
"	264	":{"character":"	笹じゃないけど葉っぱだし	","letter": "	It's not a bamboo grass, but it's a leaf.	", "pinyin":"	ささじゃないけどはっぱだし	"},																			
"	265	":{"character":"	てりやきバーガーセットがいいよ	","letter": "	I want the teriyaki burger set.	", "pinyin":"	てりやきばーがーせっとがいいよ	"},																			
"	266	":{"character":"	よし	","letter": "	Okay.	", "pinyin":"	よし	"},																			
"	267	":{"character":"	じゃあ…	","letter": "	Okay, then...	", "pinyin":"	じゃあ…	"},																			
"	268	":{"character":"	お決まりですか？	","letter": "	Are you decided?	", "pinyin":"	おきまりですか？	"},																			
"	269	":{"character":"	また来ます	","letter": "	I'll be back.	", "pinyin":"	またきます	"},																			
"	270	":{"character":"	あのグルグル回らずそこで相談なさってかまいませんから！	","letter": "	Don't go around in circles, you can talk to me there.	", "pinyin":"	あのぐるぐるまわらずそこでそうだんなさってかまいませんから！	"},																			
"	271	":{"character":"	ご注文をうけたまわりました	","letter": "	Your order has been accepted.	", "pinyin":"	ごちゅうもんをうけたまわりました	"},																			
"	272	":{"character":"	受け渡し窓口までお進みになってお待ちください	","letter": "	Please proceed to the delivery window and wait.	", "pinyin":"	うけわたしまどぐちまでおすすみになっておまちください	"},																			
"	273	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},																			
"	274	":{"character":"	はぁ…	","letter": "	Oh...	", "pinyin":"	はぁ…	"},																			
"	275	":{"character":"	うわっ！	","letter": "	Oh, my God!	", "pinyin":"	うわっ！	"},																			
"	276	":{"character":"	ここでいいの？	","letter": "	Are you sure this is the right place?	", "pinyin":"	ここでいいの？	"},																			
"	277	":{"character":"	ドライブスルーで遊ばないでくださいw(ﾟДﾟ)w	","letter": "	Don't play in the drive-through.	", "pinyin":"	どらいぶするーであそばないでくださいw(゜Д゜)w	"},																			
"	278	":{"character":"	どう？ペンギンさんコツはつかめた？	","letter": "	How's it going? You getting the hang of it, Penguin?	", "pinyin":"	どう？ぺんぎんさんこつはつかめた？	"},																			
"	279	":{"character":"	何の？	","letter": "	The what?	", "pinyin":"	なんの？	"},																			
"	280	":{"character":"	ドライブスルーで遊ぶコツ？	","letter": "	Tips for playing in the drive-thru?	", "pinyin":"	どらいぶするーであそぶこつ？	"},																			
"	281	":{"character":"	僕は運転のコツをつかみたいんだけどな～	","letter": "	I'm trying to get the hang of driving.	", "pinyin":"	ぼくはうんてんのこつをつかみたいんだけどな～	"},																			
"	282	":{"character":"	ねえシロクマくんあれはやらないの？	","letter": "	Hey, Polar Bear, are you gonna try that?	", "pinyin":"	ねえしろくまくんあれはやらないの？	"},																			
"	283	":{"character":"	あれ？	","letter": "	What's that?	", "pinyin":"	あれ？	"},																			
"	284	":{"character":"	ほらわらしべ長者	","letter": "	You know, the whack-a-mole thing?	", "pinyin":"	ほらわらしべちょうじゃ	"},																			
"	285	":{"character":"	縦列駐車のこと？	","letter": "	Parallel parking?	", "pinyin":"	じゅうれつちゅうしゃのこと？	"},																			
"	286	":{"character":"	それそれ	","letter": "	That's it.	", "pinyin":"	それそれ	"},																			
"	287	":{"character":"	全然違うから	","letter": "	That's totally different.	", "pinyin":"	ぜんぜんちがうから	"},																			
"	288	":{"character":"	ペンギンさんよくわかったね	","letter": "	Well, Penguin, you've got it all figured out.	", "pinyin":"	ぺんぎんさんよくわかったね	"},																			
"	289	":{"character":"	ねぇやってみてよシロクマくん	","letter": "	Come on, Polar Bear.	", "pinyin":"	ねぇやってみてよしろくまくん	"},																			
"	290	":{"character":"	ちゃんと運転のコツ教えてよ	","letter": "	Teach me how to drive like a good driver.	", "pinyin":"	ちゃんとうんてんのこつおしえてよ	"},																			
"	291	":{"character":"	うんわかった	","letter": "	Yeah, I got it.	", "pinyin":"	うんわかった	"},																			
"	292	":{"character":"	よしここにしよう	","letter": "	Okay, here we go.	", "pinyin":"	よしここにしよう	"},																			
"	293	":{"character":"	じゃあよく見ててね	","letter": "	Now, watch me carefully, okay?	", "pinyin":"	じゃあよくみててね	"},																			
"	294	":{"character":"	うん	","letter": "	Okay.	", "pinyin":"	うん	"},																			
"	295	":{"character":"	周りをよく見てバックする	","letter": "	I'm gonna watch the road and I'm gonna back up.	", "pinyin":"	まわりをよくみてばっくする	"},																			
"	296	":{"character":"	よく見てバックね	","letter": "	Watch your back.	", "pinyin":"	よくみてばっくね	"},																			
"	297	":{"character":"	コツはね…	","letter": "	The trick is to...	", "pinyin":"	こつはね…	"},																			
"	298	":{"character":"	コツは？	","letter": "	The trick?	", "pinyin":"	こつは？	"},																			
"	299	":{"character":"	こうやって上からだと見やすい	","letter": "	It's easier to see from above, like this.	", "pinyin":"	こうやってうえからだとみやすい	"},																			
"	300	":{"character":"	あっ何？	","letter": "	Oh, what?	", "pinyin":"	あっなに？	"},																			
"	301	":{"character":"	大丈夫？ぶつけた？	","letter": "	Are you okay? Did you hit it?	", "pinyin":"	だいじょうぶ？ぶつけた？	"},																			
"	302	":{"character":"	お～い！笹子さ～ん！	","letter": "	Hey! Sasago-san!	", "pinyin":"	お～い！ささごさ～ん！	"},																			
"	303	":{"character":"	あっシロクマさん	","letter": "	Hey, Polar Bear!	", "pinyin":"	あっしろくまさん	"},																			
"	304	":{"character":"	今日は皆さんでドライブですか？どちらまで？	","letter": "	Are you guys going for a drive today? Where to?	", "pinyin":"	きょうはみなさんでどらいぶですか？どちらまで？	"},																			
"	305	":{"character":"	当てのない旅です	","letter": "	It's a random trip.	", "pinyin":"	あてのないたびです	"},																			
"	306	":{"character":"	笹子さんは？	","letter": "	Where's Sasago-san?	", "pinyin":"	ささごさんは？	"},																			
"	307	":{"character":"	家に帰るところです	","letter": "	She's on her way home.	", "pinyin":"	いえにかえるところです	"},																			
"	308	":{"character":"	あ…そうだ	","letter": "	Oh... that's right.	", "pinyin":"	あ…そうだ	"},																			
"	309	":{"character":"	これおすそ分け	","letter": "	I'll share this with you.	", "pinyin":"	これおすそわけ	"},																			
"	310	":{"character":"	ベーグル？	","letter": "	Bagels?	", "pinyin":"	べーぐる？	"},																			
"	311	":{"character":"	この先においしいお店があるって聞いて買いに行ったんです	","letter": "	I heard there's a great place down the street, so I went to buy some.	", "pinyin":"	このさきにおいしいおみせがあるってきいてかいにいったんです	"},																			
"	312	":{"character":"	わぁ～ありがとうO(∩_∩)O	","letter": "	Wow! Thank you!	", "pinyin":"	わぁ～ありがとうO(∩_∩)O	"},																			
"	313	":{"character":"	ちょうどお腹が減ってたんだ	","letter": "	I was just hungry.	", "pinyin":"	ちょうどおなかがへってたんだ	"},																			
"	314	":{"character":"	食べてばっかりだね	","letter": "	You eat a lot, don't you?	", "pinyin":"	たべてばっかりだね	"},																			
"	315	":{"character":"	育ち盛りだもの	","letter": "	You're growing up.	", "pinyin":"	そだちざかりだもの	"},																			
"	316	":{"character":"	大丈夫です…笹は別腹ですから	","letter": "	Don't worry... we're not hungry for bamboo grass.	", "pinyin":"	だいじょうぶです…ささはべつばらですから	"},																			
"	317	":{"character":"	パンダくん夢のなかでもまだ食べてるみたいだね	","letter": "	Panda, it looks like you're still eating in your dream.	", "pinyin":"	ぱんだくんゆめのなかでもまだたべてるみたいだね	"},																			
"	318	":{"character":"	ペンギンさん？	","letter": "	Penguin?	", "pinyin":"	ぺんぎんさん？	"},																			
"	319	":{"character":"	助手席で寝るなんて失礼なこと僕はしないよ！	","letter": "	I wouldn't be rude to sleep in the passenger seat!	", "pinyin":"	じょしゅせきでねるなんてしつれいなことぼくはしないよ！	"},																			
"	320	":{"character":"	ペンギンさんって黙ってると寝てるか起きてるかわからないね	","letter": "	Penguins can't tell if you're asleep or awake when you don't talk.	", "pinyin":"	ぺんぎんさんってだまってるとねてるかおきてるかわからないね	"},																			
"	321	":{"character":"	起きてる！ほんと信じて！	","letter": "	I'm awake! Trust me!	", "pinyin":"	おきてる！ほんとしんじて！	"},																			
"	322	":{"character":"	いや寝ててもかまわないけど	","letter": "	I don't care if you're asleep.	", "pinyin":"	いやねててもかまわないけど	"},																			
"	323	":{"character":"	パンダくんと一緒にしないでよ！	","letter": "	I don't care if you're asleep or not, but you're not a panda!	", "pinyin":"	ぱんだくんといっしょにしないでよ！	"},																			
"	324	":{"character":"	僕は運転のコツを学ぶんだから	","letter": "	I'm learning how to drive.	", "pinyin":"	ぼくはうんてんのこつをまなぶんだから	"},																			
"	325	":{"character":"	免許取ったら車買うの？	","letter": "	Are you going to buy a car when you get your license?	", "pinyin":"	めんきょとったらくるまかうの？	"},																			
"	326	":{"character":"	え？う～んどうしようかなぁ	","letter": "	What? I don't know what I'm going to do.	", "pinyin":"	え？う～んどうしようかなぁ	"},																			
"	327	":{"character":"	この車みたいなミニバンもいいよね～	","letter": "	A minivan like this one is nice, isn't it?	", "pinyin":"	このくるまみたいなみにばんもいいよね～	"},																			
"	328	":{"character":"	ああいうのもかっこいいな～	","letter": "	That kind of thing is cool too!	", "pinyin":"	ああいうのもかっこいいな～	"},																			
"	329	":{"character":"	ペン子さん君に見せたいものがあるんだ	","letter": "	Mr. Penko, I want to show you something.	", "pinyin":"	ぺんごさんきみにみせたいものがあるんだ	"},																			
"	330	":{"character":"	わぁ～何かしら？	","letter": "	Wow, what is it?	", "pinyin":"	わぁ～なにかしら？	"},																			
"	331	":{"character":"	ほら見てごらん	","letter": "	Look at this	", "pinyin":"	ほらみてごらん	"},																			
"	332	":{"character":"	トビウオさ	","letter": "	A flying fish.	", "pinyin":"	とびうおさ	"},																			
"	333	":{"character":"	まぁ～！	","letter": "	Oh, my gosh!	", "pinyin":"	まぁ～！	"},																			
"	334	":{"character":"	食べ放題ですよo(*￣▽￣*)o	","letter": "	You can eat as much as you like!	", "pinyin":"	たべほうだいですよo(*￣▽￣*)o	"},																			
"	335	":{"character":"	すてき…	","letter": "	Lovely...	", "pinyin":"	すてき…	"},																			
"	336	":{"character":"	ペン子さん…	","letter": "	Penko...	", "pinyin":"	ぺんごさん…	"},																			
"	337	":{"character":"	笹だらけ…	","letter": "	Bamboos everywhere...	", "pinyin":"	ささだらけ…	"},																			
"	338	":{"character":"	ベーグル？	","letter": "	Bagels?	", "pinyin":"	べーぐる？	"},																			
"	339	":{"character":"	イーグル？	","letter": "	Eagle?	", "pinyin":"	いーぐる？	"},																			
"	340	":{"character":"	サーベル？	","letter": "	Saber?	", "pinyin":"	さーべる？	"},																			
"	341	":{"character":"	ヨロレヒヒ～！ヨーデル？	","letter": "	Yolorehihi~! Yodel?	", "pinyin":"	よろれひひ～！よーでる？	"},																			
"	342	":{"character":"	うん…ツッコんでくれる相手がいないとは寂しいね	","letter": "	Yeah... it's sad that you don't have anyone to play with.	", "pinyin":"	うん…つっこんでくれるあいてがいないとはさびしいね	"},																			
"	343	":{"character":"	何なに？	","letter": "	What is it?	", "pinyin":"	なになに？	"},																			
"	344	":{"character":"	これって…	","letter": "	It's...	", "pinyin":"	これって…	"},																			
"	345	":{"character":"	あれだね	","letter": "	That.	", "pinyin":"	あれだね	"},																			
"	346	":{"character":"	それはダンク	","letter": "	That's dank.	", "pinyin":"	それはだんく	"},																			
"	347	":{"character":"	それはインク	","letter": "	That's ink.	", "pinyin":"	それはいんく	"},																			
"	348	":{"character":"	それはピンク	","letter": "	That's pink.	", "pinyin":"	それはぴんく	"},																			
"	349	":{"character":"	それはスカンク	","letter": "	That's skunk.	", "pinyin":"	それはすかんく	"},																			
"	350	":{"character":"	いいねo(*^▽^*)o	","letter": "	That's a good one.	", "pinyin":"	いいねo(*^▽^*)o	"},																			
"	351	":{"character":"	何言ってるの？よくないでしょ	","letter": "	What are you talking about? It's not good.	", "pinyin":"	なにいってるの？よくないでしょ	"},																			
"	352	":{"character":"	どうするの？ペンギンさん	","letter": "	What are you doing? Mr. Penguin.	", "pinyin":"	どうするの？ぺんぎんさん	"},																			
"	353	":{"character":"	そうだなぁ車屋さん呼べばいいのかなぁ	","letter": "	I don't know... call an auto shop.	", "pinyin":"	そうだなぁくるまやさんよべばいいのかなぁ	"},																			
"	354	":{"character":"	慌てない慌てない	","letter": "	No need to panic, no need to panic.	", "pinyin":"	あわてないあわてない	"},																			
"	355	":{"character":"	こういうときはね	","letter": "	You know, in that case...	", "pinyin":"	こういうときはね	"},																			
"	356	":{"character":"	引いて帰ればいいから	","letter": "	Just pull over and go home.	", "pinyin":"	ひいてかえればいいから	"},																			
"	357	":{"character":"	なるほどね	","letter": "	I see.	", "pinyin":"	なるほどね	"},																			
"	358	":{"character":"	コツはバンパーにツメを引っ掛ける	","letter": "	The trick is to hook the claws in the bumper.	", "pinyin":"	こつはばんぱーにつめをひっかける	"},																			
"	359	":{"character":"	いろいろ教えてもらえてよかったね	","letter": "	I'm glad you're learning all this stuff.	", "pinyin":"	いろいろおしえてもらえてよかったね	"},																			
"	360	":{"character":"	絶対真似はできないけどね	","letter": "	I can never imitate it, though.	", "pinyin":"	ぜったいまねはできないけどね	"},																			
"	361	":{"character":"	まぁでもおもしろいから写真撮っておこう(＾－＾)V	","letter": "	But it's fun, so I'll take a picture of it.	", "pinyin":"	まぁでもおもしろいからしゃしんとっておこう(＾－＾)V	"},																			
"	362	":{"character":"	ペンギンさんペンギンさん何か面白い話して	","letter": "	Penguin, Penguin, Penguin, tell me something funny.	", "pinyin":"	ぺんぎんさんぺんぎんさんなにかおもしろいはなして	"},																			
"	363	":{"character":"	お～パンダ君	","letter": "	Oh, Mr. Panda!	", "pinyin":"	お～ぱんだくん	"},																			
"	364	":{"character":"	絵に書いたようなむちゃぶりだね	","letter": "	You are just like the picture of a panda.	", "pinyin":"	えにかいたようなむちゃぶりだね	"},																			
"	365	":{"character":"	じゃ～今日からペンギンさんのこと忠実な下部と考えていい	","letter": "	Well then, from today onwards, you can consider Mr. Penguin as your loyal subordinate.	", "pinyin":"	じゃ～きょうからぺんぎんさんのことちゅうじつなかぶとかんがえていい	"},																			
"	366	":{"character":"	ダメ	","letter": "	No.	", "pinyin":"	だめ	"},																			
"	367	":{"character":"	ペンギンさんって絵に書いたようにケチだね	","letter": "	Penguin, you are as stingy as it gets.	", "pinyin":"	ぺんぎんさんってえにかいたようにけちだね	"},																			
"	368	":{"character":"	白熊君	","letter": "	Polar bear.	", "pinyin":"	しろくまくん	"},																			
"	369	":{"character":"	さ～て来週のしろくまカフェは	","letter": "	So, next week at the Shirokuma Cafe...	", "pinyin":"	さ～てらいしゅうのしろくまかふぇは	"},																			
"	370	":{"character":"	ジャンケン	","letter": "	Rock, paper, scissors!	", "pinyin":"	じゃんけん	"},																			
"	371	":{"character":"	ちょっとやめてそういうの	","letter": "	Stop it!	", "pinyin":"	ちょっとやめてそういうの	"},																			
"	372	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},		
}																	