obj = {
"	1	":{"character":"	七夕飾り	","letter": "	Tanabata Decoration	", "pinyin":"	たなばたかざり	"},
"	2	":{"character":"	あれ？	","letter": "	Huh?	", "pinyin":"	あれ？	"},
"	3	":{"character":"	あんなところにおいしそうな笹が落ちてる	","letter": "	There's a tasty-looking bamboo branch down there!	", "pinyin":"	あんなところにおいしそうなささがおちてる	"},
"	4	":{"character":"	ちょっと味見	","letter": "	Just a little taste!	", "pinyin":"	ちょっとあじみ	"},
"	5	":{"character":"	おいしい！	","letter": "	Delicious!	", "pinyin":"	おいしい！	"},
"	6	":{"character":"	まったくもう…	","letter": "	What a waste...	", "pinyin":"	まったくもう…	"},
"	7	":{"character":"	もったいないな	","letter": "	What a waste!	", "pinyin":"	もったいないな	"},
"	8	":{"character":"	おいしい！	","letter": "	Delicious!	", "pinyin":"	おいしい！	"},
"	9	":{"character":"	あっパンダくん	","letter": "	Oh, Mr. Panda.	", "pinyin":"	あっぱんだくん	"},
"	10	":{"character":"	この笹どうするの？	","letter": "	What are we going to do with all this bamboo?	", "pinyin":"	このささどうするの？	"},
"	11	":{"character":"	笹パーティー？	","letter": "	Bamboo grass party?	", "pinyin":"	ささぱーてぃー？	"},
"	12	":{"character":"	笹パーティー？	","letter": "	Bamboo grass party?	", "pinyin":"	ささぱーてぃー？	"},
"	13	":{"character":"	笹だらけのパーティーだよ	","letter": "	We're having a party with lots of bamboos!	", "pinyin":"	ささだらけのぱーてぃーだよ	"},
"	14	":{"character":"	七夕飾りに使うんだよ	","letter": "	We're going to use them for tanabata decorations.	", "pinyin":"	たなばたかざりにつかうんだよ	"},
"	15	":{"character":"	明日七夕だから	","letter": "	Tomorrow is Tanabata.	", "pinyin":"	あしたたなばただから	"},
"	16	":{"character":"	七夕？	","letter": "	Tanabata?	", "pinyin":"	たなばた？	"},
"	17	":{"character":"	それは棚ぼた	","letter": "	That's just a shelf	", "pinyin":"	それはたなぼた	"},
"	18	":{"character":"	それは井戸端	","letter": "	It's a well	", "pinyin":"	それはいどばた	"},
"	19	":{"character":"	それは花畑	","letter": "	That's a flower garden.	", "pinyin":"	それははなばたけ	"},
"	20	":{"character":"	七夕はね夏のお祭りだよ	","letter": "	Tanabata is a summer festival.	", "pinyin":"	たなばたはねなつのおまつりだよ	"},
"	21	":{"character":"	年に１回のね	","letter": "	Once a year.	", "pinyin":"	ねんに１かいのね	"},
"	22	":{"character":"	お祭り？やっぱり笹パーティー？	","letter": "	A festival? Is it still a bamboo grass party?	", "pinyin":"	おまつり？やっぱりささぱーてぃー？	"},
"	23	":{"character":"	違うよ	","letter": "	No, it's not.	", "pinyin":"	ちがうよ	"},
"	24	":{"character":"	違うの？	","letter": "	No?	", "pinyin":"	ちがうの？	"},
"	25	":{"character":"	それで神様が怒ってしまい	","letter": "	That's why the gods got mad.	", "pinyin":"	それでかみさまがいかってしまい	"},
"	26	":{"character":"	彦星と引き離されたんだよね	","letter": "	And Hikoboshi was separated from her.	", "pinyin":"	ひこぼしとひきはなされたんだよね	"},
"	27	":{"character":"	で七夕っていうのは	","letter": "	That's why Tanabata is called...	", "pinyin":"	でたなばたっていうのは	"},
"	28	":{"character":"	その彦星と織姫の２人がね…	","letter": "	Hikoboshi and Orihime...	", "pinyin":"	そのひこぼしとおりひめの２にんがね…	"},
"	29	":{"character":"	鬼姫？	","letter": "	The devil princess?	", "pinyin":"	おにひめ？	"},
"	30	":{"character":"	なんで怖い人がいるの？	","letter": "	Why is there a scary person?	", "pinyin":"	なんでこわいひとがいるの？	"},
"	31	":{"character":"	つまりね彦星と織姫と鬼姫の３人が揃うと	","letter": "	When Hikoboshi, Orihime and Onihime come together...	", "pinyin":"	つまりねひこぼしとおりひめとおにひめの３にんがそろうと	"},
"	32	":{"character":"	夏の夜空に大三角が完成	","letter": "	They make a big triangle in the summer night sky.	", "pinyin":"	なつのよぞらにだいさんかくがかんせい	"},
"	33	":{"character":"	違うよ！	","letter": "	No, it's not!	", "pinyin":"	ちがうよ！	"},
"	34	":{"character":"	三角関係ってやつ？	","letter": "	A love triangle?	", "pinyin":"	さんかくかんけいってやつ？	"},
"	35	":{"character":"	それも違うよ！	","letter": "	No, that's not it either!	", "pinyin":"	それもちがうよ！	"},
"	36	":{"character":"	でねその彦星と織姫の２人が…	","letter": "	And when Hikoboshi and Orihime...	", "pinyin":"	でねそのひこぼしとおりひめの２にんが…	"},
"	37	":{"character":"	って…	","letter": "	And...	", "pinyin":"	って…	"},
"	38	":{"character":"	おいしい！	","letter": "	Delicious!	", "pinyin":"	おいしい！	"},
"	39	":{"character":"	ちょっと…聞いてる？	","letter": "	Are you listening to me?	", "pinyin":"	ちょっと…きいてる？	"},
"	40	":{"character":"	聞いてるよ鬼の三角関係	","letter": "	I'm listening... to the devil's love triangle.	", "pinyin":"	きいてるよおにのさんかくかんけい	"},
"	41	":{"character":"	違うってばもう…	","letter": "	No, I mean...	", "pinyin":"	ちがうってばもう…	"},
"	42	":{"character":"	七夕のこと教えてって言ったのパンダくんでしょう？	","letter": "	You're the panda who asked me to tell you about Tanabata, right?	", "pinyin":"	たなばたのことおしえてっていったのぱんだくんでしょう？	"},
"	43	":{"character":"	それで笹はいつ食べるの？	","letter": "	When are we going to eat the bamboo branches?	", "pinyin":"	それでささはいつたべるの？	"},
"	44	":{"character":"	だから食べないって	","letter": "	I told you I don't eat them.	", "pinyin":"	だからたべないって	"},
"	45	":{"character":"	紙なんかで作った飾りをいっぱいつけて	","letter": "	We're going to decorate it with paper ornaments.	", "pinyin":"	かみなんかでつくったかざりをいっぱいつけて	"},
"	46	":{"character":"	それから願いごとを書いた短冊なんかもぶら下げるんだよ	","letter": "	And hang strips of paper with wishes on them.	", "pinyin":"	それからねがいごとをかいたたんざくなんかもぶらさげるんだよ	"},
"	47	":{"character":"	そんなにいろいろつけたら食べるとき邪魔だよ	","letter": "	If you put so many decorations on the bamboos, they'll get in the way when we eat them.	", "pinyin":"	そんなにいろいろつけたらたべるときじゃまだよ	"},
"	48	":{"character":"	聞いてないなあの笹は食べないんだって	","letter": "	You didn't tell me we don't eat those bamboos.	", "pinyin":"	きいてないなあのささはたべないんだって	"},
"	49	":{"character":"	それを先に言ってよ	","letter": "	Tell me that first!	", "pinyin":"	それをさきにいってよ	"},
"	50	":{"character":"	言ってるよ！！	","letter": "	I told you!	", "pinyin":"	いってるよ！！	"},
"	51	":{"character":"	笹を食べずに短冊をぶら下げたら	","letter": "	If you hang strips of paper instead of eating them...	", "pinyin":"	ささをたべずにたんざくをぶらさげたら	"},
"	52	":{"character":"	願いごとが叶うよ	","letter": "	Your wish will come true!	", "pinyin":"	ねがいごとがかなうよ	"},
"	53	":{"character":"	どんな願いごとでも？	","letter": "	Any wish?	", "pinyin":"	どんなねがいごとでも？	"},
"	54	":{"character":"	小さいのなら	","letter": "	As long as it's a small one.	", "pinyin":"	ちいさいのなら	"},
"	55	":{"character":"	大きい願いはダメなの？	","letter": "	No big wishes?	", "pinyin":"	おおきいねがいはだめなの？	"},
"	56	":{"character":"	中くらいなら大丈夫じゃない？	","letter": "	Medium ones are fine, right?	", "pinyin":"	なかくらいならだいじょうぶじゃない？	"},
"	57	":{"character":"	何なの？それ	","letter": "	What is it? That.	", "pinyin":"	なになの？それ	"},
"	58	":{"character":"	ねぇ笹子さん	","letter": "	Hey, Sasago...	", "pinyin":"	ねぇささごさん	"},
"	59	":{"character":"	それが願いごとを書く紙？	","letter": "	Is that the paper you write your wish on?	", "pinyin":"	それがねがいごとをかくかみ？	"},
"	60	":{"character":"	ああ…これは飾りを作ってるんだよ	","letter": "	Oh... we're making decorations.	", "pinyin":"	ああ…これはかざりをつくってるんだよ	"},
"	61	":{"character":"	おもしろそうだね	","letter": "	Sounds interesting.	", "pinyin":"	おもしろそうだね	"},
"	62	":{"character":"	パンダくんもやる？	","letter": "	Do you want to do it, too, Panda?	", "pinyin":"	ぱんだくんもやる？	"},
"	63	":{"character":"	うん！やるやる！	","letter": "	Yes! I'll do it!	", "pinyin":"	うん！やるやる！	"},
"	64	":{"character":"	こんにちは	","letter": "	Hello.	", "pinyin":"	こんにちは	"},
"	65	":{"character":"	お待たせしました	","letter": "	Sorry to keep you waiting.	", "pinyin":"	おまたせしました	"},
"	66	":{"character":"	あっ…どうも	","letter": "	Oh... hi.	", "pinyin":"	あっ…どうも	"},
"	67	":{"character":"	半田さん動物園は今日はお休みなんですか？	","letter": "	Mr. Handa, is the zoo closed today?	", "pinyin":"	はんでんさんどうぶつえんはきょうはおやすみなんですか？	"},
"	68	":{"character":"	えっ！？は…はい…	","letter": "	What? Yes...	", "pinyin":"	えっ！？は…はい…	"},
"	69	":{"character":"	最近よくいらっしゃいますよね	","letter": "	You've been here a lot lately, haven't you?	", "pinyin":"	さいきんよくいらっしゃいますよね	"},
"	70	":{"character":"	あっ…いえ	","letter": "	Oh...no...	", "pinyin":"	あっ…いえ	"},
"	71	":{"character":"	いやはい！	","letter": "	Yes, yes!	", "pinyin":"	いやはい！	"},
"	72	":{"character":"	こ…ここに来ると…	","letter": "	When I come here...	", "pinyin":"	こ…ここにくると…	"},
"	73	":{"character":"	はい？	","letter": "	Yes?	", "pinyin":"	はい？	"},
"	74	":{"character":"	あっあぁいや	","letter": "	Oh, no.	", "pinyin":"	あっあぁいや	"},
"	75	":{"character":"	こ…心が落ち着くというか	","letter": "	I feel at home.	", "pinyin":"	こ…こころがおちつくというか	"},
"	76	":{"character":"	そうなんですか	","letter": "	I see.	", "pinyin":"	そうなんですか	"},
"	77	":{"character":"	あっじゃあお邪魔しちゃ悪いですね	","letter": "	I'm sorry for interrupting you.	", "pinyin":"	あっじゃあおじゃましちゃわるいですね	"},
"	78	":{"character":"	ごゆっくり	","letter": "	Take your time.	", "pinyin":"	ごゆっくり	"},
"	79	":{"character":"	ねぇ笹子さんこれどうやるの？	","letter": "	Sasago, how do you do this?	", "pinyin":"	ねぇささごさんこれどうやるの？	"},
"	80	":{"character":"	どうしたの？	","letter": "	How did you do it?	", "pinyin":"	どうしたの？	"},
"	81	":{"character":"	どうしたらこうなるか不思議だよ	","letter": "	I wonder how it works.	", "pinyin":"	どうしたらこうなるかふしぎだよ	"},
"	82	":{"character":"	ある意味器用だね	","letter": "	You're pretty good at it.	", "pinyin":"	あるいみきようだね	"},
"	83	":{"character":"	もうそんなこと言っちゃダメですよ	","letter": "	Don't say that.	", "pinyin":"	もうそんなこといっちゃだめですよ	"},
"	84	":{"character":"	いい？ここはね	","letter": "	Okay? Here.	", "pinyin":"	いい？ここはね	"},
"	85	":{"character":"	まずはこっちから折るんだよ	","letter": "	We'll start by folding this side.	", "pinyin":"	まずはこっちからおるんだよ	"},
"	86	":{"character":"	こう？	","letter": "	Like this?	", "pinyin":"	こう？	"},
"	87	":{"character":"	パンダくん反対	","letter": "	Panda, the other way.	", "pinyin":"	ぱんだくんはんたい	"},
"	88	":{"character":"	それを３枚におろして…	","letter": "	And then you fold it into three pieces...	", "pinyin":"	それを３まいにおろして…	"},
"	89	":{"character":"	できた！	","letter": "	It's done!	", "pinyin":"	できた！	"},
"	90	":{"character":"	何それ？	","letter": "	What's that?	", "pinyin":"	なにそれ？	"},
"	91	":{"character":"	パンダだよ	","letter": "	It's a panda.	", "pinyin":"	ぱんだだよ	"},
"	92	":{"character":"	ああそう	","letter": "	Yes, it's a panda.	", "pinyin":"	ああそう	"},
"	93	":{"character":"	白黒模様ではあるね	","letter": "	It's black and white.	", "pinyin":"	しろくろもようではあるね	"},
"	94	":{"character":"	はい笹子さん	","letter": "	Yes, Sasago?	", "pinyin":"	はいささごさん	"},
"	95	":{"character":"	じゃあ飾りはひとまず置いといて	","letter": "	Okay, let's leave the decorations for now.	", "pinyin":"	じゃあかざりはひとまずおいといて	"},
"	96	":{"character":"	次は短冊を作るね	","letter": "	Next, we'll make strips of paper.	", "pinyin":"	つぎはたんざくをつくるね	"},
"	97	":{"character":"	願いごとを書くやつ？	","letter": "	The kind you write your wishes on?	", "pinyin":"	ねがいごとをかくやつ？	"},
"	98	":{"character":"	そうそう	","letter": "	That's right.	", "pinyin":"	そうそう	"},
"	99	":{"character":"	これに願いごとを書いてね	","letter": "	Write your wishes on it.	", "pinyin":"	これにねがいごとをかいてね	"},
"	100	":{"character":"	明日の夕方までに持ってきてくれたら	","letter": "	If you bring it to me by tomorrow evening.	", "pinyin":"	あしたのゆうがたまでにもってきてくれたら	"},
"	101	":{"character":"	笹につるすから	","letter": "	I'll hang it on the bamboo branch.	", "pinyin":"	ささにつるすから	"},
"	102	":{"character":"	これに中くらいまでの願いごとを書くの？	","letter": "	You're going to write medium-length wishes on this?	", "pinyin":"	これになかくらいまでのねがいごとをかくの？	"},
"	103	":{"character":"	なんでも大丈夫だと思うよ	","letter": "	I think anything will be fine.	", "pinyin":"	なんでもだいじょうぶだとおもうよ	"},
"	104	":{"character":"	えっ？なんでもいいの？	","letter": "	What? Anything is okay?	", "pinyin":"	えっ？なんでもいいの？	"},
"	105	":{"character":"	なんでもいいんだよ	","letter": "	Anything is fine.	", "pinyin":"	なんでもいいんだよ	"},
"	106	":{"character":"	どうしようかな～！	","letter": "	I don't know what to do!	", "pinyin":"	どうしようかな～！	"},
"	107	":{"character":"	はいペンギンさんもどうぞ	","letter": "	Here you go, Penguin!	", "pinyin":"	はいぺんぎんさんもどうぞ	"},
"	108	":{"character":"	真剣だね	","letter": "	You're so serious.	", "pinyin":"	しんけんだね	"},
"	109	":{"character":"	なんでもいいんでしょ？	","letter": "	Anything is fine, right?	", "pinyin":"	なんでもいいんでしょ？	"},
"	110	":{"character":"	ペン子さんへの気持はなんでもよくないよ	","letter": "	I don't care what I feel for Penko-san.	", "pinyin":"	ぺんごさんへのきもちはなんでもよくないよ	"},
"	111	":{"character":"	１枚じゃ足りないな	","letter": "	One's not enough.	", "pinyin":"	１まいじゃたりないな	"},
"	112	":{"character":"	笹子さん１０枚ちょうだい	","letter": "	Sasako, give me 10.	", "pinyin":"	ささごさん１０まいちょうだい	"},
"	113	":{"character":"	ずるい	","letter": "	That's not fair.	", "pinyin":"	ずるい	"},
"	114	":{"character":"	じゃあ僕は２０枚	","letter": "	I'll take 20.	", "pinyin":"	じゃあぼくは２０まい	"},
"	115	":{"character":"	１人１枚です	","letter": "	One for each of you.	", "pinyin":"	１にん１まいです	"},
"	116	":{"character":"	どうぞ	","letter": "	Here you go.	", "pinyin":"	どうぞ	"},
"	117	":{"character":"	な…なんでしょう？	","letter": "	What is it?	", "pinyin":"	な…なんでしょう？	"},
"	118	":{"character":"	半田さんもはい	","letter": "	You too, Mr. Handa.	", "pinyin":"	はんでんさんもはい	"},
"	119	":{"character":"	短冊です七夕の	","letter": "	They're tanzaku, paper strips for the Tanabata Festival.	", "pinyin":"	たんざくですたなばたの	"},
"	120	":{"character":"	ありがとうございます	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございます	"},
"	121	":{"character":"	明日は七夕デーで夜遅くまでやってますからね	","letter": "	Tomorrow is Tanabata Day. We'll be open late.	", "pinyin":"	あしたはたなばたでーでよるおそくまでやってますからね	"},
"	122	":{"character":"	あっはい	","letter": "	Oh, yes.	", "pinyin":"	あっはい	"},
"	123	":{"character":"	それじゃ	","letter": "	Well then...	", "pinyin":"	それじゃ	"},
"	124	":{"character":"	お願い何書こう	","letter": "	What shall we write?	", "pinyin":"	おねがいなにかこう	"},
"	125	":{"character":"	笹がいっぱい食べられますようにって	","letter": "	He wants us to eat a lot of bamboo grass.	", "pinyin":"	ささがいっぱいたべられますようにって	"},
"	126	":{"character":"	どうかな？	","letter": "	I don't know about that.	", "pinyin":"	どうかな？	"},
"	127	":{"character":"	パンダくんいつもいっぱい食べてるじゃない	","letter": "	Panda always eats a lot!	", "pinyin":"	ぱんだくんいつもいっぱいたべてるじゃない	"},
"	128	":{"character":"	ペンギンさんは何書いたの？	","letter": "	What did you write, Penguin?	", "pinyin":"	ぺんぎんさんはなにかいたの？	"},
"	129	":{"character":"	まだだよ	","letter": "	Not yet.	", "pinyin":"	まだだよ	"},
"	130	":{"character":"	１枚しかないから迷っちゃうね	","letter": "	There's only one, so I'm not sure what to write on it.	", "pinyin":"	１まいしかないからまよっちゃうね	"},
"	131	":{"character":"	みんな何書いてるんだろう？	","letter": "	I wonder what they're all writing.	", "pinyin":"	みんななにかいてるんだろう？	"},
"	132	":{"character":"	お嫁さんが欲しい	","letter": "	I want a wife.	", "pinyin":"	およめさんがほしい	"},
"	133	":{"character":"	いやそもそもその前に彼女だよな	","letter": "	No, you need a girlfriend first.	", "pinyin":"	いやそもそもそのまえにかのじょだよな	"},
"	134	":{"character":"	すみません	","letter": "	Excuse me.	", "pinyin":"	すみません	"},
"	135	":{"character":"	は～い！ちょっとお待ちくださ～い！	","letter": "	Yes! Hold on a minute!	", "pinyin":"	は～い！ちょっとおまちくださ～い！	"},
"	136	":{"character":"	笹子さんかわいいな	","letter": "	Sasako's cute.	", "pinyin":"	ささごさんかわいいな	"},
"	137	":{"character":"	すみませんなんでもないですはい	","letter": "	I'm sorry... it's nothing.	", "pinyin":"	すみませんなんでもないですはい	"},
"	138	":{"character":"	パンダくん聞いた？	","letter": "	Did you hear, Panda?	", "pinyin":"	ぱんだくんきいた？	"},
"	139	":{"character":"	かわいいよねぇ	","letter": "	He's cute, isn't he?	", "pinyin":"	かわいいよねぇ	"},
"	140	":{"character":"	いや別にそれだけが目的じゃ…	","letter": "	That's not the only reason...	", "pinyin":"	いやべつにそれだけがもくてきじゃ…	"},
"	141	":{"character":"	こ…このカフェコーヒーおいしいし	","letter": "	This cafe has great coffee.	", "pinyin":"	こ…このかふぇこーひーおいしいし	"},
"	142	":{"character":"	半田さん動物園で会えるのに	","letter": "	Mr. Handa, you could've seen me at the zoo.	", "pinyin":"	はんでんさんどうぶつえんであえるのに	"},
"	143	":{"character":"	かわいい僕を見にカフェに来るなんて	","letter": "	But you came to a café to see me, a cute little panda.	", "pinyin":"	かわいいぼくをみにかふぇにくるなんて	"},
"	144	":{"character":"	もう	","letter": "	Oh, my God.	", "pinyin":"	もう	"},
"	145	":{"character":"	かわいいからね僕	","letter": "	I'm cute.	", "pinyin":"	かわいいからねぼく	"},
"	146	":{"character":"	違うでしょ！かわいいのは笹子さん	","letter": "	No, you're not! Sasago-san's cute.	", "pinyin":"	ちがうでしょ！かわいいのはささごさん	"},
"	147	":{"character":"	笹子さん！	","letter": "	Sasago-san!	", "pinyin":"	ささごさん！	"},
"	148	":{"character":"	あのね…	","letter": "	You know...	", "pinyin":"	あのね…	"},
"	149	":{"character":"	ダメ！！	","letter": "	No!	", "pinyin":"	だめ！！	"},
"	150	":{"character":"	なんで？	","letter": "	Why not?	", "pinyin":"	なんで？	"},
"	151	":{"character":"	まだそんな関係じゃないから！	","letter": "	Because we don't have that kind of relationship yet!	", "pinyin":"	まだそんなかんけいじゃないから！	"},
"	152	":{"character":"	そうなの？	","letter": "	Really?	", "pinyin":"	そうなの？	"},
"	153	":{"character":"	そうなの！	","letter": "	Yes, we are!	", "pinyin":"	そうなの！	"},
"	154	":{"character":"	わかった	","letter": "	Okay, okay.	", "pinyin":"	わかった	"},
"	155	":{"character":"	もう…	","letter": "	Oh, no...	", "pinyin":"	もう…	"},
"	156	":{"character":"	ねぇ笹子さん	","letter": "	Hey, Sasago...	", "pinyin":"	ねぇささごさん	"},
"	157	":{"character":"	動物の世話好きな男性とかどう思う？	","letter": "	What do you think of men who like taking care of animals?	", "pinyin":"	どうぶつのせわずきなだんせいとかどうおもう？	"},
"	158	":{"character":"	あとパンダみたいな体型の男の人…	","letter": "	And men who look like pandas...	", "pinyin":"	あとぱんだみたいなたいけいのおとこのひと…	"},
"	159	":{"character":"	パ…パンダくん！	","letter": "	Panda!	", "pinyin":"	ぱ…ぱんだくん！	"},
"	160	":{"character":"	どう思う？	","letter": "	What do you think?	", "pinyin":"	どうおもう？	"},
"	161	":{"character":"	こっち…こっちへ！	","letter": "	This way... this way!	", "pinyin":"	こっち…こっちへ！	"},
"	162	":{"character":"	何やってんの？あれ	","letter": "	What are you doing? Oh, that.	", "pinyin":"	なにやってんの？あれ	"},
"	163	":{"character":"	さぁね	","letter": "	I don't know.	", "pinyin":"	さぁね	"},
"	164	":{"character":"	パンダくんの願い	","letter": "	Panda's wish.	", "pinyin":"	ぱんだくんのねがい	"},
"	165	":{"character":"	ほほう…半田さんがね	","letter": "	Oh... by Mr. Handa.	", "pinyin":"	ほほう…はんでんさんがね	"},
"	166	":{"character":"	なんではっきり言わないのかな？	","letter": "	Why doesn't he say so?	", "pinyin":"	なんではっきりいわないのかな？	"},
"	167	":{"character":"	半田さんは奥手だしね	","letter": "	Mr. Handa's not very shy.	", "pinyin":"	はんでんさんはおくてだしね	"},
"	168	":{"character":"	そうなの？	","letter": "	Is that so?	", "pinyin":"	そうなの？	"},
"	169	":{"character":"	雑誌なんかで知識は豊富そうだけど	","letter": "	You seem to have a lot of knowledge from magazines.	", "pinyin":"	ざっしなんかでちしきはほうふそうだけど	"},
"	170	":{"character":"	いざとなるとてんで勇気が出ないタイプだね	","letter": "	But when it comes down to it, you're the type who can't muster up the courage.	", "pinyin":"	いざとなるとてんでゆうきがでないたいぷだね	"},
"	171	":{"character":"	あぁ知ってる	","letter": "	Yes, I know that.	", "pinyin":"	あぁしってる	"},
"	172	":{"character":"	えっと…たしか耳年寄り？	","letter": "	Are you an old person?	", "pinyin":"	えっと…たしかみみとしより？	"},
"	173	":{"character":"	ツッコみづらい間違え方しないでよ	","letter": "	Don't make a mistake that's hard to pin on me.	", "pinyin":"	つっこみづらいまちがえかたしないでよ	"},
"	174	":{"character":"	半田さんにアドバイスしたいんだけど何かない？	","letter": "	Do you have any advice for Mr. Handa?	", "pinyin":"	はんでんさんにあどばいすしたいんだけどなにかない？	"},
"	175	":{"character":"	こっちに振るの？	","letter": "	You want me to give it to you?	", "pinyin":"	こっちにふるの？	"},
"	176	":{"character":"	だって常勤パンダさん経験豊富でしょ？	","letter": "	You're a full-time panda, aren't you?	", "pinyin":"	だってじょうきんぱんださんけいけんほうふでしょ？	"},
"	177	":{"character":"	バツ２だし	","letter": "	I'm a divorcee.	", "pinyin":"	ばつ２だし	"},
"	178	":{"character":"	勝手にバツ２にしないでって言ったでしょ	","letter": "	I told you not to make me a divorcee.	", "pinyin":"	かってにばつ２にしないでっていったでしょ	"},
"	179	":{"character":"	でもさ	","letter": "	But you know what?	", "pinyin":"	でもさ	"},
"	180	":{"character":"	僕らってカップルに関しては目が肥えてるよね	","letter": "	We're a discerning couple, aren't we?	", "pinyin":"	ぼくらってかっぷるにかんしてはめがこえてるよね	"},
"	181	":{"character":"	あぁそれは確かにね	","letter": "	Yes, that's true.	", "pinyin":"	あぁそれはたしかにね	"},
"	182	":{"character":"	ここに来るお客さんはカップル多いもんね	","letter": "	Many of our customers are couples.	", "pinyin":"	ここにきたるおきゃくさんはかっぷるおおいもんね	"},
"	183	":{"character":"	そうだね	","letter": "	Yes, we do.	", "pinyin":"	そうだね	"},
"	184	":{"character":"	初デートのカップルなんてういういしいよね	","letter": "	Couples on their first date are so awkward.	", "pinyin":"	はつでーとのかっぷるなんてういういしいよね	"},
"	185	":{"character":"	手を繋ぐこともできなかったりしてさ	","letter": "	They can't even hold hands.	", "pinyin":"	てをつなぐこともできなかったりしてさ	"},
"	186	":{"character":"	うんうん	","letter": "	Yeah, yeah.	", "pinyin":"	うんうん	"},
"	187	":{"character":"	あとはケンカしてるカップルとかもいるよね	","letter": "	And there are couples fighting.	", "pinyin":"	あとはけんかしてるかっぷるとかもいるよね	"},
"	188	":{"character":"	こっちから見ててもわかるっていうか	","letter": "	You can see it from here.	", "pinyin":"	こっちからみててもわかるっていうか	"},
"	189	":{"character":"	そう？	","letter": "	You see?	", "pinyin":"	そう？	"},
"	190	":{"character":"	ほら！こっちに来るあの２人は	","letter": "	Look! Those two coming this way...	", "pinyin":"	ほら！こっちにくるあの２にんは	"},
"	191	":{"character":"	今ちょっと気まずい感じだね	","letter": "	It's a little awkward right now.	", "pinyin":"	いまちょっときまずいかんじだね	"},
"	192	":{"character":"	あぁ本当だ	","letter": "	Yeah, that's true.	", "pinyin":"	あぁほんとうだ	"},
"	193	":{"character":"	でもね見てなよ	","letter": "	But you'll see.	", "pinyin":"	でもねみてなよ	"},
"	194	":{"character":"	そこで僕らを見つけると…	","letter": "	When they see us there...	", "pinyin":"	そこでぼくらをみつけると…	"},
"	195	":{"character":"	あっ！パンダだ	","letter": "	Oh! Pandas.	", "pinyin":"	あっ！ぱんだだ	"},
"	196	":{"character":"	あぁ行こう	","letter": "	Oh, let's go.	", "pinyin":"	あぁいこう	"},
"	197	":{"character":"	わぁ～！かわいい	","letter": "	Oh, wow! So cute.	", "pinyin":"	わぁ～！かわいい	"},
"	198	":{"character":"	ねっ？	","letter": "	See?	", "pinyin":"	ねっ？	"},
"	199	":{"character":"	うん	","letter": "	Yeah.	", "pinyin":"	うん	"},
"	200	":{"character":"	ねね次はどこ行こっか	","letter": "	Okay, where to next?	", "pinyin":"	ねねつぎはどこぎょうこっか	"},
"	201	":{"character":"	ほら！仲直りした	","letter": "	There we go! They made up.	", "pinyin":"	ほら！なかなおりした	"},
"	202	":{"character":"	常勤パンダさんすご～い	","letter": "	You're a full-time panda!	", "pinyin":"	じょうきんぱんださんすご～い	"},
"	203	":{"character":"	そうかな？	","letter": "	Is that so?	", "pinyin":"	そうかな？	"},
"	204	":{"character":"	さすがはラテン系だね	","letter": "	You're a real Latino, aren't you?	", "pinyin":"	さすがはらてんけいだね	"},
"	205	":{"character":"	またそんなキャラ付けする…	","letter": "	There you go again with that characterization...	", "pinyin":"	またそんなきゃらつけする…	"},
"	206	":{"character":"	アドバイスお願いします！	","letter": "	Advice please!	", "pinyin":"	あどばいすおねがいします！	"},
"	207	":{"character":"	ガテン系の常勤パンダさん	","letter": "	You're a gruff, full-time panda.	", "pinyin":"	がてんけいのじょうきんぱんださん	"},
"	208	":{"character":"	だからツッコミづらいって…	","letter": "	That's why I said it's hard to tweak...	", "pinyin":"	だからつっこみづらいって…	"},
"	209	":{"character":"	まぁアドバイスとしては	","letter": "	Well, my advice is...	", "pinyin":"	まぁあどばいすとしては	"},
"	210	":{"character":"	一歩前へ出るのが大事だね	","letter": "	It's important to step forward.	", "pinyin":"	いっぽまえへでるのがだいじだね	"},
"	211	":{"character":"	どすこ～い！	","letter": "	What's up with that?	", "pinyin":"	どすこ～い！	"},
"	212	":{"character":"	全然恋の予感がしないよ？	","letter": "	I don't have a feeling of love at all.	", "pinyin":"	ぜんぜんこいのよかんがしないよ？	"},
"	213	":{"character":"	相撲してどうするの	","letter": "	What are you doing wrestling?	", "pinyin":"	すもうしてどうするの	"},
"	214	":{"character":"	しないの？	","letter": "	You're not going to wrestle?	", "pinyin":"	しないの？	"},
"	215	":{"character":"	しないよ	","letter": "	I don't.	", "pinyin":"	しないよ	"},
"	216	":{"character":"	なんにしても恋は積極性が大事だね	","letter": "	In any case, you have to be proactive in love.	", "pinyin":"	なんにしてもこいはせっきょくせいがだいじだね	"},
"	217	":{"character":"	説教くせぇか…	","letter": "	You're preachy...	", "pinyin":"	せっきょうくせぇか…	"},
"	218	":{"character":"	今また変な想像したよね？	","letter": "	Now you're imagining things, aren't you?	", "pinyin":"	いままたへんなそうぞうしたよね？	"},
"	219	":{"character":"	積極性だよ？	","letter": "	Proactivity, right?	", "pinyin":"	せっきょくせいだよ？	"},
"	220	":{"character":"	お疲れさまでした	","letter": "	Good work, guys.	", "pinyin":"	おつかれさまでした	"},
"	221	":{"character":"	お疲れ～	","letter": "	Good work.	", "pinyin":"	おつかれ～	"},
"	222	":{"character":"	お疲れさま	","letter": "	Good work.	", "pinyin":"	おつかれさま	"},
"	223	":{"character":"	でさ…	","letter": "	So...	", "pinyin":"	でさ…	"},
"	224	":{"character":"	恋愛経験豊富な常勤パンダさんが	","letter": "	I'm a full-time panda with a lot of relationship experience.	", "pinyin":"	れんあいけいけんほうふなじょうきんぱんださんが	"},
"	225	":{"character":"	アドバイスくれたんだよ	","letter": "	He gave me some advice.	", "pinyin":"	あどばいすくれたんだよ	"},
"	226	":{"character":"	えっそうなの？	","letter": "	Oh, really?	", "pinyin":"	えっそうなの？	"},
"	227	":{"character":"	気になる？	","letter": "	Does that bother you?	", "pinyin":"	きになる？	"},
"	228	":{"character":"	い…いや…別に	","letter": "	No...no...not really.	", "pinyin":"	い…いや…べつに	"},
"	229	":{"character":"	はぁ…じゃあやめとく？	","letter": "	Well...you don't want to?	", "pinyin":"	はぁ…じゃあやめとく？	"},
"	230	":{"character":"	えっ！せ…せっかくだから一応聞くよ	","letter": "	What? Well... since we're here, I'll ask you anyway.	", "pinyin":"	えっ！せ…せっかくだからいちおうきくよ	"},
"	231	":{"character":"	どうしたの？	","letter": "	What's wrong?	", "pinyin":"	どうしたの？	"},
"	232	":{"character":"	でもこんなものを飾って	","letter": "	But you put all this stuff on display.	", "pinyin":"	でもこんなものをかざって	"},
"	233	":{"character":"	笹子さんに見られたら恥ずかしいな…	","letter": "	I'd be embarrassed if Sasako-san saw it...	", "pinyin":"	ささごさんにみられたらはずかしいな…	"},
"	234	":{"character":"	もう…何悩んでるの？	","letter": "	What are you worried about?	", "pinyin":"	もう…なになやんでるの？	"},
"	235	":{"character":"	ほら！恋は積極性が大事！	","letter": "	Come on! Love is all about being proactive!	", "pinyin":"	ほら！こいはせっきょくせいがだいじ！	"},
"	236	":{"character":"	前に出る！	","letter": "	Step forward!	", "pinyin":"	まえにでる！	"},
"	237	":{"character":"	パンダくん！	","letter": "	Panda!	", "pinyin":"	ぱんだくん！	"},
"	238	":{"character":"	こんにちは～	","letter": "	Hello!	", "pinyin":"	こんにちは～	"},
"	239	":{"character":"	いらっしゃいあ	","letter": "	Hello, there.	", "pinyin":"	いらっしゃいあ	"},
"	240	":{"character":"	パンダくん半田さん	","letter": "	Mr. Panda, Mr. Handa.	", "pinyin":"	ぱんだくんはんでんさん	"},
"	241	":{"character":"	やっほ～	","letter": "	Hello!	", "pinyin":"	やっほ～	"},
"	242	":{"character":"	おじゃまします	","letter": "	Hello, hello, hello.	", "pinyin":"	おじゃまします	"},
"	243	":{"character":"	いいタイミングだね	","letter": "	Great timing, huh?	", "pinyin":"	いいたいみんぐだね	"},
"	244	":{"character":"	何が？	","letter": "	What's up?	", "pinyin":"	なにが？	"},
"	245	":{"character":"	ちょうど飾りつけが終わるところだよ	","letter": "	We're just finishing decorating.	", "pinyin":"	ちょうどかざりつけがおわるところだよ	"},
"	246	":{"character":"	これが最後ね	","letter": "	This is the last one.	", "pinyin":"	これがさいごね	"},
"	247	":{"character":"	僕が作った飾りだ～	","letter": "	I made these.	", "pinyin":"	ぼくがつくったかざりだ～	"},
"	248	":{"character":"	じゃあ一番上に	","letter": "	Okay, at the top...	", "pinyin":"	じゃあいちばんうえに	"},
"	249	":{"character":"	今度は願いごとの短冊をつるしますよ～	","letter": "	Now I'm going to hang up strips of paper with your wishes on them!	", "pinyin":"	こんどはねがいごとのたんざくをつるしますよ～	"},
"	250	":{"character":"	皆さ～んどうぞ	","letter": "	Here you go, everyone!	", "pinyin":"	みんなさ～んどうぞ	"},
"	251	":{"character":"	何書いたの？	","letter": "	What did you write?	", "pinyin":"	なにかいたの？	"},
"	252	":{"character":"	見る？	","letter": "	Wanna see?	", "pinyin":"	みる？	"},
"	253	":{"character":"	Stop地球温暖化	","letter": "	Stop Global Warming	", "pinyin":"	Stopちきゅうおんだんか	"},
"	254	":{"character":"	切実だからね	","letter": "	It's so urgent!	", "pinyin":"	せつじつだからね	"},
"	255	":{"character":"	僕のはこれ！	","letter": "	Here's mine!	", "pinyin":"	ぼくのはこれ！	"},
"	256	":{"character":"	ペンこさんから告白されますように	","letter": "	I hope Mr. Penko will confess his feelings for me.	", "pinyin":"	ぺんこさんからこくはくされますように	"},
"	257	":{"character":"	ずうずうしいね	","letter": "	How brazen of you!	", "pinyin":"	ずうずうしいね	"},
"	258	":{"character":"	どうしよう告白されちゃったら！	","letter": "	What should I do if he confesses his feelings to me?	", "pinyin":"	どうしようこくはくされちゃったら！	"},
"	259	":{"character":"	困っちゃうよ困っちゃうよ困っちゃうよ…	","letter": "	I'm in trouble, I'm in trouble, I'm in trouble...	", "pinyin":"	こまっちゃうよこまっちゃうよこまっちゃうよ…	"},
"	260	":{"character":"	どっちなの？	","letter": "	Which is it?	", "pinyin":"	どっちなの？	"},
"	261	":{"character":"	半田さんお願い書いてきました？	","letter": "	Did you write a request, Mr. Handa?	", "pinyin":"	はんでんさんおねがいかいてきました？	"},
"	262	":{"character":"	あいや…	","letter": "	Oh, no...	", "pinyin":"	あいや…	"},
"	263	":{"character":"	えっと…	","letter": "	Well...	", "pinyin":"	えっと…	"},
"	264	":{"character":"	いやその…	","letter": "	No, I mean...	", "pinyin":"	いやその…	"},
"	265	":{"character":"	恋は積極性が大事	","letter": "	Love is all about being positive.	", "pinyin":"	こいはせっきょくせいがだいじ	"},
"	266	":{"character":"	書いてきました	","letter": "	I wrote it down.	", "pinyin":"	かいてきました	"},
"	267	":{"character":"	じゃあつるしてください	","letter": "	Then hang me.	", "pinyin":"	じゃあつるしてください	"},
"	268	":{"character":"	はい	","letter": "	Okay.	", "pinyin":"	はい	"},
"	269	":{"character":"	半田さん彼女いないんですか？	","letter": "	You don't have a girlfriend?	", "pinyin":"	はんでんさんかのじょいないんですか？	"},
"	270	":{"character":"	はい	","letter": "	Yes, I do.	", "pinyin":"	はい	"},
"	271	":{"character":"	そうなんですか	","letter": "	I see.	", "pinyin":"	そうなんですか	"},
"	272	":{"character":"	早くできるといいですね	","letter": "	I hope you'll get one soon.	", "pinyin":"	はやくできるといいですね	"},
"	273	":{"character":"	はい	","letter": "	I hope so.	", "pinyin":"	はい	"},
"	274	":{"character":"	そろそろ締め切り	","letter": "	The deadline is almost here.	", "pinyin":"	そろそろしめきり	"},
"	275	":{"character":"	パンダくん願いごとつるした？	","letter": "	Did you hang up your wish, panda?	", "pinyin":"	ぱんだくんねがいごとつるした？	"},
"	276	":{"character":"	もう忘れてたの？	","letter": "	Did you forget already?	", "pinyin":"	もうわすれてたの？	"},
"	277	":{"character":"	う～んどうしよう	","letter": "	I don't know what to do.	", "pinyin":"	う～んどうしよう	"},
"	278	":{"character":"	えっと足が長くなりますように	","letter": "	I wish for longer legs!	", "pinyin":"	えっとあしがながくなりますように	"},
"	279	":{"character":"	おこづかいアップ	","letter": "	I want to earn more money...	", "pinyin":"	おこづかいあっぷ	"},
"	280	":{"character":"	テレビ出たい…	","letter": "	I want to be on TV...	", "pinyin":"	てれびでたい…	"},
"	281	":{"character":"	パンダくん	","letter": "	Panda.	", "pinyin":"	ぱんだくん	"},
"	282	":{"character":"	まだ？	","letter": "	You're not done yet?	", "pinyin":"	まだ？	"},
"	283	":{"character":"	飾るよ	","letter": "	I'll put it up.	", "pinyin":"	かざるよ	"},
"	284	":{"character":"	きれい	","letter": "	It's beautiful.	", "pinyin":"	きれい	"},
"	285	":{"character":"	涼しいですね	","letter": "	It's cool.	", "pinyin":"	すずしいですね	"},
"	286	":{"character":"	七夕晴れてよかったですね	","letter": "	I'm glad the sun shines on Tanabata.	", "pinyin":"	たなばたはれてよかったですね	"},
"	287	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},
"	288	":{"character":"	ペンギン君ペンギン君	","letter": "	Penguin! Penguin!	", "pinyin":"	ぺんぎんくんぺんぎんくん	"},
"	289	":{"character":"	君付け	","letter": "	You're a penguin.	", "pinyin":"	くんづけ	"},
"	290	":{"character":"	今日は距離詰めてきたね何？	","letter": "	You've gone the distance today.	", "pinyin":"	きょうはきょりつめてきたねなに？	"},
"	291	":{"character":"	思い出せないくらい恥ずかしい	","letter": "	I'm so embarrassed I can't remember.	", "pinyin":"	おもいだせないくらいはずかしい	"},
"	292	":{"character":"	人前で話せない話聞かせてよ	","letter": "	Tell me something you can't tell me in public.	", "pinyin":"	ひとまえではなせないはなしきかせてよ	"},
"	293	":{"character":"	それは人前で言わなくてもいいかな	","letter": "	I don't think I have to tell you that in public.	", "pinyin":"	それはひとまえでいわなくてもいいかな	"},
"	294	":{"character":"	じゃ僕にだけ教えて	","letter": "	Then just tell me.	", "pinyin":"	じゃぼくにだけおしえて	"},
"	295	":{"character":"	絶対嫌だ	","letter": "	I'm not gonna tell you.	", "pinyin":"	ぜったいいやだ	"},
"	296	":{"character":"	じゃ思い出せないくらい格好悪い…	","letter": "	Then it's so embarrassing I can't even remember...	", "pinyin":"	じゃおもいだせないくらいかっこわるい…	"},
"	297	":{"character":"	白熊君終わろ	","letter": "	Shirokuma, finish up.	", "pinyin":"	しろくまくんおわろ	"},
"	298	":{"character":"	次回のしろくまカフェは	","letter": "	Next time at the Shirokuma Cafe...	", "pinyin":"	じかいのしろくまかふぇは	"},
"	299	":{"character":"	静止画でお送り…	","letter": "	I'll be showing you still pictures...	", "pinyin":"	せいしがでおおくり…	"},
"	300	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},
}