const greekMap = {
    "Α": { "letter" :  "a" },
    "Β": { "letter" :  "v" },
    "Γ": { "letter" :  "g" },
    "Δ": { "letter" :  "d" },
    "Ε": { "letter" :  "e" },
    "Ζ": { "letter" :  "z" },
    "Η": { "letter" :  "ī" },
    "Θ": { "letter" :  "th" },
    "Ι": { "letter" :  "i" },
    "Κ": { "letter" :  "k" },
    "Λ": { "letter" :  "l" },
    "Μ": { "letter" :  "m" },
    "Ν": { "letter" :  "n" },
    "Ξ": { "letter" :  "x" },
    "Ο": { "letter" :  "o" },
    "Π": { "letter" :  "p" },
    "Ρ": { "letter" :  "r" },
    "Σ": { "letter" :  "s" },
    "Τ": { "letter" :  "t" },
    "Υ": { "letter" :  "y" },
    "Φ": { "letter" :  "f" },
    "Χ": { "letter" :  "ch" },
    "Ψ": { "letter" :  "ps" },
    "Ω": { "letter" :  "ō" },
    "α": { "letter" :  "a" },
    "β": { "letter" :  "v" },
    "γ": { "letter" :  "g" },
    "δ": { "letter" :  "d" },
    "ε": { "letter" :  "e" },
    "ζ": { "letter" :  "z" },
    "η": { "letter" :  "ī" },
    "θ": { "letter" :  "th" },
    "ι": { "letter" :  "i" },
    "κ": { "letter" :  "k" },
    "λ": { "letter" :  "l" },
    "μ": { "letter" :  "m" },
    "ν": { "letter" :  "n" },
    "ξ": { "letter" :  "x" },
    "ο": { "letter" :  "o" },
    "π": { "letter" :  "p" },
    "ρ": { "letter" :  "r" },
    "σ": { "letter" :  "s" },
    "ς": { "letter" :  "s" },
    "τ": { "letter" :  "t" },
    "υ": { "letter" :  "y" },
    "φ": { "letter" :  "f" },
    "χ": { "letter" :  "ch" },
    "ψ": { "letter" :  "ps" },
    "ω": { "letter" :  "ō" }
}

const greekDataArray = Object.keys(greekMap);

const greekChartData = {
   "1": { "subtitle": "Uppercase letters", "content": greekDataArray.slice(0,25) }, 
   "2": { "subtitle": "Lowercase letters", "content": greekDataArray.slice(25,50)  }, 
}

console.log(greekChartData);