obj = {
"	1	":{"character":"	シロクマくん動物園へ	","letter": "	Polar Bear Goes to the Zoo.	", "pinyin":"	しろくまくんどうぶつえんへ	"},																			
"	2	":{"character":"	シロクマくん暇だから何か問題出してよ	","letter": "	Hey, Polar Bear. I'm a little bored, so give me a problem to solve.	", "pinyin":"	しろくまくんひまだからなにかもんだいだしてよ	"},																			
"	3	":{"character":"	いいよ	","letter": "	Sure.	", "pinyin":"	いいよ	"},																			
"	4	":{"character":"	第１問	","letter": "	Question 1:	", "pinyin":"	だい１もん	"},																			
"	5	":{"character":"	Ｔ字路と呼ばれる交差点	","letter": "	The T-intersection.'	", "pinyin":"	てぃーじろとよばれるこうさてん	"},																			
"	6	":{"character":"	法令上の正式名称はＴ字路ではありません	","letter": "	The legal name for this kind of intersection is not actually 'T-intersection.'	", "pinyin":"	ほうれいじょうのせいしきめいしょうはてぃーじろではありません	"},																			
"	7	":{"character":"	さて何と言うでしょう	","letter": "	What is the proper name?	", "pinyin":"	さてなんというでしょう	"},																			
"	8	":{"character":"	もっとフランクな問題がいいな	","letter": "	I'd prefer something a little less complicated.	", "pinyin":"	もっとふらんくなもんだいがいいな	"},																			
"	9	":{"character":"	無洗米の製法にはいくつかありますが	","letter": "	There are many ways of manufacturing pre-washed rice.	", "pinyin":"	むせんまいのせいほうにはいくつかありますが	"},																			
"	10	":{"character":"	ＮＴＷＰ加工法という方法ではよく…	","letter": "	But when using the NTWP manufacturing method, it's common—	", "pinyin":"	ＮＴＷＰかこうほうというほうほうではよく…	"},																			
"	11	":{"character":"	ごめん、もういいや!!	","letter": "	Actually, never mind.	", "pinyin":"	ごめん、もういいや!!	"},																			
"	12	":{"character":"	おぉパンダくん	","letter": "	Oh, hey, Panda.	", "pinyin":"	おぉぱんだくん	"},																			
"	13	":{"character":"	いらっしゃい	","letter": "	Welcome.	", "pinyin":"	いらっしゃい	"},																			
"	14	":{"character":"	パンダくんいつもの？	","letter": "	Would you like your usual, Panda?	", "pinyin":"	ぱんだくんいつもの？	"},																			
"	15	":{"character":"	どうしたの？クイズ出す？	","letter": "	What's wrong? Want a trivia question?	", "pinyin":"	どうしたの？くいずだす？	"},																			
"	16	":{"character":"	クイズより	","letter": "	Instead of a trivia question,	", "pinyin":"	くいずより	"},																			
"	17	":{"character":"	どうしてシロクマくんは動物園に来てくれないの？	","letter": "	why don't you come visit me at the zoo, Polar Bear?	", "pinyin":"	どうしてしろくまくんはどうぶつえんにきてくれないの？	"},																			
"	18	":{"character":"	何？急に	","letter": "	What's this, all of a sudden?	", "pinyin":"	なに？きゅうに	"},																			
"	19	":{"character":"	僕はいつもシロクマくんの仕事場に遊びに来てるのにずるいよ	","letter": "	I always come to visit you at work. It's not fair.	", "pinyin":"	ぼくはいつもしろくまくんのしごとばにあそびにきてるのにずるいよ	"},																			
"	20	":{"character":"	カフェにお茶しに来てるだけでしょ	","letter": "	But you're coming to the café as a customer.	", "pinyin":"	かふぇにおちゃしにきてるだけでしょ	"},																			
"	21	":{"character":"	僕人にはモテるんだからね	","letter": "	I'm really popular with people, you know?	", "pinyin":"	ぼくひとにはもてるんだからね	"},																			
"	22	":{"character":"	聞いてないなぁ…	","letter": "	He's not listening.	", "pinyin":"	きいてないなぁ…	"},																			
"	23	":{"character":"	一度動物園に遊びに来てよ	","letter": "	Come visit me at the zoo at least once.	", "pinyin":"	いちどどうぶつえんにあそびにきてよ	"},																			
"	24	":{"character":"	大人気でびっくりするよ	","letter": "	You'll be surprised at how popular I am.	", "pinyin":"	だいにんきでびっくりするよ	"},																			
"	25	":{"character":"	なんで２回言うの?	","letter": "	Why'd you have to say it twice?	", "pinyin":"	なんで２かいいうの?	"},																			
"	26	":{"character":"	もしもしシロクマくん？	","letter": "	Hello, Polar Bear?	", "pinyin":"	もしもししろくまくん？	"},																			
"	27	":{"character":"	明日動物園に来る件だけど忘れないでよ	","letter": "	I'm calling to remind you to come to the zoo tomorrow.	", "pinyin":"	あしたどうぶつえんにくるけんだけどわすれないでよ	"},																			
"	28	":{"character":"	じゃあペンギンさんにも伝えておいてね	","letter": "	Please tell Mr. Penguin, too.	", "pinyin":"	じゃあぺんぎんさんにもつたえておいてね	"},																			
"	29	":{"character":"	おはようございま～す	","letter": "	Good morning!	", "pinyin":"	おはようございま～す	"},																			
"	30	":{"character":"	おはようパンダくん	","letter": "	Good morning, Panda.	", "pinyin":"	おはようぱんだくん	"},																			
"	31	":{"character":"	なんだか元気だね	","letter": "	You're in good spirits today.	", "pinyin":"	なんだかげんきだね	"},																			
"	32	":{"character":"	今日友達が僕のこと見に来るの	","letter": "	My friends are coming to see me today.	", "pinyin":"	きょうともだちがぼくのことみにくるの	"},																			
"	33	":{"character":"	そうなんだ	","letter": "	I see...	", "pinyin":"	そうなんだ	"},																			
"	34	":{"character":"	あっそうだ今日は常勤パンダさんが娘さんの参観日だから休むって	","letter": "	Oh, that's right! Full-time Panda has the day off today because he's visiting his daughter's class.	", "pinyin":"	あっそうだきょうはじょうきんぱんださんがむすめさんのさんかんびだからやすむって	"},																			
"	35	":{"character":"	そうなの？	","letter": "	Oh, really?	", "pinyin":"	そうなの？	"},																			
"	36	":{"character":"	あれ？ということは…	","letter": "	Wait, that means...	", "pinyin":"	あれ？ということは…	"},																			
"	37	":{"character":"	パンダは僕ひとり…	","letter": "	I'll be the only panda.	", "pinyin":"	ぱんだはぼくひとり…	"},																			
"	38	":{"character":"	パンダさんかわいい～！	","letter": "	You're so cute, Mr. Panda!	", "pinyin":"	ぱんださんかわいい～！	"},																			
"	39	":{"character":"	パンダく～ん！かわいい！	","letter": "	You're so cute, Panda!	", "pinyin":"	ぱんだく～ん！かわいい！	"},																			
"	40	":{"character":"	ようし！頑張るぞ～！	","letter": "	All right! I'll do my best!	", "pinyin":"	ようし！がんばるぞ～！	"},																			
"	41	":{"character":"	うわっすっげえ！	","letter": "	Oh, my God!	", "pinyin":"	うわっすっげえ！	"},																			
"	42	":{"character":"	何名様ですか？	","letter": "	How many?	", "pinyin":"	なんめいさまですか？	"},																			
"	43	":{"character":"	２名です	","letter": "	Two... Animals, please.	", "pinyin":"	２めいです	"},																			
"	44	":{"character":"	ここが動物園か	","letter": "	So, this is the zoo.	", "pinyin":"	ここがどうぶつえんか	"},																			
"	45	":{"character":"	思ったより広いね	","letter": "	It's a lot bigger than I thought.	", "pinyin":"	おもったよりひろいね	"},																			
"	46	":{"character":"	まずはパンダくんを見に行こう	","letter": "	Let's go see Panda first.	", "pinyin":"	まずはぱんだくんをみにいこう	"},																			
"	47	":{"character":"	ただ今からシロクマのおやつタイムを行います	","letter": "	We will now start the polar bear feeding time.	", "pinyin":"	ただいまからしろくまのおやつたいむをおこないます	"},																			
"	48	":{"character":"	シロクマがプールへダイビングする姿をどうぞお楽しみください	","letter": "	Please enjoy watching the polar bear dive into the water!	", "pinyin":"	しろくまがぷーるへだいびんぐするすがたをどうぞおたのしみください	"},																			
"	49	":{"character":"	見たい！すごそう！	","letter": "	I want to go see! That sounds amazing!	", "pinyin":"	みたい！すごそう！	"},																			
"	50	":{"character":"	えっ！？見たい！？	","letter": "	What? You want to see that?	", "pinyin":"	えっ！？みたい！？	"},																			
"	51	":{"character":"	シロクマくんってシロクマだよね？	","letter": "	You're a polar bear, right, Polar Bear?	", "pinyin":"	しろくまくんってしろくまだよね？	"},																			
"	52	":{"character":"	シロクマがシロクマのダイビングする姿が見たいの？	","letter": "	You want to see a polar bear diving, Polar Bear?	", "pinyin":"	しろくまがしろくまのだいびんぐするすがたがみたいの？	"},																			
"	53	":{"character":"	行こう行こう！	","letter": "	Let's go, let's go!	", "pinyin":"	いこういこう！	"},																			
"	54	":{"character":"	パンダく～ん	","letter": "	Panda!	", "pinyin":"	ぱんだく～ん	"},																			
"	55	":{"character":"	そんなに飛ばして大丈夫？	","letter": "	Are you doing okay, working that hard?	", "pinyin":"	そんなにとばしてだいじょうぶ？	"},																			
"	56	":{"character":"	半田さん友達が来たらちゃんと写真撮ってね	","letter": "	Mr. Handa, when my friends come, please take our picture.	", "pinyin":"	はんでんさんともだちがきたらちゃんとしゃしんとってね	"},																			
"	57	":{"character":"	でもおかしいなぁ	","letter": "	But it's strange,	", "pinyin":"	でもおかしいなぁ	"},																			
"	58	":{"character":"	シロクマくんたち１時って言ったのに来ないね	","letter": "	They said they'd be here around 1pm, but I don't see them anywhere.	", "pinyin":"	しろくまくんたち１じっていったのにこないね	"},																			
"	59	":{"character":"	シロクマくん駄目だよほら	","letter": "	We can't go in here, Polar Bear. Look.	", "pinyin":"	しろくまくんだめだよほら	"},																			
"	60	":{"character":"	なに？	","letter": "	What?	", "pinyin":"	なに？	"},																			
"	61	":{"character":"	入館不可だって	","letter": "	It says you can't enter.	", "pinyin":"	にゅうかんふかだって	"},																			
"	62	":{"character":"	しろくま館へのシロクマの入館はご遠慮ください	","letter": "	We apologize for the inconvenience, but polar bears are not allowed in the Polar Bear Hall.	", "pinyin":"	しろくまかんへのしろくまのにゅうかんはごえんりょください	"},																			
"	63	":{"character":"	まぎらわしいので	","letter": "	It confuses them!	", "pinyin":"	まぎらわしいので	"},																			
"	64	":{"character":"	こっそり入ればバレないバレないの	","letter": "	If we sneak in quietly, they'll never even notice.	", "pinyin":"	こっそりいればばれないばれないの	"},																			
"	65	":{"character":"	いやすごく目立ってるから	","letter": "	No... I think we're pretty obvious.	", "pinyin":"	いやすごくめだってるから	"},																			
"	66	":{"character":"	お～！すごい迫力	","letter": "	Wow! That's incredible!	", "pinyin":"	お～！すごいはくりょく	"},																			
"	67	":{"character":"	シロクマ！	","letter": "	A polar bear!	", "pinyin":"	しろくま！	"},																			
"	68	":{"character":"	ちょっとちょっとシロクマは入れないって書いてあったでしょう	","letter": "	Hey, hey! The sign clearly says no polar bears allowed!	", "pinyin":"	ちょっとちょっとしろくまはいれないってかいてあったでしょう	"},																			
"	69	":{"character":"	困りますよ	","letter": "	It's really troublesome.	", "pinyin":"	こまりますよ	"},																			
"	70	":{"character":"	え？これ剥製ですけど	","letter": "	Um... This is actually a stuffed animal.	", "pinyin":"	え？これはくせいですけど	"},																			
"	71	":{"character":"	今動いてましたよ剥製なわけないでしょう	","letter": "	It was just moving!	", "pinyin":"	いまうごいてましたよはくせいなわけないでしょう	"},																			
"	72	":{"character":"	なんで来ないの？	","letter": "	Why aren't they here yet?	", "pinyin":"	なんでこないの？	"},																			
"	73	":{"character":"	もう行っていいかな？来たら呼んで	","letter": "	Um, I'm going to go now. Call me when they get here.	", "pinyin":"	もういっていいかな？きたらよんで	"},																			
"	74	":{"character":"	もう叱られたじゃない	","letter": "	See? We got in trouble.	", "pinyin":"	もうしかられたじゃない	"},																			
"	75	":{"character":"	僕はバレるって言ったのに	","letter": "	I said we'd get in trouble.	", "pinyin":"	ぼくはばれるっていったのに	"},																			
"	76	":{"character":"	じゃあパンダくんとこに行こう	","letter": "	Then let's go see Panda.	", "pinyin":"	じゃあぱんだくんとこにいこう	"},																			
"	77	":{"character":"	うん	","letter": "	Okay.	", "pinyin":"	うん	"},																			
"	78	":{"character":"	パンダくんかわいいキャ～ッかわいい	","letter": "	You're so cute, Panda!	", "pinyin":"	ぱんだくんかわいいきゃ～っかわいい	"},																			
"	79	":{"character":"	パンダく～ん	","letter": "	Panda!	", "pinyin":"	ぱんだく～ん	"},																			
"	80	":{"character":"	パンダくん遅れてごめん	","letter": "	Sorry we're late, Panda!	", "pinyin":"	ぱんだくんおくれてごめん	"},																			
"	81	":{"character":"	あれ？	","letter": "	Huh?	", "pinyin":"	あれ？	"},																			
"	82	":{"character":"	お～いパンダくん	","letter": "	Hey, Panda!	", "pinyin":"	お～いぱんだくん	"},																			
"	83	":{"character":"	寝てる	","letter": "	He's asleep.	", "pinyin":"	ねてる	"},																			
"	84	":{"character":"	パンダくん起きて	","letter": "	Panda! Wake up!	", "pinyin":"	ぱんだくんおきて	"},																			
"	85	":{"character":"	笑ってる	","letter": "	He's laughing...	", "pinyin":"	わらってる	"},																			
"	86	":{"character":"	パンダくんおいパンダくん！	","letter": "	Panda!	", "pinyin":"	ぱんだくんおいぱんだくん！	"},																			
"	87	":{"character":"	駄目だ	","letter": "	It's no use.	", "pinyin":"	だめだ	"},																			
"	88	":{"character":"	他のとこ回ってこようか	","letter": "	Let's go somewhere else.	", "pinyin":"	ほかのとこまわってこようか	"},																			
"	89	":{"character":"	寝ててもいいなんてうらやましい仕事だね	","letter": "	I envy the fact that he's allowed to sleep at work.	", "pinyin":"	ねててもいいなんてうらやましいしごとだね	"},																			
"	90	":{"character":"	ハッ今ペンギンさんの声が	","letter": "	Hey, I think I just heard Mr. Penguin!	", "pinyin":"	はっいまぺんぎんさんのこえが	"},																			
"	91	":{"character":"	いない	","letter": "	Aw, he's not here.	", "pinyin":"	いない	"},																			
"	92	":{"character":"	あっ半田さん	","letter": "	Oh, Mr. Handa.	", "pinyin":"	あっはんでんさん	"},																			
"	93	":{"character":"	なに？	","letter": "	Yes?	", "pinyin":"	なに？	"},																			
"	94	":{"character":"	友達来なかった？	","letter": "	Did my friends happen to stop by?	", "pinyin":"	ともだちこなかった？	"},																			
"	95	":{"character":"	え？気づかなかったな	","letter": "	I didn't see them.	", "pinyin":"	え？きづかなかったな	"},																			
"	96	":{"character":"	ちゃんと写真撮ってよ	","letter": "	Make sure you take our picture, 'kay?	", "pinyin":"	ちゃんとしゃしんとってよ	"},																			
"	97	":{"character":"	はいはい	","letter": "	Sure, sure...	", "pinyin":"	はいはい	"},																			
"	98	":{"character":"	おっあざらし館行こう行こう	","letter": "	Hey, the Seal Hall! Let's go!	", "pinyin":"	おっあざらしかんいこういこう	"},																			
"	99	":{"character":"	シロクマの入館はご遠慮ください	","letter": "	We apologize for the inconvenience, but polar bears are not allowed in the Seal Hall	", "pinyin":"	しろくまのにゅうかんはごえんりょください	"},																			
"	100	":{"character":"	あざらしが怖がるので…	","letter": "	It scares the seals!	", "pinyin":"	あざらしがこわがるので…	"},																			
"	101	":{"character":"	だってさ	","letter": "	There ya go.	", "pinyin":"	だってさ	"},																			
"	102	":{"character":"	バレないバレない	","letter": "	No one will even notice.	", "pinyin":"	ばれないばれない	"},																			
"	103	":{"character":"	いや目立ってるし	","letter": "	No, we're pretty obvious.	", "pinyin":"	いやめだってるし	"},																			
"	104	":{"character":"	食べない食べないの	","letter": "	Don't worry, I won't eat you.	", "pinyin":"	たべないたべないの	"},																			
"	105	":{"character":"	シロクマ！	","letter": "	A polar bear!	", "pinyin":"	しろくま！	"},																			
"	106	":{"character":"	食べないとわかっていても実際本物見るとテンション上がるなあ	","letter": "	Even though I know I won't eat one, I still get a little excited when I see one.	", "pinyin":"	たべないとわかっていてもじっさいほんものみるとてんしょんあがるなあ	"},																			
"	107	":{"character":"	シロクマくんの野性が呼び覚まされないうちに早く行こうよ	","letter": "	Let's leave before your natural instincts take over.	", "pinyin":"	しろくまくんのやせいがよびさまされないうちにはやくいこうよ	"},																			
"	108	":{"character":"	ちょっとちょっと	","letter": "	Hey, hey!	", "pinyin":"	ちょっとちょっと	"},																			
"	109	":{"character":"	シロクマは入らないでって書いてあったでしょう	","letter": "	The sign clearly said no polar bears allowed!	", "pinyin":"	しろくまははいらないでってかいてあったでしょう	"},																			
"	110	":{"character":"	え？これ絨毯ですよ	","letter": "	Oh, this is just a rug.	", "pinyin":"	え？これじゅうたんですよ	"},																			
"	111	":{"character":"	ほ～ら見てみてこんなにふっかふか	","letter": "	See? Look! It's so fluffy!	", "pinyin":"	ほ～らみてみてこんなにふっかふか	"},																			
"	112	":{"character":"	いや～騙せないもんだね	","letter": "	Wow. We can't seem to pull one over on them.	", "pinyin":"	いや～だませないもんだね	"},																			
"	113	":{"character":"	もう	","letter": "	Jeez.	", "pinyin":"	もう	"},																			
"	114	":{"character":"	パンダくんそろそろ起きてるんじゃない？	","letter": "	Panda might actually be awake now.	", "pinyin":"	ぱんだくんそろそろおきてるんじゃない？	"},																			
"	115	":{"character":"	お～いパンダくん	","letter": "	Hey, Panda!	", "pinyin":"	お～いぱんだくん	"},																			
"	116	":{"character":"	また笑ってる	","letter": "	He's laughing again.	", "pinyin":"	またわらってる	"},																			
"	117	":{"character":"	よくあんな状態で寝られるね	","letter": "	It's amazing that he can sleep in that position.	", "pinyin":"	よくあんなじょうたいでねられるね	"},																			
"	118	":{"character":"	あれは逆に尊敬するね	","letter": "	I actually admire him for that.	", "pinyin":"	あれはぎゃくにそんけいするね	"},																			
"	119	":{"character":"	あのもしかしてパンダくんのお友達ですか？	","letter": "	Excuse me, are you Panda's friends?	", "pinyin":"	あのもしかしてぱんだくんのおともだちですか？	"},																			
"	120	":{"character":"	あはい	","letter": "	Yes, we are.	", "pinyin":"	あはい	"},																			
"	121	":{"character":"	写真撮りましょうか	","letter": "	Could I take a picture?	", "pinyin":"	しゃしんとりましょうか	"},																			
"	122	":{"character":"	撮ってくれって頼まれてるんで	","letter": "	He asked me to take one.	", "pinyin":"	とってくれってたのまれてるんで	"},																			
"	123	":{"character":"	キリンさんしろくまカフェに来てくれないかな？	","letter": "	I wonder if Mr. Giraffe will come to my café.	", "pinyin":"	きりんさんしろくまかふぇにきてくれないかな？	"},																			
"	124	":{"character":"	いやカフェに入れないでしょ	","letter": "	No, I don't think he can get in.	", "pinyin":"	いやかふぇにいれないでしょ	"},																			
"	125	":{"character":"	別のところも回ってみよう	","letter": "	Let's look around the other places, too.	", "pinyin":"	べつのところもまわってみよう	"},																			
"	126	":{"character":"	そうだね	","letter": "	Okay.	", "pinyin":"	そうだね	"},																			
"	127	":{"character":"	でどこ行こうか？	","letter": "	So, where did you want to go?	", "pinyin":"	でどこいこうか？	"},																			
"	128	":{"character":"	う～んあっ！ペンギンコーナー	","letter": "	Oh, how about the Penguin Corner?	", "pinyin":"	う～んあっ！ぺんぎんこーなー	"},																			
"	129	":{"character":"	えぇ～	","letter": "	Oh, my God.	", "pinyin":"	えぇ～	"},																			
"	130	":{"character":"	ペンギンさん曲芸に飛び入りしてよ	","letter": "	You should join in their acrobatics act, Mr. Penguin.	", "pinyin":"	ぺんぎんさんきょくげいにとびいりしてよ	"},																			
"	131	":{"character":"	僕運動神経悪いから	","letter": "	I'm terrible with exercise.	", "pinyin":"	ぼくうんどうしんけいわるいから	"},																			
"	132	":{"character":"	ちょっとちょっと	","letter": "	Hey, there.	", "pinyin":"	ちょっとちょっと	"},																			
"	133	":{"character":"	あラマさん	","letter": "	Oh, hello, Mr. Llama.	", "pinyin":"	あらまさん	"},																			
"	134	":{"character":"	今日はどうしたんですか？	","letter": "	What brings you here today?	", "pinyin":"	きょうはどうしたんですか？	"},																			
"	135	":{"character":"	パンダくんに会いにきたのに寝てるんだよね	","letter": "	We came to see Panda, but he's asleep.	", "pinyin":"	ぱんだくんにあいにきたのにねてるんだよね	"},																			
"	136	":{"character":"	たまには起きてますよ	","letter": "	He's awake sometimes.	", "pinyin":"	たまにはおきてますよ	"},																			
"	137	":{"character":"	そっかいいかげんパンダくん起きてるよね？	","letter": "	Oh, okay. Panda should be awake by now.	", "pinyin":"	そっかいいかげんぱんだくんおきてるよね？	"},																			
"	138	":{"character":"	戻ろう	","letter": "	Let's go look.	", "pinyin":"	もどろう	"},																			
"	139	":{"character":"	また寝てる	","letter": "	He's asleep, again.	", "pinyin":"	またねてる	"},																			
"	140	":{"character":"	更にだらしないね	","letter": "	And he looks even more shameless.	", "pinyin":"	さらにだらしないね	"},																			
"	141	":{"character":"	パンダくん僕たちにいったい何を見てもらいたかったんだろうね	","letter": "	I wonder what exactly Panda wanted us to see.	", "pinyin":"	ぱんだくんぼくたちにいったいなにをみてもらいたかったんだろうね	"},																			
"	142	":{"character":"	あのパンダさん寝てばっかりでつまんない	","letter": "	That panda's so boring. All he does is sleep.	", "pinyin":"	あのぱんださんねてばっかりでつまんない	"},																			
"	143	":{"character":"	うん行こう	","letter": "	Yeah, let's go!	", "pinyin":"	うんいこう	"},																			
"	144	":{"character":"	大人気ねぇ…	","letter": "	Popular,' huh?	", "pinyin":"	だいにんきねぇ…	"},																			
"	145	":{"character":"	あまた笑った	","letter": "	Hey, he's laughing again.	", "pinyin":"	あまたわらった	"},																			
"	146	":{"character":"	ず～っと待ってたのになんで来てくれなかったの？	","letter": "	I was waiting the whole day. Why didn't you come?	", "pinyin":"	ず～っとまってたのになんできてくれなかったの？	"},																			
"	147	":{"character":"	いや何度も行ったよ	","letter": "	Actually, we came by quite a few times.	", "pinyin":"	いやなんどもいったよ	"},																			
"	148	":{"character":"	ほんと？	","letter": "	Really?	", "pinyin":"	ほんと？	"},																			
"	149	":{"character":"	行ったってば	","letter": "	We were there!	", "pinyin":"	いったってば	"},																			
"	150	":{"character":"	ねぇラマさん今日動物園で会ったよね？	","letter": "	Right, Mr. Llama? We met at the zoo today, right?	", "pinyin":"	ねぇらまさんきょうどうぶつえんであったよね？	"},																			
"	151	":{"character":"	会いましたよ	","letter": "	We did.	", "pinyin":"	あいましたよ	"},																			
"	152	":{"character":"	ほらちゃんと行ったでしょ？	","letter": "	See? We did go.	", "pinyin":"	ほらちゃんといったでしょ？	"},																			
"	153	":{"character":"	どうして僕のとこには来てくれないの？	","letter": "	Why didn't you come see me?	", "pinyin":"	どうしてぼくのとこにはきてくれないの？	"},																			
"	154	":{"character":"	だから行ったんだって！	","letter": "	I just said we did!	", "pinyin":"	だからいったんだって！	"},																			
"	155	":{"character":"	そんなにずっとラマさんを見てたの？	","letter": "	You spent that much time watching Mr. Llama?	", "pinyin":"	そんなにずっとらまさんをみてたの？	"},																			
"	156	":{"character":"	だからパンダくんとこに行ったってば！	","letter": "	I'm trying to tell you, we went to see you, too!	", "pinyin":"	だからぱんだくんとこにいったってば！	"},																			
"	157	":{"character":"	じゃあなんで会えなかったんだろうね	","letter": "	I wonder why we didn't see each other, then.	", "pinyin":"	じゃあなんであえなかったんだろうね	"},																			
"	158	":{"character":"	パンダくんが寝てばっかりだったからでしょ	","letter": "	It's because you were asleep the whole time.	", "pinyin":"	ぱんだくんがねてばっかりだったからでしょ	"},																			
"	159	":{"character":"	起こしてよ	","letter": "	You should have woken me up.	", "pinyin":"	おこしてよ	"},																			
"	160	":{"character":"	起きなかったよ	","letter": "	You didn't wake up!	", "pinyin":"	おきなかったよ	"},																			
"	161	":{"character":"	せっかく半田さんが写真撮ってくれるって言ってたのに	","letter": "	And Mr. Handa even said he would take pictures...	", "pinyin":"	せっかくはんでんさんがしゃしんとってくれるっていってたのに	"},																			
"	162	":{"character":"	撮ったよ	","letter": "	He did.	", "pinyin":"	とったよ	"},																			
"	163	":{"character":"	ほんとだ来てたんだね	","letter": "	Wow, you really did come!	", "pinyin":"	ほんとだこてたんだね	"},																			
"	164	":{"character":"	だから言ったのに	","letter": "	That's what I've been saying.	", "pinyin":"	だからいったのに	"},																			
"	165	":{"character":"	へぇ～僕って寝ててもかわいいなぁ	","letter": "	I'm so cute even when I'm sleeping.	", "pinyin":"	へぇ～ぼくってねててもかわいいなぁ	"},																			
"	166	":{"character":"	ねえねえどの寝顔がいちばん好き？	","letter": "	Hey, hey. Which sleeping face do you like best?	", "pinyin":"	ねえねえどのねがおがいちばんすき？	"},																			
"	167	":{"character":"	シロクマくんおかわりくれる？	","letter": "	Could I get another, Polar Bear?	", "pinyin":"	しろくまくんおかわりくれる？	"},																			
"	168	":{"character":"	パンダくんの悩み	","letter": "	Panda's Problems.	", "pinyin":"	ぱんだくんのなやみ	"},																			
"	169	":{"character":"	笹子さん肉じゃがが好きな男ってどう思う？	","letter": "	Miss Sasako, how do you feel about men who like meat and potato stew?	", "pinyin":"	ささごさんにくじゃががすきなおとこってどうおもう？	"},																			
"	170	":{"character":"	え！？今答えなくていいですか？	","letter": "	I'd rather not answer right now, if that's okay.	", "pinyin":"	え！？いまこたえなくていいですか？	"},																			
"	171	":{"character":"	いいですよ	","letter": "	That's fine.	", "pinyin":"	いいですよ	"},																			
"	172	":{"character":"	つれないなぁ	","letter": "	That was standoffish.	", "pinyin":"	つれないなぁ	"},																			
"	173	":{"character":"	ねえ僕いまだに自然体っていうのがわからないの	","letter": "	You know, I still can't figure out this 'act naturally' thing.	", "pinyin":"	ねえぼくいまだにしぜんたいっていうのがわからないの	"},																			
"	174	":{"character":"	自然体でいいです	","letter": "	Just act naturally.	", "pinyin":"	しぜんたいでいいです	"},																			
"	175	":{"character":"	いくら考えても答えが出なくて	","letter": "	No matter how much I think about it, I can't find the answer.	", "pinyin":"	いくらかんがえてもこたえがでなくて	"},																			
"	176	":{"character":"	常勤パンダさん自然体って何？	","letter": "	What does it mean to act naturally, Mr. Full-time Panda?	", "pinyin":"	じょうきんぱんださんしぜんたいってなに？	"},																			
"	177	":{"character":"	寝てる！	","letter": "	He's asleep!	", "pinyin":"	ねてる！	"},																			
"	178	":{"character":"	ねえ半田さん	","letter": "	Hey, Mr. Handa,	", "pinyin":"	ねえはんでんさん	"},																			
"	179	":{"character":"	自然体って何？	","letter": "	what does it mean to 'act naturally'?	", "pinyin":"	しぜんたいってなに？	"},																			
"	180	":{"character":"	言ったでしょ「自然体でいいです」って	","letter": "	You said it yourself, 'just act naturally.'	", "pinyin":"	いったでしょ「しぜんたいでいいです」って	"},																			
"	181	":{"character":"	自然でいることが自然体じゃないかな	","letter": "	I think the act of acting naturally is 'acting natural.'	", "pinyin":"	しぜんでいることがしぜんたいじゃないかな	"},																			
"	182	":{"character":"	ちょっとお手本見せてよ	","letter": "	Could you give me an example?	", "pinyin":"	ちょっとおてほんみせてよ	"},																			
"	183	":{"character":"	えぇ～	","letter": "	Oh, yeah.	", "pinyin":"	えぇ～	"},																			
"	184	":{"character":"	こんな感じだけど	","letter": "	Something like this.	", "pinyin":"	こんなかんじだけど	"},																			
"	185	":{"character":"	う～ん	","letter": "	That's not cute.	", "pinyin":"	う～ん	"},																			
"	186	":{"character":"	自然体ってどういうことなの？	","letter": "	What does it mean to 'act naturally'?	", "pinyin":"	しぜんたいってどういうことなの？	"},																			
"	187	":{"character":"	こんな表情？	","letter": "	Something like this?	", "pinyin":"	こんなひょうじょう？	"},																			
"	188	":{"character":"	自然体かどうかわかんないけどかわいいね	","letter": "	I don't know if that's acting natural or not, but it is cute.	", "pinyin":"	しぜんたいかどうかわかんないけどかわいいね	"},																			
"	189	":{"character":"	これは？o(=∩ω∩=)m	","letter": "	How about this?	", "pinyin":"	これは？o(=∩ω∩=)m	"},																			
"	190	":{"character":"	かわいい	","letter": "	It's cute.	", "pinyin":"	かわいい	"},																			
"	191	":{"character":"	これは～?	","letter": "	And this?	", "pinyin":"	これは～？n(*≧▽≦*)n	"},																			
"	192	":{"character":"	もうかわいいのはわかったよ	","letter": "	We get it. You're cute.	", "pinyin":"	もうかわいいのはわかったよ	"},																			
"	193	":{"character":"	そうなんだよね	","letter": "	I know.	", "pinyin":"	そうなんだよね	"},																			
"	194	":{"character":"	かわいいかわいいって言われてもどうしていいかわかんなくて	","letter": "	I keep getting called cute, but I still don't know what to do.	", "pinyin":"	かわいいかわいいっていわれてもどうしていいかわかんなくて	"},																			
"	195	":{"character":"	いいなぁ僕もかわいいって言われてみたいですよ	","letter": "	How nice. I wish someone would call me cute.	", "pinyin":"	いいなぁぼくもかわいいっていわれてみたいですよ	"},																			
"	196	":{"character":"	ゴロゴロしてるだけなのになぁ	","letter": "	All I'm doing is lounging around.	", "pinyin":"	ごろごろしてるだけなのになぁ	"},																			
"	197	":{"character":"	楽しそうでうらやましいよ	","letter": "	You always look like you're having fun. I'm jealous.	", "pinyin":"	たのしそうでうらやましいよ	"},																			
"	198	":{"character":"	ラッコさん？	","letter": "	Mr. Otter?	", "pinyin":"	らっこさん？	"},																			
"	199	":{"character":"	僕さお腹で貝割るでしょ？ヾ(≧へ≦)〃	","letter": "	You know I break shellfish on my tummy, right?	", "pinyin":"	ぼくさおなかでかいわるでしょ？ヾ(≧へ≦)〃	"},																			
"	200	":{"character":"	あれって大変だよお腹痛くなる	","letter": "	It's harder than it looks. It hurts my tummy.	", "pinyin":"	あれってたいへんだよおなかいたくなる	"},																			
"	201	":{"character":"	お腹に石だよ笹子さん	","letter": "	I'm banging a rock on my tummy, Miss Sasako.	", "pinyin":"	おなかにいしだよささごさん	"},																			
"	202	":{"character":"	はい？	","letter": "	I'm sorry?	", "pinyin":"	はい？	"},																			
"	203	":{"character":"	自分のお腹を石で叩いてみなよ	","letter": "	You should try banging a rock on your tummy.	", "pinyin":"	じぶんのおなかをいしでたたいてみなよ	"},																			
"	204	":{"character":"	痛いでしょ？	","letter": "	It would hurt, right?	", "pinyin":"	いたいでしょ？	"},																			
"	205	":{"character":"	はい…	","letter": "	Yes...	", "pinyin":"	はい…	"},																			
"	206	":{"character":"	お腹で割らなければいいのに	","letter": "	Then you shouldn't try breaking it on your tummy.	", "pinyin":"	おなかでわらなければいいのに	"},																			
"	207	":{"character":"	あれをやるとお客がわくからさ	","letter": "	But the audience loves seeing that.	", "pinyin":"	あれをやるとおきゃくがわくからさ	"},																			
"	208	":{"character":"	もうやめたら？その出し物	","letter": "	Why don't you give up that act?	", "pinyin":"	もうやめたら？そのだしもの	"},																			
"	209	":{"character":"	出し物っていうか習性だからね	","letter": "	It's not really an act. It's more of a trait.	", "pinyin":"	だしものっていうかしゅうせいだからね	"},																			
"	210	":{"character":"	かわいいからいいじゃないですか	","letter": "	I think it's fine since it's cute.	", "pinyin":"	かわいいからいいじゃないですか	"},																			
"	211	":{"character":"	かわいいんだけどさもうお腹が限界	","letter": "	It's cute, but my tummy's had enough.	", "pinyin":"	かわいいんだけどさもうおなかがげんかい	"},																			
"	212	":{"character":"	かわいいで言ったら私もかわいいんですけど	","letter": "	Since we're on the topic of cute, I'm cute, too.	", "pinyin":"	かわいいでいったらわたしもかわいいんですけど	"},																			
"	213	":{"character":"	コアラさん？	","letter": "	Mr. Koala?	", "pinyin":"	こあらさん？	"},																			
"	214	":{"character":"	ユーカリ？かわいく食べてますけどもうあれ限界です	","letter": "	I'm cutely eating eucalyptus, but I'm at my limit. I'm sick of it.	", "pinyin":"	ゆーかり？かわいくたべてますけどもうあれげんかいです	"},																			
"	215	":{"character":"	１日それを１キロくらい食べるんですから	","letter": "	I eat about one kilogram of that stuff a day.	", "pinyin":"	１にちそれを１きろくらいたべるんですから	"},																			
"	216	":{"character":"	涙目にもなりますよ(-。-)	","letter": "	You'd get teary-eyed, too, if you had to do it.	", "pinyin":"	なみだめにもなりますよ(-。-)	"},																			
"	217	":{"character":"	わかるわかるよ～	","letter": "	I know! I totally get you!	", "pinyin":"	わかるわかるよ～	"},																			
"	218	":{"character":"	コアリクイくんも？	","letter": "	You, too, Anteater?	", "pinyin":"	こありくいくんも？	"},																			
"	219	":{"character":"	アリクイってやめて！	","letter": "	I don't like the name Anteater!	", "pinyin":"	ありくいってやめて！	"},																			
"	220	":{"character":"	僕だってねアリばっかり食べたくないよ！飽きたよ。	","letter": "	I don't want to eat  only ants all the time! I'm sick of them!	", "pinyin":"	ぼくだってねありばっかりたべたくないよ！あきたよ。	"},																			
"	221	":{"character":"	笹子さんアリばっかり食べる気持わかる？	","letter": "	Do you know how it feels to have to eat ants all the time, Miss Sasako?!	", "pinyin":"	ささごさんありばっかりたべるきもちわかる？	"},																			
"	222	":{"character":"	アリクイだからね	","letter": "	Well, you are an anteater...	", "pinyin":"	ありくいだからね	"},																			
"	223	":{"character":"	しかたないね	","letter": "	You don't have much of a choice.	", "pinyin":"	しかたないね	"},																			
"	224	":{"character":"	確かにそうだけどもっといろんなもの食べてみたいよ	","letter": "	I know, but I want to eat other things, too!	", "pinyin":"	たしかにそうだけどもっといろんなものたべてみたいよ	"},																			
"	225	":{"character":"	いろんなもの？	","letter": "	Other things?	", "pinyin":"	いろんなもの？	"},																			
"	226	":{"character":"	何食べたいの？	","letter": "	Like what?	", "pinyin":"	なにたべたいの？	"},																			
"	227	":{"character":"	ほらラーメンとかさ	","letter": "	You know, like ramen!	", "pinyin":"	ほららーめんとかさ	"},																			
"	228	":{"character":"	チャーシュー食べられないんじゃない？	","letter": "	But I don't think you can eat chashu pork.	", "pinyin":"	ちゃーしゅーたべられないんじゃない？	"},																			
"	229	":{"character":"	いいんだよ細かいところは	","letter": "	You don't have to be concerned with the little things.	", "pinyin":"	いいんだよこまかいところは	"},																			
"	230	":{"character":"	見てくれるだけいいじゃないですか	","letter": "	At least people look at you.	", "pinyin":"	みてくれるだけいいじゃないですか	"},																			
"	231	":{"character":"	ラマさん？	","letter": "	Mr. Llama?	", "pinyin":"	らまさん？	"},																			
"	232	":{"character":"	僕なんてみんなほぼ素通りですよ	","letter": "	Everyone pretty much passes right by me.	", "pinyin":"	ぼくなんてみんなほぼすどおりですよ	"},																			
"	233	":{"character":"	いるの気づいてます？	","letter": "	Did you even know I was there?	", "pinyin":"	いるのきづいてます？	"},																			
"	234	":{"character":"	そういえば…	","letter": "	Come to think of it...	", "pinyin":"	そういえば…	"},																			
"	235	":{"character":"	動物園に行ったとき…	","letter": "	When we went to the zoo...	", "pinyin":"	どうぶつえんにいったとき…	"},																			
"	236	":{"character":"	みごとに素通りしたね	","letter": "	We did pretty much pass right by.	", "pinyin":"	みごとにすどおりしたね	"},																			
"	237	":{"character":"	ほらねラマなんてそんなものですよ	","letter": "	See? That's how it is, being a llama.	", "pinyin":"	ほらねらまなんてそんなものですよ	"},																			
"	238	":{"character":"	行列つくって感想とか言ってほしいですΣ(￣д￣)	","letter": "	I wish people would look longer, and form huge lines to tell me what they think of me.	", "pinyin":"	ぎょうれつつくってかんそうとかいってほしいですしぐま(￣д￣)	"},																			
"	239	":{"character":"	わぁ～いラマさん！	","letter": "	Wow, it's a llama!	", "pinyin":"	わぁ～いらまさん！	"},																			
"	240	":{"character":"	おい見ろよ！草食ってるぞ！写真写真撮れって！	","letter": "	Look, it's eating grass! Hurry! Take a picture!	", "pinyin":"	おいみろよ！くさくってるぞ！しゃしんしゃしんとれって！	"},																			
"	241	":{"character":"	草食べてるだけ？	","letter": "	You just eat grass?	", "pinyin":"	くさたべてるだけ？	"},																			
"	242	":{"character":"	地味だね	","letter": "	That's a little boring.	", "pinyin":"	じみだね	"},																			
"	243	":{"character":"	ラマさんってロバなの？	","letter": "	Are you a donkey, Mr. Llama?	", "pinyin":"	らまさんってろばなの？	"},																			
"	244	":{"character":"	だからラマです	","letter": "	As I said, I'm a llama.	", "pinyin":"	だかららまです	"},																			
"	245	":{"character":"	どっちかというとラクダです	","letter": "	If you had to compare, I'm closer to a camel.	", "pinyin":"	どっちかというとらくだです	"},																			
"	246	":{"character":"	コブは？	","letter": "	Do you have a hump?	", "pinyin":"	こぶは？	"},																			
"	247	":{"character":"	ないです	","letter": "	I do not.	", "pinyin":"	ないです	"},																			
"	248	":{"character":"	あの…何か芸とかないんですか？	","letter": "	Can you do any tricks or anything?	", "pinyin":"	あの…なにかげいとかないんですか？	"},																			
"	249	":{"character":"	草を食べるくらいです	","letter": "	Just eating grass.	", "pinyin":"	くさをたべるくらいです	"},																			
"	250	":{"character":"	できるといいね行列	","letter": "	I hope you get that huge line of yours.	", "pinyin":"	できるといいねぎょうれつ	"},																			
"	251	":{"character":"	見られればいいってもんじゃないよ	","letter": "	Being looked at isn't all that great.	", "pinyin":"	みられればいいってもんじゃないよ	"},																			
"	252	":{"character":"	バクさん	","letter": "	Mr. Tapir.	", "pinyin":"	ばくさん	"},																			
"	253	":{"character":"	僕なんて夢を食べる動物って言われがちだけど	","letter": "	I'm rumored to be an animal that eats dreams,	", "pinyin":"	ぼくなんてゆめをたべるどうぶつっていわれがちだけど	"},																			
"	254	":{"character":"	見た人に夢がないなんて言われてさ	","letter": "	but everyone who sees me is unimpressed.	", "pinyin":"	みたひとにゆめがないなんていわれてさ	"},																			
"	255	":{"character":"	夢を食べる動物って何？	","letter": "	What kind of animal eats dreams, anyway?	", "pinyin":"	ゆめをたべるどうぶつってなに？	"},																			
"	256	":{"character":"	ハードル上げすぎなんだよ	","letter": "	They're setting the bar much too high.	", "pinyin":"	はーどるあげすぎなんだよ	"},																			
"	257	":{"character":"	まぁまぁ…ジュゴンさんよりはいいよ	","letter": "	Now, now. You're better off than the sea cow.	", "pinyin":"	まぁまぁ…じゅごんさんよりはいいよ	"},																			
"	258	":{"character":"	人魚って前振りされてるんだから	","letter": "	They get compared to mermaids.	", "pinyin":"	にんぎょってまえぶりされてるんだから	"},																			
"	259	":{"character":"	ママ！人魚さんどこ？	","letter": "	Mommy, where's the mermaid?	", "pinyin":"	まま！にんぎょさんどこ？	"},																			
"	260	":{"character":"	見た人みんな黙っちゃうよ	","letter": "	Everyone who sees it doesn't know what to say.	", "pinyin":"	みたひとみんなだまっちゃうよ	"},																			
"	261	":{"character":"	ねぇ？	","letter": "	Right?	", "pinyin":"	ねぇ？	"},																			
"	262	":{"character":"	私に聞かないでください…	","letter": "	Please don't ask me.	", "pinyin":"	わたしにきかないでください…	"},																			
"	263	":{"character":"	あぁそうだね…	","letter": "	You have a point.	", "pinyin":"	あぁそうだね…	"},																			
"	264	":{"character":"	ジュゴンさんに比べたら僕はまだマシかもね	","letter": "	If you compare me to Ms. Sea Cow, I'm probably better off.	", "pinyin":"	じゅごんさんにくらべたらぼくはまだましかもね	"},																			
"	265	":{"character":"	僕も…	","letter": "	Me, too...	", "pinyin":"	ぼくも…	"},																			
"	266	":{"character":"	ナマケモノくん	","letter": "	Sloth.	", "pinyin":"	なまけものくん	"},																			
"	267	":{"character":"	動物園とは関係ないけど…	","letter": "	I'm not associated with the zoo, but...	", "pinyin":"	どうぶつえんとはかんけいないけど…	"},																			
"	268	":{"character":"	僕って一日中木にぶら下がってるイメージあるけど…	","letter": "	People think I just hang from a tree all day.	", "pinyin":"	ぼくっていちにちじゅうきにぶらさがってるいめーじあるけど…	"},																			
"	269	":{"character":"	実際どうなの？	","letter": "	And in reality?	", "pinyin":"	じっさいどうなの？	"},																			
"	270	":{"character":"	実際そうだけど…大変腕パンパン	","letter": "	I do in reality... But it's hard. My arms tingle.	", "pinyin":"	じっさいそうだけど…たいへんうでぱんぱん	"},																			
"	271	":{"character":"	一日中木にぶら下がったことある？笹子さん	","letter": "	Have you ever hung from a tree all day, Miss Sasako?	", "pinyin":"	いちにちじゅうきにぶらさがったことある？ささごさん	"},																			
"	272	":{"character":"	ナマケモノくんってナマケモノじゃないな	","letter": "	I guess Sloth isn't really a sloth.	", "pinyin":"	なまけものくんってなまけものじゃないな	"},																			
"	273	":{"character":"	頑張り者だね	","letter": "	He's a really hard worker.	", "pinyin":"	がんばりしゃだね	"},																			
"	274	":{"character":"	もっと言って	","letter": "	Tell me more.	", "pinyin":"	もっといって	"},																			
"	275	":{"character":"	みんな悩んでるんだな	","letter": "	Apparently everyone has problems.	", "pinyin":"	みんななやんでるんだな	"},																			
"	276	":{"character":"	実は好きなペンギンがいてさ	","letter": "	I have a problem too. You see, I have this penguin that I like.	", "pinyin":"	じつはすきなぺんぎんがいてさ	"},																			
"	277	":{"character":"	誰にも言わないでほしいんだけどね	","letter": "	Don't tell anyone though, okay?	", "pinyin":"	だれにもいわないでほしいんだけどね	"},																			
"	278	":{"character":"	あぁやっぱりいろいろと皆さん悩みが尽きないんですね	","letter": "	It seems that there isn't an end to everyone's problems.	", "pinyin":"	あぁやっぱりいろいろとみなさんなやみがつきないんですね	"},																			
"	279	":{"character":"	そうだよね	","letter": "	You're right.	", "pinyin":"	そうだよね	"},																			
"	280	":{"character":"	ほんとですね	","letter": "	No kidding.	", "pinyin":"	ほんとですね	"},																			
"	281	":{"character":"	ちょっと聞いてよ	","letter": "	Hey, listen to me.	", "pinyin":"	ちょっときいてよ	"},																			
"	282	":{"character":"	シロクマさんは悩みはないの？	","letter": "	Don't you have any problems, Mr. Polar Bear?	", "pinyin":"	しろくまさんはなやみはないの？	"},																			
"	283	":{"character":"	あるよ	","letter": "	I do.	", "pinyin":"	あるよ	"},																			
"	284	":{"character":"	え？そうなの？意外	","letter": "	Really? You do? That's unexpected.	", "pinyin":"	え？そうなの？いがい	"},																			
"	285	":{"character":"	アイドルにならないかって言われてるんだけど	","letter": "	I've been asked if I wanted to become an idol,	", "pinyin":"	あいどるにならないかっていわれてるんだけど	"},																			
"	286	":{"character":"	アイドルと学業の両立がねぇ	","letter": "	but fitting that in with my studies would be hard.	", "pinyin":"	あいどるとがくぎょうのりょうりつがねぇ	"},																			
"	287	":{"character":"	また嘘ばっかり	","letter": "	There you go, lying again.	", "pinyin":"	またうそばっかり	"},																			
"	288	":{"character":"	笹子さんは？	","letter": "	How about you, Miss Sasako?	", "pinyin":"	ささごさんは？	"},																			
"	289	":{"character":"	え？ありません	","letter": "	I don't have any.	", "pinyin":"	え？ありません	"},																			
"	290	":{"character":"	ひとつも？	","letter": "	Not even one?	", "pinyin":"	ひとつも？	"},																			
"	291	":{"character":"	はい	","letter": "	Indeed.	", "pinyin":"	はい	"},																			
"	292	":{"character":"	あ…	","letter": "	Uh...	", "pinyin":"	あ…	"},																			
"	293	":{"character":"	ん？何？	","letter": "	What is it?	", "pinyin":"	ん？なに？	"},																			
"	294	":{"character":"	雛人形って燃えるゴミなのか、燃えないゴミなのかどっちなんだろうって	","letter": "	I was wondering if Hina dolls should go with the burnable or non-burnable garbage.	", "pinyin":"	ひなにんぎょうってもえるごみなのか、もえないごみなのかどっちなんだろうって	"},																			
"	295	":{"character":"	いいかな？それはあとで	","letter": "	How about we discuss that later?	", "pinyin":"	いいかな？それはあとで	"},																			
"	296	":{"character":"	僕なんてさパン屋に行くたびに思うよ	","letter": "	Every time I go to the bakery, I think about it.	", "pinyin":"	ぼくなんてさぱんやにいくたびにおもうよ	"},																			
"	297	":{"character":"	いい？誰にも言わないでよ	","letter": "	Listen, don't tell anyone, okay?	", "pinyin":"	いい？だれにもいわないでよ	"},																			
"	298	":{"character":"	どうやって告白しようか悩みは尽きないよ	","letter": "	I keep trying to figure out how to ask her out.	", "pinyin":"	どうやってこくはくしようかなやみはつきないよ	"},																			
"	299	":{"character":"	どう思う？パンダくん	","letter": "	What do you think, Panda?	", "pinyin":"	どうおもう？ぱんだくん	"},																			
"	300	":{"character":"	フフフ…	","letter": "	Hmph...	", "pinyin":"	ふふふ…	"},																			
"	301	":{"character":"	ちょっと笑いごとじゃないよ	","letter": "	Hey, this is no laughing matter.	", "pinyin":"	ちょっとわらいごとじゃないよ	"},																			
"	302	":{"character":"	寝てる！W(ﾟДﾟ)w	","letter": "	He's asleep!	", "pinyin":"	ねてる！W(゜Д゜)w	"},																			
"	303	":{"character":"	えぇと…	","letter": "	Hm...	", "pinyin":"	えぇと…	"},																			
"	304	":{"character":"	いつから寝てたんですかね？	","letter": "	I wonder how long he's been asleep.	", "pinyin":"	いつからねてたんですかね？	"},																			
"	305	":{"character":"	チャーシューの話のあとくらいじゃない？	","letter": "	Probably somewhere right after the talk of chashu pork.	", "pinyin":"	ちゃーしゅーのはなしのあとくらいじゃない？	"},																			
"	306	":{"character":"	前半ですね	","letter": "	So somewhere at the beginning of the conversation.	", "pinyin":"	ぜんはんですね	"},																			
"	307	":{"character":"	あっシロクマさん	","letter": "	Oh, Mr. Polar Bear.	", "pinyin":"	あっしろくまさん	"},																			
"	308	":{"character":"	おかわりお願いします	","letter": "	Could I get seconds, please?	", "pinyin":"	おかわりおねがいします	"},																			
"	309	":{"character":"	うん	","letter": "	Sure.	", "pinyin":"	うん	"},																			
"	310	":{"character":"	自然体かぁ	","letter": "	Acting naturally,' huh?	", "pinyin":"	しぜんたいかぁ	"},																			
"	311	":{"character":"	どうしたらいいんだろう…	","letter": "	I wonder what I should do?	", "pinyin":"	どうしたらいいんだろう…	"},																			
"	312	":{"character":"	パンダくんすっかり自然体だね	","letter": "	Panda is totally acting naturally right now.	", "pinyin":"	ぱんだくんすっかりしぜんたいだね	"},																			
"	313	":{"character":"	そうですね	","letter": "	Indeed he is.	", "pinyin":"	そうですね	"},																			
"	314	":{"character":"	いらっしゃい(＾?＾）／＼(＾?＾）	","letter": "	Welcome.	", "pinyin":"	いらっしゃい(＾?＾）／＼(＾?＾）	"},																			
"	315	":{"character":"	はぁ…今日は疲れちゃった	","letter": "	I'm so tired today.	", "pinyin":"	はぁ…きょうはつかれちゃった	"},																			
"	316	":{"character":"	パンダくん	","letter": "	Hey, Panda.	", "pinyin":"	ぱんだくん	"},																			
"	317	":{"character":"	なぁに？	","letter": "	What?	", "pinyin":"	なぁに？	"},																			
"	318	":{"character":"	あれからずっと考えてたんだけどさ	","letter": "	I've been thinking since then...	", "pinyin":"	あれからずっとかんがえてたんだけどさ	"},																			
"	319	":{"character":"	パンダくんにとって自然体っていうのはさ	","letter": "	Acting naturally' for you is	", "pinyin":"	ぱんだくんにとってしぜんたいっていうのはさ	"},																			
"	320	":{"character":"	君がいちばんリラックスできる場所	","letter": "	being in the place you can relax the most.	", "pinyin":"	きみがいちばんりらっくすできるばしょ	"},																			
"	321	":{"character":"	あっ！	","letter": "	Oh!	", "pinyin":"	あっ！	"},																			
"	322	":{"character":"	つまりさ…	","letter": "	Meaning―	", "pinyin":"	つまりさ…	"},																			
"	323	":{"character":"	そんなことよりペンギンさん	","letter": "	Never mind that, Mr. Penguin.	", "pinyin":"	そんなことよりぺんぎんさん	"},																			
"	324	":{"character":"	新しいパンダグッズ買っちゃったんだけど	","letter": "	I bought new panda merchandise.	", "pinyin":"	あたらしいぱんだぐっずかっちゃったんだけど	"},																			
"	325	":{"character":"	何入れればいいと思う？O(*≧▽≦)ツ	","letter": "	What do you think I should put in here?	", "pinyin":"	なにいれればいいとおもう？O(*≧▽≦)つ	"},																			
"	326	":{"character":"	肉まんでいいんじゃない？	","letter": "	How about a meat bun?	", "pinyin":"	にくまんでいいんじゃない？	"},																			
"	327	":{"character":"	ペンギンさんペンギンさん	","letter": "	Mr. Penguin, Mr. Penguin!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	328	":{"character":"	しろくまカフェが来週から駐車場になっちゃうって本当	","letter": "	Is it true that Polar Bear's Café is being turned into a parking lot next week?	", "pinyin":"	しろくまかふぇがらいしゅうからちゅうしゃじょうになっちゃうってほんとう	"},																			
"	329	":{"character":"	そんな噂聞いてないよ	","letter": "	I didn't hear a rumor like that.	", "pinyin":"	そんなうわさきいてないよ	"},																			
"	330	":{"character":"	やっぱりプチ整形してない	","letter": "	Are you sure you haven't had plastic surgery?	", "pinyin":"	やっぱりぷちせいけいしてない	"},																			
"	331	":{"character":"	してないよ	","letter": "	I did not.	", "pinyin":"	してないよ	"},																			
"	332	":{"character":"	だから逆にどこを見て思ったの	","letter": "	I ask again, what makes you think I did?	", "pinyin":"	だからぎゃくにどこをみておもったの	"},																			
"	333	":{"character":"	しろくまくん終わって	","letter": "	Polar Bear, could you finish it?	", "pinyin":"	しろくまくんおわって	"},																			
"	334	":{"character":"	次回のしろくま???	","letter": "	Next time on Polar Bear's...	", "pinyin":"	じかいのしろくま???	"},																			
"	335	":{"character":"	カフェでしょう忘れちゃった	","letter": "	It's 'Café.' Did you actually forget?	", "pinyin":"	かふぇでしょうわすれちゃった	"},																			
"	336	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}