import re
from mechanize import Browser
from bs4 import BeautifulSoup
import time
import requests

# import external file
import raw

obj = [
    "tânisi",
    "namôya",
    "namôya nânitaw",
    "nânitaw",
    "kiya",
    "mâka",
    "kiya mâka.",
    "pêyakwan",
    "nitisiyihkâson",
    "kitisiyihkâson",
    "ohci",
    "niya",
    "tânitê",
    "mêkwâc",
    "niwîkin",
    "êkota",
    "kiwîkin",
    "mîna",
    "nîsta",
    "kîsta",
    "okiskinwahamâkêw",
    "okiskinwahamâkan",
    "kayahtê",
    "omosômimâw",
    "ohkomimâw",
    "okâwîmâw",
    "ohtâwîmâw",
    "okosisimâw",
    "otânisimâw",
    "omisimâw",
    "ostêsimâw",
    "osîmimâw",
    "awâsis",
    "mitâs",
    "wâpikwaniy",
    "asikan",
    "maskosiy",
    "astis",
    "nîpiy",
    "tâpiskâkan",
    "maskihkiy",
    "maskasiy",
    "mêstakay",
    "ospwâkan",
    "mîpit",
    "asiniy",
    "miskîsik",
    "êmihkwân",
    "misit",
    "askihk",
    "miskât",
    "apoy",
    "mistikwân",
    "âhcâpiy",
    "mitôn",
    "akask",
    "mihtawakay",
    "sêhkêpayîs",
    "micihciy",
    "sôminis",
    "mitêhimin",
    "ayôskan",
    "iyinimin",
    "oskâtâsk",
    "takwahimin",
    "wihkihkasikan",
    "wihkwaskwa",
    "awa",
    "ôma",
    "ana",
    "anima",
    "nâha",
    "nêma",
    "ôki",
    "Ôhi",
    "aniki",
    "anihi",
    "nêki",
    "nêhi",
    "tâniwâ",
    "tâniwê",
    "tâniwêhkâk",
    "tâniwêhâ",
    "tâna",
    "tânima",
    "tâniki",
    "tânihi",
    "kîkwây",
    "kîkwâya",
    "awîna",
    "awîniki",
    "kêko",
    "nipâ",
    "waniskâ",
    "kâkîsimo",
    "kistâpitêho",
    "kâsihkwê",
    "sîkaho",
    "postayawinisê",
    "kîsitêpo",
    "api",
    "mîciso",
    "minihkwê",
    "pasikô",
    "wayawî",
    "pimohtê",
    "pôsi",
    "pimipayi",
    "kapâ",
    "atoskê",
    "masinahikê",
    "ayamihcikê",
    "nîmihito",
    "nikamo",
    "mâto",
    "pâhpi",
    "sêsâwî",
    "pimipahtâ",
    "kîwê",
    "pihtokwê",
    "nohtêkatê",
    "kisîpêkiyâkanê",
    "kâsîyâkanê",
    "nohtêkwasi",
    "kêtayawinisê",
    "kawisimo",
    "matwêhkwâmi",
    "otâhk ispayiw",
    "kotak ispayiki",
    "pêyak ispayiw",
    "anohc kâ-ispayik",
    "wâpahki",
    "awasi-wâpahki",
    "otâkosîhk",
    "awasi-tâkosîhk",
    "tipiskohk",
    "awasi-tipiskohk",
    "tipiskâki",
    "askîwin",
    "anohc kâ-askîwik",
    "otâhk askîwin",
    "kotak askîwiki",
    "wiyâs",
    "mostosowiyâs",
    "kohkôsiwiyâs",
    "kohkôsiwîyin",
    "kohkôsopwâm",
    "môsowiyâs",
    "atihkowiyâs",
    "sikopicikaniwiyâs",
    "mitêh",
    "wîniy",
    "mitêyaniy",
    "micakisîsa",
    "pimihkân",
    "kahkêwak",
    "paskwâmostosowiyâs",
    "pahkahâhkwânowiyâs",
    "amiskowiyâs",
    "mâyatihkowiyâs",
    "mînis",
    "iyinimina",
    "wîsakîmina",
    "maskêkômina",
    "nîpiminâna",
    "takwahiminâna",
    "mitêhimina",
    "misâskatômina",
    "otisîhkân",
    "kâ-mihkwaskwâhki",
    "nîpiya",
    "napatâkwa",
    "kiscikâna",
    "askipwâwa",
    "wîyihtihp",
    "tohtôsâpôwipimiy",
    "pimiy",
    "manihikan",
    "tohtôsâpoy",
    "wâwi",
    "iskwêsisâpoy",
    "iskotêwâpoy",
    "nihtiy",
    "maskihkîwâpoy",
    "pihkatêwâpoy",
    "sîwâpoy",
    "kisâstêwâpoy",
    "sôminâpoy",
    "mîcimâpoy",
    "osâwâpoy",
    "sîwinôs/sîwâs",
    "âmômêyi",
    "âmôsîsipâskwat",
    "sîsipâskwat",
    "pêskomina",
    "wîsakat",
    "askîwisîwihtâkan",
    "sîwihtâkan",
    "sîwinikan",
    "wihtikôwimîciwin",
    "mîciwin",
    "ohpihkasikan",
    "wihkês",
    "wihkaskwa",
    "paskwâwihkaskwa",
    "maskihkiy",
    "apistâcêkos",
    "môswa",
    "wâwâskêsiw",
    "mâyatihk",
    "wâpos",
    "apisimôsos",
    "sîsîp",
    "niska",
    "atihk",
    "maskwa",
    "mwâkwa",
    "anikwacâsk",
    "pahkahâhkwân",
    "paskwâmostos",
    "pihêw",
    "paspaskiw",
    "misihêw",
    "amisk",
    "kinosêw",
    "okâw",
    "atihkamêk",
    "iyinikinosêw",
    "miniy",
    "otônapiy",
    "namêw",
    "namêkos",
    "namêpin",
    "manôminak",
    "maskosîmina",
    "ôcîcisak",
    "wâpinôminak",
    "mahtâmin",
    "oskâtâsk",
    "maskimocisak",
    "wihcêkaskosîs",
    "kihcôkiniy",
    "okiniyak",
    "sâpôminak",
    "ayôskanak",
    "sôminisak",
    "picikwâs",
    "wâkâs",
    "osâwâs",
    "pakân",
    "pihkasikan",
    "ânômin",
    "pahkwêsikan",
    "pîswêhkasikan",
    "pîswêhkasikanisak",
    "sîwihkasikan",
    "wihkihkasikan",
    "sîwihkasikanak",
    "sîwinikan",
    "yîwahikanak",
    "miskwamiy",
    "namîscîkos",
    "mohkomân",
    "cîstahâsêpon",
    "êmihkwân",
    "oyâkan",
    "minihkwâcikan",
    "askihk",
    "sîsîpaskihk",
    "sâsâpiskisikan",
    "sâsêskihkwân",
    "kocawâkanis",
    "akocikan",
    "kotawânâpisk",
    "kêsiskawihkasikan",
    "sêkowêpinâpisk",
    "ahkwacikan",
    "tahkascikan",
    "kisêpîsim",
    "mikisiwipîsim",
    "niskipîsim",
    "ayîkipîsim",
    "sâkipakâwipîsim",
    "pâskâwihowipîsim",
    "paskowipîsim",
    "ohpahowipîsim",
    "nôcihitowipîsim",
    "takwâkipîsim",
    "pinâskowipîsim",
    "ihkopîwipîsim",
    "pawâcakinasîsipîsim",
    "pêyak",
    "nîso",
    "nisto",
    "nêwo",
    "niyânan",
    "nikotwâsik",
    "têpakohp",
    "ayênânêw",
    "kêkâ-mitâtaht*",
    "mitâtaht",
    "pêyakosâp",
    "nîsosâp",
    "nistosâp",
    "nêwosâp",
    "niyânanosâp",
    "nikotwâs(ik)osâp",
    "têpakohposâp",
    "ayênânêwosâp",
    "kêkâ-mitâtahtosâp",
    "nîs(om)itanaw",
    "nistomitanaw",
    "nê(wo)mitanaw",
    "niyânanomitanaw",
    "nikotwâsikomitanaw",
    "têpakohpomitanaw",
    "ayênânê(wo)mitanaw",
    "kêkâ-mitâtahtomitanaw",
    "mitâtahtomitanaw"
]

# word = "pimipahtâ"

def extract_audio(arg, number):

    br = Browser()
    br.set_handle_robots(False)
    
    query = "https://speech-db.altlab.app/maskwacis/advanced_search_results/?transcription=" + arg + "&translation=&analysis=&lemma=&exact=exact&status=all&quality=all&kind=all&semantic_class=&speaker="
    print(query)

    r = requests.get(query)
    soup = BeautifulSoup(r.content, 'html.parser')

    audio_array = soup.find_all('source')
    audios = ['https://speech-db.altlab.app' + audio['src'] for audio in audio_array]

    # print(audios)

    if(audios):
        print(audios[0])
        doc = requests.get(audios[0])
        filename = str(number) + '.m4a'
        with open(filename, 'wb') as f:
            f.write(doc.content)

# Set timer
starttime = time.time()
i = 0

# extract_audio(word)

while i <= len(obj):
    time.sleep(1 - ((time.time() - starttime) % 1))
    extract_audio(obj[i], i+1)
    print(obj[i])
    i = i + 1




