obj = {
"	1	":{"character":"	パンダくん張り切る	","letter": "	Panda, you're all worked up.	", "pinyin":"	ぱんだくんはりきる	"},
"	2	":{"character":"	どうしたの？パンダくん	","letter": "	What's wrong? Panda.	", "pinyin":"	どうしたの？ぱんだくん	"},
"	3	":{"character":"	元気ないですね	","letter": "	You don't seem well.	", "pinyin":"	げんきないですね	"},
"	4	":{"character":"	実はさ…常勤パンダさんが	","letter": "	Actually... my full-time panda...	", "pinyin":"	じつはさ…じょうきんぱんださんが	"},
"	5	":{"character":"	親戚の結婚式でしばらく実家の中国に帰るんだって	","letter": "	He's going back to his parents' home in China for a while for a relative's wedding.	", "pinyin":"	しんせきのけっこんしきでしばらくじっかのちゅうごくにかえるんだって	"},
"	6	":{"character":"	なんでそれで元気ないの？	","letter": "	Why are you so down?	", "pinyin":"	なんでそれでげんきないの？	"},
"	7	":{"character":"	それがね…	","letter": "	Because...	", "pinyin":"	それがね…	"},
"	8	":{"character":"	１週間留守にするからって	","letter": "	She's going away for a week.	", "pinyin":"	１しゅうかんるすにするからって	"},
"	9	":{"character":"	代わりにバイトフルに入ることになっちゃったんだよ	","letter": "	I'm going away for a week, so I'm going to get a full time job instead.	", "pinyin":"	かわりにばいとふるにはいることになっちゃったんだよ	"},
"	10	":{"character":"	動物園のバイト？	","letter": "	The zoo job?	", "pinyin":"	どうぶつえんのばいと？	"},
"	11	":{"character":"	そう	","letter": "	Yes.	", "pinyin":"	そう	"},
"	12	":{"character":"	でもたった１週間でしょ？	","letter": "	But it's only a week, right?	", "pinyin":"	でもたった１しゅうかんでしょ？	"},
"	13	":{"character":"	１週間もだよ～	","letter": "	For a week?	", "pinyin":"	１しゅうかんもだよ～	"},
"	14	":{"character":"	早起きできるかな…しかも毎日	","letter": "	I don't know if I can get up early... and every day.	", "pinyin":"	はやおきできるかな…しかもまいにち	"},
"	15	":{"character":"	自信がないよ	","letter": "	I'm not sure.	", "pinyin":"	じしんがないよ	"},
"	16	":{"character":"	大変なのは早起きじゃなくて満員電車じゃない？	","letter": "	It's not the getting up early that's hard. It's the crowded train.	", "pinyin":"	たいへんなのははやおきじゃなくてまんいんでんしゃじゃない？	"},
"	17	":{"character":"	満員電車？	","letter": "	Crowded train?	", "pinyin":"	まんいんでんしゃ？	"},
"	18	":{"character":"	朝会社に行く人たちで電車がいっぱいになるのが	","letter": "	The train is full of people going to work in the morning.	", "pinyin":"	あさかいしゃにいくひとたちででんしゃがいっぱいになるのが	"},
"	19	":{"character":"	満員電車だよ	","letter": "	It's a crowded train.	", "pinyin":"	まんいんでんしゃだよ	"},
"	20	":{"character":"	僕らコウテイペンギンは慣れてるからいいけど…	","letter": "	We penguins are used to it.	", "pinyin":"	ぼくらこうていぺんぎんはなれてるからいいけど…	"},
"	21	":{"character":"	え？ペンギンさんも電車乗るの？	","letter": "	What? Do penguins take the train too?	", "pinyin":"	え？ぺんぎんさんもでんしゃのるの？	"},
"	22	":{"character":"	違うよ	","letter": "	No, they don't.	", "pinyin":"	ちがうよ	"},
"	23	":{"character":"	南極じゃみんな集まって子育てするから	","letter": "	In Antarctica, penguins gather together to raise their young.	", "pinyin":"	なんきょくじゃみんなあつまってこそだてするから	"},
"	24	":{"character":"	もう満員電車並みの混雑だよ	","letter": "	It's as crowded as a crowded train.	", "pinyin":"	もうまんいんでんしゃなみのこんざつだよ	"},
"	25	":{"character":"	みんなおしくらまんじゅう状態だもんね	","letter": "	It's like a big joke.	", "pinyin":"	みんなおしくらまんじゅうじょうたいだもんね	"},
"	26	":{"character":"	おしくらまんじゅう？	","letter": "	A ball and chain?	", "pinyin":"	おしくらまんじゅう？	"},
"	27	":{"character":"	楽しそうだね	","letter": "	Sounds like fun. ^#)	", "pinyin":"	たのしそうだね	"},
"	28	":{"character":"	なんだか楽しみになってきたよ	","letter": "	I'm starting to look forward to it.	", "pinyin":"	なんだかたのしみになってきたよ	"},
"	29	":{"character":"	早く帰って明日に備えなくちゃ	","letter": "	I'd better go home and get ready for tomorrow.	", "pinyin":"	はやくかえってあしたにそなえなくちゃ	"},
"	30	":{"character":"	じゃあ…ごちそうさま	","letter": "	Well then... thanks for the food.	", "pinyin":"	じゃあ…ごちそうさま	"},
"	31	":{"character":"	大丈夫かな…	","letter": "	I hope you're okay...	", "pinyin":"	だいじょうぶかな…	"},
"	32	":{"character":"	あ…早く早く	","letter": "	Hurry up, hurry up, hurry up.	", "pinyin":"	あ…はやくはやく	"},
"	33	":{"character":"	急がないと満員電車に乗れないよ	","letter": "	Hurry up or you'll miss the crowded train.	", "pinyin":"	いそがないとまんいんでんしゃにのれないよ	"},
"	34	":{"character":"	おはようパンダくん	","letter": "	Good morning, panda.	", "pinyin":"	おはようぱんだくん	"},
"	35	":{"character":"	おはようございま～す	","letter": "	Good morning.	", "pinyin":"	おはようございま～す	"},
"	36	":{"character":"	バイト？頑張ってね～	","letter": "	Part-time job? Good luck.	", "pinyin":"	ばいと？がんばってね～	"},
"	37	":{"character":"	行ってきま～す	","letter": "	I'm off.	", "pinyin":"	いってきま～す	"},
"	38	":{"character":"	すみませ～ん	","letter": "	Sorry.	", "pinyin":"	すみませ～ん	"},
"	39	":{"character":"	いらっしゃいませ	","letter": "	Welcome.	", "pinyin":"	いらっしゃいませ	"},
"	40	":{"character":"	お花選んでいただけますか？	","letter": "	Would you please choose some flowers?	", "pinyin":"	おはなえらんでいただけますか？	"},
"	41	":{"character":"	おしくらまんじゅうだね～	","letter": "	You've got a bun in your head.	", "pinyin":"	おしくらまんじゅうだね～	"},
"	42	":{"character":"	ドアが閉まりますご注意くださいドアが閉まります	","letter": "	Please be careful... the doors are closing...	", "pinyin":"	どあがしまりますごちゅういくださいどあがしまります	"},
"	43	":{"character":"	すみませんパンダ専用車両はどこですか？	","letter": "	Excuse me, where is the panda car?	", "pinyin":"	すみませんぱんだせんようしゃりょうはどこですか？	"},
"	44	":{"character":"	ないと思います…	","letter": "	I don't think so...	", "pinyin":"	ないとおもいます…	"},
"	45	":{"character":"	ど…どこか…空いてるところは…	","letter": "	I don't think there's... anywhere... that's open...	", "pinyin":"	ど…どこか…あいてるところは…	"},
"	46	":{"character":"	きついよ…	","letter": "	It's tight...	", "pinyin":"	きついよ…	"},
"	47	":{"character":"	この先揺れますのでご注意ください	","letter": "	Please be careful, it's going to be bumpy.	", "pinyin":"	このさきゆれますのでごちゅういください	"},
"	48	":{"character":"	パンダく～ん	","letter": "	Panda!	", "pinyin":"	ぱんだく～ん	"},
"	49	":{"character":"	ごはんだよ？	","letter": "	I'm going to eat.	", "pinyin":"	ごはんだよ？	"},
"	50	":{"character":"	そこ置いといて	","letter": "	Leave it there.	", "pinyin":"	そこおいといて	"},
"	51	":{"character":"	うん…	","letter": "	I know it's hard...	", "pinyin":"	うん…	"},
"	52	":{"character":"	朝からバイトで大変なのはわかるけどさ	","letter": "	I know you've had a hard morning's work.	", "pinyin":"	あさからばいとでたいへんなのはわかるけどさ	"},
"	53	":{"character":"	もう少しお客さんにサービスしてよ	","letter": "	But you should serve the customers a little better.	", "pinyin":"	もうすこしおきゃくさんにさーびすしてよ	"},
"	54	":{"character":"	もう満員電車やだ…	","letter": "	I don't want to be on a crowded train anymore...	", "pinyin":"	もうまんいんでんしゃやだ…	"},
"	55	":{"character":"	半田さん朝代わってよ	","letter": "	Mr. Handa, take over this morning.	", "pinyin":"	はんでんさんあさかわってよ	"},
"	56	":{"character":"	やだって言ったって仕方ないでしょう？	","letter": "	I don't have a choice.	", "pinyin":"	やだっていったってしかたないでしょう？	"},
"	57	":{"character":"	僕もう少し遅く来るから朝だけパンダ代わって	","letter": "	I'll come a little later, so please cover for Panda in the morning.	", "pinyin":"	ぼくもうすこしおそくくるからあさだけぱんだかわって	"},
"	58	":{"character":"	代われって言われても無理だし	","letter": "	I can't do that.	", "pinyin":"	かわれっていわれてもむりだし	"},
"	59	":{"character":"	大丈夫体型似てるから	","letter": "	Don't worry. We have the same body type.	", "pinyin":"	だいじょうぶたいけいにてるから	"},
"	60	":{"character":"	いやいや…	","letter": "	No, no, no, no, no, no, no, no, no, no, no, no, no, no, no.	", "pinyin":"	いやいや…	"},
"	61	":{"character":"	ありえないから頑張ってよ約束でしょ	","letter": "	No, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no.	", "pinyin":"	ありえないからがんばってよやくそくでしょ	"},
"	62	":{"character":"	ごはんここ置いとくからね	","letter": "	I'll leave your food right here.	", "pinyin":"	ごはんここおいとくからね	"},
"	63	":{"character":"	チェッ	","letter": "	Okay.	", "pinyin":"	ちぇっ	"},
"	64	":{"character":"	あ～満員電車のこと考えると	","letter": "	Oh, I can't stop thinking about the train.	", "pinyin":"	あ～まんいんでんしゃのことかんがえると	"},
"	65	":{"character":"	食欲が出ないよ	","letter": "	I'm not hungry.	", "pinyin":"	しょくよくがでないよ	"},
"	66	":{"character":"	パンダくん	","letter": "	Panda!	", "pinyin":"	ぱんだくん	"},
"	67	":{"character":"	パンダくんにお届け物です	","letter": "	Delivery for you, Mr. Panda.	", "pinyin":"	ぱんだくんにおとどけものです	"},
"	68	":{"character":"	花？	","letter": "	Flowers?	", "pinyin":"	はな？	"},
"	69	":{"character":"	いつも見てますお仕事頑張ってね	","letter": "	I'm always watching you, good luck with your work.	", "pinyin":"	いつもみてますおしごとがんばってね	"},
"	70	":{"character":"	あなたのファンよりリンリン	","letter": "	From your fan, Rin Rin Rin.	", "pinyin":"	あなたのふぁんよりりんりん	"},
"	71	":{"character":"	僕のファン！？	","letter": "	My fan!	", "pinyin":"	ぼくのふぁん！？	"},
"	72	":{"character":"	リンリンちゃん	","letter": "	Hey, Linlin...	", "pinyin":"	りんりんちゃん	"},
"	73	":{"character":"	僕頑張るよ！	","letter": "	I'll do my best!	", "pinyin":"	ぼくがんばるよ！	"},
"	74	":{"character":"	ママパンダさん立った！	","letter": "	Mama Panda, you're up!	", "pinyin":"	ままぱんださんたった！	"},
"	75	":{"character":"	すごいわね	","letter": "	That's great!	", "pinyin":"	すごいわね	"},
"	76	":{"character":"	リンリンちゃん	","letter": "	Hey, Linlin.	", "pinyin":"	りんりんちゃん	"},
"	77	":{"character":"	いってきます！	","letter": "	I'm off!	", "pinyin":"	いってきます！	"},
"	78	":{"character":"	もしかしてリンリンちゃん？	","letter": "	Is that you, little ringtone?	", "pinyin":"	もしかしてりんりんちゃん？	"},
"	79	":{"character":"	もしもし	","letter": "	Hello?	", "pinyin":"	もしもし	"},
"	80	":{"character":"	リンリンちゃん僕頑張るからね！	","letter": "	I'll do my best, Lin-Lin!	", "pinyin":"	りんりんちゃんぼくがんばるからね！	"},
"	81	":{"character":"	リンリンちゃんが見ててくれるんだから	","letter": "	I know you're watching over me.	", "pinyin":"	りんりんちゃんがみててくれるんだから	"},
"	82	":{"character":"	きっと…あのなかにリンリンちゃんが…	","letter": "	I'm sure she's in there...	", "pinyin":"	きっと…あのなかにりんりんちゃんが…	"},
"	83	":{"character":"	ここんとこ張り切ってるなパンダくん	","letter": "	You've been working so hard lately, panda.	", "pinyin":"	ここんとこはりきってるなぱんだくん	"},
"	84	":{"character":"	でもどうして？	","letter": "	But why?	", "pinyin":"	でもどうして？	"},
"	85	":{"character":"	お疲れ様	","letter": "	Thanks for your hard work.	", "pinyin":"	おつかれさま	"},
"	86	":{"character":"	今日常勤パンダさん戻って来たんでしょ？	","letter": "	You're back full time today, right, Panda?	", "pinyin":"	きょうじょうきんぱんださんもどってきたんでしょ？	"},
"	87	":{"character":"	うん	","letter": "	Yes, I did.	", "pinyin":"	うん	"},
"	88	":{"character":"	お土産もらった	","letter": "	I got you a souvenir.	", "pinyin":"	おみやげもらった	"},
"	89	":{"character":"	パンダくん１日も遅刻しなかったんだってね	","letter": "	I heard you weren't late even for one day.	", "pinyin":"	ぱんだくん１にちもちこくしなかったんだってね	"},
"	90	":{"character":"	すごいじゃない	","letter": "	That's great.	", "pinyin":"	すごいじゃない	"},
"	91	":{"character":"	大切な人が見ててくれるから	","letter": "	Someone important is watching over you.	", "pinyin":"	たいせつなひとがみててくれるから	"},
"	92	":{"character":"	それにしてもなんかすごく疲れてない？	","letter": "	But still, don't you look tired?	", "pinyin":"	それにしてもなんかすごくつかれてない？	"},
"	93	":{"character":"	なんだかあちこちボロボロで汚れてるし	","letter": "	You're all dirty and torn up.	", "pinyin":"	なんだかあちこちぼろぼろでよごれてるし	"},
"	94	":{"character":"	頑張りすぎなんじゃない	","letter": "	I think you're working too hard.	", "pinyin":"	がんばりすぎなんじゃない	"},
"	95	":{"character":"	ゆっくり休んだほうがいいと思うよ	","letter": "	I think you should get some rest.	", "pinyin":"	ゆっくりやすんだほうがいいとおもうよ	"},
"	96	":{"character":"	うんあの子にこんな格好見せられないし	","letter": "	I can't let her see me like this.	", "pinyin":"	うんあのこにこんなかっこうみせられないし	"},
"	97	":{"character":"	あの子？	","letter": "	That girl?	", "pinyin":"	あのこ？	"},
"	98	":{"character":"	今日はもう帰るね	","letter": "	I'm going home tonight.	", "pinyin":"	こんにちはもうかえるね	"},
"	99	":{"character":"	あ忘れてるよ天津甘栗チョコレート！	","letter": "	You forgot... chocolate.	", "pinyin":"	あわすれてるよてんしんあまぐりちょこれーと！	"},
"	100	":{"character":"	昨日もステキ今日も頑張ってね	","letter": "	Yesterday was great.	", "pinyin":"	きのうもすてききょうもがんばってね	"},
"	101	":{"character":"	リンリンちゃん１週間僕頑張ったよ	","letter": "	I worked hard all week, Linlin.	", "pinyin":"	りんりんちゃん１しゅうかんぼくがんばったよ	"},
"	102	":{"character":"	急がなくっちゃ	","letter": "	I've got to hurry.	", "pinyin":"	いそがなくっちゃ	"},
"	103	":{"character":"	リンリンちゃん今日も僕が朝からいるって思ってないかな	","letter": "	I hope you didn't think I'd be here all morning.	", "pinyin":"	りんりんちゃんきょうもぼくがあさからいるっておもってないかな	"},
"	104	":{"character":"	すれ違いになったら大変	","letter": "	We'd be in trouble if we passed each other.	", "pinyin":"	すれちがいになったらたいへん	"},
"	105	":{"character":"	おはようパンダくん	","letter": "	Good morning, Panda.	", "pinyin":"	おはようぱんだくん	"},
"	106	":{"character":"	おはようございます	","letter": "	Good morning, Mr. Panda.	", "pinyin":"	おはようございます	"},
"	107	":{"character":"	今日から通常勤務じゃないの？	","letter": "	I thought you'd start your regular work today.	", "pinyin":"	きょうからつうじょうきんむじゃないの？	"},
"	108	":{"character":"	えっ？ああ…うん…	","letter": "	What? Oh... yeah...	", "pinyin":"	えっ？ああ…うん…	"},
"	109	":{"character":"	だよねドキッとしちゃったよ	","letter": "	I know, I'm so excited.	", "pinyin":"	だよねどきっとしちゃったよ	"},
"	110	":{"character":"	僕が選んだ花気に入ってくれた？	","letter": "	Did you like the flowers I chose?	", "pinyin":"	ぼくがえらんだはなきにいってくれた？	"},
"	111	":{"character":"	えっ？ああリンリンちゃんのお花？大切にしてるよ	","letter": "	What? Oh, your flowers? I treasure them.	", "pinyin":"	えっ？あありんりんちゃんのおはな？たいせつにしてるよ	"},
"	112	":{"character":"	あっそうだちょっと見せたいものがあるんだ	","letter": "	Oh, I want to show you something.	", "pinyin":"	あっそうだちょっとみせたいものがあるんだ	"},
"	113	":{"character":"	待ってて	","letter": "	Wait here.	", "pinyin":"	まってて	"},
"	114	":{"character":"	はい	","letter": "	Okay.	", "pinyin":"	はい	"},
"	115	":{"character":"	今日はリンリンちゃん来てないの？	","letter": "	Isn't Rin-ling here today?	", "pinyin":"	きょうはりんりんちゃんきてないの？	"},
"	116	":{"character":"	ああリンリンって僕のことね	","letter": "	Oh, by 'Ling Ling' you mean me.	", "pinyin":"	あありんりんってぼくのことね	"},
"	117	":{"character":"	林厘太郎	","letter": "	Rintaro.	", "pinyin":"	はやしりんたろう	"},
"	118	":{"character":"	パンダ大好きなんだ	","letter": "	I love pandas.	", "pinyin":"	ぱんだだいすきなんだ	"},
"	119	":{"character":"	あっパンダくんはその中でも別格だよ	","letter": "	Oh, pandas are special among pandas.	", "pinyin":"	あっぱんだくんはそのなかでもべっかくだよ	"},
"	120	":{"character":"	リンリンズベストショットはこれ	","letter": "	Here's my best shot of Rin-Rin.	", "pinyin":"	りんりんずべすとしょっとはこれ	"},
"	121	":{"character":"	お気に入りだから大きくしてみたんだ	","letter": "	I made it big because it's my favorite.	", "pinyin":"	おきにいりだからおおきくしてみたんだ	"},
"	122	":{"character":"	パンダくんにもあげるね	","letter": "	I'll give it to Mr. Panda too.	", "pinyin":"	ぱんだくんにもあげるね	"},
"	123	":{"character":"	いらない…	","letter": "	I don't want it...	", "pinyin":"	いらない…	"},
"	124	":{"character":"	これ返す…	","letter": "	I'll give it back...	", "pinyin":"	これかえす…	"},
"	125	":{"character":"	なんで？	","letter": "	Why?	", "pinyin":"	なんで？	"},
"	126	":{"character":"	ウワーン！	","letter": "	Oh, no!	", "pinyin":"	うわーん！	"},
"	127	":{"character":"	あっパンダくん！	","letter": "	Oh, panda!	", "pinyin":"	あっぱんだくん！	"},
"	128	":{"character":"	みんなのパフェ	","letter": "	Parfaits for everyone!	", "pinyin":"	みんなのぱふぇ	"},
"	129	":{"character":"	こんにちは	","letter": "	Hello, there.	", "pinyin":"	こんにちは	"},
"	130	":{"character":"	シロクマくん？	","letter": "	Polar bear?	", "pinyin":"	しろくまくん？	"},
"	131	":{"character":"	どうしたの？何か考え事？	","letter": "	What's wrong? Something on your mind?	", "pinyin":"	どうしたの？なにかかんがえごと？	"},
"	132	":{"character":"	これ	","letter": "	Here.	", "pinyin":"	これ	"},
"	133	":{"character":"	おだんご？	","letter": "	A dumpling?	", "pinyin":"	おだんご？	"},
"	134	":{"character":"	なんで信号って赤青黄色の３色なのか考えてた	","letter": "	I was thinking about why traffic lights are red, blue and yellow.	", "pinyin":"	なんでしんごうってあかあおきいろの３しょくなのかかんがえてた	"},
"	135	":{"character":"	そうなんだ	","letter": "	I see.	", "pinyin":"	そうなんだ	"},
"	136	":{"character":"	違うよパンダくん	","letter": "	No, panda.	", "pinyin":"	ちがうよぱんだくん	"},
"	137	":{"character":"	シロクマさんカフェのスペシャルメニューを考えてるんだよ	","letter": "	I'm thinking of a special menu for the Polar Bear Cafe.	", "pinyin":"	しろくまさんかふぇのすぺしゃるめにゅーをかんがえてるんだよ	"},
"	138	":{"character":"	スペシャルメニュー？	","letter": "	Special menu?	", "pinyin":"	すぺしゃるめにゅー？	"},
"	139	":{"character":"	また実技落とされちゃったよ…!!	","letter": "	I'm failing my practical again...	", "pinyin":"	またじつぎおとされちゃったよ...!!	"},
"	140	":{"character":"	実技？	","letter": "	Practical test?	", "pinyin":"	じつぎ？	"},
"	141	":{"character":"	ああ自動車教習所ね	","letter": "	Oh, the driving school.	", "pinyin":"	ああじどうしゃきょうしゅうじょね	"},
"	142	":{"character":"	大体あの教官細かすぎなんだよ！	","letter": "	That instructor is way too detailed!	", "pinyin":"	だいたいあのきょうかんこまかすぎなんだよ！	"},
"	143	":{"character":"	どう細かいんですか？	","letter": "	How is he too detailed?	", "pinyin":"	どうこまかいんですか？	"},
"	144	":{"character":"	いやねキョロキョロしないでまっすぐ前を見ろ！とか	","letter": "	Don't look around, look straight ahead! Or something like that.	", "pinyin":"	いやねきょろきょろしないでまっすぐまえをみろ！とか	"},
"	145	":{"character":"	慌てすぎるな！とか	","letter": "	Don't panic too much! or 'Don't be in too much of a hurry!	", "pinyin":"	あわてすぎるな！とか	"},
"	146	":{"character":"	ハンドルを握るときには手をパタパタさせるな！とか	","letter": "	Don't flap your hands when you steer! and so on.	", "pinyin":"	はんどるをにぎるときにはてをぱたぱたさせるな！とか	"},
"	147	":{"character":"	それはダメなんじゃないですか？	","letter": "	Isn't that no good?	", "pinyin":"	それはだめなんじゃないですか？	"},
"	148	":{"character":"	あの教官のおかげで	","letter": "	Thanks to that instructor.	", "pinyin":"	あのきょうかんのおかげで	"},
"	149	":{"character":"	いつまでたってもペン子さんをドライブデートに誘えないよ	","letter": "	I'll never be able to ask Penko-san out on a date.	", "pinyin":"	いつまでたってもぺんごさんをどらいぶでーとにさそえないよ	"},
"	150	":{"character":"	デート？	","letter": "	A date?	", "pinyin":"	でーと？	"},
"	151	":{"character":"	それはテント	","letter": "	That's a tent	", "pinyin":"	それはてんと	"},
"	152	":{"character":"	それは弁当	","letter": "	That's a lunch box	", "pinyin":"	それはべんとう	"},
"	153	":{"character":"	それは電灯	","letter": "	That's a light.	", "pinyin":"	それはでんとう	"},
"	154	":{"character":"	それは剣道	","letter": "	That's kendo.	", "pinyin":"	それはけんどう	"},
"	155	":{"character":"	デートだってば！！	","letter": "	It's a date!	", "pinyin":"	でーとだってば！！	"},
"	156	":{"character":"	どうやったら彼女のハートを射止めることができるんだろう？	","letter": "	How can I win her heart?	", "pinyin":"	どうやったらかのじょのはーとをいとめることができるんだろう？	"},
"	157	":{"character":"	射止める…	","letter": "	Win her heart...	", "pinyin":"	いとめる…	"},
"	158	":{"character":"	シロクマくんならどうする？	","letter": "	What would you do, Polar Bear?	", "pinyin":"	しろくまくんならどうする？	"},
"	159	":{"character":"	待つ	","letter": "	Wait.	", "pinyin":"	まつ	"},
"	160	":{"character":"	待つの？	","letter": "	Wait?	", "pinyin":"	まつの？	"},
"	161	":{"character":"	うんひたすら待つね	","letter": "	Yeah, I'd just wait and wait.	", "pinyin":"	うんひたすらまつね	"},
"	162	":{"character":"	へえ～っなんか大人だね	","letter": "	Wow, you're so mature.	", "pinyin":"	へえ～っなんかおとなだね	"},
"	163	":{"character":"	そうこれができないと大人になれない	","letter": "	If you can't do this, you can't be an adult.	", "pinyin":"	そうこれができないとおとなになれない	"},
"	164	":{"character":"	なれない？	","letter": "	You can't?	", "pinyin":"	なれない？	"},
"	165	":{"character":"	ひたすら待って待って待って	","letter": "	Just wait and wait and wait.	", "pinyin":"	ひたすらまってまってまって	"},
"	166	":{"character":"	出てきたところを…	","letter": "	Wait, wait, wait, wait, wait, wait, wait, wait.	", "pinyin":"	でてきたところを…	"},
"	167	":{"character":"	射止めてないよ！それじゃ仕留めちゃうよ！	","letter": "	I didn't shoot him! You're gonna get him!	", "pinyin":"	いとめてないよ！それじゃしとめちゃうよ！	"},
"	168	":{"character":"	シロクマくんちゃんと考えてよ！	","letter": "	Polar bear, you've got to think!	", "pinyin":"	しろくまくんちゃんとかんがえてよ！	"},
"	169	":{"character":"	ペンギンさん見てて思ったんだけど…	","letter": "	I was just looking at the penguins and I thought...	", "pinyin":"	ぺんぎんさんみてておもったんだけど…	"},
"	170	":{"character":"	えっ何？	","letter": "	What?	", "pinyin":"	えっなに？	"},
"	171	":{"character":"	笹子さんパフェフェアーはどうかな？	","letter": "	Sasago, how about a parfait?	", "pinyin":"	ささごさんぱふぇふぇあーはどうかな？	"},
"	172	":{"character":"	パフェですかいいですね	","letter": "	Parfait? That sounds good!	", "pinyin":"	ぱふぇですかいいですね	"},
"	173	":{"character":"	何それ？デートと全然関係ないよね	","letter": "	What's that? It has nothing to do with the date.	", "pinyin":"	なにそれ？でーととぜんぜんかんけいないよね	"},
"	174	":{"character":"	どこをどうすればそうなるの？	","letter": "	How can it be?	", "pinyin":"	どこをどうすればそうなるの？	"},
"	175	":{"character":"	さっきまでスペシャルメニューの話をしてたんですけど	","letter": "	We were talking about the special menu earlier.	", "pinyin":"	さっきまですぺしゃるめにゅーのはなしをしてたんですけど	"},
"	176	":{"character":"	なかなか決まらなくて	","letter": "	But we couldn't decide on anything.	", "pinyin":"	なかなかきまらなくて	"},
"	177	":{"character":"	スペシャルメニューでパフェ？	","letter": "	Parfaits on the special menu?	", "pinyin":"	すぺしゃるめにゅーでぱふぇ？	"},
"	178	":{"character":"	僕パフェ好き	","letter": "	I like parfaits.	", "pinyin":"	ぼくぱふぇずき	"},
"	179	":{"character":"	パフェはいいですけど	","letter": "	Parfait is fine.	", "pinyin":"	ぱふぇはいいですけど	"},
"	180	":{"character":"	パフェフェアーってなんか言いづらいですよね	","letter": "	But 'parfait' is hard to say, isn't it?	", "pinyin":"	ぱふぇふぇあーってなんかいいづらいですよね	"},
"	181	":{"character":"	いや全然大丈夫	","letter": "	No, it's totally fine.	", "pinyin":"	いやぜんぜんだいじょうぶ	"},
"	182	":{"character":"	よし決まり	","letter": "	Okay, it's decided!	", "pinyin":"	よしきまり	"},
"	183	":{"character":"	パヘヘアーにしよう	","letter": "	Let's say 'parfait hair.	", "pinyin":"	ぱへへあーにしよう	"},
"	184	":{"character":"	言えてないよね	","letter": "	You didn't say it!	", "pinyin":"	いえてないよね	"},
"	185	":{"character":"	イチゴパフェバナナパフェチョコパフェ	","letter": "	Strawberry parfait, banana parfait, chocolate parfait...	", "pinyin":"	いちごぱふぇばななぱふぇちょこぱふぇ	"},
"	186	":{"character":"	間違いはないけどフェアなのに定番だけじゃつまらない	","letter": "	I'm sure there's no mistake, but it's a fair, and it's boring to just have the standard stuff.	", "pinyin":"	まちがいはないけどふぇあなのにていばんだけじゃつまらない	"},
"	187	":{"character":"	う～んスペシャルなパフェか	","letter": "	A special parfait...	", "pinyin":"	う～んすぺしゃるなぱふぇか	"},
"	188	":{"character":"	シロクマさん	","letter": "	Polar bear!	", "pinyin":"	しろくまさん	"},
"	189	":{"character":"	パフェフェアー	","letter": "	You do parfait fairs, don't you?	", "pinyin":"	ぱふぇふぇあー	"},
"	190	":{"character":"	をするんですよね？メニューは決まりましたか？	","letter": "	You're having a parfait fair, right? Have you decided on the menu?	", "pinyin":"	をするんですよね？めにゅーはきまりましたか？	"},
"	191	":{"character":"	今検討中	","letter": "	I'm thinking about it now.	", "pinyin":"	いまけんとうちゅう	"},
"	192	":{"character":"	だったらマンドリルパフェはどうですか？	","letter": "	Then how about a mandoril parfait?	", "pinyin":"	だったらまんどりるぱふぇはどうですか？	"},
"	193	":{"character":"	それ何？	","letter": "	What's that?	", "pinyin":"	それなに？	"},
"	194	":{"character":"	マンドリルなパフェです	","letter": "	It's a mandrill parfait!	", "pinyin":"	まんどりるなぱふぇです	"},
"	195	":{"character":"	それはもうすごい迫力なんです！	","letter": "	It's so powerful!	", "pinyin":"	それはもうすごいはくりょくなんです！	"},
"	196	":{"character":"	パフェに迫力はいらないかな	","letter": "	I don't think parfaits need to be powerful.	", "pinyin":"	ぱふぇにはくりょくはいらないかな	"},
"	197	":{"character":"	う～んスペシャルなパフェね	","letter": "	A very special parfait!	", "pinyin":"	う～んすぺしゃるなぱふぇね	"},
"	198	":{"character":"	シロクマさんじゃないですか	","letter": "	Isn't that a polar bear?	", "pinyin":"	しろくまさんじゃないですか	"},
"	199	":{"character":"	ああラマさん	","letter": "	Llama!	", "pinyin":"	ああらまさん	"},
"	200	":{"character":"	こんにちは	","letter": "	Hello, Mr. Llama.	", "pinyin":"	こんにちは	"},
"	201	":{"character":"	聞きましたよ	","letter": "	I heard.	", "pinyin":"	ききましたよ	"},
"	202	":{"character":"	何を？	","letter": "	Heard what?	", "pinyin":"	なにを？	"},
"	203	":{"character":"	パフェフェアーをやるんですよね？	","letter": "	You're having a parfait event, aren't you?	", "pinyin":"	ぱふぇふぇあーをやるんですよね？	"},
"	204	":{"character":"	ステキなパフェを思いついたんですよ	","letter": "	I came up with a great idea for a parfait.	", "pinyin":"	すてきなぱふぇをおもいついたんですよ	"},
"	205	":{"character":"	パフェなのにとってもヘルシーなんです	","letter": "	It's a parfait, but it's healthy.	", "pinyin":"	ぱふぇなのにとってもへるしーなんです	"},
"	206	":{"character":"	いいねどんなの？	","letter": "	What kind of parfait?	", "pinyin":"	いいねどんなの？	"},
"	207	":{"character":"	自信作ですよ	","letter": "	I'm very proud of it!	", "pinyin":"	じしんさくですよ	"},
"	208	":{"character":"	草大盛りパフェです	","letter": "	It's a parfait with a big bowl of grass!	", "pinyin":"	くさおおもりぱふぇです	"},
"	209	":{"character":"	どんなパフェかというとですね	","letter": "	What kind of parfait is it?	", "pinyin":"	どんなぱふぇかというとですね	"},
"	210	":{"character":"	お皿の上に草がのっていてですね	","letter": "	It's a plate with grass on it.	", "pinyin":"	おさらのうえにくさがのっていてですね	"},
"	211	":{"character":"	お皿？	","letter": "	A plate?	", "pinyin":"	おさら？	"},
"	212	":{"character":"	その上に水煮の草がのっていていてですね	","letter": "	On top of that, there is boiled grass!	", "pinyin":"	そのうえにみずにのくさがのっていていてですね	"},
"	213	":{"character":"	更にその上に覆いかぶさるように産地直送の草がのるんです	","letter": "	And on top of that, there's grass directly from the farm!	", "pinyin":"	さらにそのうえにおおいかぶさるようにさんちちょくそうのくさがのるんです	"},
"	214	":{"character":"	いやそれすでにパフェじゃないしどっちかっていうとサラダかな	","letter": "	No, it's not a parfait, it's more like a salad!	", "pinyin":"	いやそれすでにぱふぇじゃないしどっちかっていうとさらだかな	"},
"	215	":{"character":"	う～んスペシャルなパフェ…	","letter": "	A special parfait...	", "pinyin":"	う～んすぺしゃるなぱふぇ…	"},
"	216	":{"character":"	シロクマさ～んここです！	","letter": "	Polar bear!	", "pinyin":"	しろくまさ～んここです！	"},
"	217	":{"character":"	待って～！	","letter": "	Wait~! I'll be right back!	", "pinyin":"	まって～！	"},
"	218	":{"character":"	は…話があるから…	","letter": "	I need to talk to you...	", "pinyin":"	は…はなしがあるから…	"},
"	219	":{"character":"	どうしたの？ゾウガメさん	","letter": "	What's wrong? Mr. Elephant Turtle!	", "pinyin":"	どうしたの？ぞうがめさん	"},
"	220	":{"character":"	パフェ…フェ…	","letter": "	Parfait... fe...	", "pinyin":"	ぱふぇ…ふぇ…	"},
"	221	":{"character":"	パフェフェアー？	","letter": "	Parfait?	", "pinyin":"	ぱふぇふぇあー？	"},
"	222	":{"character":"	甲羅パフェは？	","letter": "	Shell parfait?	", "pinyin":"	こうらぱふぇは？	"},
"	223	":{"character":"	甲羅パフェ？	","letter": "	Shell parfait?	", "pinyin":"	こうらぱふぇ？	"},
"	224	":{"character":"	食べづらいかな	","letter": "	Is it hard to eat?	", "pinyin":"	たべづらいかな	"},
"	225	":{"character":"	う～んスペシャルなパフェ…	","letter": "	Special parfait...	", "pinyin":"	う～んすぺしゃるなぱふぇ…	"},
"	226	":{"character":"	何がいいかな？	","letter": "	What would you like?	", "pinyin":"	なにがいいかな？	"},
"	227	":{"character":"	シロクマさん！	","letter": "	Polar bear!	", "pinyin":"	しろくまさん！	"},
"	228	":{"character":"	あっ！コアリクイくん	","letter": "	Ah! A core-eater!	", "pinyin":"	あっ！こありくいくん	"},
"	229	":{"character":"	すごいパフェを…	","letter": "	I've come up with an amazing parfait...	", "pinyin":"	すごいぱふぇを…	"},
"	230	":{"character":"	すごいパフェを考えました	","letter": "	I've come up with an amazing parfait!	", "pinyin":"	すごいぱふぇをかんがえました	"},
"	231	":{"character":"	どんなパフェ？	","letter": "	What kind of parfait?	", "pinyin":"	どんなぱふぇ？	"},
"	232	":{"character":"	それはもうすごいトッピングで！	","letter": "	With amazing toppings!	", "pinyin":"	それはもうすごいとっぴんぐで！	"},
"	233	":{"character":"	ビジュアルは黒ゴマ的ですが…	","letter": "	It looks like a black sesame seed...	", "pinyin":"	びじゅあるはくろごまてきですが…	"},
"	234	":{"character":"	すごくうごめいている！	","letter": "	It's very moaning!	", "pinyin":"	すごくうごめいている！	"},
"	235	":{"character":"	いやそれはいいかな	","letter": "	No, that's okay.	", "pinyin":"	いやそれはいいかな	"},
"	236	":{"character":"	だからめちゃくちゃ生き生きとうごめいている黒ゴマ的トッピングの…	","letter": "	So lively and lively with black sesame-like toppings...	", "pinyin":"	だからめちゃくちゃいきいきとうごめいているくろごまてきとっぴんぐの…	"},
"	237	":{"character":"	う～ん和のテイストもいいけど…	","letter": "	I like the Japanese taste, but...	", "pinyin":"	う～んわのていすともいいけど…	"},
"	238	":{"character":"	どうしたの？シロクマくん	","letter": "	What's wrong? Polar bear!	", "pinyin":"	どうしたの？しろくまくん	"},
"	239	":{"character":"	早くパフェフェアーのメニュー考えないとみんなが暴走してるから	","letter": "	We need to think of a menu for the parfait event, otherwise everyone's going to run out of control.	", "pinyin":"	はやくぱふぇふぇあーのめにゅーかんがえないとみんながぼうそうしてるから	"},
"	240	":{"character":"	暴走?	","letter": "	Runaway? (;P-please!)!	", "pinyin":"	ぼうそう?	"},
"	241	":{"character":"	スペシャルメニューだけにみんな結構楽しみにしてるんだね	","letter": "	Everyone's looking forward to the special menu, huh?	", "pinyin":"	すぺしゃるめにゅーだけにみんなけっこうたのしみにしてるんだね	"},
"	242	":{"character":"	はいは～い！僕にいいアイディア	","letter": "	Yes, yes! I have a great idea!	", "pinyin":"	はいは～い！ぼくにいいあいでぃあ	"},
"	243	":{"character":"	はい	","letter": "	Here you go!	", "pinyin":"	はい	"},
"	244	":{"character":"	これこれ！竹パフェ	","letter": "	This is it! Bamboo parfait!	", "pinyin":"	これこれ！たけぱふぇ	"},
"	245	":{"character":"	パンダくんに聞いて作ってみました	","letter": "	I made it after asking Mr. Panda!	", "pinyin":"	ぱんだくんにきいてつくってみました	"},
"	246	":{"character":"	すごいでしょ？	","letter": "	Isn't it amazing?	", "pinyin":"	すごいでしょ？	"},
"	247	":{"character":"	竹ゼリーに笹クリームをのせて新鮮な笹とタケノコをトッピングした上に	","letter": "	Bamboo jelly topped with bamboo cream and fresh bamboo grass and bamboo shoots.	", "pinyin":"	たけぜりーにささくりーむをのせてしんせんなささとたけのこをとっぴんぐしたうえに	"},
"	248	":{"character":"	刻んだ竹がいっぱいのっかってるの	","letter": "	topped with fresh bamboo grass and bamboo shoots!	", "pinyin":"	きざんだたけがいっぱいのっかってるの	"},
"	249	":{"character":"	すごく緑色なパフェだね	","letter": "	It's a very green parfait!	", "pinyin":"	すごくみどりいろなぱふぇだね	"},
"	250	":{"character":"	パンダくん以外食べないかも	","letter": "	Only Mr. Panda would eat it!	", "pinyin":"	ぱんだくんいがいたべないかも	"},
"	251	":{"character":"	そう？こんなにおいしそうなのに？	","letter": "	Is that so? Even though it looks so delicious?	", "pinyin":"	そう？こんなにおいしそうなのに？	"},
"	252	":{"character":"	刻んだ竹が口に刺さりそうだよ	","letter": "	The chopped bamboo is sticking in my mouth!	", "pinyin":"	きざんだたけがくちにささりそうだよ	"},
"	253	":{"character":"	パンダくん…パフェって言えばなんでもパフェだと思ってるでしょ	","letter": "	Panda... you think anything that says parfait is parfait.	", "pinyin":"	ぱんだくん…ぱふぇっていえばなんでもぱふぇだとおもってるでしょ	"},
"	254	":{"character":"	任せておけないよ	","letter": "	I won't leave it to you.	", "pinyin":"	まかせておけないよ	"},
"	255	":{"character":"	よしここは僕のアイディアを…	","letter": "	Okay, here's my idea...	", "pinyin":"	よしここはぼくのあいでぃあを…	"},
"	256	":{"character":"	イワシパフェ	","letter": "	Sardine parfait.	", "pinyin":"	いわしぱふぇ	"},
"	257	":{"character":"	ＤＨＡたっぷり頭もよくなる	","letter": "	Full of DHA... and it'll make you smarter.	", "pinyin":"	ＤＨＡたっぷりあたまもよくなる	"},
"	258	":{"character":"	ダメ？	","letter": "	No?	", "pinyin":"	だめ？	"},
"	259	":{"character":"	じゃあ今からだと旬なアジとかでもいいと思うよ	","letter": "	Well, I think we could try some horse mackerels. They're in season now.	", "pinyin":"	じゃあいまからだとしゅんなあじとかでもいいとおもうよ	"},
"	260	":{"character":"	魚から離れようよ	","letter": "	Let's get away from the fish.	", "pinyin":"	さかなからはなれようよ	"},
"	261	":{"character":"	なんていうかそれパフェっていうより…	","letter": "	That's not really a parfait, it's more like...	", "pinyin":"	なんていうかそれぱふぇっていうより…	"},
"	262	":{"character":"	オシャレなお刺身？	","letter": "	Stylish sashimi?	", "pinyin":"	おしゃれなおさしみ？	"},
"	263	":{"character":"	あっ！こういうのはどうでしょうか？	","letter": "	Ah! How about this?	", "pinyin":"	あっ！こういうのはどうでしょうか？	"},
"	264	":{"character":"	パンダパフェ	","letter": "	Panda Parfait	", "pinyin":"	ぱんだぱふぇ	"},
"	265	":{"character":"	パンダの頭はバニラアイスで耳や顔はチョコレートです	","letter": "	The panda's head is vanilla ice cream, and its ears and face are chocolate!	", "pinyin":"	ぱんだのあたまはばにらあいすでみみやかおはちょこれーとです	"},
"	266	":{"character":"	わぁ～！パフェになってもパンダってやっぱりかわいいね	","letter": "	Wow! Pandas are so cute even as parfaits!	", "pinyin":"	わぁ～！ぱふぇになってもぱんだってやっぱりかわいいね	"},
"	267	":{"character":"	クマクマパフェ	","letter": "	Kumakuma Parfait	", "pinyin":"	くまくまぱふぇ	"},
"	268	":{"character":"	バニラとコーヒーアイスで作ってみました	","letter": "	I made it with vanilla and coffee ice cream!	", "pinyin":"	ばにらとこーひーあいすでつくってみました	"},
"	269	":{"character":"	いいね！	","letter": "	So good!	", "pinyin":"	いいね！	"},
"	270	":{"character":"	南極パフェ	","letter": "	Antarctic Parfait	", "pinyin":"	なんきょくぱふぇ	"},
"	271	":{"character":"	かき氷で氷山をイメージしました	","letter": "	I made it with shaved ice to resemble an iceberg!	", "pinyin":"	かきごおりでひょうざんをいめーじしました	"},
"	272	":{"character":"	すご～い！かわいい！新商品ですか？	","letter": "	Amazing! So cute! Is this a new product?	", "pinyin":"	すご～い！かわいい！しんしょうひんですか？	"},
"	273	":{"character":"	あ…いえ試作品です	","letter": "	Oh...no, it's just a prototype.	", "pinyin":"	あ…いえしさくひんです	"},
"	274	":{"character":"	よかったらどうぞ	","letter": "	Please try it if you like.	", "pinyin":"	よかったらどうぞ	"},
"	275	":{"character":"	えっ！？いいんですか？	","letter": "	What? You don't mind?	", "pinyin":"	えっ！？いいんですか？	"},
"	276	":{"character":"	では…いただきます！	","letter": "	Then...let's eat!	", "pinyin":"	では…いただきます！	"},
"	277	":{"character":"	まずはパンダさんから！	","letter": "	Let's start with the panda!	", "pinyin":"	まずはぱんださんから！	"},
"	278	":{"character":"	じゃあペンギンさんも！	","letter": "	Then the penguins!	", "pinyin":"	じゃあぺんぎんさんも！	"},
"	279	":{"character":"	じゃあシロクマさんも！	","letter": "	Then the polar bear!	", "pinyin":"	じゃあしろくまさんも！	"},
"	280	":{"character":"	この鼻のとこ食べちゃおうかな！	","letter": "	I think I'll eat his nose!	", "pinyin":"	このはなのとこたべちゃおうかな！	"},
"	281	":{"character":"	アハハハハ！ひどい！！私もえい！	","letter": "	Hahahahaha! That's terrible! Me too Ei!	", "pinyin":"	あはははは！ひどい！！わたしもえい！	"},
"	282	":{"character":"	これ絶対お店で出してくださいね	","letter": "	Please serve this at the restaurant for sure!	", "pinyin":"	これぜったいおみせでだしてくださいね	"},
"	283	":{"character":"	よかった！大人気です	","letter": "	Thank goodness! It's a big hit!	", "pinyin":"	よかった！だいにんきです	"},
"	284	":{"character":"	そ…そうだね	","letter": "	Well... yes.	", "pinyin":"	そ…そうだね	"},
"	285	":{"character":"	ちょっと聞いてよ！また今日も落とされたよ	","letter": "	Hey, listen up! You dropped me again today.	", "pinyin":"	ちょっときいてよ！またきょうもおとされたよ	"},
"	286	":{"character":"	すみませんお水ください	","letter": "	Excuse me, can I have a glass of water, please?	", "pinyin":"	すみませんおみずください	"},
"	287	":{"character":"	いつも以上に大繁盛じゃないどうしたの？	","letter": "	What's going on?	", "pinyin":"	いつもいじょうにだいはんじょうじゃないどうしたの？	"},
"	288	":{"character":"	新メニューのフェアが大人気らしいよ	","letter": "	What's going on? I heard the new menu is very popular at the fair.	", "pinyin":"	しんめにゅーのふぇあがだいにんきらしいよ	"},
"	289	":{"character":"	あぁパフェフェアー？	","letter": "	Oh, the parfait fair?	", "pinyin":"	あぁぱふぇふぇあー？	"},
"	290	":{"character":"	ワンプレートランチフェア	","letter": "	One-plate lunch fair.	", "pinyin":"	わんぷれーとらんちふぇあ	"},
"	291	":{"character":"	パフェじゃないんだ？	","letter": "	Not a parfait?	", "pinyin":"	ぱふぇじゃないんだ？	"},
"	292	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguin, penguin, penguin.	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},
"	293	":{"character":"	どうしたのパンダ君	","letter": "	What's the matter, panda?	", "pinyin":"	どうしたのぱんだくん	"},
"	294	":{"character":"	何も言わないで預金通帳もらえるかな	","letter": "	Can I have my bank book without saying anything?	", "pinyin":"	なにもいわないでよきんつうちょうもらえるかな	"},
"	295	":{"character":"	嫌だってこといいかな	","letter": "	Can I tell you what I don't want to do?	", "pinyin":"	いやだってこといいかな	"},
"	296	":{"character":"	白熊君まとめて	","letter": "	Polar Bear, put it all together.	", "pinyin":"	しろくまくんまとめて	"},
"	297	":{"character":"	次回のしろくまカフェは	","letter": "	Next time at the Shirokuma Cafe.	", "pinyin":"	じかいのしろくまかふぇは	"},
"	298	":{"character":"	ボルトがル語でお送りします	","letter": "	Bolt will be speaking in Japanese.	", "pinyin":"	ぼるとがるごでおおくりします	"},
"	299	":{"character":"	日本語で行こう	","letter": "	Let's go in Japanese!	", "pinyin":"	にほんごでいこう	"},
"	300	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみにY	"},
}