const hiraganaMonographMap = {
    "あ": { "letter": "a" },
    "い": { "letter": "i" },
    "う": { "letter": "u" },
    "え": { "letter": "e" },
    "お": { "letter": "o" },
    "か": { "letter": "ka" },
    "き": { "letter": "ki" },
    "く": { "letter": "ku" },
    "け": { "letter": "ke" },
    "こ": { "letter": "ko" },
    "さ": { "letter": "sa" },
    "し": { "letter": "shi" },
    "す": { "letter": "su" },
    "せ": { "letter": "se" },
    "そ": { "letter": "so" },
    "た": { "letter": "ta" },
    "ち": { "letter": "chi" },
    "つ": { "letter": "tsu" },
    "て": { "letter": "te" },
    "と": { "letter": "to" },
    "な": { "letter": "na" },
    "に": { "letter": "ni" },
    "ぬ": { "letter": "nu" },
    "ね": { "letter": "ne" },
    "の": { "letter": "no" },
    "は": { "letter": "ha" },
    "ひ": { "letter": "hi" },
    "ふ": { "letter": "fu" },
    "へ": { "letter": "he" },
    "ほ": { "letter": "ho" },
    "ま": { "letter": "ma" },
    "み": { "letter": "mi" },
    "む": { "letter": "mu" },
    "め": { "letter": "me" },
    "も": { "letter": "mo" },
    "や": { "letter": "ya" },
    " ": { "letter": " " },
    "ゆ": { "letter": "yu" },
    "  ": { "letter": " " },
    "よ": { "letter": "yo" },
    "ら": { "letter": "ra" },
    "り": { "letter": "ri" },
    "る": { "letter": "ru" },
    "れ": { "letter": "re" },
    "ろ": { "letter": "ro" },
    "わ": { "letter": "wa" },
    "   ": { "letter": " " },
    "   ": { "letter": " " },
    "     ": { "letter": " " },
    "      ": { "letter": " " },
    "を": { "letter": "wo" },
    "ん": { "letter": "n" }
}

const hiraganaDiacriticMap = {
    "が": { "letter": "ga" },
    "ぎ": { "letter": "gi" },
    "ぐ": { "letter": "gu" },
    "げ": { "letter": "ge" },
    "ご": { "letter": "go" },
    "ざ": { "letter": "za" },
    "じ": { "letter": "ji" },
    "ず": { "letter": "zu" },
    "ぜ": { "letter": "ze" },
    "ぞ": { "letter": "zo" },
    "だ": { "letter": "da" },
    "ぢ": { "letter": "ji" },
    "づ": { "letter": "zu" },
    "で": { "letter": "de" },
    "ど": { "letter": "do" },
    "ば": { "letter": "ba" },
    "び": { "letter": "bi" },
    "ぶ": { "letter": "bu" },
    "べ": { "letter": "be" },
    "ぼ": { "letter": "bo" },
    "ぱ": { "letter": "pa" },
    "ぴ": { "letter": "pi" },
    "ぷ": { "letter": "pu" },
    "ぺ": { "letter": "pe" },
    "ぽ": { "letter": "po" },
}

const hiraganaDiagraphMap = {
    "きゃ": { "letter": "kya" },
    "きゅ": { "letter": "kyu" },
    "きょ": { "letter": "kyo" },
    "しゃ": { "letter": "sha" },
    "しゅ": { "letter": "shu" },
    "しょ": { "letter": "sho" },
    "ちゃ": { "letter": "cha" },
    "ちゅ": { "letter": "chu" },
    "ちょ": { "letter": "cho" },
    "にゃ": { "letter": "nya" },
    "にゅ": { "letter": "nyu" },
    "にょ": { "letter": "nyo" },
    "ひゃ": { "letter": "hya" },
    "ひゅ": { "letter": "hyu" },
    "ひょ": { "letter": "hyo" },
    "みゃ": { "letter": "mya" },
    "みゅ": { "letter": "myu" },
    "みょ": { "letter": "myo" },
    "りゃ": { "letter": "rya" },
    "りゅ": { "letter": "ryu" },
    "りょ": { "letter": "ryo" },
    "ぎゃ": { "letter": "gya" },
    "ぎゅ": { "letter": "gyu" },
    "ぎょ": { "letter": "gyo" },
    "じゃ": { "letter": "ja" },
    "じゅ": { "letter": "ju" },
    "じょ": { "letter": "jo" },
    "びゃ": { "letter": "bya" },
    "びゅ": { "letter": "byu" },
    "びょ": { "letter": "byo" },
    "ぴゃ": { "letter": "pya" },
    "ぴゅ": { "letter": "pyu" },
    "ぴょ": { "letter": "pyo" },
}

const katakanaMonographMap = {
    "ア": { "letter": "a" },
    "イ": { "letter": "i" },
    "ウ": { "letter": "u" },
    "エ": { "letter": "e" },
    "オ": { "letter": "o" },
    "カ": { "letter": "ka" },
    "キ": { "letter": "ki" },
    "ク": { "letter": "ku" },
    "ケ": { "letter": "ke" },
    "コ": { "letter": "ko" },
    "サ": { "letter": "sa" },
    "シ": { "letter": "shi" },
    "ス": { "letter": "su" },
    "セ": { "letter": "se" },
    "ソ": { "letter": "so" },
    "タ": { "letter": "ta" },
    "チ": { "letter": "chi" },
    "ツ": { "letter": "tsu" },
    "テ": { "letter": "te" },
    "ト": { "letter": "to" },
    "ナ": { "letter": "na" },
    "ニ": { "letter": "ni" },
    "ヌ": { "letter": "nu" },
    "ネ": { "letter": "ne" },
    "ノ": { "letter": "no" },
    "ハ": { "letter": "ha" },
    "ヒ": { "letter": "hi" },
    "フ": { "letter": "fu" },
    "ヘ": { "letter": "he" },
    "ホ": { "letter": "ho" },
    "マ": { "letter": "ma" },
    "ミ": { "letter": "mi" },
    "ム": { "letter": "mu" },
    "メ": { "letter": "me" },
    "モ": { "letter": "mo" },
    "ヤ": { "letter": "ya" },
    " ": { "letter": " " },
    "ユ": { "letter": "yu" },
    "  ": { "letter": " " },
    "ヨ": { "letter": "yo" },
    "ラ": { "letter": "ra" },
    "リ": { "letter": "ri" },
    "ル": { "letter": "ru" },
    "レ": { "letter": "re" },
    "ロ": { "letter": "ro" },
    "ワ": { "letter": "wa" },
    "   ": { "letter": " " },
    "   ": { "letter": " " },
    "     ": { "letter": " " },
    "      ": { "letter": " " },
    "ヲ": { "letter": "wo" },
    "ン": { "letter": "n" },
}

const katakanaDiacriticMap = {
    "ガ": { "letter": "ga" },
    "ギ": { "letter": "gi" },
    "グ": { "letter": "gu" },
    "ゲ": { "letter": "ge" },
    "ゴ": { "letter": "go" },
    "ザ": { "letter": "za" },
    "ジ": { "letter": "ji" },
    "ズ": { "letter": "zu" },
    "ゼ": { "letter": "ze" },
    "ゾ": { "letter": "zo" },
    "ダ": { "letter": "da" },
    "ヂ": { "letter": "ji" },
    "ヅ": { "letter": "zu" },
    "デ": { "letter": "de" },
    "ド": { "letter": "do" },
    "バ": { "letter": "ba" },
    "ビ": { "letter": "bi" },
    "ブ": { "letter": "bu" },
    "ベ": { "letter": "be" },
    "ボ": { "letter": "bo" },
    "パ": { "letter": "pa" },
    "ピ": { "letter": "pi" },
    "プ": { "letter": "pu" },
    "ペ": { "letter": "pe" },
    "ポ": { "letter": "po" },
}

var katakanaDiagraphMap = {
    "キャ": { "letter": "kya" },
    "キュ": { "letter": "kyu" },
    "キョ": { "letter": "kyo" },
    "シャ": { "letter": "sha" },
    "シュ": { "letter": "shu" },
    "ショ": { "letter": "sho" },
    "チャ": { "letter": "cha" },
    "チュ": { "letter": "chu" },
    "チョ": { "letter": "cho" },
    "ニャ": { "letter": "nya" },
    "ニュ": { "letter": "nyu" },
    "ニョ": { "letter": "nyo" },
    "ヒャ": { "letter": "hya" },
    "ヒュ": { "letter": "hyu" },
    "ヒョ": { "letter": "hyo" },
    "ミャ": { "letter": "mya" },
    "ミュ": { "letter": "myu" },
    "ミョ": { "letter": "myo" },
    "リャ": { "letter": "rya" },
    "リュ": { "letter": "ryu" },
    "リョ": { "letter": "ryo" },
    "ギャ": { "letter": "gya" },
    "ギュ": { "letter": "gyu" },
    "ギョ": { "letter": "gyo" },
    "ジャ": { "letter": "ja" },
    "ジュ": { "letter": "ju" },
    "ジョ": { "letter": "jo" },
    "ビャ": { "letter": "bya" },
    "ビュ": { "letter": "byu" },
    "ビョ": { "letter": "byo" },
    "ピャ": { "letter": "pya" },
    "ピュ": { "letter": "pyu" },
    "ピョ": { "letter": "pyo" },
}

const japaneseKatakanaMap = Object.assign({}, katakanaMonographMap, katakanaDiacriticMap, katakanaDiagraphMap);
const japaneseHiraganaMap = Object.assign({}, hiraganaMonographMap, hiraganaDiacriticMap, hiraganaDiagraphMap);

const japaneseAllKanaChartData = [
    { "subtitle": "Hiragana Monograph", "content": Object.keys(hiraganaMonographMap), "column": "character-content-5-column" },
    { "subtitle": "Hiragana Diacritic", "content": Object.keys(hiraganaDiacriticMap), "column": "character-content-5-column" },
    { "subtitle": "Hiragana Diagraph", "content": Object.keys(hiraganaDiagraphMap), "column": "character-content-3-column" },
    { "subtitle": "Katakana Monograph", "content": Object.keys(katakanaMonographMap), "column": "character-content-5-column" },
    { "subtitle": "Katakana Diacritic", "content": Object.keys(katakanaDiacriticMap), "column": "character-content-5-column" },
    { "subtitle": "Katakana Diagraph", "content": Object.keys(katakanaDiagraphMap), "column": "character-content-3-column" },
]