obj = {	
"	1	":{"character":"	半田さん改造計画	","letter": "	Mr. Handa's Remodeling Project	", "pinyin":"	はんでんさんかいぞうけいかく	"},																			
"	2	":{"character":"	ねぇねぇモテ期って知ってる？	","letter": "	Hey, hey, do you know what the 'irresistible phase' is?	", "pinyin":"	ねぇねぇもてきってしってる？	"},																			
"	3	":{"character":"	モテ期？	","letter": "	Popularity Phase?	", "pinyin":"	もてき？	"},																			
"	4	":{"character":"	それは汽笛	","letter": "	That's a whistle.	", "pinyin":"	それはきてき	"},																			
"	5	":{"character":"	それは射的	","letter": "	That's target practice.	", "pinyin":"	それはしゃてき	"},																			
"	6	":{"character":"	それは奇跡	","letter": "	It's a miracle.	", "pinyin":"	それはきせき	"},																			
"	7	":{"character":"	モテ期って？	","letter": "	What's the 'irresistible phase'?	", "pinyin":"	もてきって？	"},																			
"	8	":{"character":"	人は一生のうちすごくモテる時期があって	","letter": "	There are times in a person's life when they are very popular.	", "pinyin":"	ひとはいっしょうのうちすごくもてるじきがあって	"},																			
"	9	":{"character":"	それをモテ期って言うんだって	","letter": "	It's called the 'irresistible phase.	", "pinyin":"	それをもてきっていうんだって	"},																			
"	10	":{"character":"	それ繁殖期でしょ	","letter": "	That's the breeding season.	", "pinyin":"	それはんしょくきでしょ	"},																			
"	11	":{"character":"	だよね	","letter": "	Right.	", "pinyin":"	だよね	"},																			
"	12	":{"character":"	ちょっと違うらしいよ	","letter": "	Not exactly.	", "pinyin":"	ちょっとちがうらしいよ	"},																			
"	13	":{"character":"	繁殖期は季節が巡ってこないと訪れないんだけど	","letter": "	The breeding season doesn't come until the season comes around.	", "pinyin":"	はんしょくきはきせつがめぐってこないとおとずれないんだけど	"},																			
"	14	":{"character":"	モテ期は努力によってくるらしいんだよ	","letter": "	But the season for being popular comes with effort.	", "pinyin":"	もてきはどりょくによってくるらしいんだよ	"},																			
"	15	":{"character":"	何のお話ですか？	","letter": "	What are you talking about?	", "pinyin":"	なにのおはなしですか？	"},																			
"	16	":{"character":"	見てて	","letter": "	Watch this.	", "pinyin":"	みてて	"},																			
"	17	":{"character":"	笹子さん	","letter": "	Sasago.	", "pinyin":"	ささごさん	"},																			
"	18	":{"character":"	はい？	","letter": "	Yes?	", "pinyin":"	はい？	"},																			
"	19	":{"character":"	はい！	","letter": "	Yes!	", "pinyin":"	はい！	"},																			
"	20	":{"character":"	お面？	","letter": "	A mask?	", "pinyin":"	おめん？	"},																			
"	21	":{"character":"	あれ？じゃあ…	","letter": "	Huh? Then...	", "pinyin":"	あれ？じゃあ…	"},																			
"	22	":{"character":"	はい	","letter": "	Yes.	", "pinyin":"	はい	"},																			
"	23	":{"character":"	ニンジン？	","letter": "	Carrot?	", "pinyin":"	にんじん？	"},																			
"	24	":{"character":"	あれ？じゃあ…	","letter": "	Huh? Then...	", "pinyin":"	あれ？じゃあ…	"},																			
"	25	":{"character":"	僕体重１００キロ以上あるんだ	","letter": "	I weigh over 100 kilos.	", "pinyin":"	ぼくたいじゅう１００きろいじょうあるんだ	"},																			
"	26	":{"character":"	そう	","letter": "	Yes, you weigh over 100 pounds.	", "pinyin":"	そう	"},																			
"	27	":{"character":"	重いでしょ？	","letter": "	Heavy, right?	", "pinyin":"	おもいでしょ？	"},																			
"	28	":{"character":"	重いね	","letter": "	Yes, you're heavy.	", "pinyin":"	おもいね	"},																			
"	29	":{"character":"	それだけ？	","letter": "	Is that all?	", "pinyin":"	それだけ？	"},																			
"	30	":{"character":"	うん	","letter": "	Yeah, that's it.	", "pinyin":"	うん	"},																			
"	31	":{"character":"	おかしいな…	","letter": "	It's funny...	", "pinyin":"	おかしいな…	"},																			
"	32	":{"character":"	モテるにはお面で野菜で重かったりするはずなんだけど…	","letter": "	To be popular, you have to be a vegetable with a mask and heavy...	", "pinyin":"	もてるにはおめんでやさいでおもかったりするはずなんだけど…	"},																			
"	33	":{"character":"	あの…	","letter": "	Well...	", "pinyin":"	あの…	"},																			
"	34	":{"character":"	イケメンで優しくておもしろかったりしたらじゃ…	","letter": "	If you're good-looking, kind, funny...	", "pinyin":"	いけめんでやさしくておもしろかったりしたらじゃ…	"},																			
"	35	":{"character":"	ちょっと違った	","letter": "	Not quite right.	", "pinyin":"	ちょっとちがった	"},																			
"	36	":{"character":"	ニアピン賞	","letter": "	Nearest-to-the-Pin Award.	", "pinyin":"	にあぴんしょう	"},																			
"	37	":{"character":"	いや大きく間違ってるから	","letter": "	No, you're very wrong.	", "pinyin":"	いやおおきくまちがってるから	"},																			
"	38	":{"character":"	あっ！配達ですか？	","letter": "	Oh! Delivery?	", "pinyin":"	あっ！はいたつですか？	"},																			
"	39	":{"character":"	ステキなお花ですね	","letter": "	Lovely flowers.	", "pinyin":"	すてきなおはなですね	"},																			
"	40	":{"character":"	ありがとうございます	","letter": "	Thank you.	", "pinyin":"	ありがとうございます	"},																			
"	41	":{"character":"	あれがモテ期かぁ	","letter": "	That's the popular season, huh?	", "pinyin":"	あれがもてきかぁ	"},																			
"	42	":{"character":"	じゃあこれ売店に届けてきますので	","letter": "	I'll deliver them to the store.	", "pinyin":"	じゃあこればいてんにとどけてきますので	"},																			
"	43	":{"character":"	行っちゃイヤ！	","letter": "	Don't go!	", "pinyin":"	いっちゃいや！	"},																			
"	44	":{"character":"	す…すみません	","letter": "	I'm sorry.	", "pinyin":"	す…すみません	"},																			
"	45	":{"character":"	ああいえこちらこそ	","letter": "	Oh, no, it's my pleasure.	", "pinyin":"	ああいえこちらこそ	"},																			
"	46	":{"character":"	大丈夫ですか？	","letter": "	Are you okay?	", "pinyin":"	だいじょうぶですか？	"},																			
"	47	":{"character":"	ケガはないかい？	","letter": "	Are you hurt?	", "pinyin":"	けがはないかい？	"},																			
"	48	":{"character":"	ああ僕は大丈夫です	","letter": "	Yeah, I'm fine.	", "pinyin":"	ああぼくはだいじょうぶです	"},																			
"	49	":{"character":"	本当に？	","letter": "	Are you sure?	", "pinyin":"	ほんとうに？	"},																			
"	50	":{"character":"	ええ	","letter": "	Yeah, I'm fine.	", "pinyin":"	ええ	"},																			
"	51	":{"character":"	よかった	","letter": "	Oh, thank God.	", "pinyin":"	よかった	"},																			
"	52	":{"character":"	心配しちゃったよ	","letter": "	I was so worried about you.	", "pinyin":"	しんぱいしちゃったよ	"},																			
"	53	":{"character":"	半田さん	","letter": "	Mr. Handa.	", "pinyin":"	はんでんさん	"},																			
"	54	":{"character":"	僕が力になるよ	","letter": "	Let me help you.	", "pinyin":"	ぼくがちからになるよ	"},																			
"	55	":{"character":"	なんとかしてあげるから	","letter": "	I'll take care of you.	", "pinyin":"	なんとかしてあげるから	"},																			
"	56	":{"character":"	ああパンダくんおはよう！	","letter": "	Good morning, panda!	", "pinyin":"	ああぱんだくんおはよう！	"},																			
"	57	":{"character":"	リンリンは僕のこと必要ないでしょ	","letter": "	I'm sure she doesn't need me.	", "pinyin":"	りんりんはぼくのことひつようないでしょ	"},																			
"	58	":{"character":"	さあ半田さん行こう	","letter": "	Come on, Mr. Handa, let's go.	", "pinyin":"	さあはんでんさんいこう	"},																			
"	59	":{"character":"	こんにちは！聞いて聞いて！	","letter": "	Hello! Listen, listen!	", "pinyin":"	こんにちは！きいてきいて！	"},																			
"	60	":{"character":"	どうしたんですか？	","letter": "	What's going on?	", "pinyin":"	どうしたんですか？	"},																			
"	61	":{"character":"	やっと仮免受かったよ	","letter": "	I finally got my provisional.	", "pinyin":"	やっとかりめんうかったよ	"},																			
"	62	":{"character":"	ついにだよとうとうだよ！	","letter": "	Finally, finally!	", "pinyin":"	ついにだよとうとうだよ！	"},																			
"	63	":{"character":"	あれ？シロクマくんはいないの？	","letter": "	What? Where's Polar Bear?	", "pinyin":"	あれ？しろくまくんはいないの？	"},																			
"	64	":{"character":"	大切な用事があるからって…	","letter": "	He said he had something important to do...	", "pinyin":"	たいせつなようじがあるからって…	"},																			
"	65	":{"character":"	ここでやるの？	","letter": "	You're doing it here?	", "pinyin":"	ここでやるの？	"},																			
"	66	":{"character":"	協力してねシロクマくん	","letter": "	Help us out, Polar Bear.	", "pinyin":"	きょうりょくしてねしろくまくん	"},																			
"	67	":{"character":"	パンダくんやる気だね	","letter": "	Panda, you're up for it.	", "pinyin":"	ぱんだくんやるきだね	"},																			
"	68	":{"character":"	いろいろ情報仕入れてきたよ	","letter": "	I've got a lot of information for you.	", "pinyin":"	いろいろじょうほうしいれてきたよ	"},																			
"	69	":{"character":"	ごめん！ちょっとお年寄りに道を聞かれてさ	","letter": "	Sorry! I got a little old lady asking for directions.	", "pinyin":"	ごめん！ちょっとおとしよりにみちをきかれてさ	"},																			
"	70	":{"character":"	さあ行くよ半田さん	","letter": "	Here we go, Mr. Handa.	", "pinyin":"	さあいくよはんでんさん	"},																			
"	71	":{"character":"	えっ？どこへ？	","letter": "	What? Where are you going?	", "pinyin":"	えっ？どこへ？	"},																			
"	72	":{"character":"	半田さん改造計画！	","letter": "	Mr. Handa's makeover plan!	", "pinyin":"	はんでんさんかいぞうけいかく！	"},																			
"	73	":{"character":"	まずはファッションだよ	","letter": "	First, let's start with fashion.	", "pinyin":"	まずはふぁっしょんだよ	"},																			
"	74	":{"character":"	さり気ないトラッド	","letter": "	Casual trad.	", "pinyin":"	さりげないとらっど	"},																			
"	75	":{"character":"	う～んちょっとカタイね	","letter": "	Well, it's a little too tight.	", "pinyin":"	う～んちょっとかたいね	"},																			
"	76	":{"character":"	パンクはどう？	","letter": "	How about punk?	", "pinyin":"	ぱんくはどう？	"},																			
"	77	":{"character":"	う～んこれもね…	","letter": "	Well, this too...	", "pinyin":"	う～んこれもね…	"},																			
"	78	":{"character":"	渋谷系とか	","letter": "	Shibuya style	", "pinyin":"	しぶやけいとか	"},																			
"	79	":{"character":"	というよりサブカル系？	","letter": "	Or more like subculture?	", "pinyin":"	というよりさぶかるけい？	"},																			
"	80	":{"character":"	あぁ～！これこれ	","letter": "	Ah~! This, this...	", "pinyin":"	あぁ～！これこれ	"},																			
"	81	":{"character":"	いいんじゃない？	","letter": "	It's good, isn't it?	", "pinyin":"	いいんじゃない？	"},																			
"	82	":{"character":"	これじゃいつもと同じだよ	","letter": "	It's the same as usual.	", "pinyin":"	これじゃいつもとおなじだよ	"},																			
"	83	":{"character":"	う～んじゃあ…	","letter": "	Well...	", "pinyin":"	う～んじゃあ…	"},																			
"	84	":{"character":"	モテファッションといえば	","letter": "	When it comes to fashion that appeals to the ladies...	", "pinyin":"	もてふぁっしょんといえば	"},																			
"	85	":{"character":"	オスとして強くアピールできるものがいいよね	","letter": "	Something that strongly appeals to the male sex.	", "pinyin":"	おすとしてつよくあぴーるできるものがいいよね	"},																			
"	86	":{"character":"	ニワトリなら立派なトサカだし	","letter": "	If it's a chicken, it should be a great crest.	", "pinyin":"	にわとりならりっぱなとさかだし	"},																			
"	87	":{"character":"	猫なら耳かな？	","letter": "	Ears for a cat?	", "pinyin":"	ねこならみみかな？	"},																			
"	88	":{"character":"	鳥なら羽でしょ	","letter": "	Or feathers for a bird?	", "pinyin":"	とりならはねでしょ	"},																			
"	89	":{"character":"	でもやっぱこれだよね	","letter": "	But I think this is it.	", "pinyin":"	でもやっぱこれだよね	"},																			
"	90	":{"character":"	パンダの着ぐるみ？	","letter": "	A stuffed panda?	", "pinyin":"	ぱんだのきぐるみ？	"},																			
"	91	":{"character":"	半田さん日ごろの僕を見ててわからない？	","letter": "	Handa, can't you tell by the way I look at myself?	", "pinyin":"	はんでんさんひごろのぼくをみててわからない？	"},																			
"	92	":{"character":"	モテモテだよ	","letter": "	I'm irresistible.	", "pinyin":"	もてもてだよ	"},																			
"	93	":{"character":"	これなんかどう？	","letter": "	How about this?	", "pinyin":"	これなんかどう？	"},																			
"	94	":{"character":"	ちょっときついけど	","letter": "	It's a little tight.	", "pinyin":"	ちょっときついけど	"},																			
"	95	":{"character":"	シロクマくんパンダみたいだね	","letter": "	Polar bear, you look like a panda.	", "pinyin":"	しろくまくんぱんだみたいだね	"},																			
"	96	":{"character":"	パンダくんの代わりに動物園で働こうかな	","letter": "	Maybe I'll work at the zoo instead of being a panda.	", "pinyin":"	ぱんだくんのかわりにどうぶつえんではたらこうかな	"},																			
"	97	":{"character":"	ムリでしょ	","letter": "	You can't do that.	", "pinyin":"	むりでしょ	"},																			
"	98	":{"character":"	袋開けたんだからちゃんと買いなよ	","letter": "	You've opened the bag, so you'd better buy something.	", "pinyin":"	ふくろあけたんだからちゃんとかいなよ	"},																			
"	99	":{"character":"	お財布持ってきてない	","letter": "	I didn't bring my wallet.	", "pinyin":"	おさいふもってきてない	"},																			
"	100	":{"character":"	ありがとうございました	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございました	"},																			
"	101	":{"character":"	じゃあ次	","letter": "	Next time.	", "pinyin":"	じゃあつぎ	"},																			
"	102	":{"character":"	グルメ情報も大事らしいよ	","letter": "	I hear it's important to know where the food is.	", "pinyin":"	ぐるめじょうほうもおおごとらしいよ	"},																			
"	103	":{"character":"	どう大事なの？	","letter": "	How is it important?	", "pinyin":"	どうだいじなの？	"},																			
"	104	":{"character":"	半田さんの人生にだよ	","letter": "	It's important to Mr. Handa's life.	", "pinyin":"	はんでんさんのじんせいにだよ	"},																			
"	105	":{"character":"	そうなんだ…	","letter": "	I see...	", "pinyin":"	そうなんだ…	"},																			
"	106	":{"character":"	もう！何？そのやる気のなさ	","letter": "	Oh, my God! What? That lack of motivation.	", "pinyin":"	もう！なに？そのやるきのなさ	"},																			
"	107	":{"character":"	僕がこんなに一生懸命なのに	","letter": "	I'm working so hard.	", "pinyin":"	ぼくがこんなにいっしょうけんめいなのに	"},																			
"	108	":{"character":"	おいしそうなものいっぱいあるね	","letter": "	There's so much delicious food here.	", "pinyin":"	おいしそうなものいっぱいあるね	"},																			
"	109	":{"character":"	あぁ～！笹まんじゅう笹だんご笹ようかん	","letter": "	Ah~! Sasa manju, sasa dango, sasa yokan...	", "pinyin":"	あぁ～！ささまんじゅうささだんごささようかん	"},																			
"	110	":{"character":"	買ってあげなよ	","letter": "	Buy him one.	", "pinyin":"	かってあげなよ	"},																			
"	111	":{"character":"	しようがないな…１個だけね	","letter": "	I can't help it... just one.	", "pinyin":"	しようがないな…１こだけね	"},																			
"	112	":{"character":"	これもよろしく	","letter": "	Here's one for you too.	", "pinyin":"	これもよろしく	"},																			
"	113	":{"character":"	半田さん！	","letter": "	Mr. Handa!	", "pinyin":"	はんでんさん！	"},																			
"	114	":{"character":"	半田さん！	","letter": "	Mr. Handa!	", "pinyin":"	はんでんさん！	"},																			
"	115	":{"character":"	１００円１００円	","letter": "	One hundred yen, one hundred yen.	", "pinyin":"	１００えん１００えん	"},																			
"	116	":{"character":"	シロクマくん何やってるの！？	","letter": "	Polar bear, what are you doing?	", "pinyin":"	しろくまくんなにやってるの！？	"},																			
"	117	":{"character":"	半田さんいっぱい持ってるねモテモテだよ	","letter": "	Mr. Handa, you have so many things, you're irresistible.	", "pinyin":"	はんでんさんいっぱいもってるねもてもてだよ	"},																			
"	118	":{"character":"	これで半田さんもだいぶ改造人間になったね	","letter": "	Now you've become a much better person, haven't you, Mr. Handa?	", "pinyin":"	これではんでんさんもだいぶかいぞうにんげんになったね	"},																			
"	119	":{"character":"	いや…それ戦っちゃうから	","letter": "	No... that's fighting.	", "pinyin":"	いや…それたたかっちゃうから	"},																			
"	120	":{"character":"	どうする？	","letter": "	What should we do?	", "pinyin":"	どうする？	"},																			
"	121	":{"character":"	行こう！	","letter": "	Let's go!	", "pinyin":"	いこう！	"},																			
"	122	":{"character":"	なんだろう？こっち見てるよ	","letter": "	What's that? He's looking at me.	", "pinyin":"	なんだろう？こっちみてるよ	"},																			
"	123	":{"character":"	あの…	","letter": "	Uh...	", "pinyin":"	あの…	"},																			
"	124	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},																			
"	125	":{"character":"	もしよかったら…	","letter": "	If you don't mind...	", "pinyin":"	もしよかったら…	"},																			
"	126	":{"character":"	一緒に写真撮ってもらえますか？	","letter": "	Can you take a picture with me?	", "pinyin":"	いっしょにしゃしんとってもらえますか？	"},																			
"	127	":{"character":"	きたよモテ期！	","letter": "	It's time to be popular!	", "pinyin":"	きたよもてき！	"},																			
"	128	":{"character":"	いいですよ	","letter": "	Sure.	", "pinyin":"	いいですよ	"},																			
"	129	":{"character":"	お願いします！	","letter": "	Please!	", "pinyin":"	おねがいします！	"},																			
"	130	":{"character":"	パンダくん人気者だね	","letter": "	Panda, you're so popular.	", "pinyin":"	ぱんだくんにんきものだね	"},																			
"	131	":{"character":"	僕も一緒に撮ってくる	","letter": "	I'll take one with you.	", "pinyin":"	ぼくもいっしょにとってくる	"},																			
"	132	":{"character":"	もう１枚撮りますよ	","letter": "	I'll take another one.	", "pinyin":"	もう１まいとりますよ	"},																			
"	133	":{"character":"	は～い！	","letter": "	Yes!	", "pinyin":"	は～い！	"},																			
"	134	":{"character":"	あぁ楽しかった！	","letter": "	That was fun!	", "pinyin":"	あぁたのしかった！	"},																			
"	135	":{"character":"	おかえり遅かったね	","letter": "	You're back late.	", "pinyin":"	おかえりおそかったね	"},																			
"	136	":{"character":"	すみません！注文お願いします	","letter": "	Sorry! Order, please.	", "pinyin":"	すみません！ちゅうもんおねがいします	"},																			
"	137	":{"character":"	はいお待たせしました	","letter": "	Here you go.	", "pinyin":"	はいおまたせしました	"},																			
"	138	":{"character":"	お水のお代わりください	","letter": "	More water, please.	", "pinyin":"	おみずのおかわりください	"},																			
"	139	":{"character":"	ただ今！	","letter": "	I'm back!	", "pinyin":"	ただいま！	"},																			
"	140	":{"character":"	忙しそうだな	","letter": "	You look busy.	", "pinyin":"	いそがしそうだな	"},																			
"	141	":{"character":"	笹子さんモテモテだね	","letter": "	Sasago, you're irresistible.	", "pinyin":"	ささごさんもてもてだね	"},																			
"	142	":{"character":"	あっ！半田さんじゃないですか	","letter": "	Ah! It's Mr. Handa, isn't it?	", "pinyin":"	あっ！はんでんさんじゃないですか	"},																			
"	143	":{"character":"	すみませんお水お代わりお願いします	","letter": "	Can I have another glass of water, please?	", "pinyin":"	すみませんおみずおかわりおねがいします	"},																			
"	144	":{"character":"	あぁ半田さん！背中かいてもらえますか？	","letter": "	Mr. Handa! Can you scratch my back?	", "pinyin":"	あぁはんでんさん！せなかかいてもらえますか？	"},																			
"	145	":{"character":"	半田さ～ん…	","letter": "	Mr. Handa...	", "pinyin":"	はんでんさ～ん…	"},																			
"	146	":{"character":"	ここに座らないように言って	","letter": "	Tell him not to sit here.	", "pinyin":"	ここにすわらないようにいって	"},																			
"	147	":{"character":"	はいはい	","letter": "	Okay.	", "pinyin":"	はいはい	"},																			
"	148	":{"character":"	うんありがとうございます	","letter": "	Thank you very much.	", "pinyin":"	うんありがとうございます	"},																			
"	149	":{"character":"	いえいえ	","letter": "	No problem.	", "pinyin":"	いえいえ	"},																			
"	150	":{"character":"	このへん？	","letter": "	Around here?	", "pinyin":"	このへん？	"},																			
"	151	":{"character":"	も…もうちょい右です	","letter": "	A little more to the right.	", "pinyin":"	も…もうちょいみぎです	"},																			
"	152	":{"character":"	ここに座ってね	","letter": "	Here, have a seat.	", "pinyin":"	ここにすわってね	"},																			
"	153	":{"character":"	ありがとう	","letter": "	Thank you.	", "pinyin":"	ありがとう	"},																			
"	154	":{"character":"	半田さんにもやっと…	","letter": "	Mr. Handa finally got his...	", "pinyin":"	はんでんさんにもやっと…	"},																			
"	155	":{"character":"	きたね	","letter": "	Finally.	", "pinyin":"	きたね	"},																			
"	156	":{"character":"	モテ期	","letter": "	He's getting popular.	", "pinyin":"	もてき	"},																			
"	157	":{"character":"	半田さんお水もう１杯もらえますか？	","letter": "	Mr. Handa, can I have another glass of water?	", "pinyin":"	はんでんさんおみずもう１ぱいもらえますか？	"},																			
"	158	":{"character":"	はいはい	","letter": "	Yes, yes.	", "pinyin":"	はいはい	"},																			
"	159	":{"character":"	半田さんこっちもかいて	","letter": "	Mr. Handa, write here, too.	", "pinyin":"	はんでんさんこっちもかいて	"},																			
"	160	":{"character":"	かくよ！	","letter": "	I'll draw!	", "pinyin":"	かくよ！	"},																			
"	161	":{"character":"	半田さ～ん！	","letter": "	Mr. Handa!	", "pinyin":"	はんでんさ～ん！	"},																			
"	162	":{"character":"	なんだい？	","letter": "	What is it?	", "pinyin":"	なんだい？	"},																			
"	163	":{"character":"	ラブラブドライブ大作戦	","letter": "	Operation Love Drive!	", "pinyin":"	らぶらぶどらいぶだいさくせん	"},																			
"	164	":{"character":"	見て見て！	","letter": "	Look, look, look!	", "pinyin":"	みてみて！	"},																			
"	165	":{"character":"	ついに取ったよ！	","letter": "	I finally got it!	", "pinyin":"	ついにとったよ！	"},																			
"	166	":{"character":"	免許！	","letter": "	My license!	", "pinyin":"	めんきょ！	"},																			
"	167	":{"character":"	よかったね	","letter": "	That's great.	", "pinyin":"	よかったね	"},																			
"	168	":{"character":"	ちょっと！おめでとうって言ってよ！	","letter": "	Oh, my God! Say congratulations!	", "pinyin":"	ちょっと！おめでとうっていってよ！	"},																			
"	169	":{"character":"	それはこんぺいとう！	","letter": "	It's a kelpcake!	", "pinyin":"	それはこんぺいとう！	"},																			
"	170	":{"character":"	それはエッフェル塔！	","letter": "	It's the Eiffel Tower!	", "pinyin":"	それはえっふぇるとう！	"},																			
"	171	":{"character":"	それは合気道！	","letter": "	It's aikido!	", "pinyin":"	それはあいきどう！	"},																			
"	172	":{"character":"	違う！全然違うよ	","letter": "	That's not aikido! Not even close.	", "pinyin":"	ちがう！ぜんぜんちがうよ	"},																			
"	173	":{"character":"	おめでとうございます	","letter": "	Congratulations!	", "pinyin":"	おめでとうございます	"},																			
"	174	":{"character":"	うん！ありがとう	","letter": "	Yeah! Thank you.	", "pinyin":"	うん！ありがとう	"},																			
"	175	":{"character":"	おめでとう	","letter": "	Congratulations.	", "pinyin":"	おめでとう	"},																			
"	176	":{"character":"	うん！	","letter": "	Yeah! - Yeah!	", "pinyin":"	うん！	"},																			
"	177	":{"character":"	永遠に取れないかと思ったよ	","letter": "	I thought I'd never get it.	", "pinyin":"	えいえんにとれないかとおもったよ	"},																			
"	178	":{"character":"	縁起でもないこと言わないでくれる？	","letter": "	Don't give me that kind of bad luck, okay?	", "pinyin":"	えんぎでもないこといわないでくれる？	"},																			
"	179	":{"character":"	さぁこれでペン子さんと…	","letter": "	Now you and Penko...	", "pinyin":"	さぁこれでぺんごさんと…	"},																			
"	180	":{"character":"	海へドライブだよ！	","letter": "	We're going for a drive to the beach!	", "pinyin":"	うみへどらいぶだよ！	"},																			
"	181	":{"character":"	いきなりはどうかな？	","letter": "	I don't think we should do this out of the blue.	", "pinyin":"	いきなりはどうかな？	"},																			
"	182	":{"character":"	なんで？	","letter": "	Why not?	", "pinyin":"	なんで？	"},																			
"	183	":{"character":"	たとえば…	","letter": "	For example...	", "pinyin":"	たとえば…	"},																			
"	184	":{"character":"	道を間違えて海へ行くはずが山へ行っちゃったり…	","letter": "	We take a wrong turn and end up in the mountains instead of the ocean...	", "pinyin":"	みちをまちがえてうみへいくはずがやまへいっちゃったり…	"},																			
"	185	":{"character":"	ギア壊しちゃったり…	","letter": "	You break a gear...	", "pinyin":"	ぎあこわしちゃったり…	"},																			
"	186	":{"character":"	ハンドル引っこ抜いたり…	","letter": "	Pulling the handlebars off...	", "pinyin":"	はんどるひっこぬいたり…	"},																			
"	187	":{"character":"	いやそんな失敗しないから	","letter": "	No, I don't make mistakes like that.	", "pinyin":"	いやそんなしっぱいしないから	"},																			
"	188	":{"character":"	でもただのドライブじゃないよね？	","letter": "	But it's not just a drive, right?	", "pinyin":"	でもただのどらいぶじゃないよね？	"},																			
"	189	":{"character":"	デートだよデート	","letter": "	It's a date.	", "pinyin":"	でーとだよでーと	"},																			
"	190	":{"character":"	ペン子さんを助手席に乗せて	","letter": "	Put Penko in the passenger seat.	", "pinyin":"	ぺんごさんをじょしゅせきにのせて	"},																			
"	191	":{"character":"	洒落た会話をこなしつつ	","letter": "	Can you escort her without making a wrong turn?	", "pinyin":"	しゃれたかいわをこなしつつ	"},																			
"	192	":{"character":"	しかも道を間違えずにうまくエスコートできるかな？	","letter": "	And can you escort her without making a wrong turn?	", "pinyin":"	しかもみちをまちがえずにうまくえすこーとできるかな？	"},																			
"	193	":{"character":"	すごいミッションだね	","letter": "	That's quite a mission, isn't it?	", "pinyin":"	すごいみっしょんだね	"},																			
"	194	":{"character":"	わかった！明日予行演習しよう	","letter": "	I'll do a practice run tomorrow. Let's practice tomorrow.	", "pinyin":"	わかった！あしたよこうえんしゅうしよう	"},																			
"	195	":{"character":"	デートの練習って何するの？	","letter": "	What do you do to practice for a date?	", "pinyin":"	でーとのれんしゅうってなにするの？	"},																			
"	196	":{"character":"	それはいろいろ考えてあるから	","letter": "	I've got lots of ideas for that.	", "pinyin":"	それはいろいろかんがえてあるから	"},																			
"	197	":{"character":"	ペンギンさんおはよう	","letter": "	Good morning, Penguin.	", "pinyin":"	ぺんぎんさんおはよう	"},																			
"	198	":{"character":"	あれ？	","letter": "	Oh, hey...	", "pinyin":"	あれ？	"},																			
"	199	":{"character":"	ペン子さん…	","letter": "	Mr. Penguin...	", "pinyin":"	ぺんごさん…	"},																			
"	200	":{"character":"	ペンギンさん！	","letter": "	Penguin!	", "pinyin":"	ぺんぎんさん！	"},																			
"	201	":{"character":"	なんでこんなとこで寝てるの？	","letter": "	Why are you sleeping here?	", "pinyin":"	なんでこんなとこでねてるの？	"},																			
"	202	":{"character":"	いや…	","letter": "	Well...	", "pinyin":"	いや…	"},																			
"	203	":{"character":"	３時間前に来ちゃって…	","letter": "	I came here 3 hours ago...	", "pinyin":"	３じかんまえにきちゃって…	"},																			
"	204	":{"character":"	早いのはいいけど寝るのは最悪だね	","letter": "	I like being early, but sleeping in is the worst.	", "pinyin":"	はやいのはいいけどねるのはさいあくだね	"},																			
"	205	":{"character":"	その１待ち合わせ不合格	","letter": "	No. 1, meeting rejection.	", "pinyin":"	その１まちあわせふごうかく	"},																			
"	206	":{"character":"	何それ？	","letter": "	What's that?	", "pinyin":"	なにそれ？	"},																			
"	207	":{"character":"	採点表だよ	","letter": "	It's a grading scale.	", "pinyin":"	さいてんひょうだよ	"},																			
"	208	":{"character":"	合格しないとデートする免許がもらえないの	","letter": "	If you don't pass, you don't get a license to date.	", "pinyin":"	ごうかくしないとでーとするめんきょがもらえないの	"},																			
"	209	":{"character":"	デートにも免許がいるんだ？	","letter": "	You need a license to date?	", "pinyin":"	でーとにもめんきょがいるんだ？	"},																			
"	210	":{"character":"	いるの	","letter": "	Yes.	", "pinyin":"	いるの	"},																			
"	211	":{"character":"	いや普通いらないから	","letter": "	No, I don't usually need one.	", "pinyin":"	いやふつういらないから	"},																			
"	212	":{"character":"	ペンギンさん今日は僕がデートの教官	","letter": "	Penguin, I'm your date teacher today.	", "pinyin":"	ぺんぎんさんきょうはぼくがでーとのきょうかん	"},																			
"	213	":{"character":"	わ…わかってるよ	","letter": "	I know, I know.	", "pinyin":"	わ…わかってるよ	"},																			
"	214	":{"character":"	で…今日の計画は？	","letter": "	So... what's the plan for today?	", "pinyin":"	で…きょうのけいかくは？	"},																			
"	215	":{"character":"	海に行きます！	","letter": "	We're going to the beach!	", "pinyin":"	うみにいきます！	"},																			
"	216	":{"character":"	それだけ？	","letter": "	That's it?	", "pinyin":"	それだけ？	"},																			
"	217	":{"character":"	オシャレなレストランで食事したり	","letter": "	We're going to eat at a fancy restaurant.	", "pinyin":"	おしゃれなれすとらんでしょくじしたり	"},																			
"	218	":{"character":"	ムード盛り上げる演出はないの？	","letter": "	No mood enhancer?	", "pinyin":"	むーどもりあげるえんしゅつはないの？	"},																			
"	219	":{"character":"	考えてなかったでしょ？	","letter": "	You didn't think of that, did you?	", "pinyin":"	かんがえてなかったでしょ？	"},																			
"	220	":{"character":"	その２段取り不合格	","letter": "	You failed the second step.	", "pinyin":"	その２だんどりふごうかく	"},																			
"	221	":{"character":"	合格までの道のりは厳しそうだね	","letter": "	The road to success is tough, isn't it?	", "pinyin":"	ごうかくまでのみちのりはきびしそうだね	"},																			
"	222	":{"character":"	あとはどんなチェック項目があるの？	","letter": "	What else is there to check?	", "pinyin":"	あとはどんなちぇっくこうもくがあるの？	"},																			
"	223	":{"character":"	３楽しい会話。	","letter": "	3Fun conversation.	", "pinyin":"	３たのしいかいわ。	"},																			
"	224	":{"character":"	４おいしい食事	","letter": "	4Good food.	", "pinyin":"	４おいしいしょくじ	"},																			
"	225	":{"character":"	５ロマンチックなムード	","letter": "	5Romantic mood.	", "pinyin":"	５ろまんちっくなむーど	"},																			
"	226	":{"character":"	全部合格すれば仮免	","letter": "	If you pass all of them, you get your provisional license.	", "pinyin":"	ぜんぶごうかくすればかりめん	"},																			
"	227	":{"character":"	でラブラブでドライブした最後に愛の告白	","letter": "	And at the end of the drive, confess your love.	", "pinyin":"	でらぶらぶでどらいぶしたさいごにあいのこくはく	"},																			
"	228	":{"character":"	そうすればラブラブ免許を獲得できるよ	","letter": "	Then you'll get your love license!	", "pinyin":"	そうすればらぶらぶめんきょをかくとくできるよ	"},																			
"	229	":{"character":"	えっラブラブ免許？	","letter": "	Love license?	", "pinyin":"	えっらぶらぶめんきょ？	"},																			
"	230	":{"character":"	すでに２つ不合格だね	","letter": "	You've already failed two.	", "pinyin":"	すでに２つふごうかくだね	"},																			
"	231	":{"character":"	え～っ！	","letter": "	What? !	", "pinyin":"	え～っ！	"},																			
"	232	":{"character":"	じゃあやり直してみよう	","letter": "	Let's try again.	", "pinyin":"	じゃあやりなおしてみよう	"},																			
"	233	":{"character":"	はい	","letter": "	Okay.	", "pinyin":"	はい	"},																			
"	234	":{"character":"	おはよう待った？	","letter": "	Good morning.	", "pinyin":"	おはようまった？	"},																			
"	235	":{"character":"	おはよう	","letter": "	Good morning.	", "pinyin":"	おはよう	"},																			
"	236	":{"character":"	僕も今来たところだよ	","letter": "	I just got here.	", "pinyin":"	ぼくもいまきたところだよ	"},																			
"	237	":{"character":"	いいね合格	","letter": "	Great. You're in.	", "pinyin":"	いいねごうかく	"},																			
"	238	":{"character":"	デートの計画は？	","letter": "	So, what's the plan for our date?	", "pinyin":"	でーとのけいかくは？	"},																			
"	239	":{"character":"	おいしいレストランに行って海に行って	","letter": "	We're going to a nice restaurant, then we're going to the beach.	", "pinyin":"	おいしいれすとらんにいってうみにいって	"},																			
"	240	":{"character":"	ムードを盛り上げて告白します教官	","letter": "	I'm gonna set the mood, and then I'm gonna tell you my feelings, counselor.	", "pinyin":"	むーどをもりあげてこくはくしますきょうかん	"},																			
"	241	":{"character":"	ザックリしてるけどまぁ合格	","letter": "	That's a little rough, but it'll do.	", "pinyin":"	ざっくりしてるけどまぁごうかく	"},																			
"	242	":{"character":"	じゃあいこうか	","letter": "	Let's go.	", "pinyin":"	じゃあいこうか	"},																			
"	243	":{"character":"	ハァーなんか疲れた	","letter": "	I'm so tired.	", "pinyin":"	はぁーなんかつかれた	"},																			
"	244	":{"character":"	シロクマくん運転して	","letter": "	Polar bear, you're driving.	", "pinyin":"	しろくまくんうんてんして	"},																			
"	245	":{"character":"	ダメでしょそれ	","letter": "	You can't do that!	", "pinyin":"	だめでしょそれ	"},																			
"	246	":{"character":"	あおやつ忘れた	","letter": "	I forgot my snack.	", "pinyin":"	あおやつわすれた	"},																			
"	247	":{"character":"	ペンギンさん持ってない？	","letter": "	Do you have any penguins?	", "pinyin":"	ぺんぎんさんもってない？	"},																			
"	248	":{"character":"	気が散るから話かけないで	","letter": "	Don't talk to me, I'm distracting you.	", "pinyin":"	きがちるからはなしかけないで	"},																			
"	249	":{"character":"	そういえばさぁこの間ね…	","letter": "	You know, the other day...	", "pinyin":"	そういえばさぁこのあいだね…	"},																			
"	250	":{"character":"	だから話かけないで	","letter": "	So don't talk to me.	", "pinyin":"	だからはなしかけないで	"},																			
"	251	":{"character":"	３楽しい会話不合格	","letter": "	3Failure to have a pleasant conversation	", "pinyin":"	３たのしいかいわふごうかく	"},																			
"	252	":{"character":"	もっと盛り上げないと	","letter": "	You've got to make it more fun.	", "pinyin":"	もっともりあげないと	"},																			
"	253	":{"character":"	だって男３人でドライブじゃ盛り上がらないよ	","letter": "	Three guys on a road trip isn't much fun.	", "pinyin":"	だっておとこ３にんでどらいぶじゃもりあがらないよ	"},																			
"	254	":{"character":"	予行演習したいって言ったのペンギンさんでしょ	","letter": "	You're the one who said you wanted to rehearse, right, Penguin?	", "pinyin":"	よこうえんしゅうしたいっていったのぺんぎんさんでしょ	"},																			
"	255	":{"character":"	そうだけどさ	","letter": "	Yeah, I know, but...	", "pinyin":"	そうだけどさ	"},																			
"	256	":{"character":"	仕方ないな	","letter": "	I don't blame you.	", "pinyin":"	しかたないな	"},																			
"	257	":{"character":"	うわ～ステキな景色ね	","letter": "	Wow, that's a beautiful view.	", "pinyin":"	うわ～すてきなけしきね	"},																			
"	258	":{"character":"	何やってるの？	","letter": "	What are you doing?	", "pinyin":"	なにやってるの？	"},																			
"	259	":{"character":"	僕がペン子さんのふりしてあげるから	","letter": "	I'm going to pretend I'm Penko-san.	", "pinyin":"	ぼくがぺんごさんのふりしてあげるから	"},																			
"	260	":{"character":"	えっシロクマくん今から女の子なんだ	","letter": "	Oh, Polar Bear, you're a girl now?	", "pinyin":"	えっしろくまくんいまからおんなのこなんだ	"},																			
"	261	":{"character":"	私日焼け止め持ってくるの忘れちゃった	","letter": "	I forgot to bring sunscreen.	", "pinyin":"	わたしひやけどめもってくるのわすれちゃった	"},																			
"	262	":{"character":"	へぇ～	","letter": "	Oh, really?	", "pinyin":"	へぇ～	"},																			
"	263	":{"character":"	ちょっとそれじゃダメ	","letter": "	That's not good enough!	", "pinyin":"	ちょっとそれじゃだめ	"},																			
"	264	":{"character":"	えっ何言えばいいの？	","letter": "	What do you want me to say?	", "pinyin":"	えっなにいえばいいの？	"},																			
"	265	":{"character":"	とにかく褒めて私を褒めて	","letter": "	Just compliment me.	", "pinyin":"	とにかくほめてわたしをほめて	"},																			
"	266	":{"character":"	ううん	","letter": "	No, I don't.	", "pinyin":"	ううん	"},																			
"	267	":{"character":"	シシロクマちゃんて色白できれいだね	","letter": "	Polar bears are so white and beautiful.	", "pinyin":"	ししろくまちゃんていろじろできれいだね	"},																			
"	268	":{"character":"	やだペンギンさんたら	","letter": "	Oh, no, Penguin!	", "pinyin":"	やだぺんぎんさんたら	"},																			
"	269	":{"character":"	うわ～っ！	","letter": "	Oh, my God!	", "pinyin":"	うわ～っ！	"},																			
"	270	":{"character":"	あらごめんなさい	","letter": "	Oh, I'm sorry.	", "pinyin":"	あらごめんなさい	"},																			
"	271	":{"character":"	私最近太っちゃって	","letter": "	I've gained a lot of weight recently.	", "pinyin":"	わたしさいきんふとっちゃって	"},																			
"	272	":{"character":"	へぇ～	","letter": "	Oh, really?	", "pinyin":"	へぇ～	"},																			
"	273	":{"character":"	へぇ～？	","letter": "	Really?	", "pinyin":"	へぇ～？	"},																			
"	274	":{"character":"	シシロクマちゃんみたいにポッチャリしてる女の子のほうがかわいいよ	","letter": "	Girls who are chubby like polar bears are cuter.	", "pinyin":"	ししろくまちゃんみたいにぽっちゃりしてるおんなのこのほうがかわいいよ	"},																			
"	275	":{"character":"	ホント？	","letter": "	Really?	", "pinyin":"	ほんと？	"},																			
"	276	":{"character":"	うわ～っシロクマちゃん爪爪！	","letter": "	Polar bear claws!	", "pinyin":"	うわ～っしろくまちゃんつめつめ！	"},																			
"	277	":{"character":"	あらごめんなさい	","letter": "	Oh, I'm sorry.	", "pinyin":"	あらごめんなさい	"},																			
"	278	":{"character":"	爪痛かったかしら	","letter": "	Did I hurt your nails?	", "pinyin":"	つめいたかったかしら	"},																			
"	279	":{"character":"	痛いよ！	","letter": "	They hurt!	", "pinyin":"	いたいよ！	"},																			
"	280	":{"character":"	シロクマちゃんの爪頑丈でステキ	","letter": "	Polar bear claws are sturdy and beautiful.	", "pinyin":"	しろくまちゃんのつめがんじょうですてき	"},																			
"	281	":{"character":"	ホント？	","letter": "	Really?	", "pinyin":"	ほんと？	"},																			
"	282	":{"character":"	ホントホント	","letter": "	Really, really, really.	", "pinyin":"	ほんとほんと	"},																			
"	283	":{"character":"	３楽しい会話合格	","letter": "	Three happy conversations passed.	", "pinyin":"	３たのしいかいわごうかく	"},																			
"	284	":{"character":"	よかったねペンギンさん	","letter": "	Good for you, Penguin!	", "pinyin":"	よかったねぺんぎんさん	"},																			
"	285	":{"character":"	お昼はどうする？	","letter": "	What are you going to do for lunch?	", "pinyin":"	おひるはどうする？	"},																			
"	286	":{"character":"	笹食べたい！	","letter": "	I want some bamboo grass!	", "pinyin":"	ささたべたい！	"},																			
"	287	":{"character":"	ん～ペン子さんが喜びそうなところ…	","letter": "	I'm sure Penko will be happy to have some...	", "pinyin":"	ん～ぺんごさんがよろこびそうなところ…	"},																			
"	288	":{"character":"	笹がない	","letter": "	There's no bamboo grass!	", "pinyin":"	ささがない	"},																			
"	289	":{"character":"	全然レストランじゃないわね	","letter": "	This isn't a restaurant at all!	", "pinyin":"	ぜんぜんれすとらんじゃないわね	"},																			
"	290	":{"character":"	本番ではステキなシーフードレストランに行くから	","letter": "	We'll go to a nice seafood restaurant for the show.	", "pinyin":"	ほんばんではすてきなしーふーどれすとらんにいくから	"},																			
"	291	":{"character":"	すみませんサーモンください	","letter": "	Excuse me, can I have some salmon, please?	", "pinyin":"	すみませんさーもんください	"},																			
"	292	":{"character":"	売り切れです	","letter": "	We're out of salmon.	", "pinyin":"	うりきれです	"},																			
"	293	":{"character":"	シロクマくんが食べきっちゃったよここのサーモン	","letter": "	Polar bear ate up all the salmon.	", "pinyin":"	しろくまくんがたべきっちゃったよここのさーもん	"},																			
"	294	":{"character":"	じゃあいきましょうか	","letter": "	Shall we go then?	", "pinyin":"	じゃあいきましょうか	"},																			
"	295	":{"character":"	もちろんペンギンさんのおごりね	","letter": "	Of course, it's Penguin's treat.	", "pinyin":"	もちろんぺんぎんさんのおごりね	"},																			
"	296	":{"character":"	えっ？	","letter": "	What?	", "pinyin":"	えっ？	"},																			
"	297	":{"character":"	やだデートで女の子にお金払わせるつもり？	","letter": "	You're going to make a girl pay for your date?	", "pinyin":"	やだでーとでおんなのこにおかねはらわせるつもり？	"},																			
"	298	":{"character":"	信じらんな～い	","letter": "	Unbelievable!	", "pinyin":"	しんじらんな～い	"},																			
"	299	":{"character":"	わかったよ…	","letter": "	Okay, okay...	", "pinyin":"	わかったよ…	"},																			
"	300	":{"character":"	４おいしい食事も合格だね	","letter": "	4...a good meal passes the test, too!	", "pinyin":"	４おいしいしょくじもごうかくだね	"},																			
"	301	":{"character":"	う～ん…デートで回転寿司ってどうなのかしら…	","letter": "	I wonder what a conveyor belt sushi on a date would be like...	", "pinyin":"	う～ん…でーとでかいてんずしってどうなのかしら…	"},																			
"	302	":{"character":"	あれだけ食べといて！？	","letter": "	After all that food?	", "pinyin":"	あれだけたべといて！？	"},																			
"	303	":{"character":"	じゃ合格でいいよ合格で…	","letter": "	Well then, you get a pass...	", "pinyin":"	じゃごうかくでいいよごうかくで…	"},																			
"	304	":{"character":"	会話…ないんだけど	","letter": "	I don't have a conversation...	", "pinyin":"	かいわ…ないんだけど	"},																			
"	305	":{"character":"	そこはもう合格したから	","letter": "	I've already passed that part.	", "pinyin":"	そこはもうごうかくしたから	"},																			
"	306	":{"character":"	ここからが本番だよ	","letter": "	This is where the real work begins.	", "pinyin":"	ここからがほんばんだよ	"},																			
"	307	":{"character":"	ムード盛り上げないと	","letter": "	We have to set the mood.	", "pinyin":"	むーどもりあげないと	"},																			
"	308	":{"character":"	どうやって？	","letter": "	How do we do that?	", "pinyin":"	どうやって？	"},																			
"	309	":{"character":"	会話が途切れたらＢＧМとか	","letter": "	If there's a lull in the conversation, we'll do BGM.	", "pinyin":"	かいわがとぎれたらＢＧМとか	"},																			
"	310	":{"character":"	ＣＤ持ってきてないよ	","letter": "	I don't have my CDs with me.	", "pinyin":"	ＣＤもってきてないよ	"},																			
"	311	":{"character":"	じゃあ僕歌うよ	","letter": "	Okay, I'll sing.	", "pinyin":"	じゃあぼくうたうよ	"},																			
"	312	":{"character":"	「ねむれねむれ」	","letter": "	Nemure, nemure, nemure.	", "pinyin":"	「ねむれねむれ」	"},																			
"	313	":{"character":"	「母のむねに」	","letter": "	In My Mother's Bed	", "pinyin":"	「ははのむねに」	"},																			
"	314	":{"character":"	「ねむれねむれ」	","letter": "	Nemure nemure	", "pinyin":"	「ねむれねむれ」	"},																			
"	315	":{"character":"	ペンギンさん！眠っちゃダメ！！	","letter": "	Penguin! Don't fall asleep!	", "pinyin":"	ぺんぎんさん！ねむっちゃだめ！！	"},																			
"	316	":{"character":"	なんで子守唄歌うの！？	","letter": "	Why are you singing a lullaby?	", "pinyin":"	なんでこもりうたうたうの！？	"},																			
"	317	":{"character":"	これじゃ合格点あげられないね	","letter": "	I can't give you a passing grade for that.	", "pinyin":"	これじゃごうかくてんあげられないね	"},																			
"	318	":{"character":"	じゃあ不合格？	","letter": "	So you didn't pass?	", "pinyin":"	じゃあふごうかく？	"},																			
"	319	":{"character":"	海見たら絶対盛り上がるから！	","letter": "	I'll be so excited when I see the ocean!	", "pinyin":"	うみみたらぜったいもりあがるから！	"},																			
"	320	":{"character":"	ペンギン的には	","letter": "	From a penguin's point of view.	", "pinyin":"	ぺんぎんてきには	"},																			
"	321	":{"character":"	海だ	","letter": "	The ocean.	", "pinyin":"	うみだ	"},																			
"	322	":{"character":"	遠いけどね	","letter": "	It's a long way.	", "pinyin":"	とおいけどね	"},																			
"	323	":{"character":"	道間違えた…	","letter": "	I took a wrong turn...	", "pinyin":"	みちまちがえた…	"},																			
"	324	":{"character":"	あっ…ペンギンさん	","letter": "	Ah... penguins!	", "pinyin":"	あっ…ぺんぎんさん	"},																			
"	325	":{"character":"	１００円１００円	","letter": "	One hundred yen, one hundred yen...	", "pinyin":"	１００えん１００えん	"},																			
"	326	":{"character":"	もう見なくていいから…	","letter": "	You don't have to look anymore...	", "pinyin":"	もうみなくていいから…	"},																			
"	327	":{"character":"	もう…道間違えるなんて最低	","letter": "	You're such a jerk for taking a wrong turn	", "pinyin":"	もう…みちまちがえるなんてさいてい	"},																			
"	328	":{"character":"	ペン子さん怒って帰っちゃうよ？	","letter": "	Penko-san will get angry and go home	", "pinyin":"	ぺんごさんいかってかえっちゃうよ？	"},																			
"	329	":{"character":"	大丈夫…これは予行演習	","letter": "	Don't worry... this is just a rehearsal	", "pinyin":"	だいじょうぶ…これはよこうえんしゅう	"},																			
"	330	":{"character":"	今から行くとちょうど海に夕日が沈む頃だから…	","letter": "	If we go there now, just as the sun is setting over the ocean...	", "pinyin":"	いまからいくとちょうどうみにゆうひがしずむころだから…	"},																			
"	331	":{"character":"	絶対ロマンチックだよ！！	","letter": "	It's gonna be so romantic!	", "pinyin":"	ぜったいろまんちっくだよ！！	"},																			
"	332	":{"character":"	海だ	","letter": "	The ocean!	", "pinyin":"	うみだ	"},																			
"	333	":{"character":"	けど…	","letter": "	But...	", "pinyin":"	けど…	"},																			
"	334	":{"character":"	夕日間に合わなかったね	","letter": "	You missed the sunset.	", "pinyin":"	ゆうひまにあわなかったね	"},																			
"	335	":{"character":"	５ロマンチックなムードは不合格と…	","letter": "	5... the romantic mood is not acceptable...	", "pinyin":"	５ろまんちっくなむーどはふごうかくと…	"},																			
"	336	":{"character":"	や…夜景もきれいじゃない？	","letter": "	Well... isn't the view beautiful at night?	", "pinyin":"	や…やけいもきれいじゃない？	"},																			
"	337	":{"character":"	ほらほらムードが盛り上がってるよ！	","letter": "	Look, look, the mood is rising!	", "pinyin":"	ほらほらむーどがもりあがってるよ！	"},																			
"	338	":{"character":"	じゃあいってみる？告白	","letter": "	Shall we go for it? Confession.	", "pinyin":"	じゃあいってみる？こくはく	"},																			
"	339	":{"character":"	いってみようよ	","letter": "	Let's do it!	", "pinyin":"	いってみようよ	"},																			
"	340	":{"character":"	さあペンギンさん	","letter": "	Come on, Penguin.	", "pinyin":"	さあぺんぎんさん	"},																			
"	341	":{"character":"	私への思いのたけを熱く語って	","letter": "	Tell me how you feel about me.	", "pinyin":"	わたしへのおもいのたけをあつくかたって	"},																			
"	342	":{"character":"	ペ…ペン子さん…	","letter": "	P...Penko-san...	", "pinyin":"	ぺ…ぺんごさん…	"},																			
"	343	":{"character":"	ずっと…好きでした	","letter": "	I've always... loved you.	", "pinyin":"	ずっと…すきでした	"},																			
"	344	":{"character":"	僕と…	","letter": "	With me...	", "pinyin":"	ぼくと…	"},																			
"	345	":{"character":"	僕と…	","letter": "	Please be with me...	", "pinyin":"	ぼくと…	"},																			
"	346	":{"character":"	つきあってください	","letter": "	Please go out with me.	", "pinyin":"	つきあってください	"},																			
"	347	":{"character":"	はい	","letter": "	Yes...	", "pinyin":"	はい	"},																			
"	348	":{"character":"	痛い！！	","letter": "	Ow!	", "pinyin":"	いたい！！	"},																			
"	349	":{"character":"	やったね！	","letter": "	You did it!	", "pinyin":"	やったね！	"},																			
"	350	":{"character":"	いや…練習とわかっていてもドキドキするよね	","letter": "	I'm nervous even though I know it's just for practice.	", "pinyin":"	いや…れんしゅうとわかっていてもどきどきするよね	"},																			
"	351	":{"character":"	じゃあ…まあ合格ってことで	","letter": "	Well, then... you've passed the test.	", "pinyin":"	じゃあ…まあごうかくってことで	"},																			
"	352	":{"character":"	はいラブラブ免許	","letter": "	Yes, love license!	", "pinyin":"	はいらぶらぶめんきょ	"},																			
"	353	":{"character":"	やった！	","letter": "	Yes!	", "pinyin":"	やった！	"},																			
"	354	":{"character":"	よかったね	","letter": "	That's great.	", "pinyin":"	よかったね	"},																			
"	355	":{"character":"	あっペンギンさん	","letter": "	Hey, Penguin.	", "pinyin":"	あっぺんぎんさん	"},																			
"	356	":{"character":"	デートどうだった？	","letter": "	How was your date?	", "pinyin":"	でーとどうだった？	"},																			
"	357	":{"character":"	はい食べて	","letter": "	Eat.	", "pinyin":"	はいたべて	"},																			
"	358	":{"character":"	ありがとうございます	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございます	"},																			
"	359	":{"character":"	それでデートは？	","letter": "	So, no date?	", "pinyin":"	それででーとは？	"},																			
"	360	":{"character":"	行ってないよ	","letter": "	I didn't.	", "pinyin":"	いってないよ	"},																			
"	361	":{"character":"	えっ？	","letter": "	What?	", "pinyin":"	えっ？	"},																			
"	362	":{"character":"	いやほら…まだ夏じゃないし海へドライブには早いよ	","letter": "	It's not summer yet, it's too early to drive to the beach.	", "pinyin":"	いやほら…まだなつじゃないしうみへどらいぶにははやいよ	"},																			
"	363	":{"character":"	ダメじゃん…	","letter": "	No, no, no...	", "pinyin":"	だめじゃん…	"},																			
"	364	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguins, penguins, penguins.	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	365	":{"character":"	何？パンダ君	","letter": "	What? Panda...	", "pinyin":"	なに？ぱんだくん	"},																			
"	366	":{"character":"	どうしたら黙っていてもアイドルたちから告白されるかな	","letter": "	How can I get my idols to confess their feelings for me without telling them?	", "pinyin":"	どうしたらだまっていてもあいどるたちからこくはくされるかな	"},																			
"	367	":{"character":"	図々しいなぁ	","letter": "	You're so brazen.	", "pinyin":"	ずうずうしいなぁ	"},																			
"	368	":{"character":"	白熊君終わろ	","letter": "	Polar bear, finish!	", "pinyin":"	しろくまくんおわろ	"},																			
"	369	":{"character":"	次回しろくまカフェ	","letter": "	Next time at Shirokuma Cafe	", "pinyin":"	じかいしろくまかふぇ	"},																			
"	370	":{"character":"	ＶＳカンブリヤ宮殿	","letter": "	VS Cambria Palace	", "pinyin":"	ＶＳかんぶりやきゅうでん	"},																			
"	371	":{"character":"	しろくまカフェだけでいいでしょう	","letter": "	Just the Shirokuma Cafe will do.	", "pinyin":"	しろくまかふぇだけでいいでしょう	"},																			
"	372	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}