obj = {
"	1	":{"character":"	真夏の雑草取り	","letter": "	Weeding in Midsummer	", "pinyin":"	まなつのざっそうどり	"},																			
"	2	":{"character":"	やっと着いた	","letter": "	Finally arrived!	", "pinyin":"	やっとついた	"},																			
"	3	":{"character":"	近道しようとしたら雑草がすごくて迷ちゃったよ	","letter": "	I tried to take a shortcut, but the weeds were so thick, I got lost.	", "pinyin":"	ちかみちしようとしたらざっそうがすごくてまよいちゃったよ	"},																			
"	4	":{"character":"	そうなの迷ちゃうお客さんもいるみたい	","letter": "	Yeah, I guess some of the customers get lost.	", "pinyin":"	そうなのまよいちゃうおきゃくさんもいるみたい	"},																			
"	5	":{"character":"	隣なのに家から20分かかちゃったよ	","letter": "	It took me 20 minutes to get there from my house, even though it's right next door.	", "pinyin":"	となりなのにいえから20ふんかかちゃったよ	"},																			
"	6	":{"character":"	雑草すごいね	","letter": "	Weeds are so thick!	", "pinyin":"	ざっそうすごいね	"},																			
"	7	":{"character":"	中の席にしようか	","letter": "	Shall we sit inside?	", "pinyin":"	なかのせきにしようか	"},																			
"	8	":{"character":"	よしやろう	","letter": "	Let's do it.	", "pinyin":"	よしやろう	"},																			
"	9	":{"character":"	よいしょ(」・ω・)」	","letter": "	Here we go.	", "pinyin":"	よいしょ(」・ω・)」	"},																			
"	10	":{"character":"	何してるの白熊君	","letter": "	What are you doing, polar bear?	", "pinyin":"	なにしてるのしろくまくん	"},																			
"	11	":{"character":"	テラスで風を感じながらキンキンに冷したミントティーを飲んでる	","letter": "	I'm sitting on the terrace, feeling the breeze and drinking mint tea that's been chilled to a crisp.	", "pinyin":"	てらすでかぜをかんじながらきんきんにひやしたみんとてぃーをのんでる	"},																			
"	12	":{"character":"	そうじゃなくて	","letter": "	No, I mean...	", "pinyin":"	そうじゃなくて	"},																			
"	13	":{"character":"	なんで僕に君の店の雑草取りさせて	","letter": "	Why do you make me weed your store?	", "pinyin":"	なんでぼくにきみのみせのざっそうどりさせて	"},																			
"	14	":{"character":"	君がテラスをすすんでるの	","letter": "	And you're sipping on the terrace.	", "pinyin":"	きみがてらすをすすんでるの	"},																			
"	15	":{"character":"	僕は普通寒いところにいるでしょう	","letter": "	I'm usually out in the cold.	", "pinyin":"	ぼくはふつうさむいところにいるでしょう	"},																			
"	16	":{"character":"	僕もだよ	","letter": "	Me, too.	", "pinyin":"	ぼくもだよ	"},																			
"	17	":{"character":"	真夏に雑草取りをするペンギンなんてどこの世界にいるの	","letter": "	What kind of penguin weeds in the middle of summer?	", "pinyin":"	まなつにざっそうどりをするぺんぎんなんてどこのせかいにいるの	"},																			
"	18	":{"character":"	ごちそうさまでした	","letter": "	Thank you for dinner.	", "pinyin":"	ごちそうさまでした	"},																			
"	19	":{"character":"	では	","letter": "	Bye.	", "pinyin":"	では	"},																			
"	20	":{"character":"	らまさんどこ行くの	","letter": "	Where are you going, Mr. Lama?	", "pinyin":"	らまさんどこいくの	"},																			
"	21	":{"character":"	もう食べられないんで失礼しようかなって	","letter": "	I can't eat any more, so I'm leaving.	", "pinyin":"	もうたべられないんでしつれいしようかなって	"},																			
"	22	":{"character":"	ちょっと待ってなんで帰ちゃうの	","letter": "	Wait a minute... why are you leaving?	", "pinyin":"	ちょっとまってなんでかえさちゃうの	"},																			
"	23	":{"character":"	僕たちの雑草取り始まったばかりでしょう	","letter": "	We've just started picking weeds.	", "pinyin":"	ぼくたちのざっそうどりはじまったばかりでしょう	"},																			
"	24	":{"character":"	けどもうお腹いっぱいですよ	","letter": "	But I'm full.	", "pinyin":"	けどもうおはらいっぱいですよ	"},																			
"	25	":{"character":"	雑草取りってそういうことじゃないでしょう	","letter": "	That's not what weeding means.	", "pinyin":"	ざっそうどりってそういうことじゃないでしょう	"},																			
"	26	":{"character":"	もうちょっと頑張ろうよ	","letter": "	Let's work a little harder.	", "pinyin":"	もうちょっとがんばろうよ	"},																			
"	27	":{"character":"	僕もうお腹はじけちゃいますよ	","letter": "	I'm bursting with hunger.	", "pinyin":"	ぼくもうおなかはじけちゃいますよ	"},																			
"	28	":{"character":"	そうじゃなくて	","letter": "	No, I mean...	", "pinyin":"	そうじゃなくて	"},																			
"	29	":{"character":"	y--oO○ｴｰﾄ･･･食べる以外の方法で雑草を取れないのかな	","letter": "	Y-o-oO-ate... Can't we get the weeds in a way other than eating them?	", "pinyin":"	y--oO○えーと・・・たべるいがいのほうほうでざっそうをとれないのかな	"},																			
"	30	":{"character":"	そうでしたかちょっと考えてみます	","letter": "	I'll think about it.	", "pinyin":"	そうでしたかちょっとかんがえてみます	"},																			
"	31	":{"character":"	寝てる	","letter": "	He's sleeping.	", "pinyin":"	ねてる	"},																			
"	32	":{"character":"	起きてますよ	","letter": "	I'm awake.	", "pinyin":"	おきてますよ	"},																			
"	33	":{"character":"	寝てたでしょう	","letter": "	You've been asleep.	", "pinyin":"	ねてたでしょう	"},																			
"	34	":{"character":"	ミントティーどう？	","letter": "	Would you like some mint tea?	", "pinyin":"	みんとてぃーどう？	"},																			
"	35	":{"character":"	あいただきます	","letter": "	Thank you.	", "pinyin":"	あいただきます	"},																			
"	36	":{"character":"	もう皆頑張ろうよ	","letter": "	Come on, guys, let's go for it.	", "pinyin":"	もうみんながんばろうよ	"},																			
"	37	":{"character":"	頑張りたいんだけど僕ユーカリしか食べられなっくて	","letter": "	I'd love to, but I can only eat eucalyptus.	", "pinyin":"	がんばりたいんだけどぼくゆーかりしかたべられなっくて	"},																			
"	38	":{"character":"	だから食べない方法もあるんじゃないかな	","letter": "	So maybe there are other ways.	", "pinyin":"	だからたべないほうほうもあるんじゃないかな	"},																			
"	39	":{"character":"	ペンギンさん	","letter": "	Hey, Penguin.	", "pinyin":"	ぺんぎんさん	"},																			
"	40	":{"character":"	変な形の石拾った	","letter": "	I picked up a weird-shaped rock.	", "pinyin":"	へんなかたちのいしひろった	"},																			
"	41	":{"character":"	要らないのその報告は雑草取ろう	","letter": "	I don't want it.	", "pinyin":"	いらないのそのほうこくはざっそうとろう	"},																			
"	42	":{"character":"	ペンギンさん	","letter": "	Penguin.	", "pinyin":"	ぺんぎんさん	"},																			
"	43	":{"character":"	笹子さんそれは？	","letter": "	Mr. Sasago, what's that?	", "pinyin":"	ささごさんそれは？	"},																			
"	44	":{"character":"	土偶です	","letter": "	It's a clay figurine.	", "pinyin":"	どぐうです	"},																			
"	45	":{"character":"	拾いました	","letter": "	I picked it up.	", "pinyin":"	ひろいました	"},																			
"	46	":{"character":"	要らない報告でした	","letter": "	I don't want it.	", "pinyin":"	いらないほうこくでした	"},																			
"	47	":{"character":"	何この庭	","letter": "	What's in this garden?	", "pinyin":"	なにこのにわ	"},																			
"	48	":{"character":"	よく落ちてるんだ	","letter": "	I find them all the time.	", "pinyin":"	よくおちてるんだ	"},																			
"	49	":{"character":"	遮光器土偶ですね	","letter": "	It's a 'Shakugan-dogu', isn't it?	", "pinyin":"	しゃこうきどぐうですね	"},																			
"	50	":{"character":"	うん	","letter": "	Yes, it is.	", "pinyin":"	うん	"},																			
"	51	":{"character":"	面白い顔だね	","letter": "	Interesting face.	", "pinyin":"	おもしろいかおだね	"},																			
"	52	":{"character":"	僕だけかな雑草取り真面目にやってるの	","letter": "	Am I the only one who takes weeding seriously?	", "pinyin":"	ぼくだけかなざっそうとりまじめにやってるの	"},																			
"	53	":{"character":"	僕も～	","letter": "	Me too.	", "pinyin":"	ぼくも～	"},																			
"	54	":{"character":"	あ	","letter": "	I'm here.	", "pinyin":"	あ	"},																			
"	55	":{"character":"	いるよ～～	","letter": "	There he is!	", "pinyin":"	いるよ～～	"},																			
"	56	":{"character":"	怠け者くん	","letter": "	Lazybones!	", "pinyin":"	なまけものくん	"},																			
"	57	":{"character":"	が～ん～ば～る～ぞ～	","letter": "	I'm going to work my butt off!	", "pinyin":"	が～ん～ば～る～ぞ～	"},																			
"	58	":{"character":"	やる気はあるんだけどな	","letter": "	I've got the will to do it.	", "pinyin":"	やるきはあるんだけどな	"},																			
"	59	":{"character":"	クーラーは涼しいな	","letter": "	It's cooler in the air conditioner.	", "pinyin":"	くーらーはすずしいな	"},																			
"	60	":{"character":"	ねぇ笹持ってきてお母さん	","letter": "	Hey, bring me some bamboo grass, Mom.	", "pinyin":"	ねぇささもってきておかあさん	"},																			
"	61	":{"character":"	涼しいでしょう	","letter": "	It'll be cooler.	", "pinyin":"	すずしいでしょう	"},																			
"	62	":{"character":"	あペンギンさん何してるの	","letter": "	What are you doing, Penguin?	", "pinyin":"	あぺんぎんさんなにしてるの	"},																			
"	63	":{"character":"	何してるのじゃないよパンダ君雑草取りは？	","letter": "	What are you doing, Mr. Panda?	", "pinyin":"	なにしてるのじゃないよぱんだくんざっそうどりは？	"},																			
"	64	":{"character":"	ペンギンさんはなんでそんなに雑草取りがすきなの	","letter": "	Why do you like weeding so much, Penguin?	", "pinyin":"	ぺんぎんさんはなんでそんなにざっそうどりがすきなの	"},																			
"	65	":{"character":"	好きじゃないよ	","letter": "	I don't.	", "pinyin":"	すきじゃないよ	"},																			
"	66	":{"character":"	けどこのままじゃ一日じゃ終わらないよ	","letter": "	But I don't think we're gonna make it through the day.	", "pinyin":"	けどこのままじゃいちにちじゃおわらないよ	"},																			
"	67	":{"character":"	分かったよ	","letter": "	Okay, okay, okay, okay.	", "pinyin":"	わかったよ	"},																			
"	68	":{"character":"	もう	","letter": "	Okay.	", "pinyin":"	もう	"},																			
"	69	":{"character":"	じゃ行こうか	","letter": "	Shall we go?	", "pinyin":"	じゃいこうか	"},																			
"	70	":{"character":"	うん昼寝してからすぐ行くよ	","letter": "	I'll be right down after my nap.	", "pinyin":"	うんひるねしてからすぐいくよ	"},																			
"	71	":{"character":"	あ～～～吸わないで～～～	","letter": "	Oh, no, don't smoke.	", "pinyin":"	あ～～～すわないで～～～	"},																			
"	72	":{"character":"	暑いな	","letter": "	It's so hot.	", "pinyin":"	あついな	"},																			
"	73	":{"character":"	僕だって暑いよ	","letter": "	I'm hot too.	", "pinyin":"	ぼくだってあついよ	"},																			
"	74	":{"character":"	何！え！火事？	","letter": "	What? What? Fire?	", "pinyin":"	なに！え！かじ？	"},																			
"	75	":{"character":"	ええ？	","letter": "	What?	", "pinyin":"	ええ？	"},																			
"	76	":{"character":"	パンダ君急ごう	","letter": "	Come on, panda, let's hurry up.	", "pinyin":"	ぱんだくんいそごう	"},																			
"	77	":{"character":"	ちょっと何してるの	","letter": "	What are you doing?	", "pinyin":"	ちょっとなにしてるの	"},																			
"	78	":{"character":"	バーベキュー	","letter": "	Barbecuing.	", "pinyin":"	ばーべきゅー	"},																			
"	79	":{"character":"	らまさんお腹いっぱいだって言ってたでしょう	","letter": "	I thought you said you were full, Lamma.	", "pinyin":"	らまさんおなかいっぱいだっていってたでしょう	"},																			
"	80	":{"character":"	バーベキューは別腹ですよ	","letter": "	Barbecue is not for everyone.	", "pinyin":"	ばーべきゅーはべつばらですよ	"},																			
"	81	":{"character":"	聞いたことないよそんな言葉	","letter": "	I've never heard of that.	", "pinyin":"	きいたことないよそんなことば	"},																			
"	82	":{"character":"	ペンギンさんそこで拾った土偶です	","letter": "	Mr. Penguin, I found this clay figurine.	", "pinyin":"	ぺんぎんさんそこでひろったどぐうです	"},																			
"	83	":{"character":"	また？	","letter": "	Again?	", "pinyin":"	また？	"},																			
"	84	":{"character":"	だからすごいんだけれど要らないよその報告は	","letter": "	That's what's so great about it, but I don't want to hear about it.	", "pinyin":"	だからすごいんだけれどいらないよそのほうこくは	"},																			
"	85	":{"character":"	見せて見せて	","letter": "	Let me see. Let me see.	", "pinyin":"	みせてみせて	"},																			
"	86	":{"character":"	らまさん	","letter": "	Ramasan.	", "pinyin":"	らまさん	"},																			
"	87	":{"character":"	はいどうぞ	","letter": "	Here you go.	", "pinyin":"	はいどうぞ	"},																			
"	88	":{"character":"	焼けたよ	","letter": "	It's done.	", "pinyin":"	やけたよ	"},																			
"	89	":{"character":"	ありがとうございます	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございます	"},																			
"	90	":{"character":"	僕ちょっと倒れるよ	","letter": "	I'm going to fall over.	", "pinyin":"	ぼくちょっとたおれるよ	"},																			
"	91	":{"character":"	ペンギンさん	","letter": "	Penguin.	", "pinyin":"	ぺんぎんさん	"},																			
"	92	":{"character":"	ナイスショット	","letter": "	Nice shot.	", "pinyin":"	ないすしょっと	"},																			
"	93	":{"character":"	打てるもんですね	","letter": "	You're good at that.	", "pinyin":"	うてるもんですね	"},																			
"	94	":{"character":"	何してるの	","letter": "	What are you doing?	", "pinyin":"	なにしてるの	"},																			
"	95	":{"character":"	ゴルフ	","letter": "	Golf.	", "pinyin":"	ごるふ	"},																			
"	96	":{"character":"	誰も僕を見習って頑張ろうとしないなんて	","letter": "	I can't believe no one's trying to learn from me.	", "pinyin":"	だれもぼくをみならってがんばろうとしないなんて	"},																			
"	97	":{"character":"	ごめん	","letter": "	Sorry.	", "pinyin":"	ごめん	"},																			
"	98	":{"character":"	ペンギンさん	","letter": "	Penguin!	", "pinyin":"	ぺんぎんさん	"},																			
"	99	":{"character":"	何笹子さんまた土偶？	","letter": "	What are you, a clay figurine again?	", "pinyin":"	なにささごさんまたどぐう？	"},																			
"	100	":{"character":"	いいえ皆でここだけはやったんですよ	","letter": "	No, we all did this part together.	", "pinyin":"	いいえみんなでここだけはやったんですよ	"},																			
"	101	":{"character":"	え？	","letter": "	What?	", "pinyin":"	え？	"},																			
"	102	":{"character":"	この木陰なら涼しいし	","letter": "	It's cooler here in the shade.	", "pinyin":"	このこかげならすずしいし	"},																			
"	103	":{"character":"	ペンギンさんを休ませてあげられるってらまさんが	","letter": "	We can give Mr. Penguin a break, Ramasan said.	", "pinyin":"	ぺんぎんさんをやすませてあげられるってらまさんが	"},																			
"	104	":{"character":"	テラスが日が射してきちゃって	","letter": "	The sun is shining on the terrace.	", "pinyin":"	てらすがひがさしてきちゃって	"},																			
"	105	":{"character":"	ごめんねm(____)m	","letter": "	Sorry m(____)m	", "pinyin":"	ごめんねm(____)m	"},																			
"	106	":{"character":"	友達と一緒に賑やかにできたほうがいいなぁって	","letter": "	I thought it would be better to have a lively party with my friends.	", "pinyin":"	ともだちといっしょににぎやかにできたほうがいいなぁって	"},																			
"	107	":{"character":"	だってみんなでこうしてるだけで楽しいよ	","letter": "	It's fun just to be together like this.	", "pinyin":"	だってみんなでこうしてるだけでたのしいよ	"},																			
"	108	":{"character":"	そうだね	","letter": "	I know...	", "pinyin":"	そうだね	"},																			
"	109	":{"character":"	僕大事なこと忘れてたみたい	","letter": "	I think I forgot something important.	", "pinyin":"	ぼくだいじなことわすれてたみたい	"},																			
"	110	":{"character":"	ミントティー飲む？	","letter": "	Do you want some mint tea?	", "pinyin":"	みんとてぃーのむ？	"},																			
"	111	":{"character":"	うん	","letter": "	Sure.	", "pinyin":"	うん	"},																			
"	112	":{"character":"	私たちは雑草取りに戻りましょうか	","letter": "	Shall we go back to picking weeds?	", "pinyin":"	わたしたちはざっそうとりにもどりましょうか	"},																			
"	113	":{"character":"	うん	","letter": "	Yeah. - Okay.	", "pinyin":"	うん	"},																			
"	114	":{"character":"	ペンギンさんは休んでてください	","letter": "	You go rest, Mr. Penguin.	", "pinyin":"	ぺんぎんさんはやすんでてください	"},																			
"	115	":{"character":"	じゃあ	","letter": "	Okay, then.	", "pinyin":"	じゃあ	"},																			
"	116	":{"character":"	もう一頑張りしますか	","letter": "	Let's try one more time.	", "pinyin":"	もういちがんばりしますか	"},																			
"	117	":{"character":"	もう食べられません	","letter": "	I can't eat any more.	", "pinyin":"	もうたべられません	"},																			
"	118	":{"character":"	ペンギンさん出番が来たよ	","letter": "	Penguin, it's your turn.	", "pinyin":"	ぺんぎんさんでばんがきたよ	"},																			
"	119	":{"character":"	大～丈～夫～	","letter": "	I'll take care of it.	", "pinyin":"	だい～たけ～おっと～	"},																			
"	120	":{"character":"	後は僕が～	","letter": "	I'll take care of it.	", "pinyin":"	あとはぼくが～	"},																			
"	121	":{"character":"	終わらないね	","letter": "	It's not over.	", "pinyin":"	おわらないね	"},																			
"	122	":{"character":"	どうしましょうか	","letter": "	I don't know what I'll do.	", "pinyin":"	どうしましょうか	"},																			
"	123	":{"character":"	バービキュ食べ過ぎて僕もう草は食べられません	","letter": "	I've eaten so much barbecue, I can't eat grass anymore.	", "pinyin":"	ばーびきゅたべすぎてぼくもうくさはたべられません	"},																			
"	124	":{"character":"	もしもし	","letter": "	Hello?	", "pinyin":"	もしもし	"},																			
"	125	":{"character":"	何だよこのクソ暑い中に呼び出しやがって	","letter": "	What the hell are you doing calling me up here in this heat?	", "pinyin":"	なんだよこのくそあついなかによびだしやがって	"},																			
"	126	":{"character":"	庭の雑草が伸びちゃってさ	","letter": "	The weeds in the garden have grown.	", "pinyin":"	にわのざっそうがのびちゃってさ	"},																			
"	127	":{"character":"	庭の雑草？白熊	","letter": "	Weeds in the garden? White bear!	", "pinyin":"	にわのざっそう？しろくま	"},																			
"	128	":{"character":"	おめぇまさか俺に雑草取らせようってじゃねんだろうな	","letter": "	You don't want me to get rid of the weeds, do you?	", "pinyin":"	おめぇまさかおれにざっそうとらせようってじゃねんだろうな	"},																			
"	129	":{"character":"	いい？	","letter": "	Okay?	", "pinyin":"	いい？	"},																			
"	130	":{"character":"	いい？	","letter": "	Ready?	", "pinyin":"	いい？	"},																			
"	131	":{"character":"	じゃねぇー	","letter": "	No!	", "pinyin":"	じゃねぇー	"},																			
"	132	":{"character":"	これでいいのか	","letter": "	Is this what you want?	", "pinyin":"	これでいいのか	"},																			
"	133	":{"character":"	なんて暴力的でなんて丁寧な仕事だ	","letter": "	How violent... how polite...	", "pinyin":"	なんてぼうりょくてきでなんてていねいなしごとだ	"},																			
"	134	":{"character":"	飯食わせろ！	","letter": "	Feed me!	", "pinyin":"	めしくわせろ！	"},																			
"	135	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},																			
"	136	":{"character":"	うめぇー！	","letter": "	Yum!	", "pinyin":"	うめぇー！	"},																			
"	137	":{"character":"	またな	","letter": "	See you later.	", "pinyin":"	またな	"},																			
"	138	":{"character":"	暴風のように去っていた	","letter": "	He was gone like a storm.	", "pinyin":"	ぼうふうのようにさっていた	"},																			
"	139	":{"character":"	今日はおごるよ	","letter": "	I'll buy you a drink today.	", "pinyin":"	きょうはおごるよ	"},																			
"	140	":{"character":"	ぺんぎんさんにも迷惑かけちゃったし	","letter": "	I'm sorry I bothered Pengin-san.	", "pinyin":"	ぺんぎんさんにもめいわくかけちゃったし	"},																			
"	141	":{"character":"	飲もうか	","letter": "	Shall we drink?	", "pinyin":"	のもうか	"},																			
"	142	":{"character":"	うん(/ω＼)	","letter": "	Yes.	", "pinyin":"	うん(/ω＼)	"},																			
"	143	":{"character":"	やぁ今日は働いたね	","letter": "	Hey, you worked hard today.	", "pinyin":"	やぁきょうははたらいたね	"},																			
"	144	":{"character":"	白熊さんもこっちに来て飲みましょう	","letter": "	Let's have a drink, polar bear!	", "pinyin":"	しろくまさんもこっちにきてのみましょう	"},																			
"	145	":{"character":"	楽しにゃ	","letter": "	Let's have fun!	", "pinyin":"	らくしにゃ	"},																			
"	146	":{"character":"	でしょう	","letter": "	I'm sure you will.	", "pinyin":"	でしょう	"},																			
"	147	":{"character":"	白熊君相談って何	","letter": "	What do you want to talk about, polar bear?	", "pinyin":"	しろくまくんそうだんってなに	"},																			
"	148	":{"character":"	それが	","letter": "	What's wrong?	", "pinyin":"	それが	"},																			
"	149	":{"character":"	どうしたの僕でよかったら相談に乗るよ	","letter": "	What's wrong?	", "pinyin":"	どうしたのぼくでよかったらそうだんにのるよ	"},																			
"	150	":{"character":"	え工ｴｴｪｪ(´д｀)ｪｪｴｴ工	","letter": "	What?	", "pinyin":"	えこうええぇぇ(´д｀)ぇぇええこう	"},																			
"	151	":{"character":"	たった数日でこんなに伸びたの	","letter": "	It's grown so much in just a few days!	", "pinyin":"	たったすうじつでこんなにのびたの	"},																			
"	152	":{"character":"	夏の雑草は伸びるの早いんだよ	","letter": "	Summer weeds grow fast.	", "pinyin":"	なつのざっそうはのびるのはやいんだよ	"},																			
"	153	":{"character":"	僕が手伝う理由が見えないんだけど	","letter": "	I don't see why I should help you.	", "pinyin":"	ぼくがてつだうりゆうがみえないんだけど	"},																			
"	154	":{"character":"	ほら僕は寒いところの生き物だから	","letter": "	You see, I'm a creature of the cold.	", "pinyin":"	ほらぼくはさむいところのいきものだから	"},																			
"	155	":{"character":"	だから僕もだよ	","letter": "	That's why I'm here.	", "pinyin":"	だからぼくもだよ	"},																			
"	156	":{"character":"	さっき見つけた土偶です	","letter": "	The clay figurine we found earlier.	", "pinyin":"	さっきみつけたどぐうです	"},																			
"	157	":{"character":"	笹子さんその報告はもういいから	","letter": "	Sasago, that's enough.	", "pinyin":"	ささごさんそのほうこくはもういいから	"},																			
"	158	":{"character":"	ペンギンさんのロマンス	","letter": "	Penguin Romance.	", "pinyin":"	ぺんぎんさんのろまんす	"},																			
"	159	":{"character":"	夏ですね	","letter": "	It's summer.	", "pinyin":"	なつですね	"},																			
"	160	":{"character":"	夏だね	","letter": "	It is, isn't it?	", "pinyin":"	なつだね	"},																			
"	161	":{"character":"	今年は蝉がよく泣きますね	","letter": "	The cicadas are crying a lot this year.	", "pinyin":"	ことしはせみがよくなきますね	"},																			
"	162	":{"character":"	雄は腹腔内の発音筋と発音膜で音を出して共鳴室で音を大きく出して雌を呼んでるね	","letter": "	The male calls for the female by making sounds with the sound-producing muscles and membranes in his abdominal cavity, and by making the sounds louder in the resonance chamber.	", "pinyin":"	おすはふくこうないのはつおんすじとはつおんまくでおとをだしてきょうめいしつでおとをおおきくだしてめすをよんでるね	"},																			
"	163	":{"character":"	情緒のない言い方やめてくれますか	","letter": "	Can you please stop being so emotionless?	", "pinyin":"	じょうちょのないいいかたやめてくれますか	"},																			
"	164	":{"character":"	どうしたのパンダ君	","letter": "	What's wrong, panda?	", "pinyin":"	どうしたのぱんだくん	"},																			
"	165	":{"character":"	食べないのパンダあんぱん	","letter": "	Aren't you eating, panda?	", "pinyin":"	たべないのぱんだあんぱん	"},																			
"	166	":{"character":"	体調悪いの	","letter": "	I'm not feeling well.	", "pinyin":"	たいちょうわるいの	"},																			
"	167	":{"character":"	毎日パンじゃなくてたまには高級フルーツでも買ってきてよ	","letter": "	You should buy me some fancy fruit instead of bread every day	", "pinyin":"	まいにちぱんじゃなくてたまにはこうきゅうふるーつでもかってきてよ	"},																			
"	168	":{"character":"	果物屋にはペン子さんがいないじゃない	","letter": "	There's no Penko-san at the fruit stand.	", "pinyin":"	くだものやにはぺんごさんがいないじゃない	"},																			
"	169	":{"character":"	ペンギンさん	","letter": "	Penguin!	", "pinyin":"	ぺんぎんさん	"},																			
"	170	":{"character":"	何？パン食べる	","letter": "	What? I'll have some bread.	", "pinyin":"	なに？ぱんたべる	"},																			
"	171	":{"character":"	いいえそうじゃなくて	","letter": "	No, I mean...	", "pinyin":"	いいえそうじゃなくて	"},																			
"	172	":{"character":"	ペンギンさん夏にはペン子さんに告白してドライブって言ってませんでしたっけ	","letter": "	Penguin, didn't you confess to Penko-san in the summer and say you'd like to go for a drive?	", "pinyin":"	ぺんぎんさんなつにはぺんごさんにこくはくしてどらいぶっていってませんでしたっけ	"},																			
"	173	":{"character":"	もう夏だね	","letter": "	It's already summer.	", "pinyin":"	もうなつだね	"},																			
"	174	":{"character":"	夏とは言ったけど今年のとはいってないでしょう	","letter": "	You said summer, but you didn't say this year.	", "pinyin":"	なつとはいったけどことしのとはいってないでしょう	"},																			
"	175	":{"character":"	来年かもしれないし再来年かもしれないし十年後の夏かもしれないよ	","letter": "	It could be next year, or the year after that, or the summer ten years from now.	", "pinyin":"	らいねんかもしれないしさらいねんかもしれないしじゅうねんごのなつかもしれないよ	"},																			
"	176	":{"character":"	そんな長いスパンの話なんですか	","letter": "	Are you talking about such a long time span?	", "pinyin":"	そんなながいすぱんのはなしなんですか	"},																			
"	177	":{"character":"	もう今からチョロっと告白してきなよ	","letter": "	Go make a little confession now.	", "pinyin":"	もういまからちょろっとこくはくしてきなよ	"},																			
"	178	":{"character":"	チョロっとってちょっと待ってよ	","letter": "	Wait a minute.	", "pinyin":"	ちょろっとってちょっとまってよ	"},																			
"	179	":{"character":"	いいんじゃないですか告白してきたら	","letter": "	Why don't you just go ahead and confess?	", "pinyin":"	いいんじゃないですかこくはくしてきたら	"},																			
"	180	":{"character":"	告白に当たっての心の準備をしないとだね	","letter": "	I have to prepare myself for the confession.	", "pinyin":"	こくはくにあたってのこころのじゅんびをしないとだね	"},																			
"	181	":{"character":"	いやいやその前に心の準備の用意の前振りをだね	","letter": "	No, no, no, no... before that, you need to prepare yourself for the confession.	", "pinyin":"	いやいやそのまえにこころのじゅんびのよういのまえぶりをだね	"},																			
"	182	":{"character":"	でも早く告白しないとペン子さん取られちゃうかもしれないですよ	","letter": "	But if you don't confess soon, Penko-san might be taken away from you.	", "pinyin":"	でもはやくこくはくしないとぺんごさんとられちゃうかもしれないですよ	"},																			
"	183	":{"character":"	けどふられたらどうしよう	","letter": "	But what if she rejects me?	", "pinyin":"	けどふられたらどうしよう	"},																			
"	184	":{"character":"	大丈夫だよまだふられたわけじゃないんだから	","letter": "	Don't worry, she hasn't been rejected yet	", "pinyin":"	だいじょうぶだよまだふられたわけじゃないんだから	"},																			
"	185	":{"character":"	そうですよ	","letter": "	That's right	", "pinyin":"	そうですよ	"},																			
"	186	":{"character":"	ちゃんと告白してふられようよ	","letter": "	Let's confess and get dumped	", "pinyin":"	ちゃんとこくはくしてふられようよ	"},																			
"	187	":{"character":"	白熊さん	","letter": "	White Bear!	", "pinyin":"	しろくまさん	"},																			
"	188	":{"character":"	そうだね	","letter": "	I know.	", "pinyin":"	そうだね	"},																			
"	189	":{"character":"	いつかの夏にと思ってたけど	","letter": "	I was thinking of doing it sometime this summer.	", "pinyin":"	いつかのなつにとおもってたけど	"},																			
"	190	":{"character":"	もう告白してしまおうかな	","letter": "	Maybe I should confess already.	", "pinyin":"	もうこくはくしてしまおうかな	"},																			
"	191	":{"character":"	そうですよ	","letter": "	Yes, you're right.	", "pinyin":"	そうですよ	"},																			
"	192	":{"character":"	そうだよふられるなら早いほうがいいよ	","letter": "	Yeah, if you're going to be rejected, the sooner the better.	", "pinyin":"	そうだよふられるならはやいほうがいいよ	"},																			
"	193	":{"character":"	パンダ君	","letter": "	Mr. Panda.	", "pinyin":"	ぱんだくん	"},																			
"	194	":{"character":"	よし行くよ	","letter": "	Okay, I'm going.	", "pinyin":"	よしいくよ	"},																			
"	195	":{"character":"	これでようやく彼女の名前も分かるしね	","letter": "	And now I finally know her name.	", "pinyin":"	これでようやくかのじょのなまえもわかるしね	"},																			
"	196	":{"character":"	何？	","letter": "	What?	", "pinyin":"	なに？	"},																			
"	197	":{"character":"	ペン子さんじゃないの	","letter": "	I thought you were Penko.	", "pinyin":"	ぺんごさんじゃないの	"},																			
"	198	":{"character":"	え？言ってなかった	","letter": "	What? I didn't tell you.	", "pinyin":"	え？いってなかった	"},																			
"	199	":{"character":"	ペン子さんっていうのは僕が彼女に付けた名前だよ	","letter": "	Penko is the name I gave her.	", "pinyin":"	ぺんごさんっていうのはぼくがかのじょにつけたなまえだよ	"},																			
"	200	":{"character":"	まさか名前知らないんですか	","letter": "	You don't know her name?	", "pinyin":"	まさかなまえしらないんですか	"},																			
"	201	":{"character":"	知らないよ	","letter": "	No, I don't.	", "pinyin":"	しらないよ	"},																			
"	202	":{"character":"	悪い？	","letter": "	Is that bad?	", "pinyin":"	わるい？	"},																			
"	203	":{"character":"	だって	","letter": "	Because...	", "pinyin":"	だって	"},																			
"	204	":{"character":"	じゃ笹子さんは名前も知らない花をきれいだなって思ったことはないですか	","letter": "	Then, Sasako-san, have you ever thought a flower you don't know the name of was beautiful?	", "pinyin":"	じゃささごさんはなまえもしらないはなをきれいだなっておもったことはないですか	"},																			
"	205	":{"character":"	名前も知らない美味しい魚を食べたことはないですか	","letter": "	Have you ever eaten a delicious fish you don't know the name of?	", "pinyin":"	なまえもしらないおいしいさかなをたべたことはないですか	"},																			
"	206	":{"character":"	名前も知らない曲に心揺さぶれたことはないですか	","letter": "	Have you ever been moved by a song you don't know the name of?	", "pinyin":"	なまえもしらないきょくにこころゆさぶれたことはないですか	"},																			
"	207	":{"character":"	名前も知らない未知の風景に美しいと思ったことはないですか	","letter": "	Have you ever thought of the beauty of an unknown landscape that you don't know the name of?	", "pinyin":"	なまえもしらないみちのふうけいにうつくしいとおもったことはないですか	"},																			
"	208	":{"character":"	分かりましたからもう行ってください	","letter": "	All right, you can go now.	", "pinyin":"	わかりましたからもういってください	"},																			
"	209	":{"character":"	じゃ	","letter": "	Well then...	", "pinyin":"	じゃ	"},																			
"	210	":{"character":"	名前も知らないんですね	","letter": "	You don't know its name, do you?	", "pinyin":"	なまえもしらないんですね	"},																			
"	211	":{"character":"	大丈夫ですかね	","letter": "	Is everything all right?	", "pinyin":"	だいじょうぶですかね	"},																			
"	212	":{"character":"	ありがとうございました	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございました	"},																			
"	213	":{"character":"	いらっしゃいませ	","letter": "	Welcome.	", "pinyin":"	いらっしゃいませ	"},																			
"	214	":{"character":"	あのう	","letter": "	Excuse me.	", "pinyin":"	あのう	"},																			
"	215	":{"character":"	今日はサービス券もらいに来たんじゃないです	","letter": "	I didn't come here for a coupon.	", "pinyin":"	きょうはさーびすけんもらいにきたんじゃないです	"},																			
"	216	":{"character":"	言わなくていい言葉だった	","letter": "	You didn't have to say that.	", "pinyin":"	いわなくていいことばだった	"},																			
"	217	":{"character":"	待とう人がいなくなるのを	","letter": "	Let's wait for them to go away.	", "pinyin":"	まとうひとがいなくなるのを	"},																			
"	218	":{"character":"	またくるわ	","letter": "	I'll be back.	", "pinyin":"	またくるわ	"},																			
"	219	":{"character":"	ありがとうございました	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございました	"},																			
"	220	":{"character":"	いまだ今しかないでも緊張してきた	","letter": "	It's now or never, but I'm getting nervous.	", "pinyin":"	いまだいましかないでもきんちょうしてきた	"},																			
"	221	":{"character":"	こういう時どうするんだっけ	","letter": "	I don't know what I'm supposed to do in a situation like this.	", "pinyin":"	こういうときどうするんだっけ	"},																			
"	222	":{"character":"	人という字3回書いて呑むんだ	","letter": "	Write the word 'person' three times and drink.	", "pinyin":"	ひとというじ3かいかいてのむんだ	"},																			
"	223	":{"character":"	いや待ってよ	","letter": "	No, wait!	", "pinyin":"	いやまってよ	"},																			
"	224	":{"character":"	ペンギンの場合はペンギンって3回書いて呑む方がいいのかな	","letter": "	I wonder if it's better to write 'penguin' three times and drink it.	", "pinyin":"	ぺんぎんのばあいはぺんぎんって3かいかいてのむほうがいいのかな	"},																			
"	225	":{"character":"	ペ－ン－ギ－ン	","letter": "	Penguins.	", "pinyin":"	ぺ－ん－ぎ－ん	"},																			
"	226	":{"character":"	ペ－ン－ギ－ン	","letter": "	Penguins.	", "pinyin":"	ぺ－ん－ぎ－ん	"},																			
"	227	":{"character":"	ペ－ン－ギ－ン	","letter": "	Pengui-gee-gee-gee-gee-gee-gee-gee-gee-gee.	", "pinyin":"	ぺ－ん－ぎ－ん	"},																			
"	228	":{"character":"	そんなたくさんの文字呑めるか	","letter": "	I can't drink that many letters.	", "pinyin":"	そんなたくさんのもじのめるか	"},																			
"	229	":{"character":"	あのう	","letter": "	Excuse me.	", "pinyin":"	あのう	"},																			
"	230	":{"character":"	すみません大きいな声出して	","letter": "	I'm sorry, I didn't mean to speak so loud.	", "pinyin":"	すみませんおおきいなこえだして	"},																			
"	231	":{"character":"	いいえいつもありがとうございます	","letter": "	No, thank you for everything.	", "pinyin":"	いいえいつもありがとうございます	"},																			
"	232	":{"character":"	いえそんな大したこと	","letter": "	No, it's no big deal.	", "pinyin":"	いえそんなたいしたこと	"},																			
"	233	":{"character":"	分かりますすごく好きなんだなって	","letter": "	I can see why you like it so much.	", "pinyin":"	わかりますすごくすきなんだなって	"},																			
"	234	":{"character":"	パンが	","letter": "	The bread.	", "pinyin":"	ぱんが	"},																			
"	235	":{"character":"	ありがとうございました	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございました	"},																			
"	236	":{"character":"	あのう	","letter": "	Excuse me.	", "pinyin":"	あのう	"},																			
"	237	":{"character":"	はい	","letter": "	Yes, ma'am.	", "pinyin":"	はい	"},																			
"	238	":{"character":"	前からあなたの事が好きでした	","letter": "	I've always liked you.	", "pinyin":"	まえからあなたのことがすきでした	"},																			
"	239	":{"character":"	僕とデートしてください	","letter": "	Please go on a date with me.	", "pinyin":"	ぼくとでーとしてください	"},																			
"	240	":{"character":"	日曜日駅前で一時にまってます	","letter": "	I'll be waiting for you in front of the station on Sunday.	", "pinyin":"	にちようびえきまえでいっときにまってます	"},																			
"	241	":{"character":"	それじゃ	","letter": "	Okay, bye.	", "pinyin":"	それじゃ	"},																			
"	242	":{"character":"	あれからペンギンさん毎日パン屋さんに行ってデートに誘ってるらしいですよ	","letter": "	Penguin says he's been going to the bakery every day since then, asking you out.	", "pinyin":"	あれからぺんぎんさんまいにちぱんやさんにいってでーとにさそってるらしいですよ	"},																			
"	243	":{"character":"	今日で四日目ですって	","letter": "	Today is his fourth day.	", "pinyin":"	きょうでよっかめですって	"},																			
"	244	":{"character":"	ＯＫもらうまで通うって	","letter": "	He said he'll keep going until she says yes.	", "pinyin":"	ＯＫもらうまでかようって	"},																			
"	245	":{"character":"	しつこくない	","letter": "	He's not persistent.	", "pinyin":"	しつこくない	"},																			
"	246	":{"character":"	そんなことないよ	","letter": "	No, he's not.	", "pinyin":"	そんなことないよ	"},																			
"	247	":{"character":"	ペンギンさん頑張ってるよね	","letter": "	Penguin is doing his best.	", "pinyin":"	ぺんぎんさんがんばってるよね	"},																			
"	248	":{"character":"	笹子さんは毎日毎日しつこく誘われたらどうなの	","letter": "	What if he asks you out all day, every day?	", "pinyin":"	ささごさんはまいにちまいにちしつこくさそわれたらどうなの	"},																			
"	249	":{"character":"	えそれは嫌ですけど	","letter": "	I wouldn't like that.	", "pinyin":"	えそれはいやですけど	"},																			
"	250	":{"character":"	今日で一週間ですよ	","letter": "	It's been a week today.	", "pinyin":"	きょうでいっしゅうかんですよ	"},																			
"	251	":{"character":"	幸せなんじゃないですかね	","letter": "	You must be happy.	", "pinyin":"	しあわせなんじゃないですかね	"},																			
"	252	":{"character":"	こんなふうに一途に思われたら	","letter": "	If he was this devoted to you...	", "pinyin":"	こんなふうにいちずにおもわれたら	"},																			
"	253	":{"character":"	そう	","letter": "	Yes.	", "pinyin":"	そう	"},																			
"	254	":{"character":"	そうですよ	","letter": "	That's right.	", "pinyin":"	そうですよ	"},																			
"	255	":{"character":"	笹子さんは一週間毎日毎日しつこくされるのはどうなの	","letter": "	Sasako, how do you feel about being pestered every day for a week?	", "pinyin":"	ささごさんはいっしゅうかんまいにちまいにちしつこくされるのはどうなの	"},																			
"	256	":{"character":"	それは嫌ですけど	","letter": "	I don't like that.	", "pinyin":"	それはいやですけど	"},																			
"	257	":{"character":"	前からあなたの事が好きでした	","letter": "	I've liked you for a while.	", "pinyin":"	まえからあなたのことがすきでした	"},																			
"	258	":{"character":"	僕とデートしてください	","letter": "	Please go on a date with me.	", "pinyin":"	ぼくとでーとしてください	"},																			
"	259	":{"character":"	日曜日駅前で一時にまってます	","letter": "	I'll be waiting for you in front of the station on Sunday.	", "pinyin":"	にちようびえきまえでいっときにまってます	"},																			
"	260	":{"character":"	日曜日って明日ですよね	","letter": "	Sunday is tomorrow, right?	", "pinyin":"	にちようびってあしたですよね	"},																			
"	261	":{"character":"	うんはい急ですねすみません	","letter": "	I'm sorry, it's short notice.	", "pinyin":"	うんはいきゅうですねすみません	"},																			
"	262	":{"character":"	分かりました	","letter": "	I'm sorry. - Okay.	", "pinyin":"	わかりました	"},																			
"	263	":{"character":"	え？	","letter": "	What?	", "pinyin":"	え？	"},																			
"	264	":{"character":"	僕らはね最初から愛し合っていたんじゃないかな	","letter": "	I think we loved each other from the start.	", "pinyin":"	ぼくらはねさいしょからあいしあっていたんじゃないかな	"},																			
"	265	":{"character":"	一週間毎日パン屋さんに行って告白をしたわけだよ	","letter": "	We went to the bakery every day for a week and confessed our feelings.	", "pinyin":"	いっしゅうかんまいにちぱんやさんにいってこくはくをしたわけだよ	"},																			
"	266	":{"character":"	でねとうとう一週間目のことだよ	","letter": "	And finally, on the first week...	", "pinyin":"	でねとうとういちしゅうかんめのことだよ	"},																			
"	267	":{"character":"	それでさペン美ちゃんがね	","letter": "	And then... Penmi...	", "pinyin":"	それでさぺんみちゃんがね	"},																			
"	268	":{"character":"	あ彼女ペン子ちゃんじゃなくてペン美ちゃんって名前だったんだけど	","letter": "	Her name was Penmi-chan, not Penko	", "pinyin":"	あかのじょぺんごちゃんじゃなくてぺんみちゃんってなまえだったんだけど	"},																			
"	269	":{"character":"	ペン美ちゃんがどうしたって聞いてみて	","letter": "	Ask her what's wrong with Penmi-chan	", "pinyin":"	ぺんみちゃんがどうしたってきいてみて	"},																			
"	270	":{"character":"	もう5回目だよ	","letter": "	That's the fifth time	", "pinyin":"	もう5かいめだよ	"},																			
"	271	":{"character":"	聞いたほうがいいんですか	","letter": "	Should I ask?	", "pinyin":"	きいたほうがいいんですか	"},																			
"	272	":{"character":"	だからペン美ちゃんがどうしたか聞いてみて	","letter": "	Ask her what's wrong with Penmi	", "pinyin":"	だからぺんみちゃんがどうしたかきいてみて	"},																			
"	273	":{"character":"	ペン美ちゃんがどうしたんですか？	","letter": "	What's wrong with Penmi?	", "pinyin":"	ぺんみちゃんがどうしたんですか？	"},																			
"	274	":{"character":"	日曜日って明日ですかって聞いてきたの	","letter": "	She asked me if Sunday is tomorrow	", "pinyin":"	にちようびってあしたですかってきいてきたの	"},																			
"	275	":{"character":"	もう分かったよ	","letter": "	I already know.	", "pinyin":"	もうわかったよ	"},																			
"	276	":{"character":"	きっと僕たちは愛し合う運命だったんだよ	","letter": "	We were meant to make love.	", "pinyin":"	きっとぼくたちはあいしあううんめいだったんだよ	"},																			
"	277	":{"character":"	あパン食べていいから遠慮なく食べて	","letter": "	You can eat the bread.	", "pinyin":"	あぱんたべていいからえんりょなくたべて	"},																			
"	278	":{"character":"	じゃまた明日～	","letter": "	See you tomorrow.	", "pinyin":"	じゃまたあした～	"},																			
"	279	":{"character":"	明日は何回聞けばいいのかな	","letter": "	How many times do I have to ask you tomorrow?	", "pinyin":"	あしたはなんかいきけばいいのかな	"},																			
"	280	":{"character":"	20回くらい	","letter": "	About 20 times.	", "pinyin":"	20かいくらい	"},																			
"	281	":{"character":"	工ｴｴｪｪ(´д｀)ｪｪｴｴ工	","letter": "	I'll ask you 20 times tomorrow.	", "pinyin":"	こうええぇぇ(´д｀)ぇぇええこう	"},																			
"	282	":{"character":"	ペン美ちゃんまだかな	","letter": "	Penmi, are you ready yet?	", "pinyin":"	ぺんみちゃんまだかな	"},																			
"	283	":{"character":"	まだちょっと早かったかな	","letter": "	Maybe it's a little early.	", "pinyin":"	まだちょっとはやかったかな	"},																			
"	284	":{"character":"	ペン美ちゃん	","letter": "	Penmi!	", "pinyin":"	ぺんみちゃん	"},																			
"	285	":{"character":"	おいペン美ちゃん	","letter": "	Hey, Penmi!	", "pinyin":"	おいぺんみちゃん	"},																			
"	286	":{"character":"	えあたしペン子だけど	","letter": "	I'm Penko	", "pinyin":"	えあたしぺんごだけど	"},																			
"	287	":{"character":"	え	","letter": "	What?	", "pinyin":"	え	"},																			
"	288	":{"character":"	ちょっとどういうこと？	","letter": "	What's going on?	", "pinyin":"	ちょっとどういうこと？	"},																			
"	289	":{"character":"	え！ペン美ちゃんがもう一人	","letter": "	What? There's another Penmi!	", "pinyin":"	え！ぺんみちゃんがもうひとり	"},																			
"	290	":{"character":"	何言ってるのわたしペン花よ	","letter": "	What are you talking about, I'm Penka!	", "pinyin":"	なにいってるのわたしぺんはなよ	"},																			
"	291	":{"character":"	え！	","letter": "	What?	", "pinyin":"	え！	"},																			
"	292	":{"character":"	ちょっとあんたあたしのこと好きだったんじゃないの	","letter": "	I thought you liked me!	", "pinyin":"	ちょっとあんたあたしのことすきだったんじゃないの	"},																			
"	293	":{"character":"	あれ君がペン美ちゃん？	","letter": "	Are you Penmi?	", "pinyin":"	あれきみがぺんみちゃん？	"},																			
"	294	":{"character":"	ペン奈よ	","letter": "	I'm Penna	", "pinyin":"	ぺんだいよ	"},																			
"	295	":{"character":"	ペン乃よ	","letter": "	I'm Pen-no.	", "pinyin":"	ぺんのよ	"},																			
"	296	":{"character":"	どういうこと？	","letter": "	What do you mean?	", "pinyin":"	どういうこと？	"},																			
"	297	":{"character":"	違うんだペン美ちゃん	","letter": "	No, Penmi.	", "pinyin":"	ちがうんだぺんみちゃん	"},																			
"	298	":{"character":"	ペンジョリナよ	","letter": "	I'm Penjolina.	", "pinyin":"	ぺんじょりなよ	"},																			
"	299	":{"character":"	ペンジョリナ	","letter": "	Penjolina.	", "pinyin":"	ぺんじょりな	"},																			
"	300	":{"character":"	ちょっとペンギンさん	","letter": "	Hey, Penguin!	", "pinyin":"	ちょっとぺんぎんさん	"},																			
"	301	":{"character":"	ごめんペン美ちゃん	","letter": "	I'm sorry, Penmi.	", "pinyin":"	ごめんぺんみちゃん	"},																			
"	302	":{"character":"	これはその	","letter": "	This is, um...	", "pinyin":"	これはその	"},																			
"	303	":{"character":"	ペンニュエルよ	","letter": "	Pennyuel.	", "pinyin":"	ぺんにゅえるよ	"},																			
"	304	":{"character":"	ペンニュエル！	","letter": "	Pennyuel!	", "pinyin":"	ぺんにゅえる！	"},																			
"	305	":{"character":"	ペンギンさん	","letter": "	Mr. Penguin.	", "pinyin":"	ぺんぎんさん	"},																			
"	306	":{"character":"	はい	","letter": "	Yes?	", "pinyin":"	はい	"},																			
"	307	":{"character":"	あたしがペン美よ	","letter": "	I'm Penny.	", "pinyin":"	あたしがぺんびよ	"},																			
"	308	":{"character":"	どういうこと？	","letter": "	What do you mean?	", "pinyin":"	どういうこと？	"},																			
"	309	":{"character":"	いやどういう事なんだろ	","letter": "	I don't know. I don't know what's going on.	", "pinyin":"	いやどういうことなんだろ	"},																			
"	310	":{"character":"	どういうこと？	","letter": "	What do you mean?	", "pinyin":"	どういうこと？	"},																			
"	311	":{"character":"	ペペン美ちゃん	","letter": "	Pepenmei.	", "pinyin":"	ぺぺんみちゃん	"},																			
"	312	":{"character":"	ペペン乃ちゃん	","letter": "	Pepenno-chan.	", "pinyin":"	ぺぺんのちゃん	"},																			
"	313	":{"character":"	やめてあいたい	","letter": "	Stop, I want to see you	", "pinyin":"	やめてあいたい	"},																			
"	314	":{"character":"	ペン美ちゃんペン美ちゃん助けて	","letter": "	Pepenmei-chan, Pepenmei-chan, help me	", "pinyin":"	ぺんみちゃんぺんみちゃんたすけて	"},																			
"	315	":{"character":"	まさか七人いるなんて思わなかった	","letter": "	I didn't think there were seven of you	", "pinyin":"	まさかななにんいるなんておもわなかった	"},																			
"	316	":{"character":"	毎日違う子に告白してたなんて	","letter": "	I can't believe I confessed to a different girl every day	", "pinyin":"	まいにちちがうこにこくはくしてたなんて	"},																			
"	317	":{"character":"	パン屋さんのシフトのせいだ	","letter": "	It's because of my shift at the bakery	", "pinyin":"	ぱんやさんのしふとのせいだ	"},																			
"	318	":{"character":"	シフト目	","letter": "	Shift one.	", "pinyin":"	しふとめ	"},																			
"	319	":{"character":"	行くよ	","letter": "	Let's go.	", "pinyin":"	いくよ	"},																			
"	320	":{"character":"	もう	","letter": "	Oh, God.	", "pinyin":"	もう	"},																			
"	321	":{"character":"	気配がするんだよ	","letter": "	I can feel it.	", "pinyin":"	けはいがするんだよ	"},																			
"	322	":{"character":"	じゃ	","letter": "	Bye.	", "pinyin":"	じゃ	"},																			
"	323	":{"character":"	ペンギンさん告白できてよかったね	","letter": "	I'm glad you confessed, Penguin.	", "pinyin":"	ぺんぎんさんこくはくできてよかったね	"},																			
"	324	":{"character":"	これで良かったんですかね	","letter": "	I hope that's all right.	", "pinyin":"	これでよかったんですかね	"},																			
"	325	":{"character":"	笹子さんは毎日毎日しつこくノロケ話を聞かされるのってどうなの	","letter": "	What about Sasago-san, who has to listen to your constant flirting day in and day out?	", "pinyin":"	ささごさんはまいにちまいにちしつこくのろけはなしをきかされるのってどうなの	"},																			
"	326	":{"character":"	さあー	","letter": "	Come on...	", "pinyin":"	さあー	"},																			
"	327	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguin! Penguin!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	328	":{"character":"	何パンダ君	","letter": "	What's up, Panda?	", "pinyin":"	なにぱんだくん	"},																			
"	329	":{"character":"	なんか落ち着かないね	","letter": "	You don't seem at ease.	", "pinyin":"	なんかおちつかないね	"},																			
"	330	":{"character":"	そう？	","letter": "	Really?	", "pinyin":"	そう？	"},																			
"	331	":{"character":"	ペンギンさんに何か不吉なことが起きなければいいけど	","letter": "	I hope nothing bad happens to Mr. Penguin.	", "pinyin":"	ぺんぎんさんになにかふきつなことがおきなければいいけど	"},																			
"	332	":{"character":"	僕限定	","letter": "	I'm limited.	", "pinyin":"	ぼくげんてい	"},																			
"	333	":{"character":"	もしかしてペンギンさんプチじゃない整形した	","letter": "	Maybe you're not a petite penguin, maybe you've had plastic surgery.	", "pinyin":"	もしかしてぺんぎんさんぷちじゃないせいけいした	"},																			
"	334	":{"character":"	してませんけどなんか落ち着かないね	","letter": "	No, I haven't, but I'm still a little uncomfortable.	", "pinyin":"	してませんけどなんかおちつかないね	"},																			
"	335	":{"character":"	白熊君終わろ	","letter": "	Polar Bear, finish up!	", "pinyin":"	しろくまくんおわろ	"},																			
"	336	":{"character":"	来週のしろくまカフェは	","letter": "	Next week at the Shirokuma Cafe	", "pinyin":"	らいしゅうのしろくまかふぇは	"},																			
"	337	":{"character":"	50倍でお送りします	","letter": "	We'll be back with 50 times more!	", "pinyin":"	50ばいでおおくりします	"},																			
"	338	":{"character":"	何が何が50倍なの	","letter": "	What's 50 times more?	", "pinyin":"	なにがなにが50ばいなの	"},																			
"	339	":{"character":"	笹子さん終わって	","letter": "	Sasago, finish up.	", "pinyin":"	ささごさんおわって	"},																			
"	340	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}