obj = {
"	1	":{"character":"	パンダくんヒマに困る	","letter": "	Panda, I'm having a hard time.	", "pinyin":"	ぱんだくんひまにこまる	"},																			
"	2	":{"character":"	どうしたの?パンダくん	","letter": "	What's the matter, panda? Panda.	", "pinyin":"	どうしたの?ぱんだくん	"},																			
"	3	":{"character":"	バイト行きたくないよ	","letter": "	I don't want to work.	", "pinyin":"	ばいといきたくないよ	"},																			
"	4	":{"character":"	梅雨に入ってからお客さんが少なくてさ	","letter": "	We haven't had many customers since the rainy season started.	", "pinyin":"	つゆにはいってからおきゃくさんがすくなくてさ	"},																			
"	5	":{"character":"	ヒマでヒマで超退屈なんだ	","letter": "	I'm bored out of my mind. I'm bored out of my mind.	", "pinyin":"	ひまでひまでちょうたいくつなんだ	"},																			
"	6	":{"character":"	贅沢だな	","letter": "	That's extravagant.	", "pinyin":"	ぜいたくだな	"},																			
"	7	":{"character":"	どうせゴロゴロしてるだけでしょ	","letter": "	You're just sitting around.	", "pinyin":"	どうせごろごろしてるだけでしょ	"},																			
"	8	":{"character":"	ヒマすぎるってつらいんだよ	","letter": "	It's hard to be too bored.	", "pinyin":"	ひますぎるってつらいんだよ	"},																			
"	9	":{"character":"	それに僕は仕事でゴロゴロしてるの	","letter": "	Besides, I'm just moping around at work.	", "pinyin":"	それにぼくはしごとでごろごろしてるの	"},																			
"	10	":{"character":"	ただのゴロゴロとは違うんだから	","letter": "	It's not the same as just moping around.	", "pinyin":"	ただのごろごろとはちがうんだから	"},																			
"	11	":{"character":"	意味がわからないよ	","letter": "	I don't understand.	", "pinyin":"	いみがわからないよ	"},																			
"	12	":{"character":"	僕もヒマになってゴロゴロしてみたいね	","letter": "	I'd love to have some free time to just hang out.	", "pinyin":"	ぼくもひまになってごろごろしてみたいね	"},																			
"	13	":{"character":"	ゆっくりオヤツ食べても	","letter": "	I'd like to be able to eat my snacks slowly.	", "pinyin":"	ゆっくりおやつたべても	"},																			
"	14	":{"character":"	１時間しか経ってなかったりするんだよ	","letter": "	I'm sometimes only gone an hour.	", "pinyin":"	１じかんしかたってなかったりするんだよ	"},																			
"	15	":{"character":"	オヤツに１時間ってまるでセレブなマダムだね	","letter": "	An hour for a snack? You're like a celebrity.	", "pinyin":"	おやつに１じかんってまるでせれぶなまだむだね	"},																			
"	16	":{"character":"	コラ!何してるんですか	","letter": "	Hey! What are you doing?	", "pinyin":"	こら!なにしてるんですか	"},																			
"	17	":{"character":"	だってお客さんいなくてヒマなんだもん	","letter": "	I don't have any customers.	", "pinyin":"	だっておきゃくさんいなくてひまなんだもん	"},																			
"	18	":{"character":"	もう...ちゃぶ台なんか持ち込んで	","letter": "	Oh, no... You brought in a tea table.	", "pinyin":"	もう...ちゃぶだいなんかもちこんで	"},																			
"	19	":{"character":"	いやぁ気づかれないように持ち込むのが大変で大変で	","letter": "	It's so hard to bring it in without them noticing.	", "pinyin":"	いやぁきづかれないようにもちこむのがたいへんでたいへんで	"},																			
"	20	":{"character":"	持ち込んじゃいけません!	","letter": "	You can't bring it in!	", "pinyin":"	もちこんじゃいけません!	"},																			
"	21	":{"character":"	まぁまぁ落ち着いて	","letter": "	Calm down.	", "pinyin":"	まぁまぁおちついて	"},																			
"	22	":{"character":"	健康にいい熊笹茶でも一杯どう?	","letter": "	How about a cup of Kumazasa tea?	", "pinyin":"	けんこうにいいくまざさちゃでもいっぱいどう?	"},																			
"	23	":{"character":"	えっ?熊笹茶?	","letter": "	What? Kumazasa tea?	", "pinyin":"	えっ?くまざさちゃ?	"},																			
"	24	":{"character":"	熊笹茶に含まれる笹多糖体には	","letter": "	The bamboo polysaccharides in kumazasa tea	", "pinyin":"	くまざさちゃにふくまれるささたとうからだには	"},																			
"	25	":{"character":"	ダイエット効果もあるしね	","letter": "	It's also good for weight loss.	", "pinyin":"	だいえっとこうかもあるしね	"},																			
"	26	":{"character":"	ホント?	","letter": "	Really?	", "pinyin":"	ほんと?	"},																			
"	27	":{"character":"	いや最近メタボ気味でさ	","letter": "	No, I've been feeling a little metabolic lately.	", "pinyin":"	いやさいきんめたぼぎみでさ	"},																			
"	28	":{"character":"	さっさと片付けなさ～い!	","letter": "	Get it over with!	", "pinyin":"	さっさとかたづけなさ～い!	"},																			
"	29	":{"character":"	今何時?	","letter": "	What time is it?	", "pinyin":"	いまなんじ?	"},																			
"	30	":{"character":"	寝てたの?う～んとね	","letter": "	Were you sleeping? I don't know.	", "pinyin":"	ねてたの?う～んとね	"},																			
"	31	":{"character":"	まだ１０時だね	","letter": "	It's only 10:00.	", "pinyin":"	まだ１０じだね	"},																			
"	32	":{"character":"	まだたったの３０分しか経ってないの?	","letter": "	It's only been half an hour?	", "pinyin":"	まだたったの３０ぷんしかたってないの?	"},																			
"	33	":{"character":"	夢の中ではアイドル歌手としてＣＤデビューして	","letter": "	In my dream, I debuted as an idol singer.	", "pinyin":"	ゆめのなかではあいどるかしゅとしてＣＤでびゅーして	"},																			
"	34	":{"character":"	年末にはヤマアラシさんと年越しカウントダウンライブまでしたのに	","letter": "	And at the end of the year, I even did a countdown live with Porcupine.	", "pinyin":"	ねんまつにはやまあらしさんととしこしかうんとだうんらいぶまでしたのに	"},																			
"	35	":{"character":"	よくそんな都合のいい夢が見られるもんだね	","letter": "	How can you have such a convenient dream?	", "pinyin":"	よくそんなつごうのいいゆめがみられるもんだね	"},																			
"	36	":{"character":"	でヤマアラシって誰?	","letter": "	So who's Porcupine?	", "pinyin":"	でやまあらしってだれ?	"},																			
"	37	":{"character":"	えっ!?あの国民的アイドルグループを知らないの?	","letter": "	What? You don't know that national idol group?	", "pinyin":"	えっ!?あのこくみんてきあいどるぐるーぷをしらないの?	"},																			
"	38	":{"character":"	一般常識だよ	","letter": "	It's common knowledge.	", "pinyin":"	いっぱんじょうしきだよ	"},																			
"	39	":{"character":"	グサっときた	","letter": "	That's a good point.	", "pinyin":"	ぐさっときた	"},																			
"	40	":{"character":"	パンダくんに一般常識って言われて	","letter": "	Panda said it's common knowledge.	", "pinyin":"	ぱんだくんにいっぱんじょうしきっていわれて	"},																			
"	41	":{"character":"	今なんかグサっときた	","letter": "	Now you've just hit me.	", "pinyin":"	いまなんかぐさっときた	"},																			
"	42	":{"character":"	娘さんが２人もいるんでしょ?	","letter": "	You have two daughters, right?	", "pinyin":"	むすめさんが２にんもいるんでしょ?	"},																			
"	43	":{"character":"	ファンじゃないの?	","letter": "	You're not a fan?	", "pinyin":"	ふぁんじゃないの?	"},																			
"	44	":{"character":"	最近あんまり会話がないしね	","letter": "	We don't talk much these days.	", "pinyin":"	さいきんあんまりかいわがないしね	"},																			
"	45	":{"character":"	なんか切なくなってきたから	","letter": "	I'm starting to feel sad.	", "pinyin":"	なんかせつなくなってきたから	"},																			
"	46	":{"character":"	あっち向いてホイでもやろうか	","letter": "	Let's do the 'turn your back on me' thing.	", "pinyin":"	あっちむいてほいでもやろうか	"},																			
"	47	":{"character":"	いいよ	","letter": "	Sure.	", "pinyin":"	いいよ	"},																			
"	48	":{"character":"	ジャンケンポン!	","letter": "	Rock, paper, scissors!	", "pinyin":"	じゃんけんぽん!	"},																			
"	49	":{"character":"	あっち向いてホイ!	","letter": "	Look away, look away!	", "pinyin":"	あっちむいてほい!	"},																			
"	50	":{"character":"	ジャンケンポン!	","letter": "	Rock, paper, scissors!	", "pinyin":"	じゃんけんぽん!	"},																			
"	51	":{"character":"	あっち向いてホイ!	","letter": "	Jankenpon! Go away!	", "pinyin":"	あっちむいてほい!	"},																			
"	52	":{"character":"	ジャンケンポン!	","letter": "	Rock, paper, scissors!	", "pinyin":"	じゃんけんぽん!	"},																			
"	53	":{"character":"	あっち向いてホイ!	","letter": "	Face that way, hoi!	", "pinyin":"	あっちむいてほい!	"},																			
"	54	":{"character":"	ホイ!	","letter": "	Hui!	", "pinyin":"	ほい!	"},																			
"	55	":{"character":"	ホイ!	","letter": "	Hui!	", "pinyin":"	ほい!	"},																			
"	56	":{"character":"	ホイ!	","letter": "	Hui!	", "pinyin":"	ほい!	"},																			
"	57	":{"character":"	もしかして私をバカにしてる?	","letter": "	Are you making fun of me?	", "pinyin":"	もしかしてわたしをばかにしてる?	"},																			
"	58	":{"character":"	さっき寝違えてさ	","letter": "	I think I fell asleep.	", "pinyin":"	さっきねちがえてさ	"},																			
"	59	":{"character":"	右にしか首が回らなくなっちゃったみたい	","letter": "	I think I can only turn my head to the right.	", "pinyin":"	みぎにしかくびがまわらなくなっちゃったみたい	"},																			
"	60	":{"character":"	ねぇ何作ってるの?	","letter": "	What are you making?	", "pinyin":"	ねぇなにつくってるの?	"},																			
"	61	":{"character":"	星銃士ビスマルＡの復刻版だよ	","letter": "	It's a reissue of Bismarck Bismarck A.	", "pinyin":"	ほしじゅうしびすまるＡのふっこくばんだよ	"},																			
"	62	":{"character":"	ふ～ん	","letter": "	Hmmm...	", "pinyin":"	ふ～ん	"},																			
"	63	":{"character":"	ふ～んってうちの奥さんみたいなリアクションしないでよ	","letter": "	Don't react like my wife.	", "pinyin":"	ふ～んってうちのおくさんみたいなりあくしょんしないでよ	"},																			
"	64	":{"character":"	これはねプレミアもので	","letter": "	This one's a premium item.	", "pinyin":"	これはねぷれみあもので	"},																			
"	65	":{"character":"	ネットオークションで落札するのが大変だったんだから	","letter": "	It was very hard to get it on the internet auction.	", "pinyin":"	ねっとおーくしょんでらくさつするのがたいへんだったんだから	"},																			
"	66	":{"character":"	ふ～ん	","letter": "	Hmm?	", "pinyin":"	ふ～ん	"},																			
"	67	":{"character":"	だからふ～んはやめて	","letter": "	So don't 'hmmm' me.	", "pinyin":"	だからふ～んはやめて	"},																			
"	68	":{"character":"	常勤パンダさんがモデラーなんて知らなかったよ	","letter": "	I didn't know you were a modeler.	", "pinyin":"	じょうきんぱんださんがもでらーなんてしらなかったよ	"},																			
"	69	":{"character":"	プラモは男のロマンだからね	","letter": "	Plastic models are a man's dream.	", "pinyin":"	ぷらもはおとこのろまんだからね	"},																			
"	70	":{"character":"	ねぇ私のコレクション見たい?	","letter": "	Hey, do you want to see my collection?	", "pinyin":"	ねぇわたしのこれくしょんみたい?	"},																			
"	71	":{"character":"	えっ!どこにあるの?	","letter": "	What? Where is it?	", "pinyin":"	えっ!どこにあるの?	"},																			
"	72	":{"character":"	家にもたくさんあるんだけど	","letter": "	I have a lot at home.	", "pinyin":"	いえにもたくさんあるんだけど	"},																			
"	73	":{"character":"	狭くなるからって家族に迷惑がられててさ	","letter": "	But my family doesn't like them because they make the house too small.	", "pinyin":"	せまくなるからってかぞくにめいわくがられててさ	"},																			
"	74	":{"character":"	娘さんが２人もいるしね	","letter": "	And you have two daughters.	", "pinyin":"	むすめさんが２にんもいるしね	"},																			
"	75	":{"character":"	実は...	","letter": "	Actually...	", "pinyin":"	じつは...	"},																			
"	76	":{"character":"	えっ!?何?	","letter": "	What? What?	", "pinyin":"	えっ!?なに?	"},																			
"	77	":{"character":"	奥さんのお腹に３人目が...	","letter": "	Your wife is pregnant with baby number three...	", "pinyin":"	おくさんのおなかに３にんめが...	"},																			
"	78	":{"character":"	４人目も入ってるかもね	","letter": "	And a fourth on the way.	", "pinyin":"	４にんめもはいってるかもね	"},																			
"	79	":{"character":"	やめてよ～	","letter": "	Oh, come on!	", "pinyin":"	やめてよ～	"},																			
"	80	":{"character":"	ヒマだね	","letter": "	You're busy.	", "pinyin":"	ひまだね	"},																			
"	81	":{"character":"	はいしろくまカフェです	","letter": "	Hello, Polar Bear Cafe.	", "pinyin":"	はいしろくまかふぇです	"},																			
"	82	":{"character":"	シロクマくん?	","letter": "	Polar bear?	", "pinyin":"	しろくまくん?	"},																			
"	83	":{"character":"	僕今ヒマだからさ	","letter": "	I'm free.	", "pinyin":"	ぼくいまひまだからさ	"},																			
"	84	":{"character":"	しりとりやろうよ	","letter": "	Let's play Shiritori.	", "pinyin":"	しりとりやろうよ	"},																			
"	85	":{"character":"	僕はヒマじゃないんだけど	","letter": "	I'm not busy.	", "pinyin":"	ぼくはひまじゃないんだけど	"},																			
"	86	":{"character":"	じゃありんご!	","letter": "	Apples!	", "pinyin":"	じゃありんご!	"},																			
"	87	":{"character":"	合コン	","letter": "	Let's play.	", "pinyin":"	ごうこん	"},																			
"	88	":{"character":"	はいふれあい動物園です	","letter": "	Yes, it's a petting zoo.	", "pinyin":"	はいふれあいどうぶつえんです	"},																			
"	89	":{"character":"	えっ?パンダがいない?	","letter": "	What? No pandas?	", "pinyin":"	えっ?ぱんだがいない?	"},																			
"	90	":{"character":"	そう言われましてもね...	","letter": "	I'm sorry to hear that, but...	", "pinyin":"	そういわれましてもね...	"},																			
"	91	":{"character":"	パンダだって休みたいときがありますよ	","letter": "	Even pandas need a break sometimes.	", "pinyin":"	ぱんだだってやすみたいときがありますよ	"},																			
"	92	":{"character":"	すみません!すぐ行かせますので...	","letter": "	Excuse me! I'll send someone right over...	", "pinyin":"	すみません!すぐいかせますので...	"},																			
"	93	":{"character":"	ちゃんと仕事しなさい!	","letter": "	I'll have you out of here in a minute...	", "pinyin":"	ちゃんとしごとしなさい!	"},																			
"	94	":{"character":"	かわいい!	","letter": "	You're so cute!	", "pinyin":"	かわいい!	"},																			
"	95	":{"character":"	こっち向いて!	","letter": "	Turn around!	", "pinyin":"	こっちむいて!	"},																			
"	96	":{"character":"	今日のお客さん第１号だからサービスしちゃおう	","letter": "	You're the first customer of the day, so let's serve you.	", "pinyin":"	きょうのおきゃくさんだい１ごうだからさーびすしちゃおう	"},																			
"	97	":{"character":"	サービスサービス!サービスサービス!	","letter": "	Service, service, service! Service, service, service!	", "pinyin":"	さーびすさーびす!さーびすさーびす!	"},																			
"	98	":{"character":"	パンダさんがけいれんしてる!	","letter": "	Panda has a cramp!	", "pinyin":"	ぱんださんがけいれんしてる!	"},																			
"	99	":{"character":"	早く飼育員さんに知らせなきゃ!!	","letter": "	We have to tell the keeper!	", "pinyin":"	はやくしいくいんさんにしらせなきゃ!!	"},																			
"	100	":{"character":"	せつないね...	","letter": "	That's not good...	", "pinyin":"	せつないね...	"},																			
"	101	":{"character":"	あれやろうか	","letter": "	Shall we do that?	", "pinyin":"	あれやろうか	"},																			
"	102	":{"character":"	あれ?	","letter": "	What's that?	", "pinyin":"	あれ?	"},																			
"	103	":{"character":"	半田さん急いでパンダコーナーに来てください	","letter": "	Mr. Handa, please hurry up and come to the panda corner.	", "pinyin":"	はんでんさんいそいでぱんだこーなーにきてください	"},																			
"	104	":{"character":"	なんだ?これ...	","letter": "	What's this? This...	", "pinyin":"	なんだ?これ...	"},																			
"	105	":{"character":"	今度は何やってるんですか?	","letter": "	What are you doing now?	", "pinyin":"	こんどはなにやってるんですか?	"},																			
"	106	":{"character":"	半田さんマージャンできる?	","letter": "	Mr. Handa, can you play Mahjong?	", "pinyin":"	はんでんさんまーじゃんできる?	"},																			
"	107	":{"character":"	できません	","letter": "	No, I don't.	", "pinyin":"	できません	"},																			
"	108	":{"character":"	大丈夫だよ僕もルール知らないから	","letter": "	That's okay, I don't know the rules either.	", "pinyin":"	だいじょうぶだよぼくもるーるしらないから	"},																			
"	109	":{"character":"	雨も降っててお客さんも少ないし	","letter": "	It's raining. Not many customers.	", "pinyin":"	あめもふってておきゃくさんもすくないし	"},																			
"	110	":{"character":"	半田さんもどうせヒマでしょ?	","letter": "	You're not busy, are you, Mr. Handa?	", "pinyin":"	はんでんさんもどうせひまでしょ?	"},																			
"	111	":{"character":"	さっさと片づけなさい!	","letter": "	Get your stuff and get out of here!	", "pinyin":"	さっさとかたづけなさい!	"},																			
"	112	":{"character":"	ありがとうございました	","letter": "	Thank you very much.	", "pinyin":"	ありがとうございました	"},																			
"	113	":{"character":"	それでさヒマでヒマですごくつらかったんだ	","letter": "	I've been so busy, so busy, it's been really hard.	", "pinyin":"	それでさひまでひまですごくつらかったんだ	"},																			
"	114	":{"character":"	まったく共感できないんだけど	","letter": "	I don't know if I can sympathize with you at all.	", "pinyin":"	まったくきょうかんできないんだけど	"},																			
"	115	":{"character":"	今日なんか同じ漫画を３０回も読み返したんだよ	","letter": "	Today I read the same comic 30 times.	", "pinyin":"	きょうなんかおなじまんがを３０かいもよみかえしたんだよ	"},																			
"	116	":{"character":"	カフェモカおかわり	","letter": "	Another cafe mocha!	", "pinyin":"	かふぇもかおかわり	"},																			
"	117	":{"character":"	シロクマくんいいヒマつぶしの方法ってないかな?	","letter": "	Polar bear, do you have any good ways to kill time?	", "pinyin":"	しろくまくんいいひまつぶしのほうほうってないかな?	"},																			
"	118	":{"character":"	ヒマつぶし	","letter": "	How do you kill time?	", "pinyin":"	ひまつぶし	"},																			
"	119	":{"character":"	それはひつまぶし	","letter": "	That's 'tsubamabushi'.	", "pinyin":"	それはひつまぶし	"},																			
"	120	":{"character":"	それはかつおぶし	","letter": "	That's katsuobushi.	", "pinyin":"	それはかつおぶし	"},																			
"	121	":{"character":"	月が...	","letter": "	The moon is...	", "pinyin":"	つきが...	"},																			
"	122	":{"character":"	それは炭坑節	","letter": "	That's Tankobushi	", "pinyin":"	それはたんこうぶし	"},																			
"	123	":{"character":"	シロクマくんってヒマつぶしに困らなそうだよね	","letter": "	Polar bears don't seem to have any trouble killing time.	", "pinyin":"	しろくまくんってひまつぶしにこまらなそうだよね	"},																			
"	124	":{"character":"	笹子さんは?	","letter": "	What about you, Sasago?	", "pinyin":"	ささごさんは?	"},																			
"	125	":{"character":"	私は目的を決めずに自転車で遠出するとかかな	","letter": "	I go on long bike rides with no set goal.	", "pinyin":"	わたしはもくてきをきめずにじてんしゃでとおでするとかかな	"},																			
"	126	":{"character":"	あとは地図を眺めて風景を想像しながらの街歩き	","letter": "	Then I walk around town, looking at a map and imagining the scenery.	", "pinyin":"	あとはちずをながめてふうけいをそうぞうしながらのまちあるき	"},																			
"	127	":{"character":"	みんなは?	","letter": "	What about you?	", "pinyin":"	みんなは?	"},																			
"	128	":{"character":"	プチプチをひたすら潰します	","letter": "	I'll just keep crushing the bits and pieces.	", "pinyin":"	ぷちぷちをひたすらつぶします	"},																			
"	129	":{"character":"	長い...歴史...小説	","letter": "	Long... History... Novels	", "pinyin":"	ながい...れきし...しょうせつ	"},																			
"	130	":{"character":"	黒ベタのジグソーパズルが難しすぎて時間を忘れられますよ	","letter": "	Jigsaw puzzles with solid black are so difficult that you can lose track of time!	", "pinyin":"	くろべたのじぐそーぱずるがむずかしすぎてじかんをわすれられますよ	"},																			
"	131	":{"character":"	みんなうらやましいな	","letter": "	I envy you all.	", "pinyin":"	みんなうらやましいな	"},																			
"	132	":{"character":"	僕なんか１日２０時間は休まないとダメだから	","letter": "	I have to rest 20 hours a day.	", "pinyin":"	ぼくなんか１にち２０じかんはやすまないとだめだから	"},																			
"	133	":{"character":"	起きてる時間が足りなくて困って困って...	","letter": "	I don't have enough time to stay awake...	", "pinyin":"	おきてるじかんがたりなくてこまってこまって...	"},																			
"	134	":{"character":"	僕だって予定表がいっぱいで足りないよ。	","letter": "	I don't have enough time in my schedule either.	", "pinyin":"	ぼくだってよていひょうがいっぱいでたりないよ。	"},																			
"	135	":{"character":"	ほら!	","letter": "	Look!	", "pinyin":"	ほら!	"},																			
"	136	":{"character":"	何?	","letter": "	What?	", "pinyin":"	なに?	"},																			
"	137	":{"character":"	ペン子さんってすごい働き者でね	","letter": "	Penko-san is such a hard worker.	", "pinyin":"	ぺんごさんってすごいはたらきものでね	"},																			
"	138	":{"character":"	毎日会いにいくのが大変でヒマなんかないよ	","letter": "	It's so hard for me to see her every day, I don't have time.	", "pinyin":"	まいにちあいにいくのがたいへんでひまなんかないよ	"},																			
"	139	":{"character":"	それにね...	","letter": "	Besides...	", "pinyin":"	それにね...	"},																			
"	140	":{"character":"	シロクマくん笹をちょうだい	","letter": "	Polar bear, give me some bamboo grass.	", "pinyin":"	しろくまくんささをちょうだい	"},																			
"	141	":{"character":"	聞いてよ!	","letter": "	Listen!	", "pinyin":"	きいてよ!	"},																			
"	142	":{"character":"	それでさペン子さんがサービス券をね...	","letter": "	Penko-san gave me a coupon...	", "pinyin":"	それでさぺんごさんがさーびすけんをね...	"},																			
"	143	":{"character":"	その話はもう何度も聞いたよ	","letter": "	I've heard that story a thousand times.	", "pinyin":"	そのはなしはもうなんどもきいたよ	"},																			
"	144	":{"character":"	まもなく当店は閉店いたします	","letter": "	We'll be closing soon.	", "pinyin":"	まもなくとうてんはへいてんいたします	"},																			
"	145	":{"character":"	何やってるの?	","letter": "	What are you doing?	", "pinyin":"	なにやってるの?	"},																			
"	146	":{"character":"	一度やってみたくて	","letter": "	I just wanted to try it.	", "pinyin":"	いちどやってみたくて	"},																			
"	147	":{"character":"	もう閉店か...	","letter": "	Closed already...	", "pinyin":"	もうへいてんか...	"},																			
"	148	":{"character":"	しろくまカフェにいると時間があっという間に過ぎるな	","letter": "	Time flies when you're in the Polar Bear Cafe.	", "pinyin":"	しろくまかふぇにいるとじかんがあっというまにすぎるな	"},																			
"	149	":{"character":"	あっそうだ!	","letter": "	Oh, yeah!	", "pinyin":"	あっそうだ!	"},																			
"	150	":{"character":"	何?	","letter": "	What is it?	", "pinyin":"	なに?	"},																			
"	151	":{"character":"	半田さん至急パンダコーナーに来てください	","letter": "	Mr. Handa, please come to the Panda Corner immediately.	", "pinyin":"	はんでんさんしきゅうぱんだこーなーにきてください	"},																			
"	152	":{"character":"	なんですかこれは!	","letter": "	What's this?	", "pinyin":"	なんですかこれは!	"},																			
"	153	":{"character":"	半田さんいつもの	","letter": "	Mr. Handa, please bring your usual	", "pinyin":"	はんでんさんいつもの	"},																			
"	154	":{"character":"	半田さんモーニングセット	","letter": "	Mr. Handa, morning set.	", "pinyin":"	はんでんさんもーにんぐせっと	"},																			
"	155	":{"character":"	チョコパフェください	","letter": "	Chocolate parfait, please.	", "pinyin":"	ちょこぱふぇください	"},																			
"	156	":{"character":"	僕はミルフィーユ	","letter": "	I'll have mille-feuille.	", "pinyin":"	ぼくはみるふぃーゆ	"},																			
"	157	":{"character":"	半田さんココア!	","letter": "	Mr. Handa, cocoa!	", "pinyin":"	はんでんさんここあ!	"},																			
"	158	":{"character":"	さっさと片づけなさい!	","letter": "	Clean up your mess!	", "pinyin":"	さっさとかたづけなさい!	"},																			
"	159	":{"character":"	ここはカフェじゃありませ～ん!	","letter": "	This isn't a cafe!	", "pinyin":"	ここはかふぇじゃありませ～ん!	"},																			
"	160	":{"character":"	は～ん～だ...	","letter": "	What~?	", "pinyin":"	は～ん～だ...	"},																			
"	161	":{"character":"	パンダの悩み相談室	","letter": "	Panda's Worry Room	", "pinyin":"	ぱんだのなやみそうだんしつ	"},																			
"	162	":{"character":"	今日も１日雨ですかね	","letter": "	I wonder if it's going to rain all day today too...	", "pinyin":"	きょうも１にちあめですかね	"},																			
"	163	":{"character":"	書けた	","letter": "	I can write!	", "pinyin":"	かけた	"},																			
"	164	":{"character":"	読めるけど書けない漢字	","letter": "	Kanji I can read but can't write	", "pinyin":"	よめるけどかけないかんじ	"},																			
"	165	":{"character":"	ゆう	","letter": "	Yu	", "pinyin":"	ゆう	"},																			
"	166	":{"character":"	うつ	","letter": "	I can't write it.	", "pinyin":"	うつ	"},																			
"	167	":{"character":"	シロクマさんさすがですね	","letter": "	Polar bear, you're the best!	", "pinyin":"	しろくまさんさすがですね	"},																			
"	168	":{"character":"	ホント...雨続きで憂鬱ですよね	","letter": "	It's really... It's been raining a lot, and it's depressing, isn't it?	", "pinyin":"	ほんと...あめつづきでゆううつですよね	"},																			
"	169	":{"character":"	もう...	","letter": "	Oh, no...	", "pinyin":"	もう...	"},																			
"	170	":{"character":"	遅刻しないようにせっかくケータイ渡してあげたのに	","letter": "	I went to the trouble of giving you my cell phone so you wouldn't be late.	", "pinyin":"	ちこくしないようにせっかくけーたいわたしてあげたのに	"},																			
"	171	":{"character":"	半田さ～ん	","letter": "	Handa~!	", "pinyin":"	はんでんさ～ん	"},																			
"	172	":{"character":"	ねぇ半田さ～ん	","letter": "	Hey, Handa~!	", "pinyin":"	ねぇはんでんさ～ん	"},																			
"	173	":{"character":"	半田さ～ん遊ぼう!	","letter": "	Handa~! Let's play!	", "pinyin":"	はんでんさ～んあそぼう!	"},																			
"	174	":{"character":"	先輩あいかわらずモテますね	","letter": "	You're still popular with everyone, aren't you?	", "pinyin":"	せんぱいあいかわらずもてますね	"},																			
"	175	":{"character":"	動物と子供とお年寄りにはモテるんだ	","letter": "	I'm popular with animals, children and the elderly.	", "pinyin":"	どうぶつとこどもとおとしよりにはもてるんだ	"},																			
"	176	":{"character":"	女性にはさっぱりだけどな	","letter": "	I'm not so popular with the ladies, though.	", "pinyin":"	じょせいにはさっぱりだけどな	"},																			
"	177	":{"character":"	彼はパンダ飼育員の半田さん	","letter": "	This is Mr. Handa, a panda keeper.	", "pinyin":"	かれはぱんだしいくいんのはんでんさん	"},																			
"	178	":{"character":"	日夜パンダの世話を頑張っています	","letter": "	He takes care of pandas day and night.	", "pinyin":"	にちやぱんだのせわをがんばっています	"},																			
"	179	":{"character":"	特技は料理	","letter": "	His specialty is cooking.	", "pinyin":"	とくぎはりょうり	"},																			
"	180	":{"character":"	流行りの弁当男子です	","letter": "	He's the new 'bento' guy.	", "pinyin":"	はやりのべんとうだんしです	"},																			
"	181	":{"character":"	ちなみに彼女いる歴０年	","letter": "	He's had a girlfriend for zero years.	", "pinyin":"	ちなみにかのじょいるれき０ねん	"},																			
"	182	":{"character":"	聞こえてるよ	","letter": "	I hear you.	", "pinyin":"	きこえてるよ	"},																			
"	183	":{"character":"	彼女いる歴０年	","letter": "	I've had a girlfriend for zero years.	", "pinyin":"	かのじょいるれき０ねん	"},																			
"	184	":{"character":"	もう!ちゃんとお仕事してください!	","letter": "	Oh, my God! Please do your job!	", "pinyin":"	もう!ちゃんとおしごとしてください!	"},																			
"	185	":{"character":"	パンダくんは今日も遅刻だし...	","letter": "	You're late again today, Mr. Panda.	", "pinyin":"	ぱんだくんはきょうもちこくだし...	"},																			
"	186	":{"character":"	何度もモーニングコールしたのに	","letter": "	I tried to wake him up.	", "pinyin":"	なんどももーにんぐこーるしたのに	"},																			
"	187	":{"character":"	半田さんていい人だよね	","letter": "	Mr. Handa is a nice guy.	", "pinyin":"	はんでんさんていいひとだよね	"},																			
"	188	":{"character":"	パンダのストラップもつけてくれるし	","letter": "	He even put a panda strap on me.	", "pinyin":"	ぱんだのすとらっぷもつけてくれるし	"},																			
"	189	":{"character":"	まぁパンダくんはパンダ好きだしね	","letter": "	Well, you like pandas, don't you?	", "pinyin":"	まぁぱんだくんはぱんだすきだしね	"},																			
"	190	":{"character":"	じゃなくてちゃんとお仕事しなさい	","letter": "	You should get a job.	", "pinyin":"	じゃなくてちゃんとおしごとしなさい	"},																			
"	191	":{"character":"	彼女ができない半田さんのことが	","letter": "	I'm so worried about you, Mr. Handa.	", "pinyin":"	かのじょができないはんでんさんのことが	"},																			
"	192	":{"character":"	心配で心配で仕事にならないんだよ	","letter": "	I can't work because I'm worried about you.	", "pinyin":"	しんぱいでしんぱいでしごとにならないんだよ	"},																			
"	193	":{"character":"	いいわけしないの!	","letter": "	I'm not making excuses!	", "pinyin":"	いいわけしないの!	"},																			
"	194	":{"character":"	だって見てよあれ	","letter": "	Look at that.	", "pinyin":"	だってみてよあれ	"},																			
"	195	":{"character":"	お客さんはカップルばかりだよ	","letter": "	All the customers are couples.	", "pinyin":"	おきゃくさんはかっぷるばかりだよ	"},																			
"	196	":{"character":"	そうだね	","letter": "	Yes, that's right.	", "pinyin":"	そうだね	"},																			
"	197	":{"character":"	相合傘でアツアツだよ	","letter": "	They're all under umbrellas, making love.	", "pinyin":"	あいあいがさであつあつだよ	"},																			
"	198	":{"character":"	雨の日の動物園は穴場のデートスポットだからね	","letter": "	The zoo is a great date spot on a rainy day.	", "pinyin":"	あめのひのどうぶつえんはあなばのでーとすぽっとだからね	"},																			
"	199	":{"character":"	彼女もいないのに	","letter": "	You don't even have a girlfriend.	", "pinyin":"	かのじょもいないのに	"},																			
"	200	":{"character":"	まるでデートの達人のようなセリフだね	","letter": "	You sound like a dating expert.	", "pinyin":"	まるででーとのたつじんのようなせりふだね	"},																			
"	201	":{"character":"	大きなお世話です!	","letter": "	Don't mind me!	", "pinyin":"	おおきなおせわです!	"},																			
"	202	":{"character":"	デートの特集ばかり読んでないで	","letter": "	Don't read all those specials on dating.	", "pinyin":"	でーとのとくしゅうばかりよんでないで	"},																			
"	203	":{"character":"	ちゃんと仕事しなきゃダメだよ	","letter": "	You need to get a job.	", "pinyin":"	ちゃんとしごとしなきゃだめだよ	"},																			
"	204	":{"character":"	そんなの読んでないし	","letter": "	I don't read that stuff.	", "pinyin":"	そんなのよんでないし	"},																			
"	205	":{"character":"	仕事もさぼってないよ	","letter": "	I'm not skipping work.	", "pinyin":"	しごともさぼってないよ	"},																			
"	206	":{"character":"	恋人ができれば	","letter": "	If you had a girlfriend...	", "pinyin":"	こいびとができれば	"},																			
"	207	":{"character":"	仕事に張り合いが出るのに	","letter": "	I'd have more motivation to do my job.	", "pinyin":"	しごとにはりあいがでるのに	"},																			
"	208	":{"character":"	僕にとっては	","letter": "	For me, it's like...	", "pinyin":"	ぼくにとっては	"},																			
"	209	":{"character":"	動物園のみんなが恋人みたいなもんさ	","letter": "	I'd have to be in love with everyone at the zoo.	", "pinyin":"	どうぶつえんのみんながこいびとみたいなもんさ	"},																			
"	210	":{"character":"	そんな清純派アイドルみたいなセリフは	","letter": "	I don't want to hear you talk like an idol.	", "pinyin":"	そんなせいじゅんはあいどるみたいなせりふは	"},																			
"	211	":{"character":"	聞きたくないね	","letter": "	I don't want to hear it.	", "pinyin":"	ききたくないね	"},																			
"	212	":{"character":"	そうだよ私トイレに行きません	","letter": "	I'm not going to the bathroom.	", "pinyin":"	そうだよわたしといれにいきません	"},																			
"	213	":{"character":"	なんてアイドルみたいなセリフは聞きたくないよ	","letter": "	I don't want to hear that kind of idle talk.	", "pinyin":"	なんてあいどるみたいなせりふはききたくないよ	"},																			
"	214	":{"character":"	ホントのアイドルは僕たちのように	","letter": "	The real idols are like us.	", "pinyin":"	ほんとのあいどるはぼくたちのように	"},																			
"	215	":{"character":"	ウンチがレモンの香りなんだよ	","letter": "	Their poop smells like lemon.	", "pinyin":"	うんちがれもんのかおりなんだよ	"},																			
"	216	":{"character":"	パンダくん話がそれてるよ	","letter": "	Panda, you're getting off topic.	", "pinyin":"	ぱんだくんばなしがそれてるよ	"},																			
"	217	":{"character":"	それに半田さんがいくら動物好きでも	","letter": "	Besides, no matter how much Mr. Handa loves animals.	", "pinyin":"	それにはんでんさんがいくらどうぶつすきでも	"},																			
"	218	":{"character":"	動物との結婚生活は難しいと思うよ	","letter": "	I don't think it's easy to be married to an animal.	", "pinyin":"	どうぶつとのけっこんせいかつはむずかしいとおもうよ	"},																			
"	219	":{"character":"	何言ってるの?	","letter": "	What are you talking about?	", "pinyin":"	なにいってるの?	"},																			
"	220	":{"character":"	いい半田さん	","letter": "	Okay, Mr. Handa.	", "pinyin":"	いいはんでんさん	"},																			
"	221	":{"character":"	これからバツ２の常勤パンダさんが	","letter": "	Mr. Panda, a full-time divorced couple...	", "pinyin":"	これからばつ２のじょうきんぱんださんが	"},																			
"	222	":{"character":"	恋愛相談してくれるから	","letter": "	Mr. Panda, a full-time divorcee, will be here to help you with your love life.	", "pinyin":"	れんあいそうだんしてくれるから	"},																			
"	223	":{"character":"	ではお願いします先生	","letter": "	Okay, please, Ms. Handa.	", "pinyin":"	ではおねがいしますせんせい	"},																			
"	224	":{"character":"	私バツ２じゃないんだけど	","letter": "	I'm not a divorcee.	", "pinyin":"	わたしばつ２じゃないんだけど	"},																			
"	225	":{"character":"	じゃあお願いします	","letter": "	Then, please.	", "pinyin":"	じゃあおねがいします	"},																			
"	226	":{"character":"	先生じゃなくて愛の狩人	","letter": "	I'm not a teacher. I'm a love hunter.	", "pinyin":"	せんせいじゃなくてあいのかりうど	"},																			
"	227	":{"character":"	訂正するのはそこじゃないから	","letter": "	That's not what I'm correcting you about.	", "pinyin":"	ていせいするのはそこじゃないから	"},																			
"	228	":{"character":"	っていうか変なキャラづけしないで	","letter": "	I mean, don't make me into something I'm not.	", "pinyin":"	っていうかへんなきゃらづけしないで	"},																			
"	229	":{"character":"	ともかく恋愛相談なんていりません	","letter": "	Anyway, I don't need advice on relationships.	", "pinyin":"	ともかくれんあいそうだんなんていりません	"},																			
"	230	":{"character":"	あんなこと言ってますよ恋愛番長	","letter": "	I'm just saying that you're the love hotshot.	", "pinyin":"	あんなこといってますよれんあいばんちょう	"},																			
"	231	":{"character":"	番長もやめて	","letter": "	And don't be the boss.	", "pinyin":"	ばんちょうもやめて	"},																			
"	232	":{"character":"	でも半田さん	","letter": "	But, Mr. Handa...	", "pinyin":"	でもはんでんさん	"},																			
"	233	":{"character":"	一生彼女できなくてもいいの?	","letter": "	You don't need a girlfriend for the rest of your life?	", "pinyin":"	いっしょうかのじょできなくてもいいの?	"},																			
"	234	":{"character":"	い...一生...	","letter": "	I don't... Forever...	", "pinyin":"	い...いっしょう...	"},																			
"	235	":{"character":"	そうなんだよね	","letter": "	Yes, that's right.	", "pinyin":"	そうなんだよね	"},																			
"	236	":{"character":"	彼女がほしいのはもちろんなんだけど	","letter": "	Of course I want a girlfriend.	", "pinyin":"	かのじょがほしいのはもちろんなんだけど	"},																			
"	237	":{"character":"	もう彼女というかお嫁さんがほしい年頃なんだよね	","letter": "	I'm at the age where I want a girlfriend or even a wife.	", "pinyin":"	もうかのじょというかおよめさんがほしいとしごろなんだよね	"},																			
"	238	":{"character":"	大丈夫だよ	","letter": "	Don't worry.	", "pinyin":"	だいじょうぶだよ	"},																			
"	239	":{"character":"	半田さんいい人だから	","letter": "	Mr. Handa is a good man.	", "pinyin":"	はんでんさんいいひとだから	"},																			
"	240	":{"character":"	パンダくん!	","letter": "	Panda!	", "pinyin":"	ぱんだくん!	"},																			
"	241	":{"character":"	そしていい人で終わっちゃうタイプだね	","letter": "	And you're the type of person who ends up being nice.	", "pinyin":"	そしていいひとでおわっちゃうたいぷだね	"},																			
"	242	":{"character":"	ああどうでもいい人	","letter": "	Yeah, a person who doesn't give a shit.	", "pinyin":"	ああどうでもいいひと	"},																			
"	243	":{"character":"	あごめん	","letter": "	Oh, sorry.	", "pinyin":"	あごめん	"},																			
"	244	":{"character":"	元気出して	","letter": "	Cheer up.	", "pinyin":"	げんきだして	"},																			
"	245	":{"character":"	半田さんのよさをわかってくれる女の子がきっといるよ	","letter": "	I'm sure there's a girl out there who understands your qualities.	", "pinyin":"	はんでんさんのよさをわかってくれるおんなのこがきっといるよ	"},																			
"	246	":{"character":"	そそうかな	","letter": "	I doubt it.	", "pinyin":"	そそうかな	"},																			
"	247	":{"character":"	いるよ	","letter": "	Yes, there is.	", "pinyin":"	いるよ	"},																			
"	248	":{"character":"	宇宙に１人くらいは	","letter": "	There's at least one girl in the universe.	", "pinyin":"	うちゅうに１にんくらいは	"},																			
"	249	":{"character":"	宇宙に１人だけ...	","letter": "	Just one in the universe...	", "pinyin":"	うちゅうに１にんだけ...	"},																			
"	250	":{"character":"	１人いれば十分じゃない	","letter": "	One is not enough.	", "pinyin":"	１にんいればじゅうぶんじゃない	"},																			
"	251	":{"character":"	たった１人の運命の人	","letter": "	Just one person in the universe.	", "pinyin":"	たった１にんのうんめいのひと	"},																			
"	252	":{"character":"	その人と出会えれば	","letter": "	And if you meet that person...	", "pinyin":"	そのひととであえれば	"},																			
"	253	":{"character":"	それだけで幸運でしょ	","letter": "	That's how lucky you are.	", "pinyin":"	それだけでこううんでしょ	"},																			
"	254	":{"character":"	常勤パンダさん	","letter": "	Hey, Panda.	", "pinyin":"	じょうきんぱんださん	"},																			
"	255	":{"character":"	だからほら元気出しなよ	","letter": "	So, come on, cheer up.	", "pinyin":"	だからほらげんきだしなよ	"},																			
"	256	":{"character":"	僕たちがついてるよ	","letter": "	We're here for you.	", "pinyin":"	ぼくたちがついてるよ	"},																			
"	257	":{"character":"	半田さん	","letter": "	Mr. Handa.	", "pinyin":"	はんでんさん	"},																			
"	258	":{"character":"	パンダになぐさめられてていいんすか	","letter": "	You don't need a panda to comfort you, do you?	", "pinyin":"	ぱんだになぐさめられてていいんすか	"},																			
"	259	":{"character":"	パンダくんほらもっと食べなよ	","letter": "	Come on, panda, eat more food.	", "pinyin":"	ぱんだくんほらもっとたべなよ	"},																			
"	260	":{"character":"	もういいよ	","letter": "	I've had enough.	", "pinyin":"	もういいよ	"},																			
"	261	":{"character":"	じゃあシロクマくん	","letter": "	Okay, Polar Bear.	", "pinyin":"	じゃあしろくまくん	"},																			
"	262	":{"character":"	僕も	","letter": "	Me too.	", "pinyin":"	ぼくも	"},																			
"	263	":{"character":"	じゃあ...	","letter": "	Okay, then...	", "pinyin":"	じゃあ...	"},																			
"	264	":{"character":"	もういいです	","letter": "	That's enough.	", "pinyin":"	もういいです	"},																			
"	265	":{"character":"	ペンギンさんの買ってくるパンの食べ過ぎで	","letter": "	I've been eating too much bread from Penguin.	", "pinyin":"	ぺんぎんさんのかってくるぱんのたべすぎで	"},																			
"	266	":{"character":"	また太っちゃったよ	","letter": "	I've gained weight again.	", "pinyin":"	またふとっちゃったよ	"},																			
"	267	":{"character":"	何言ってるの?	","letter": "	What are you talking about?	", "pinyin":"	なにいってるの?	"},																			
"	268	":{"character":"	もっと食べて	","letter": "	You need to eat more.	", "pinyin":"	もっとたべて	"},																			
"	269	":{"character":"	だって...	","letter": "	I'm just saying...	", "pinyin":"	だって...	"},																			
"	270	":{"character":"	ほら!	","letter": "	Look!	", "pinyin":"	ほら!	"},																			
"	271	":{"character":"	またペン子さんにサービス券をサービスしてもらっちゃったんだ!	","letter": "	Penko gave me a service ticket again!	", "pinyin":"	またぺんごさんにさーびすけんをさーびすしてもらっちゃったんだ!	"},																			
"	272	":{"character":"	これが握手券だったらもっと嬉しいんだけどな...	","letter": "	I'd be more than happy if it was a handshake ticket...	", "pinyin":"	これがあくしゅけんだったらもっとうれしいんだけどな...	"},																			
"	273	":{"character":"	ウヒヒヒヒ...	","letter": "	Uhuhihihihihihi...	", "pinyin":"	うひひひひ...	"},																			
"	274	":{"character":"	ウヒヒって...	","letter": "	Whoo-hee-hee...	", "pinyin":"	うひひって...	"},																			
"	275	":{"character":"	そんな下品な笑い方してるとペン子さんに嫌われますよ	","letter": "	Penko-san won't like you if you laugh like that.	", "pinyin":"	そんなげひんなわらいかたしてるとぺんごさんにきらわれますよ	"},																			
"	276	":{"character":"	失礼な!!僕ウヒヒ...なんて笑い方してないよ!	","letter": "	That's rude! I'm not laughing... I'm not laughing like that!	", "pinyin":"	しつれいな!!ぼくうひひ...なんてわらいかたしてないよ!	"},																			
"	277	":{"character":"	そうだよウヒヒ...なんてしてないよ	","letter": "	That's right... I didn't.	", "pinyin":"	そうだようひひ...なんてしてないよ	"},																			
"	278	":{"character":"	だよね?	","letter": "	Right?	", "pinyin":"	だよね?	"},																			
"	279	":{"character":"	グヒヒ...だよ	","letter": "	I'm not a... I didn't say...	", "pinyin":"	ぐひひ...だよ	"},																			
"	280	":{"character":"	言ってないから...	","letter": "	I didn't say that...	", "pinyin":"	いってないから...	"},																			
"	281	":{"character":"	先輩この間のコンパの子たちが	","letter": "	The girls from the party last time...	", "pinyin":"	せんぱいこのあいだのこんぱのこたちが	"},																			
"	282	":{"character":"	また半田さんと飲みたいって言ってましたよ	","letter": "	They said they want to have drinks with you again.	", "pinyin":"	またはんでんさんとのみたいっていってましたよ	"},																			
"	283	":{"character":"	またセッティングしましょうか?	","letter": "	Shall I set it up again?	", "pinyin":"	またせってぃんぐしましょうか?	"},																			
"	284	":{"character":"	うん...	","letter": "	Yeah...	", "pinyin":"	うん...	"},																			
"	285	":{"character":"	まあそのうちな	","letter": "	Maybe some other time.	", "pinyin":"	まあそのうちな	"},																			
"	286	":{"character":"	はいわかりました	","letter": "	Okay, I'll do that.	", "pinyin":"	はいわかりました	"},																			
"	287	":{"character":"	じゃあお先に失礼します	","letter": "	I'll leave you to it.	", "pinyin":"	じゃあおさきにしつれいします	"},																			
"	288	":{"character":"	ああお疲れさま	","letter": "	Okay. Thanks for coming.	", "pinyin":"	ああおつかれさま	"},																			
"	289	":{"character":"	雨ちょっと強いから気をつけてな	","letter": "	It's raining a little hard, so be careful.	", "pinyin":"	あめちょっとつよいからきをつけてな	"},																			
"	290	":{"character":"	はい先輩もほどほどにして帰ってくださいね	","letter": "	You go home in moderation, too.	", "pinyin":"	はいせんぱいもほどほどにしてかえってくださいね	"},																			
"	291	":{"character":"	わかってるよ	","letter": "	I know, I know.	", "pinyin":"	わかってるよ	"},																			
"	292	":{"character":"	半田さんに借りたケータイ忘れちゃった	","letter": "	I forgot the cell phone I borrowed from Mr. Handa.	", "pinyin":"	はんでんさんにかりたけーたいわすれちゃった	"},																			
"	293	":{"character":"	今しろくまカフェにいるから	","letter": "	I'm at the Shirokuma Cafe.	", "pinyin":"	いましろくまかふぇにいるから	"},																			
"	294	":{"character":"	帰りに届けてくれない?	","letter": "	Can you deliver it to me on your way home?	", "pinyin":"	かえりにとどけてくれない?	"},																			
"	295	":{"character":"	もう...パンダくんってば...	","letter": "	Oh my God... What a panda.	", "pinyin":"	もう...ぱんだくんってば...	"},																			
"	296	":{"character":"	いらっしゃいませ	","letter": "	Welcome to the cafe.	", "pinyin":"	いらっしゃいませ	"},																			
"	297	":{"character":"	大変でしたね	","letter": "	I'm sorry to hear about your troubles.	", "pinyin":"	たいへんでしたね	"},																			
"	298	":{"character":"	カッパお預かりします	","letter": "	I'll take your kappa.	", "pinyin":"	かっぱおあずかりします	"},																			
"	299	":{"character":"	ああ...どうも	","letter": "	Oh... Hello, sir.	", "pinyin":"	ああ...どうも	"},																			
"	300	":{"character":"	はい	","letter": "	Here you go.	", "pinyin":"	はい	"},																			
"	301	":{"character":"	今度から忘れないでよ	","letter": "	Don't forget it next time.	", "pinyin":"	こんどからわすれないでよ	"},																			
"	302	":{"character":"	ありがとう	","letter": "	Thank you.	", "pinyin":"	ありがとう	"},																			
"	303	":{"character":"	半田さんってホントいい人だよね	","letter": "	You're a really nice guy, Mr. Handa.	", "pinyin":"	はんでんさんってほんといいひとだよね	"},																			
"	304	":{"character":"	もう...	","letter": "	Can I...	", "pinyin":"	もう...	"},																			
"	305	":{"character":"	少し休ませてもらってもいいですか?	","letter": "	Can I take a break?	", "pinyin":"	すこしやすませてもらってもいいですか?	"},																			
"	306	":{"character":"	どうぞ	","letter": "	Go ahead.	", "pinyin":"	どうぞ	"},																			
"	307	":{"character":"	でペン子さんがさ...	","letter": "	And Penko-san...	", "pinyin":"	でぺんごさんがさ...	"},																			
"	308	":{"character":"	それさっきも聞いたよ	","letter": "	I heard that earlier too.	", "pinyin":"	それさっきもきいたよ	"},																			
"	309	":{"character":"	恋は動物の目を曇らせるんですかね	","letter": "	Love blinds animals, huh?	", "pinyin":"	こいはどうぶつのめをくもらせるんですかね	"},																			
"	310	":{"character":"	いいじゃない聞いてよ	","letter": "	That's fine, just listen.	", "pinyin":"	いいじゃないきいてよ	"},																			
"	311	":{"character":"	お目覚めですか?	","letter": "	Are you awake?	", "pinyin":"	おめざめですか?	"},																			
"	312	":{"character":"	すみませんついウトウトしちゃって	","letter": "	I'm sorry, I just fell asleep.	", "pinyin":"	すみませんついうとうとしちゃって	"},																			
"	313	":{"character":"	お気になさらずに	","letter": "	Don't worry about it.	", "pinyin":"	おきになさらずに	"},																			
"	314	":{"character":"	これ店長からのサービスです	","letter": "	This is for you from the manager.	", "pinyin":"	これてんちょうからのさーびすです	"},																			
"	315	":{"character":"	あったかい	","letter": "	It's warm.	", "pinyin":"	あったかい	"},																			
"	316	":{"character":"	雨に濡れた緑が鮮やかで	","letter": "	The rain soaked greens are so bright.	", "pinyin":"	あめにぬれたみどりがあざやかで	"},																			
"	317	":{"character":"	ホントきれいですよね	","letter": "	It's really beautiful, isn't it?	", "pinyin":"	ほんときれいですよね	"},																			
"	318	":{"character":"	はい	","letter": "	Penguins!	", "pinyin":"	はい	"},																			
"	319	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguins!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	320	":{"character":"	何?パンダ君	","letter": "	What? Panda.	", "pinyin":"	なに?ぱんだくん	"},																			
"	321	":{"character":"	僕の可愛いところを500個言って	","letter": "	Tell me 500 pretty things about me.	", "pinyin":"	ぼくのかわいいところを500こいって	"},																			
"	322	":{"character":"	ハードなお願いだなぁ	","letter": "	That's a tough request.	", "pinyin":"	はーどなおねがいだなぁ	"},																			
"	323	":{"character":"	じゃあ499個でいいや	","letter": "	I'll settle for 499.	", "pinyin":"	じゃあ499こでいいや	"},																			
"	324	":{"character":"	君妥協を知らないパンダだね	","letter": "	You are an uncompromising panda.	", "pinyin":"	きみだきょうをしらないぱんだだね	"},																			
"	325	":{"character":"	ありがとう	","letter": "	Thank you.	", "pinyin":"	ありがとう	"},																			
"	326	":{"character":"	じゃあ僕の可愛いところを	","letter": "	Now, tell me what's cute about me.	", "pinyin":"	じゃあぼくのかわいいところを	"},																			
"	327	":{"character":"	白熊君終わって	","letter": "	Polar Bear, you're done.	", "pinyin":"	しろくまくんおわって	"},																			
"	328	":{"character":"	次回のしろくまカフェは	","letter": "	The next Shirokuma Cafe...	", "pinyin":"	じかいのしろくまかふぇは	"},																			
"	329	":{"character":"	ご覧の放送局以外でお送りします	","letter": "	We'll be showing it on a station other than the one you're watching.	", "pinyin":"	ごらんのほうそうきょくいがいでおおくりします	"},																			
"	330	":{"character":"	ご覧の放送局で見れますよ	","letter": "	You can watch it on the station you're watching.	", "pinyin":"	ごらんのほうそうきょくでみれますよ	"},																			
"	331	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																				
}