obj = {
"	1	":{"character":"	半田さんの合コン？	","letter": "	Mr. Handa's blind date?	", "pinyin":"	はんでんさんのごうこん？	"},																			
"	2	":{"character":"	すみませんでした	","letter": "	I'm sorry.	", "pinyin":"	すみませんでした	"},																			
"	3	":{"character":"	どうしたの？	","letter": "	What's wrong?	", "pinyin":"	どうしたの？	"},																			
"	4	":{"character":"	いつものって頼んだらさ	","letter": "	I asked for the usual.	", "pinyin":"	いつものってたのんだらさ	"},																			
"	5	":{"character":"	餃子が出てきたんだよ	","letter": "	They brought out dumplings.	", "pinyin":"	ぎょーざがでてきたんだよ	"},																			
"	6	":{"character":"	僕カフェで餃子頼んだことあった？	","letter": "	Have I ever ordered gyoza at a cafe?	", "pinyin":"	ぼくかふぇでぎょーざたのんだことあった？	"},																			
"	7	":{"character":"	ありませんでしたっけ？	","letter": "	Didn't I?	", "pinyin":"	ありませんでしたっけ？	"},																			
"	8	":{"character":"	ないでしょ	","letter": "	No, you haven't.	", "pinyin":"	ないでしょ	"},																			
"	9	":{"character":"	餃子…メニューにないでしょ	","letter": "	Gyoza... aren't on the menu.	", "pinyin":"	ぎょーざ…めにゅーにないでしょ	"},																			
"	10	":{"character":"	はい…	","letter": "	Yes...	", "pinyin":"	はい…	"},																			
"	11	":{"character":"	わざわざ作ったの？	","letter": "	You made them on purpose?	", "pinyin":"	わざわざつくったの？	"},																			
"	12	":{"character":"	はい	","letter": "	Yes, I did.	", "pinyin":"	はい	"},																			
"	13	":{"character":"	笹子さん偉い！	","letter": "	Great job, Sasako!	", "pinyin":"	ささごさんえらい！	"},																			
"	14	":{"character":"	褒めるところかな？	","letter": "	Is that a compliment?	", "pinyin":"	ほめるところかな？	"},																			
"	15	":{"character":"	おいしいよ	","letter": "	It's delicious.	", "pinyin":"	おいしいよ	"},																			
"	16	":{"character":"	ホントですか？	","letter": "	Really?	", "pinyin":"	ほんとですか？	"},																			
"	17	":{"character":"	喜ぶところかな！？	","letter": "	Is that supposed to make me happy?	", "pinyin":"	よろこぶところかな！？	"},																			
"	18	":{"character":"	まぁいいやいつものくれる？	","letter": "	Well, whatever. Can I have one now?	", "pinyin":"	まぁいいやいつものくれる？	"},																			
"	19	":{"character":"	うん	","letter": "	Yeah, sure.	", "pinyin":"	うん	"},																			
"	20	":{"character":"	何これ	","letter": "	What's this?	", "pinyin":"	なにこれ	"},																			
"	21	":{"character":"	餃子定食	","letter": "	Gyoza set meal.	", "pinyin":"	ぎょーざていしょく	"},																			
"	22	":{"character":"	頼んだことある？	","letter": "	Have you ever ordered it?	", "pinyin":"	たのんだことある？	"},																			
"	23	":{"character":"	ないね	","letter": "	No, I haven't.	", "pinyin":"	ないね	"},																			
"	24	":{"character":"	遊んでる？	","letter": "	Are you playing?	", "pinyin":"	あそんでる？	"},																			
"	25	":{"character":"	うん	","letter": "	Yeah, I am.	", "pinyin":"	うん	"},																			
"	26	":{"character":"	はぁ…疲れた	","letter": "	I'm tired.	", "pinyin":"	はぁ…つかれた	"},																			
"	27	":{"character":"	バイトお疲れ	","letter": "	Good job.	", "pinyin":"	ばいとおつかれ	"},																			
"	28	":{"character":"	いつものちょうだい	","letter": "	Give me the usual.	", "pinyin":"	いつものちょうだい	"},																			
"	29	":{"character":"	いつものね	","letter": "	The usual.	", "pinyin":"	いつものね	"},																			
"	30	":{"character":"	笹子さん餃子定食	","letter": "	Sasago's gyoza set meal.	", "pinyin":"	ささごさんぎょーざていしょく	"},																			
"	31	":{"character":"	はい竹大盛りとアイスコーヒーね	","letter": "	Bamboo and iced coffee, please.	", "pinyin":"	はいたけおおもりとあいすこーひーね	"},																			
"	32	":{"character":"	ねぇねぇ聞いてよ今日ね…	","letter": "	Hey, hey, listen, today...	", "pinyin":"	ねぇねぇきいてよきょうね…	"},																			
"	33	":{"character":"	え～？もうこんな時間？	","letter": "	What? Is it that late already?	", "pinyin":"	え～？もうこんなじかん？	"},																			
"	34	":{"character":"	まだ眠いよもうちょっと寝よう	","letter": "	I'm still sleepy.	", "pinyin":"	まだねむいよもうちょっとねよう	"},																			
"	35	":{"character":"	ちょっと待って！	","letter": "	Wait a minute!	", "pinyin":"	ちょっとまって！	"},																			
"	36	":{"character":"	二度寝の話がしたいの？	","letter": "	You want to talk about going back to sleep?	", "pinyin":"	にどねのはなしがしたいの？	"},																			
"	37	":{"character":"	どっから話そうかなと思って	","letter": "	I'm just trying to figure out where to start.	", "pinyin":"	どっからはなそうかなとおもって	"},																			
"	38	":{"character":"	もうちょっとまとめてから話してくれる？	","letter": "	Can't you just get it together and talk about it first?	", "pinyin":"	もうちょっとまとめてからはなしてくれる？	"},																			
"	39	":{"character":"	ヒマじゃないんだから	","letter": "	I don't have time for this.	", "pinyin":"	ひまじゃないんだから	"},																			
"	40	":{"character":"	うんわかった	","letter": "	Okay.	", "pinyin":"	うんわかった	"},																			
"	41	":{"character":"	桐野君おはよう	","letter": "	Good morning, Kirino.	", "pinyin":"	きりのくんおはよう	"},																			
"	42	":{"character":"	おはようパンダ君	","letter": "	Good morning, Panda.	", "pinyin":"	おはようぱんだくん	"},																			
"	43	":{"character":"	って…早くないよ遅刻だよ？	","letter": "	You're late.	", "pinyin":"	って…はやくないよちこくだよ？	"},																			
"	44	":{"character":"	半田さんのお弁当だ開けてみよう	","letter": "	Handa-san's lunch box.	", "pinyin":"	はんでんさんのおべんとうだあけてみよう	"},																			
"	45	":{"character":"	ダメだよパンダ君	","letter": "	No, Panda-kun.	", "pinyin":"	だめだよぱんだくん	"},																			
"	46	":{"character":"	ちょっと開けるだけだよ	","letter": "	I'm just going to open it.	", "pinyin":"	ちょっとあけるだけだよ	"},																			
"	47	":{"character":"	ダーメ！	","letter": "	Dame!	", "pinyin":"	だーめ！	"},																			
"	48	":{"character":"	ダメだからね	","letter": "	No, no, no, no, no, no, no, no, no, no, no...	", "pinyin":"	だめだからね	"},																			
"	49	":{"character":"	開けるだけだよ	","letter": "	Just open it.	", "pinyin":"	あけるだけだよ	"},																			
"	50	":{"character":"	なんて茶色いお弁当なんだろう	","letter": "	What a brown lunch box!	", "pinyin":"	なんてちゃいろいおべんとうなんだろう	"},																			
"	51	":{"character":"	おばあちゃんのお弁当みたいだ	","letter": "	It looks like my grandma's lunch.	", "pinyin":"	おばあちゃんのおべんとうみたいだ	"},																			
"	52	":{"character":"	ちょっと待って！	","letter": "	Wait a minute!	", "pinyin":"	ちょっとまって！	"},																			
"	53	":{"character":"	お弁当の話がしたいの？	","letter": "	You want to talk about lunch?	", "pinyin":"	おべんとうのはなしがしたいの？	"},																			
"	54	":{"character":"	もうまだ話してる途中なんだから	","letter": "	We're already in the middle of a conversation.	", "pinyin":"	もうまだはなしてるとちゅうなんだから	"},																			
"	55	":{"character":"	頼むよ！ヒマじゃないって言ってるでしょ	","letter": "	Come on! I told you I'm not busy.	", "pinyin":"	たのむよ！ひまじゃないっていってるでしょ	"},																			
"	56	":{"character":"	ヒマでしょ？	","letter": "	You're not busy, are you?	", "pinyin":"	ひまでしょ？	"},																			
"	57	":{"character":"	いつもここにいるじゃない	","letter": "	You're always here.	", "pinyin":"	いつもここにいるじゃない	"},																			
"	58	":{"character":"	ペンギンさんってふだん何してんの？	","letter": "	What do you do, Penguin?	", "pinyin":"	ぺんぎんさんってふだんなにしてんの？	"},																			
"	59	":{"character":"	い…いいから早く本題に入ってよ	","letter": "	Just cut to the chase.	", "pinyin":"	い…いいからはやくほんだいにはいってよ	"},																			
"	60	":{"character":"	わかったよ	","letter": "	Okay, okay.	", "pinyin":"	わかったよ	"},																			
"	61	":{"character":"	パンダ君今日は午後から小学生の団体が来るから	","letter": "	Mr. Panda, we have a group of elementary school kids coming this afternoon.	", "pinyin":"	ぱんだくんきょうはごごからしょうがくせいのだんたいがくるから	"},																			
"	62	":{"character":"	サービスしようね	","letter": "	I'll serve them.	", "pinyin":"	さーびすしようね	"},																			
"	63	":{"character":"	はいいつもより多めにゴロゴロしま～す	","letter": "	Okay, I'll do a little more lollygagging than usual.	", "pinyin":"	はいいつもよりおおめにごろごろしま～す	"},																			
"	64	":{"character":"	ねぇ常勤パンダさん	","letter": "	Hey, full-time panda.	", "pinyin":"	ねぇじょうきんぱんださん	"},																			
"	65	":{"character":"	何？	","letter": "	What's up?	", "pinyin":"	なに？	"},																			
"	66	":{"character":"	今日半田さんのお弁当見ちゃったんだけどね	","letter": "	I saw Mr. Handa's lunch today.	", "pinyin":"	きょうはんでんさんのおべんとうみちゃったんだけどね	"},																			
"	67	":{"character":"	茶色くてさおばあちゃんのお弁当みたいだったよ	","letter": "	It was brown, like my grandma's lunch.	", "pinyin":"	ちゃいろくてさおばあちゃんのおべんとうみたいだったよ	"},																			
"	68	":{"character":"	おいしかったけど	","letter": "	It was delicious.	", "pinyin":"	おいしかったけど	"},																			
"	69	":{"character":"	食べちゃったの？	","letter": "	You ate it?	", "pinyin":"	たべちゃったの？	"},																			
"	70	":{"character":"	うん	","letter": "	Yes, I did.	", "pinyin":"	うん	"},																			
"	71	":{"character":"	食べちゃったの…	","letter": "	You ate it?	", "pinyin":"	たべちゃったの…	"},																			
"	72	":{"character":"	うん！	","letter": "	Yeah!	", "pinyin":"	うん！	"},																			
"	73	":{"character":"	お弁当おいしかったけど何ていうのかな…	","letter": "	The bento was delicious, but I don't know what to call it...	", "pinyin":"	おべんとうおいしかったけどなんていうのかな…	"},																			
"	74	":{"character":"	男が男のために作ったお弁当というか	","letter": "	It's more like a bento that a man made for a man.	", "pinyin":"	おとこがおとこのためにつくったおべんとうというか	"},																			
"	75	":{"character":"	まぁ半田さんが自分のために作った弁当だからね	","letter": "	Well, Mr. Handa made it for himself.	", "pinyin":"	まぁはんでんさんがじぶんのためにつくったべんとうだからね	"},																			
"	76	":{"character":"	というよりおばあちゃんがおばあちゃんのために作ったお弁当というか	","letter": "	It's more like a bento made by a grandmother for a grandmother.	", "pinyin":"	というよりおばあちゃんがおばあちゃんのためにつくったおべんとうというか	"},																			
"	77	":{"character":"	ひと言でいうとモテなさそう	","letter": "	In a word, he doesn't seem to be popular.	", "pinyin":"	ひとことでいうともてなさそう	"},																			
"	78	":{"character":"	モテなさそうなお弁当なんだよね	","letter": "	It's a lunch box that doesn't look popular.	", "pinyin":"	もてなさそうなおべんとうなんだよね	"},																			
"	79	":{"character":"	見たかったなそのモテなさそうな弁当	","letter": "	I wish I could have seen it.	", "pinyin":"	みたかったなそのもてなさそうなべんとう	"},																			
"	80	":{"character":"	聞こえてますよ	","letter": "	I can hear you.	", "pinyin":"	きこえてますよ	"},																			
"	81	":{"character":"	聞こえるように言ったんだよ	","letter": "	I said it so you could hear.	", "pinyin":"	きこえるようにいったんだよ	"},																			
"	82	":{"character":"	半田さん今度そのモテなさそうな弁当私にも見せてよ	","letter": "	Mr. Handa, next time you show me that unattractive-looking bento.	", "pinyin":"	はんでんさんこんどそのもてなさそうなべんとうわたしにもみせてよ	"},																			
"	83	":{"character":"	ちょっと失礼だな	","letter": "	That's a little rude.	", "pinyin":"	ちょっとしつれいだな	"},																			
"	84	":{"character":"	じゃあモテるの？	","letter": "	So you're popular with the ladies?	", "pinyin":"	じゃあもてるの？	"},																			
"	85	":{"character":"	最近女性と喋った？	","letter": "	Have you talked to any women lately?	", "pinyin":"	さいきんじょせいとしゃべった？	"},																			
"	86	":{"character":"	何急に	","letter": "	What? Suddenly?	", "pinyin":"	なにきゅうに	"},																			
"	87	":{"character":"	だから最近女性と喋った？	","letter": "	Have you talked to any women lately?	", "pinyin":"	だからさいきんじょせいとしゃべった？	"},																			
"	88	":{"character":"	お母さん以外だよ	","letter": "	No, not your mother.	", "pinyin":"	おかあさんいがいだよ	"},																			
"	89	":{"character":"	動物以外だよ	","letter": "	No animals.	", "pinyin":"	どうぶついがいだよ	"},																			
"	90	":{"character":"	ほらね	","letter": "	There you go.	", "pinyin":"	ほらね	"},																			
"	91	":{"character":"	おかしいな	","letter": "	That's funny.	", "pinyin":"	おかしいな	"},																			
"	92	":{"character":"	そんなモテない半田さんのために	","letter": "	For Mr. Handa, who's so unattractive.	", "pinyin":"	そんなもてないはんでんさんのために	"},																			
"	93	":{"character":"	僕が桐野くんに頼んでおいたから	","letter": "	I asked Mr. Kirino for you.	", "pinyin":"	ぼくがきりのくんにたのんでおいたから	"},																			
"	94	":{"character":"	え何を	","letter": "	What?	", "pinyin":"	えなにを	"},																			
"	95	":{"character":"	半田さん！	","letter": "	Mr. Handa!	", "pinyin":"	はんでんさん！	"},																			
"	96	":{"character":"	決まりましたよ	","letter": "	It's decided.	", "pinyin":"	きまりましたよ	"},																			
"	97	":{"character":"	何だ？	","letter": "	What's this?	", "pinyin":"	なんだ？	"},																			
"	98	":{"character":"	合コンですよ半田さんがやりたいってパンダくんが	","letter": "	Mr. Handa wants to go to a party with Mr. Panda.	", "pinyin":"	ごうこんですよはんでんさんがやりたいってぱんだくんが	"},																			
"	99	":{"character":"	俺言ってないよ	","letter": "	I didn't say that.	", "pinyin":"	おれいってないよ	"},																			
"	100	":{"character":"	そんなの行かないよ	","letter": "	I'm not going to that party.	", "pinyin":"	そんなのいかないよ	"},																			
"	101	":{"character":"	ちょっと待ってくださいよ	","letter": "	Wait a minute!	", "pinyin":"	ちょっとまってくださいよ	"},																			
"	102	":{"character":"	半田さんのためにセッティングしたんですから	","letter": "	I set this up for Mr. Handa.	", "pinyin":"	はんでんさんのためにせってぃんぐしたんですから	"},																			
"	103	":{"character":"	相手はＯＬさんですよ	","letter": "	It's for an office worker.	", "pinyin":"	あいてはＯＬさんですよ	"},																			
"	104	":{"character":"	俺忙しいから	","letter": "	I'm busy.	", "pinyin":"	おれいそがしいから	"},																			
"	105	":{"character":"	何かあるんですか？	","letter": "	What's going on?	", "pinyin":"	なにかあるんですか？	"},																			
"	106	":{"character":"	帰って風呂の掃除しないと	","letter": "	I have to go home and clean the bathroom.	", "pinyin":"	かえってふろのそうじしないと	"},																			
"	107	":{"character":"	それは忙しいに入りませんよ	","letter": "	That's not part of being busy.	", "pinyin":"	それはいそがしいにはいりませんよ	"},																			
"	108	":{"character":"	行くよね半田さん	","letter": "	You're going, right, Mr. Handa?	", "pinyin":"	いくよねはんでんさん	"},																			
"	109	":{"character":"	桐野くん半田さんをよろしくお願いします	","letter": "	Kirino-san, please take care of Mr. Handa.	", "pinyin":"	きりのくんはんでんさんをよろしくおねがいします	"},																			
"	110	":{"character":"	もう勝手に決めないで	","letter": "	Don't decide on your own.	", "pinyin":"	もうかってにきめないで	"},																			
"	111	":{"character":"	行きましょうよ半田さん	","letter": "	Let's go, Mr. Handa.	", "pinyin":"	いきましょうよはんでんさん	"},																			
"	112	":{"character":"	半田さん！	","letter": "	Mr. Handa!	", "pinyin":"	はんでんさん！	"},																			
"	113	":{"character":"	かわいくてもダメ！	","letter": "	Don't be cute!	", "pinyin":"	かわいくてもだめ！	"},																			
"	114	":{"character":"	桐野くんはねパンダくんに言われて	","letter": "	Kirino... at Panda-kun's insistence.	", "pinyin":"	きりのくんはねぱんだくんにいわれて	"},																			
"	115	":{"character":"	半田さんのためにやったこともない合コンをセッティングしたんだよ	","letter": "	I set up a party for Mr. Handa, something I've never done before.	", "pinyin":"	はんでんさんのためにやったこともないごうこんをせってぃんぐしたんだよ	"},																			
"	116	":{"character":"	ちょっとくらいはやったことありますけど	","letter": "	I've done a little bit of that before.	", "pinyin":"	ちょっとくらいはやったことありますけど	"},																			
"	117	":{"character":"	半田さん行こうよ！	","letter": "	Let's go, Handa-san!	", "pinyin":"	はんでんさんいこうよ！	"},																			
"	118	":{"character":"	もういいよ２人とも	","letter": "	That's enough, you two.	", "pinyin":"	もういいよ２にんとも	"},																			
"	119	":{"character":"	わかりました	","letter": "	Understood.	", "pinyin":"	わかりました	"},																			
"	120	":{"character":"	半田さんがどうしても嫌なら断ります	","letter": "	If Mr. Handa really doesn't want to go, I'll decline.	", "pinyin":"	はんでんさんがどうしてもいやならことわります	"},																			
"	121	":{"character":"	わかった行くよ	","letter": "	Okay, I'll go.	", "pinyin":"	わかったいくよ	"},																			
"	122	":{"character":"	ホントですか！	","letter": "	Really?	", "pinyin":"	ほんとですか！	"},																			
"	123	":{"character":"	よかった	","letter": "	I'm glad.	", "pinyin":"	よかった	"},																			
"	124	":{"character":"	男性チームは僕の友人が来て３対３です	","letter": "	The men's team will be three against three.	", "pinyin":"	だんせいちーむはぼくのゆうじんがきて３たい３です	"},																			
"	125	":{"character":"	じゃあ今晩７時ですから	","letter": "	It's 7:00 p.m. tonight.	", "pinyin":"	じゃあこんばん７じですから	"},																			
"	126	":{"character":"	半田さんＯＬさんにお弁当見せちゃダメだよ	","letter": "	Mr. Handa, don't let the office lady see your lunch.	", "pinyin":"	はんでんさんＯＬさんにおべんとうみせちゃだめだよ	"},																			
"	127	":{"character":"	見せないよ	","letter": "	I won't.	", "pinyin":"	みせないよ	"},																			
"	128	":{"character":"	お疲れ様	","letter": "	Good night.	", "pinyin":"	おつかれさま	"},																			
"	129	":{"character":"	今日合コン頑張ってね	","letter": "	Good luck at the party.	", "pinyin":"	きょうごうこんがんばってね	"},																			
"	130	":{"character":"	シーッ！声が大きいよ	","letter": "	Shh! You're talking too loud.	", "pinyin":"	しーっ！こえがおおきいよ	"},																			
"	131	":{"character":"	ごめんごめん	","letter": "	Sorry. Sorry.	", "pinyin":"	ごめんごめん	"},																			
"	132	":{"character":"	じゃあまた明日	","letter": "	See you tomorrow.	", "pinyin":"	じゃあまたあした	"},																			
"	133	":{"character":"	これで半田さんのお弁当も変わるな	","letter": "	Now Handa's bento will be different.	", "pinyin":"	これではんでんさんのおべんとうもかわるな	"},																			
"	134	":{"character":"	えっウソホントに？	","letter": "	Really?	", "pinyin":"	えっうそほんとに？	"},																			
"	135	":{"character":"	そうかわかった	","letter": "	I see.	", "pinyin":"	そうかわかった	"},																			
"	136	":{"character":"	困ったな	","letter": "	I'm in trouble.	", "pinyin":"	こまったな	"},																			
"	137	":{"character":"	どうしたの？	","letter": "	What's wrong?	", "pinyin":"	どうしたの？	"},																			
"	138	":{"character":"	今日の合コンなんだけど友達が来られなくなっちゃって	","letter": "	My friend can't come to the party today.	", "pinyin":"	きょうのごうこんなんだけどともだちがきられなくなっちゃって	"},																			
"	139	":{"character":"	今からじゃメンバー見つからないよ	","letter": "	We won't be able to find any members.	", "pinyin":"	いまからじゃめんばーみつからないよ	"},																			
"	140	":{"character":"	桐野くん大丈夫だよ	","letter": "	Don't worry, Kirino.	", "pinyin":"	きりのくんだいじょうぶだよ	"},																			
"	141	":{"character":"	僕にあてがあるから	","letter": "	I have an idea.	", "pinyin":"	ぼくにあてがあるから	"},																			
"	142	":{"character":"	ホント？	","letter": "	You sure?	", "pinyin":"	ほんと？	"},																			
"	143	":{"character":"	うん任せておいて	","letter": "	I'll take care of it.	", "pinyin":"	うんまかせておいて	"},																			
"	144	":{"character":"	ありがとうパンダくんありがとう	","letter": "	Thank you, Panda.	", "pinyin":"	ありがとうぱんだくんありがとう	"},																			
"	145	":{"character":"	そういうわけなんだ	","letter": "	That's why...	", "pinyin":"	そういうわけなんだ	"},																			
"	146	":{"character":"	ふ～ん話はわかった	","letter": "	I see what you mean.	", "pinyin":"	ふ～んはなしはわかった	"},																			
"	147	":{"character":"	要するに合コンのメンバーが必要なんだね	","letter": "	So you're saying that you need a couple of people to go to a party with.	", "pinyin":"	ようするにごうこんのめんばーがひつようなんだね	"},																			
"	148	":{"character":"	それでシロクマくんを誘おうと思うんだけどどう思う？	","letter": "	So I'm thinking of asking Mr. Polar bear out.	", "pinyin":"	それでしろくまくんをさそおうとおもうんだけどどうおもう？	"},																			
"	149	":{"character":"	えっ！？僕じゃなくて？	","letter": "	What? Not me?	", "pinyin":"	えっ！？ぼくじゃなくて？	"},																			
"	150	":{"character":"	シロクマくん今日ヒマ？	","letter": "	Are you free today, Polar Bear?	", "pinyin":"	しろくまくんきょうひま？	"},																			
"	151	":{"character":"	今日ヒマ？	","letter": "	Are you free today?	", "pinyin":"	きょうひま？	"},																			
"	152	":{"character":"	僕じゃないんだ…	","letter": "	Not me...	", "pinyin":"	ぼくじゃないんだ…	"},																			
"	153	":{"character":"	僕結構話聞いてたのに	","letter": "	I was listening to you.	", "pinyin":"	ぼくけっこうはなしきいてたのに	"},																			
"	154	":{"character":"	ペンギンさんさっきからヒマじゃないヒマじゃないって…	","letter": "	Penguin, you've been saying you're not busy.	", "pinyin":"	ぺんぎんさんさっきからひまじゃないひまじゃないって…	"},																			
"	155	":{"character":"	いやまあそうだけど…	","letter": "	I'm sure you're right, but...	", "pinyin":"	いやまあそうだけど…	"},																			
"	156	":{"character":"	やりくりすれば合コンに行けないこともないんじゃないかな	","letter": "	I'm sure you could find a way to go to a party.	", "pinyin":"	やりくりすればごうこんにいけないこともないんじゃないかな	"},																			
"	157	":{"character":"	ヒマじゃないんでしょ？	","letter": "	You don't have time, do you?	", "pinyin":"	ひまじゃないんでしょ？	"},																			
"	158	":{"character":"	ああ僕ヒマじゃないからね	","letter": "	No, I'm not busy.	", "pinyin":"	ああぼくひまじゃないからね	"},																			
"	159	":{"character":"	じゃ楽しんでくれば？	","letter": "	Well, why don't you go have some fun?	", "pinyin":"	じゃたのしんでくれば？	"},																			
"	160	":{"character":"	パンダくんにシロクマさん？	","letter": "	Pandas and polar bears?	", "pinyin":"	ぱんだくんにしろくまさん？	"},																			
"	161	":{"character":"	どうして…	","letter": "	How did you...	", "pinyin":"	どうして…	"},																			
"	162	":{"character":"	今日の男性チームです	","letter": "	Here's today's male team.	", "pinyin":"	きょうのだんせいちーむです	"},																			
"	163	":{"character":"	半田さん頑張ろうね	","letter": "	Let's do our best, Mr. Handa.	", "pinyin":"	はんでんさんがんばろうね	"},																			
"	164	":{"character":"	半田さんすみません頑張りましょうね	","letter": "	Mr. Handa, I'm sorry, let's do our best.	", "pinyin":"	はんでんさんすみませんがんばりましょうね	"},																			
"	165	":{"character":"	じゃあ行こうか	","letter": "	Let's go.	", "pinyin":"	じゃあいこうか	"},																			
"	166	":{"character":"	後半へつづく	","letter": "	Continue to the second half	", "pinyin":"	こうはんへつづく	"},																			
"	167	":{"character":"	半田さんの合コン！	","letter": "	Mr. Handa's party!	", "pinyin":"	はんでんさんのごうこん！	"},																			
"	168	":{"character":"	前半からつづく	","letter": "	Continue from the first half	", "pinyin":"	ぜんはんからつづく	"},																			
"	169	":{"character":"	ご注文お決まりですか？	","letter": "	Ready to order?	", "pinyin":"	ごちゅうもんおきまりですか？	"},																			
"	170	":{"character":"	シロクマ！？	","letter": "	Polar bear!	", "pinyin":"	しろくま！？	"},																			
"	171	":{"character":"	そ…それじゃ自己紹介から始めましょうか	","letter": "	Well...let's start with self-introductions, shall we?	", "pinyin":"	そ…それじゃじこしょうかいからはじめましょうか	"},																			
"	172	":{"character":"	僕からいきますね	","letter": "	I'll go first.	", "pinyin":"	ぼくからいきますね	"},																			
"	173	":{"character":"	桐野です	","letter": "	I'm Kirino.	", "pinyin":"	きりのです	"},																			
"	174	":{"character":"	動物園の飼育員をやっています	","letter": "	I'm a zookeeper.	", "pinyin":"	どうぶつえんのしいくいんをやっています	"},																			
"	175	":{"character":"	よろしくお願いします	","letter": "	Pleased to meet you.	", "pinyin":"	よろしくおねがいします	"},																			
"	176	":{"character":"	じゃ次は先輩	","letter": "	Next, senpai...	", "pinyin":"	じゃつぎはせんぱい	"},																			
"	177	":{"character":"	は…は…半田です！	","letter": "	I'm Handa!	", "pinyin":"	は…は…はんでんです！	"},																			
"	178	":{"character":"	本日はこのように晴れがましい合コンにお…お招きいただき	","letter": "	Thank you for inviting me to this very special party today.	", "pinyin":"	ほんじつはこのようにはれがましいごうこんにお…おまねきいただき	"},																			
"	179	":{"character":"	誠にありがとうございます	","letter": "	Thank you very much.	", "pinyin":"	まことにありがとうございます	"},																			
"	180	":{"character":"	ふつつか者ではありますが	","letter": "	I know I'm a bit of a loose cannon.	", "pinyin":"	ふつつかものではありますが	"},																			
"	181	":{"character":"	以後よろしくお見知りおきください	","letter": "	But please do not hesitate to make my acquaintance.	", "pinyin":"	いごよろしくおみしりおきください	"},																			
"	182	":{"character":"	先輩かたい…	","letter": "	You're a senior...	", "pinyin":"	せんぱいかたい…	"},																			
"	183	":{"character":"	そこまで丁寧な自己紹介じゃなくて大丈夫です	","letter": "	You don't have to introduce yourself so politely.	", "pinyin":"	そこまでていねいなじこしょうかいじゃなくてだいじょうぶです	"},																			
"	184	":{"character":"	けど初対面だから	","letter": "	But it's our first meeting.	", "pinyin":"	けどしょたいめんだから	"},																			
"	185	":{"character":"	大丈夫です	","letter": "	I'm fine.	", "pinyin":"	だいじょうぶです	"},																			
"	186	":{"character":"	合コンってそういう感じのものじゃないんで	","letter": "	It's not the kind of thing you do at a blind date.	", "pinyin":"	ごうこんってそういうかんじのものじゃないんで	"},																			
"	187	":{"character":"	続きまして私と同じ職場に勤める	","letter": "	Next, I'd like to introduce you to Mr. Panda, who works at the same place as me.	", "pinyin":"	つづきましてわたしとおなじしょくばにつとめる	"},																			
"	188	":{"character":"	パンダくんを紹介します！	","letter": "	Mr. Panda, who works at the same place as me!	", "pinyin":"	ぱんだくんをしょうかいします！	"},																			
"	189	":{"character":"	だからかたいって…	","letter": "	That's why he's so stiff...	", "pinyin":"	だからかたいって…	"},																			
"	190	":{"character":"	すみませんパンダ連れてきちゃって	","letter": "	I'm sorry for bringing a panda.	", "pinyin":"	すみませんぱんだつれてきちゃって	"},																			
"	191	":{"character":"	パンダで～す	","letter": "	I'm a panda!	", "pinyin":"	ぱんだで～す	"},																			
"	192	":{"character":"	かわいい！！	","letter": "	He's so cute!	", "pinyin":"	かわいい！！	"},																			
"	193	":{"character":"	パンダ意外にウケた…	","letter": "	Panda was surprisingly funny...	", "pinyin":"	ぱんだいがいにうけた…	"},																			
"	194	":{"character":"	では続いて…	","letter": "	Next up...	", "pinyin":"	ではつづいて…	"},																			
"	195	":{"character":"	シロクマですふだんはカフェやってます	","letter": "	This is a polar bear.	", "pinyin":"	しろくまですふだんはかふぇやってます	"},																			
"	196	":{"character":"	すご～い！	","letter": "	Amazing!	", "pinyin":"	すご～い！	"},																			
"	197	":{"character":"	カフェですか？	","letter": "	A cafe?	", "pinyin":"	かふぇですか？	"},																			
"	198	":{"character":"	行ってみたい！	","letter": "	I want to go there!	", "pinyin":"	いってみたい！	"},																			
"	199	":{"character":"	なんてカフェですか？	","letter": "	What kind of cafe?	", "pinyin":"	なんてかふぇですか？	"},																			
"	200	":{"character":"	しろくまカフェ	","letter": "	Polar Bear Cafe.	", "pinyin":"	しろくまかふぇ	"},																			
"	201	":{"character":"	そのまんまなんですね	","letter": "	It's just like that, isn't it?	", "pinyin":"	そのまんまなんですね	"},																			
"	202	":{"character":"	あのもしかして雑誌とかに載ってないですか？	","letter": "	Have you seen it in a magazine or something?	", "pinyin":"	あのもしかしてざっしとかにのってないですか？	"},																			
"	203	":{"character":"	時々	","letter": "	Sometimes.	", "pinyin":"	ときどき	"},																			
"	204	":{"character":"	すごい！見たことある	","letter": "	That's great! I've seen it.	", "pinyin":"	すごい！みたことある	"},																			
"	205	":{"character":"	今度行ってもいいですか？	","letter": "	Can I go there sometime?	", "pinyin":"	こんどいってもいいですか？	"},																			
"	206	":{"character":"	もちろん	","letter": "	Sure.	", "pinyin":"	もちろん	"},																			
"	207	":{"character":"	こっちも大好評だな…	","letter": "	You're a big hit over here, too...	", "pinyin":"	こっちもだいこうひょうだな…	"},																			
"	208	":{"character":"	趣味はアザラシの捕獲	","letter": "	My hobby is catching seals.	", "pinyin":"	しゅみはあざらしのほかく	"},																			
"	209	":{"character":"	何ですか？それ	","letter": "	What's that? That.	", "pinyin":"	なんですか？それ	"},																			
"	210	":{"character":"	今度連れてってください	","letter": "	Please take me out sometime.	", "pinyin":"	こんどつれてってください	"},																			
"	211	":{"character":"	やめたほうがいいよ…	","letter": "	I don't think that's a good idea...	", "pinyin":"	やめたほうがいいよ…	"},																			
"	212	":{"character":"	じゃあ女子いきますね	","letter": "	I'll go with a girl.	", "pinyin":"	じゃあじょしいきますね	"},																			
"	213	":{"character":"	ヒロミで～す	","letter": "	I'm Hiromi.	", "pinyin":"	ひろみで～す	"},																			
"	214	":{"character":"	先輩ヒロミちゃん	","letter": "	Hiromi, my senior.	", "pinyin":"	せんぱいひろみちゃん	"},																			
"	215	":{"character":"	リカです	","letter": "	I'm Rika.	", "pinyin":"	りかです	"},																			
"	216	":{"character":"	リカちゃん	","letter": "	Rika.	", "pinyin":"	りかちゃん	"},																			
"	217	":{"character":"	ミズキです	","letter": "	I'm Mizuki.	", "pinyin":"	みずきです	"},																			
"	218	":{"character":"	ミズキちゃん	","letter": "	Mizuki.	", "pinyin":"	みずきちゃん	"},																			
"	219	":{"character":"	わかってるよ大丈夫聞こえるから	","letter": "	I know, it's okay, I can hear you.	", "pinyin":"	わかってるよだいじょうぶきこえるから	"},																			
"	220	":{"character":"	ご注文どうぞ	","letter": "	What can I get for you?	", "pinyin":"	ごちゅうもんどうぞ	"},																			
"	221	":{"character":"	とりあえず生	","letter": "	Raw for now.	", "pinyin":"	とりあえずなま	"},																			
"	222	":{"character":"	はい	","letter": "	Yes, sir.	", "pinyin":"	はい	"},																			
"	223	":{"character":"	とりあえず竹	","letter": "	Bamboo for now.	", "pinyin":"	とりあえずたけ	"},																			
"	224	":{"character":"	竹？	","letter": "	Bamboo?	", "pinyin":"	たけ？	"},																			
"	225	":{"character":"	ちょっと置いてないんですが…	","letter": "	We don't have any bamboo...	", "pinyin":"	ちょっとおいてないんですが…	"},																			
"	226	":{"character":"	え～っじゃあ笹	","letter": "	Then, bamboo grass...	", "pinyin":"	え～っじゃあささ	"},																			
"	227	":{"character":"	笹もないんですが…	","letter": "	We don't have any bamboo either...	", "pinyin":"	ささもないんですが…	"},																			
"	228	":{"character":"	じゃあみんなどうしてるの？	","letter": "	Then what do people do?	", "pinyin":"	じゃあみんなどうしてるの？	"},																			
"	229	":{"character":"	ビール飲んだり…	","letter": "	Drinking beer...	", "pinyin":"	びーるのんだり…	"},																			
"	230	":{"character":"	枝豆食べたり…	","letter": "	Eat edamame (green soybeans)	", "pinyin":"	えだまめたべたり…	"},																			
"	231	":{"character":"	唐揚げ食べたり…	","letter": "	Eat fried bean curd...	", "pinyin":"	からあげたべたり…	"},																			
"	232	":{"character":"	とりあえずアザラシ	","letter": "	At any rate, seals...	", "pinyin":"	とりあえずあざらし	"},																			
"	233	":{"character":"	ないです	","letter": "	I don't have any.	", "pinyin":"	ないです	"},																			
"	234	":{"character":"	持ち込みは？	","letter": "	You can't bring your own?	", "pinyin":"	もちこみは？	"},																			
"	235	":{"character":"	ダメです	","letter": "	No, you can't.	", "pinyin":"	だめです	"},																			
"	236	":{"character":"	とりあえず生６つとジュース１つでいいです	","letter": "	I'll just have six raw ones and a juice.	", "pinyin":"	とりあえずなま６つとじゅーす１つでいいです	"},																			
"	237	":{"character":"	僕竹がいいよ	","letter": "	I want bamboo.	", "pinyin":"	ぼくたけがいいよ	"},																			
"	238	":{"character":"	そうよねパンダっていったらやっぱり竹よね	","letter": "	I know, right? Pandas are all about the bamboo.	", "pinyin":"	そうよねぱんだっていったらやっぱりたけよね	"},																			
"	239	":{"character":"	食べてるとこ見てみたい	","letter": "	I want to see them eat.	", "pinyin":"	たべてるとこみてみたい	"},																			
"	240	":{"character":"	かわいいかも！	","letter": "	It might be cute!	", "pinyin":"	かわいいかも！	"},																			
"	241	":{"character":"	いや～ん！竹食べて！	","letter": "	No! Eat the bamboo!	", "pinyin":"	いや～ん！たけたべて！	"},																			
"	242	":{"character":"	何なんだ？この合コン…	","letter": "	What's going on? This blind date...	", "pinyin":"	なになんだ？このごうこん…	"},																			
"	243	":{"character":"	いや僕はね合コンに行きたいって言ってるわけじゃないんだよ	","letter": "	I'm not saying I want to go to a party.	", "pinyin":"	いやぼくはねごうこんにいきたいっていってるわけじゃないんだよ	"},																			
"	244	":{"character":"	はい	","letter": "	I'm not saying I want to go to a party.	", "pinyin":"	はい	"},																			
"	245	":{"character":"	ただね僕がずっとパンダくんの話を聞いていたわけだからさ	","letter": "	I've been listening to you for a long time.	", "pinyin":"	ただねぼくがずっとぱんだくんのはなしをきいていたわけだからさ	"},																			
"	246	":{"character":"	誘うなら僕を誘うでしょ？	","letter": "	If you were going to ask me out, you would have asked me out, right?	", "pinyin":"	さそうならぼくをさそうでしょ？	"},																			
"	247	":{"character":"	僕にはペン子さんといペンギンがいるわけだから	","letter": "	I have Penko-san, the penguin.	", "pinyin":"	ぼくにはぺんごさんといぺんぎんがいるわけだから	"},																			
"	248	":{"character":"	別に行きたくはないんだけど社会勉強というか…	","letter": "	I don't really want to go, but it's a social lesson...	", "pinyin":"	べつにいきたくはないんだけどしゃかいべんきょうというか…	"},																			
"	249	":{"character":"	行きたいんですか？	","letter": "	You want to go?	", "pinyin":"	いきたいんですか？	"},																			
"	250	":{"character":"	だから行きたくないよ	","letter": "	That's why I don't want to go.	", "pinyin":"	だからいきたくないよ	"},																			
"	251	":{"character":"	笹子さんも笹子さんでしょ	","letter": "	You're Sasago, right?	", "pinyin":"	ささごさんもささごさんでしょ	"},																			
"	252	":{"character":"	誘うならシロクマさんじゃなくてペンギンさんですよってひと言…	","letter": "	If you're going to invite me, tell me you're a penguin, not a polar bear...	", "pinyin":"	さそうならしろくまさんじゃなくてぺんぎんさんですよってひとこと…	"},																			
"	253	":{"character":"	欲しかったな	","letter": "	I wish I had.	", "pinyin":"	ほしかったな	"},																			
"	254	":{"character":"	行きたいんですか？	","letter": "	You want to go?	", "pinyin":"	いきたいんですか？	"},																			
"	255	":{"character":"	行きたいよ	","letter": "	I want to go.	", "pinyin":"	いきたいよ	"},																			
"	256	":{"character":"	みんな今頃楽しくやってるんだろうな！	","letter": "	I bet everyone's having fun right now.	", "pinyin":"	みんないまごろたのしくやってるんだろうな！	"},																			
"	257	":{"character":"	笹子さんカフェモカおかわり	","letter": "	Sasago, another cafe mocha.	", "pinyin":"	ささごさんかふぇもかおかわり	"},																			
"	258	":{"character":"	はい	","letter": "	Yes, ma'am.	", "pinyin":"	はい	"},																			
"	259	":{"character":"	へぇ～みんな大学からのお友達なんだ	","letter": "	So you're all friends from college?	", "pinyin":"	へぇ～みんなだいがくからのおともだちなんだ	"},																			
"	260	":{"character":"	そうなんです	","letter": "	Yes, we are.	", "pinyin":"	そうなんです	"},																			
"	261	":{"character":"	そうそう動物園にカピバラいますか？	","letter": "	Do you see capybaras at the zoo?	", "pinyin":"	そうそうどうぶつえんにかぴばらいますか？	"},																			
"	262	":{"character":"	今流行ってますよね	","letter": "	They're all the rage now, aren't they?	", "pinyin":"	いまはやってますよね	"},																			
"	263	":{"character":"	カピバラはネズミだってホントですか？	","letter": "	Is it true that capybaras are rats?	", "pinyin":"	かぴばらはねずみだってほんとですか？	"},																			
"	264	":{"character":"	じゃあ動物園にはカピバラの温泉とかあるんですか？	","letter": "	Then, do they have capybara hot springs at the zoo?	", "pinyin":"	じゃあどうぶつえんにはかぴばらのおんせんとかあるんですか？	"},																			
"	265	":{"character":"	先輩声に出してしゃべってください	","letter": "	Please speak aloud!	", "pinyin":"	せんぱいこえにだしてしゃべってください	"},																			
"	266	":{"character":"	っていうかさっきから何もしゃべってないじゃないですか	","letter": "	I mean, you haven't said a word since a minute ago!	", "pinyin":"	っていうかさっきからなにもしゃべってないじゃないですか	"},																			
"	267	":{"character":"	俺そろそろ…	","letter": "	I'm about to...	", "pinyin":"	おれそろそろ…	"},																			
"	268	":{"character":"	何か用事あるんですか？	","letter": "	Do you have something to do?	", "pinyin":"	なにかようじあるんですか？	"},																			
"	269	":{"character":"	いや風呂の掃除があるから	","letter": "	No, I have to clean the bathroom.	", "pinyin":"	いやふろのそうじがあるから	"},																			
"	270	":{"character":"	わぁ～ちょっと半田さん！	","letter": "	Oh, Mr. Handa!	", "pinyin":"	わぁ～ちょっとはんでんさん！	"},																			
"	271	":{"character":"	風呂の掃除で帰るとか	","letter": "	You're leaving to clean the bathroom?	", "pinyin":"	ふろのそうじでかえるとか	"},																			
"	272	":{"character":"	絶対女の子の前で言っちゃダメですって	","letter": "	Don't ever say that in front of a girl.	", "pinyin":"	ぜったいおんなのこのまえでいっちゃだめですって	"},																			
"	273	":{"character":"	どうかしたの？	","letter": "	Is something wrong?	", "pinyin":"	どうかしたの？	"},																			
"	274	":{"character":"	い…いや大丈夫	","letter": "	No, I'm fine.	", "pinyin":"	い…いやだいじょうぶ	"},																			
"	275	":{"character":"	先輩ちょっと酔っちゃって	","letter": "	I just got a little drunk.	", "pinyin":"	せんぱいちょっとよっちゃって	"},																			
"	276	":{"character":"	掃除がどうかしたんですか？	","letter": "	What's wrong with cleaning?	", "pinyin":"	そうじがどうかしたんですか？	"},																			
"	277	":{"character":"	ソ…ソーセージ注文しようかって先輩が	","letter": "	He asked me to order sausages.	", "pinyin":"	そ…そーせーじちゅうもんしようかってせんぱいが	"},																			
"	278	":{"character":"	ねっ先輩僕注文しますね	","letter": "	I'll order.	", "pinyin":"	ねっせんぱいぼくちゅうもんしますね	"},																			
"	279	":{"character":"	ソーセージ盛り合わせ２つ	","letter": "	Two sausages.	", "pinyin":"	そーせーじもりあわせ２つ	"},																			
"	280	":{"character":"	お刺身盛り合わせも	","letter": "	And sashimi.	", "pinyin":"	おさしみもりあわせも	"},																			
"	281	":{"character":"	シロクマさんすみません	","letter": "	Excuse me, Polar Bear.	", "pinyin":"	しろくまさんすみません	"},																			
"	282	":{"character":"	あれ？パンダくんは？	","letter": "	Where's the panda? Where's the panda?	", "pinyin":"	あれ？ぱんだくんは？	"},																			
"	283	":{"character":"	お待ちどおさま！	","letter": "	Hey, wait for me!	", "pinyin":"	おまちどおさま！	"},																			
"	284	":{"character":"	待ってないよ！	","letter": "	I'm not waiting for you!	", "pinyin":"	まってないよ！	"},																			
"	285	":{"character":"	わざわざ取りに行ったの？	","letter": "	Did you go all the way out here to get it?	", "pinyin":"	わざわざとりにいったの？	"},																			
"	286	":{"character":"	だってここ何もないんだもん	","letter": "	Because there's nothing here.	", "pinyin":"	だってここなにもないんだもん	"},																			
"	287	":{"character":"	あるでしょいろいろ！	","letter": "	We have everything!	", "pinyin":"	あるでしょいろいろ！	"},																			
"	288	":{"character":"	ナッツとか小エビの唐揚げとか	","letter": "	Nuts, fried shrimp...	", "pinyin":"	なっつとかこえびのからあげとか	"},																			
"	289	":{"character":"	いただきま～す	","letter": "	Bon appétit!	", "pinyin":"	いただきま～す	"},																			
"	290	":{"character":"	かわいい！	","letter": "	So cute!	", "pinyin":"	かわいい！	"},																			
"	291	":{"character":"	パンダが竹食べてるとこ初めて見た！	","letter": "	I've never seen a panda eat bamboo before!	", "pinyin":"	ぱんだがたけたべてるとこはじめてみた！	"},																			
"	292	":{"character":"	私も私も！	","letter": "	Me too! Me too!	", "pinyin":"	わたしもわたしも！	"},																			
"	293	":{"character":"	写メ撮っていいですか？	","letter": "	Can I take a picture?	", "pinyin":"	しゃめとっていいですか？	"},																			
"	294	":{"character":"	うん！	","letter": "	Sure!	", "pinyin":"	うん！	"},																			
"	295	":{"character":"	持ち込みはダメだって書いてあるよ	","letter": "	It says you can't bring your own.	", "pinyin":"	もちこみはだめだってかいてあるよ	"},																			
"	296	":{"character":"	お店の人にバレたら…	","letter": "	If the store owner finds out...	", "pinyin":"	おみせのひとにばれたら…	"},																			
"	297	":{"character":"	お待ちどおさまで…	","letter": "	Here you go...	", "pinyin":"	おまちどおさまで…	"},																			
"	298	":{"character":"	すみません持ち込みはダメだって言ったんですけど	","letter": "	I'm sorry, I said you can't bring in your own stuff.	", "pinyin":"	すみませんもちこみはだめだっていったんですけど	"},																			
"	299	":{"character":"	か…かわいい！	","letter": "	You're so cute!	", "pinyin":"	か…かわいい！	"},																			
"	300	":{"character":"	写メいいですか！？	","letter": "	Can I take a picture?	", "pinyin":"	しゃめいいですか！？	"},																			
"	301	":{"character":"	あの持ち込みは？	","letter": "	Can I bring it in?	", "pinyin":"	あのもちこみは？	"},																			
"	302	":{"character":"	いいですいいです！	","letter": "	Yes, of course!	", "pinyin":"	いいですいいです！	"},																			
"	303	":{"character":"	半田さんは何の動物の飼育をしているんですか？	","letter": "	What kind of animals do you keep, Mr. Handa?	", "pinyin":"	はんでんさんはなにのどうぶつのしいくをしているんですか？	"},																			
"	304	":{"character":"	パ…パンダとか	","letter": "	P...pandas...	", "pinyin":"	ぱ…ぱんだとか	"},																			
"	305	":{"character":"	パンダ！？パンダの飼育をしてるんですか？	","letter": "	Pandas? You breed pandas?	", "pinyin":"	ぱんだ！？ぱんだのしいくをしてるんですか？	"},																			
"	306	":{"character":"	え…えぇ	","letter": "	Uh...yeah.	", "pinyin":"	え…えぇ	"},																			
"	307	":{"character":"	かわいい！	","letter": "	Cute!	", "pinyin":"	かわいい！	"},																			
"	308	":{"character":"	か…かわいい？	","letter": "	Cute?	", "pinyin":"	か…かわいい？	"},																			
"	309	":{"character":"	パンダの話いろいろ聞かせてください！	","letter": "	Tell us all about pandas!	", "pinyin":"	ぱんだのはなしいろいろきかせてください！	"},																			
"	310	":{"character":"	昼寝しているところ	","letter": "	They're taking a nap.	", "pinyin":"	ひるねしているところ	"},																			
"	311	":{"character":"	キャーッ！かわいい！！	","letter": "	Crikey! So cute!	", "pinyin":"	きゃーっ！かわいい！！	"},																			
"	312	":{"character":"	遊んでいるところ	","letter": "	Playing	", "pinyin":"	あそんでいるところ	"},																			
"	313	":{"character":"	キャーッ！かわいい！！	","letter": "	Crikey! Cute!	", "pinyin":"	きゃーっ！かわいい！！	"},																			
"	314	":{"character":"	ダラダラしているところ	","letter": "	Lazy!	", "pinyin":"	だらだらしているところ	"},																			
"	315	":{"character":"	キャーッ！かわいい！！	","letter": "	Cute! Cute!	", "pinyin":"	きゃーっ！かわいい！！	"},																			
"	316	":{"character":"	よく見分けがつきますね	","letter": "	How can you tell them apart?	", "pinyin":"	よくみわけがつきますね	"},																			
"	317	":{"character":"	一応プロだから	","letter": "	I'm a pro, in case you were wondering.	", "pinyin":"	いちおうぷろだから	"},																			
"	318	":{"character":"	かわいい！	","letter": "	Cute!	", "pinyin":"	かわいい！	"},																			
"	319	":{"character":"	もっと聞かせてください！	","letter": "	Tell me more!	", "pinyin":"	もっときかせてください！	"},																			
"	320	":{"character":"	パンダは腸が短くて竹からだとあまり栄養がとれないんです	","letter": "	Pandas have short intestines, so they can't get much nutrition from bamboo.	", "pinyin":"	ぱんだはちょうがみじかくてたけからだとあまりえいようがとれないんです	"},																			
"	321	":{"character":"	だから量で補うために１日中竹を食べているんです	","letter": "	So they eat bamboo all day long to make up for it.	", "pinyin":"	だからりょうでおぎなうために１にちじゅうたけをたべているんです	"},																			
"	322	":{"character":"	腸が短いんだ	","letter": "	They have short intestines.	", "pinyin":"	ちょうがみじかいんだ	"},																			
"	323	":{"character":"	かわいい！	","letter": "	So cute!	", "pinyin":"	かわいい！	"},																			
"	324	":{"character":"	そこもかわいいんだ	","letter": "	That's cute too!	", "pinyin":"	そこもかわいいんだ	"},																			
"	325	":{"character":"	半田さんもっと教えてあげて僕のかわいいとこ	","letter": "	Mr. Handa, tell him more about my cute side.	", "pinyin":"	はんでんさんもっとおしえてあげてぼくのかわいいとこ	"},																			
"	326	":{"character":"	竹しか食べてないから	","letter": "	I only eat bamboo.	", "pinyin":"	たけしかたべてないから	"},																			
"	327	":{"character":"	パンダのウンチっていいにおいなんですよ	","letter": "	Panda poop smells good.	", "pinyin":"	ぱんだのうんちっていいにおいなんですよ	"},																			
"	328	":{"character":"	ちょっとレモンのにおいに似ているんです	","letter": "	It smells a little like lemon.	", "pinyin":"	ちょっとれもんのにおいににているんです	"},																			
"	329	":{"character":"	あぁ…これこれ	","letter": "	Oh... that's it.	", "pinyin":"	あぁ…これこれ	"},																			
"	330	":{"character":"	うんパンダのウンチのにおいです	","letter": "	Panda poop.	", "pinyin":"	うんぱんだのうんちのにおいです	"},																			
"	331	":{"character":"	どうぞ	","letter": "	Here you go.	", "pinyin":"	どうぞ	"},																			
"	332	":{"character":"	先輩！その情報はいらないんじゃないですか？	","letter": "	Sir! You don't need that information, do you?	", "pinyin":"	せんぱい！そのじょうほうはいらないんじゃないですか？	"},																			
"	333	":{"character":"	もう！もっとかわいいエピソードにしてよ	","letter": "	Oh, my God! Make it a cuter episode.	", "pinyin":"	もう！もっとかわいいえぴそーどにしてよ	"},																			
"	334	":{"character":"	えっ！？そう？	","letter": "	What? Really?	", "pinyin":"	えっ！？そう？	"},																			
"	335	":{"character":"	あっ！パンダって垂れ目でかわいい感じでしょ？	","letter": "	Ah! Pandas are cute with droopy eyes, right?	", "pinyin":"	あっ！ぱんだってたれめでかわいいかんじでしょ？	"},																			
"	336	":{"character":"	あれって実際の目は小さくて鋭いんですよ	","letter": "	Their eyes are actually small and sharp.	", "pinyin":"	あれってじっさいのめはちいさくてするどいんですよ	"},																			
"	337	":{"character":"	それもいらないよ	","letter": "	I don't need that either.	", "pinyin":"	それもいらないよ	"},																			
"	338	":{"character":"	そうなの？	","letter": "	Really?	", "pinyin":"	そうなの？	"},																			
"	339	":{"character":"	僕にとってはかわいいところなんだけど	","letter": "	It's a cute part for me.	", "pinyin":"	ぼくにとってはかわいいところなんだけど	"},																			
"	340	":{"character":"	もう！半田さん！！	","letter": "	Oh, my God! Mr. Handa!	", "pinyin":"	もう！はんでんさん！！	"},																			
"	341	":{"character":"	かわいい！	","letter": "	So cute!	", "pinyin":"	かわいい！	"},																			
"	342	":{"character":"	ペンギンさんカフェモカおかわりお待たせしました	","letter": "	Penguin, another cafe mocha!	", "pinyin":"	ぺんぎんさんかふぇもかおかわりおまたせしました	"},																			
"	343	":{"character":"	あれ？いない…	","letter": "	What? He's not here...	", "pinyin":"	あれ？いない…	"},																			
"	344	":{"character":"	今度パンダコーナー遊びにいってもいいですか？	","letter": "	Can I visit the panda corner next time?	", "pinyin":"	こんどぱんだこーなーあそびにいってもいいですか？	"},																			
"	345	":{"character":"	もちろんです見にきてください	","letter": "	Of course you can!	", "pinyin":"	もちろんですみにきてください	"},																			
"	346	":{"character":"	常勤パンダさんも紹介しますよ	","letter": "	I'll introduce you to our full-time panda.	", "pinyin":"	じょうきんぱんださんもしょうかいしますよ	"},																			
"	347	":{"character":"	常勤パンダさん？このパンダさんは何なんですか？	","letter": "	A full-time panda? What is this panda?	", "pinyin":"	じょうきんぱんださん？このぱんださんはなになんですか？	"},																			
"	348	":{"character":"	週２のバイトなんです	","letter": "	He works part-time two days a week.	", "pinyin":"	しゅう２のばいとなんです	"},																			
"	349	":{"character":"	へぇ～アルバイトなんだ？	","letter": "	Oh, he's a part-timer?	", "pinyin":"	へぇ～あるばいとなんだ？	"},																			
"	350	":{"character":"	かわいい！	","letter": "	Cute!	", "pinyin":"	かわいい！	"},																			
"	351	":{"character":"	かわいいかな？	","letter": "	Is he cute?	", "pinyin":"	かわいいかな？	"},																			
"	352	":{"character":"	かわいいですよ！	","letter": "	He's cute!	", "pinyin":"	かわいいですよ！	"},																			
"	353	":{"character":"	ねっ？	","letter": "	Right?	", "pinyin":"	ねっ？	"},																			
"	354	":{"character":"	あっ！	","letter": "	Ah!	", "pinyin":"	あっ！	"},																			
"	355	":{"character":"	どうしたの？	","letter": "	What's wrong?	", "pinyin":"	どうしたの？	"},																			
"	356	":{"character":"	な…何？	","letter": "	Wha...what?	", "pinyin":"	な…なに？	"},																			
"	357	":{"character":"	ペンギン！？	","letter": "	A penguin!	", "pinyin":"	ぺんぎん！？	"},																			
"	358	":{"character":"	どうもこんばんは	","letter": "	Good evening.	", "pinyin":"	どうもこんばんは	"},																			
"	359	":{"character":"	何しにきたの？	","letter": "	What are you doing here?	", "pinyin":"	なにしにきたの？	"},																			
"	360	":{"character":"	忙しいんじゃなかったの？ペンギンさん	","letter": "	I thought you were busy. Penguin!	", "pinyin":"	いそがしいんじゃなかったの？ぺんぎんさん	"},																			
"	361	":{"character":"	いやそれは…	","letter": "	No, it's...	", "pinyin":"	いやそれは…	"},																			
"	362	":{"character":"	かわいい！	","letter": "	Cute!	", "pinyin":"	かわいい！	"},																			
"	363	":{"character":"	えっ！？そこも？	","letter": "	What? There too?	", "pinyin":"	えっ！？そこも？	"},																			
"	364	":{"character":"	マ*マ*マハロ	","letter": "	Ma-ma-ma-ma-ma-ma-mahalo.	", "pinyin":"	ま*ま*まはろ	"},																			
"	365	":{"character":"	ペンギンさんマイク代わってもらっていいですか？	","letter": "	Penguin, can I ask you to take over the microphone?	", "pinyin":"	ぺんぎんさんまいくかわってもらっていいですか？	"},																			
"	366	":{"character":"	もう１曲もう１曲！	","letter": "	One more song, one more song!	", "pinyin":"	もう１きょくもう１きょく！	"},																			
"	367	":{"character":"	しようがないな	","letter": "	I can't help it.	", "pinyin":"	しようがないな	"},																			
"	368	":{"character":"	「ぐぅ」？	","letter": "	Guh?	", "pinyin":"	「ぐぅ」？	"},																			
"	369	":{"character":"	寝てる！	","letter": "	He's sleeping!	", "pinyin":"	ねてる！	"},																			
"	370	":{"character":"	パンダくん起きて！パンダくん！！	","letter": "	Wake up, panda! Panda, wake up!	", "pinyin":"	ぱんだくんおきて！ぱんだくん！！	"},																			
"	371	":{"character":"	って…先輩まで！	","letter": "	Even my senpai!	", "pinyin":"	って…せんぱいまで！	"},																			
"	372	":{"character":"	見て寝てる！	","letter": "	Look, he's sleeping!	", "pinyin":"	みてねてる！	"},																			
"	373	":{"character":"	ねぇなんか似てない？	","letter": "	Hey, don't they look alike?	", "pinyin":"	ねぇなんかにてない？	"},																			
"	374	":{"character":"	このカフェにたどり着いたラッキーボーイズアンドガールズ	","letter": "	Lucky boys and girls who found their way to this cafe!	", "pinyin":"	このかふぇにたどりついたらっきーぼーいずあんどがーるず	"},																			
"	375	":{"character":"	今日はありがとうございました	","letter": "	Thank you so much for today.	", "pinyin":"	きょうはありがとうございました	"},																			
"	376	":{"character":"	楽しかったです	","letter": "	It was fun.	", "pinyin":"	たのしかったです	"},																			
"	377	":{"character":"	またパンダの話聞かせてください	","letter": "	Please tell us about the pandas again.	", "pinyin":"	またぱんだのはなしきかせてください	"},																			
"	378	":{"character":"	えぇ動物園に遊びにきてください	","letter": "	Yes, please come visit us at the zoo.	", "pinyin":"	えぇどうぶつえんにあそびにきてください	"},																			
"	379	":{"character":"	はいじゃあおやすみなさい	","letter": "	Okay, good night.	", "pinyin":"	はいじゃあおやすみなさい	"},																			
"	380	":{"character":"	それじゃ俺も風呂の掃除あるから帰るわ	","letter": "	Well, I'm gonna go home. I've got to clean the bathroom.	", "pinyin":"	それじゃおれもふろのそうじあるからかえるわ	"},																			
"	381	":{"character":"	また明日な	","letter": "	See you tomorrow.	", "pinyin":"	またあしたな	"},																			
"	382	":{"character":"	はい	","letter": "	Okay.	", "pinyin":"	はい	"},																			
"	383	":{"character":"	半田さんらしいや	","letter": "	That's just like Mr. Handa.	", "pinyin":"	はんでんさんらしいや	"},																			
"	384	":{"character":"	うちでコーヒーでも飲んでく？	","letter": "	You want to have coffee at my place?	", "pinyin":"	うちでこーひーでものんでく？	"},																			
"	385	":{"character":"	はいシロクマさん	","letter": "	Yes, Polar Bear.	", "pinyin":"	はいしろくまさん	"},																			
"	386	":{"character":"	マ*マ*マハロ	","letter": "	Mahalo.	", "pinyin":"	ま*ま*まはろ	"},																			
"	387	":{"character":"	イエーイ！	","letter": "	Yay!	", "pinyin":"	いえーい！	"},																			
"	388	":{"character":"	あっ！あれ？みんなは？	","letter": "	Ah! Where is everyone? Where is everybody?	", "pinyin":"	あっ！あれ？みんなは？	"},																			
"	389	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguins! Penguins!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	390	":{"character":"	何？パンダ君	","letter": "	What? Panda.	", "pinyin":"	なに？ぱんだくん	"},																			
"	391	":{"character":"	ペンギンさんってカフェの椅子にどうやって座ってるの	","letter": "	How do penguins sit on chairs in cafes?	", "pinyin":"	ぺんぎんさんってかふぇのいすにどうやってすわってるの	"},																			
"	392	":{"character":"	白熊君終わろ	","letter": "	Polar bear, finish.	", "pinyin":"	しろくまくんおわろ	"},																			
"	393	":{"character":"	ペンギンさんってカフェの椅子にどうやって座ってるの	","letter": "	How do penguins sit on chairs in cafes?	", "pinyin":"	ぺんぎんさんってかふぇのいすにどうやってすわってるの	"},																			
"	394	":{"character":"	白熊君終わろ	","letter": "	Polar bear, finish.	", "pinyin":"	しろくまくんおわろ	"},																			
"	395	":{"character":"	ペンギンさんってカフェの椅子に…	","letter": "	How does Mr. Penguin sit on a chair...	", "pinyin":"	ぺんぎんさんってかふぇのいすに…	"},																			
"	396	":{"character":"	終わろ	","letter": "	End	", "pinyin":"	おわろ	"},																			
"	397	":{"character":"	次回のしろくまカフェ第80話	","letter": "	Next time on Shirokuma Cafe Episode 80	", "pinyin":"	じかいのしろくまかふぇだい80わ	"},																			
"	398	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
"	399	":{"character":"	11話	","letter": "	Episode 11	", "pinyin":"	11わ	"},																			
"	400	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}