const cherokeeMap = {
    "Ꭰ": { "letter": "a" },
    "Ꭱ": { "letter": "e" },
    "Ꭲ": { "letter": "i" },
    "Ꭳ": { "letter": "o" },
    "Ꭴ": { "letter": "u" },
    "Ꭵ": { "letter": "v" },
    " ": { "letter": " " },
    "  ": { "letter": " " },
    "   ": { "letter": " " },
    "Ꭶ": { "letter": "ga" },
    "Ꭷ": { "letter": "ka" },
    "Ꭸ": { "letter": "ge" },
    "Ꭹ": { "letter": "gi" },
    "Ꭺ": { "letter": "go" },
    "Ꭻ": { "letter": "gu" },
    "Ꭼ": { "letter": "gv" },
    "    ": { "letter": " " },
    "     ": { "letter": " " },
    "Ꭽ": { "letter": "ha" },
    "Ꭾ": { "letter": "he" },
    "Ꭿ": { "letter": "hi" },
    "Ꮀ": { "letter": "ho" },
    "Ꮁ": { "letter": "hu" },
    "Ꮂ": { "letter": "hv" },
    "      ": { "letter": " " },
    "       ": { "letter": " " },
    "        ": { "letter": " " },
    "Ꮃ": { "letter": "la" },
    "Ꮄ": { "letter": "le" },
    "Ꮅ": { "letter": "li" },
    "Ꮆ": { "letter": "lo" },
    "Ꮇ": { "letter": "lu" },
    "Ꮈ": { "letter": "lv" },
    "         ": { "letter": " " },
    "          ": { "letter": " " },
    "           ": { "letter": " " },
    "Ꮉ": { "letter": "ma" },
    "Ꮊ": { "letter": "me" },
    "Ꮋ": { "letter": "mi" },
    "Ꮌ": { "letter": "mo" },
    "Ꮍ": { "letter": "mu" },
    "            ": { "letter": " " },
    "             ": { "letter": " " },
    "              ": { "letter": " " },
    "                ": { "letter": " " },
    "Ꮎ": { "letter": "na" },
    "Ꮏ": { "letter": "hna" },
    "Ꮐ": { "letter": "nah" },
    "Ꮑ": { "letter": "ne" },
    "Ꮒ": { "letter": "ni" },
    "Ꮓ": { "letter": "no" },
    "Ꮔ": { "letter": "nu" },
    "Ꮕ": { "letter": "nv" },
    "                 ": { "letter": " " },
    "Ꮖ": { "letter": "qua" },
    "Ꮗ": { "letter": "que" },
    "Ꮘ": { "letter": "qui" },
    "Ꮙ": { "letter": "quo" },
    "Ꮚ": { "letter": "quu" },
    "Ꮛ": { "letter": "quv" },
    "                  ": { "letter": " " },
    "                   ": { "letter": " " },
    "                    ": { "letter": " " },
    "Ꮝ": { "letter": "s" },
    "Ꮜ": { "letter": "sa" },
    "Ꮞ": { "letter": "se" },
    "Ꮟ": { "letter": "si" },
    "Ꮠ": { "letter": "so" },
    "Ꮡ": { "letter": "su" },
    "Ꮢ": { "letter": "sv" },
    "                     ": { "letter": " " },
    "                      ": { "letter": " " },
    "Ꮣ": { "letter": "da" },
    "Ꮤ": { "letter": "ta" },
    "Ꮥ": { "letter": "de" },
    "Ꮦ": { "letter": "te" },
    "Ꮧ": { "letter": "di" },
    "Ꮨ": { "letter": "ti" },
    "Ꮩ": { "letter": "do" },
    "Ꮪ": { "letter": "du" },
    "Ꮫ": { "letter": "dv" },
    "Ꮬ": { "letter": "dla" },
    "Ꮭ": { "letter": "tla" },
    "Ꮮ": { "letter": "tle" },
    "Ꮯ": { "letter": "tli" },
    "Ꮰ": { "letter": "tlo" },
    "Ꮱ": { "letter": "tlu" },
    "Ꮲ": { "letter": "tlv" },
    "                       ": { "letter": " " },
    "                        ": { "letter": " " },
    "Ꮳ": { "letter": "tsa" },
    "Ꮴ": { "letter": "tse" },
    "Ꮵ": { "letter": "tsi" },
    "Ꮶ": { "letter": "tso" },
    "Ꮷ": { "letter": "tsu" },
    "Ꮸ": { "letter": "tsv" },
    "                          ": { "letter": " " },
    "                           ": { "letter": " " },  
    "                            ": { "letter": " " },
    "Ꮹ": { "letter": "wa" },
    "Ꮺ": { "letter": "we" },
    "Ꮻ": { "letter": "wi" },
    "Ꮼ": { "letter": "wo" },
    "Ꮽ": { "letter": "wu" },
    "Ꮾ": { "letter": "wv" },
    "                             ": { "letter": " " },
    "                              ": { "letter": " " },
    "                               ": { "letter": " " },
    "Ꮿ": { "letter": "ya" },
    "Ᏸ": { "letter": "ye" },
    "Ᏹ": { "letter": "yi" },
    "Ᏺ": { "letter": "yo" },
    "Ᏻ": { "letter": "yu" },
    "Ᏼ": { "letter": "yv" },
    "                                 ": { "letter": " " },
    "                                  ": { "letter": " " },
    "                                   ": { "letter": " " },
}


const cherokeeChartData = [
    { "subtitle": "", "content": cherokeeMap, "chartColumn": "character-content-9-column" },
]