obj = {
	"	1	":{"character":"	パンダくんのダイエット	","letter": "	Panda-kun's Diet	", "pinyin":"	ぱんだくんのだいえっと	"},																			
"	2	":{"character":"	いらっしゃいませ	","letter": "	Welcome!	", "pinyin":"	いらっしゃいませ	"},																			
"	3	":{"character":"	どうしたの？元気ないね	","letter": "	What's wrong? You don't look well.	", "pinyin":"	どうしたの？げんきないね	"},																			
"	4	":{"character":"	パンダくんいつもの？	","letter": "	Panda, usual?	", "pinyin":"	ぱんだくんいつもの？	"},																			
"	5	":{"character":"	うん	","letter": "	Yes, I'm fine.	", "pinyin":"	うん	"},																			
"	6	":{"character":"	あぁいや…普通盛りで	","letter": "	Oh, no, I'll have a regular serving.	", "pinyin":"	あぁいや…ふつうざかりで	"},																			
"	7	":{"character":"	えっ！？大盛りじゃないの？	","letter": "	What? Not a large portion?	", "pinyin":"	えっ！？おおもりじゃないの？	"},																			
"	8	":{"character":"	今日からダイエットするの	","letter": "	I'm going on a diet starting today.	", "pinyin":"	きょうからだいえっとするの	"},																			
"	9	":{"character":"	え～っ！？	","letter": "	What?	", "pinyin":"	え～っ！？	"},																			
"	10	":{"character":"	ダイエット？	","letter": "	Diet?	", "pinyin":"	だいえっと？	"},																			
"	11	":{"character":"	それはインターネット	","letter": "	That's the Internet	", "pinyin":"	それはいんたーねっと	"},																			
"	12	":{"character":"	それはイヌイット	","letter": "	That's Inuit.	", "pinyin":"	それはいぬいっと	"},																			
"	13	":{"character":"	それはカルテット	","letter": "	It's a quartet.	", "pinyin":"	それはかるてっと	"},																			
"	14	":{"character":"	どうしたの？急に	","letter": "	What's wrong? Suddenly...	", "pinyin":"	どうしたの？きゅうに	"},																			
"	15	":{"character":"	実は今日動物園でさ…	","letter": "	I was at the zoo today and...	", "pinyin":"	じつはきょうどうぶつえんでさ…	"},																			
"	16	":{"character":"	パンダさん！	","letter": "	Panda!	", "pinyin":"	ぱんださん！	"},																			
"	17	":{"character":"	サービスサービス	","letter": "	Service, service, service.	", "pinyin":"	さーびすさーびす	"},																			
"	18	":{"character":"	え～っ！？ケガしなくてよかったね	","letter": "	What? You're lucky you didn't get hurt.	", "pinyin":"	え～っ！？けがしなくてよかったね	"},																			
"	19	":{"character":"	それでダイエット？	","letter": "	Is that why you're on a diet?	", "pinyin":"	それでだいえっと？	"},																			
"	20	":{"character":"	まぁ昔から	","letter": "	Well, for a long time.	", "pinyin":"	まぁむかしから	"},																			
"	21	":{"character":"	スマートな動物に生まれたかったなって思ってたんだよ	","letter": "	I always wanted to be born a smart animal.	", "pinyin":"	すまーとなどうぶつにうまれたかったなっておもってたんだよ	"},																			
"	22	":{"character":"	スタイル気になるの？	","letter": "	Are you worried about your style?	", "pinyin":"	すたいるきになるの？	"},																			
"	23	":{"character":"	うんだって…	","letter": "	Well...	", "pinyin":"	うんだって…	"},																			
"	24	":{"character":"	生まれたときからおっさん体型なんだもん	","letter": "	I've been an old man since birth.	", "pinyin":"	うまれたときからおっさんたいけいなんだもん	"},																			
"	25	":{"character":"	どうなりたいの？	","letter": "	What do you want to be?	", "pinyin":"	どうなりたいの？	"},																			
"	26	":{"character":"	僕の理想はね…	","letter": "	My ideal would be...	", "pinyin":"	ぼくのりそうはね…	"},																			
"	27	":{"character":"	もっと脚が長くて	","letter": "	Longer legs.	", "pinyin":"	もっとあしがながくて	"},																			
"	28	":{"character":"	逆三角形の体型で	","letter": "	Inverted triangle.	", "pinyin":"	ぎゃくさんかくけいのたいけいで	"},																			
"	29	":{"character":"	顔も逆三角形なの	","letter": "	And an inverted triangle face.	", "pinyin":"	かおもぎゃくさんかくけいなの	"},																			
"	30	":{"character":"	ドリームパンダハハハハハ！	","letter": "	Dream panda hahahahahaha!	", "pinyin":"	どりーむぱんだははははは！	"},																			
"	31	":{"character":"	それかっこいいの？	","letter": "	Is that cool?	", "pinyin":"	それかっこいいの？	"},																			
"	32	":{"character":"	パンダくん悪いヤツみたいになっちゃうね	","letter": "	Panda, you look like a bad guy.	", "pinyin":"	ぱんだくんわるいやつみたいになっちゃうね	"},																			
"	33	":{"character":"	いいの僕ワルに憧れてるから	","letter": "	That's okay, I've always wanted to be a badass.	", "pinyin":"	いいのぼくわるにあこがれてるから	"},																			
"	34	":{"character":"	お待たせ	","letter": "	Here you go.	", "pinyin":"	おまたせ	"},																			
"	35	":{"character":"	はい普通盛りね	","letter": "	Here you go.	", "pinyin":"	はいふつうもりね	"},																			
"	36	":{"character":"	やっぱりいつもので	","letter": "	I knew it! I always get a large!	", "pinyin":"	やっぱりいつもので	"},																			
"	37	":{"character":"	大盛りね	","letter": "	I'll have a large.	", "pinyin":"	おおもりね	"},																			
"	38	":{"character":"	ダイエットは？	","letter": "	What about your diet?	", "pinyin":"	だいえっとは？	"},																			
"	39	":{"character":"	明日からにするよ	","letter": "	I'll start tomorrow.	", "pinyin":"	あしたからにするよ	"},																			
"	40	":{"character":"	パンダさん！	","letter": "	Panda!	", "pinyin":"	ぱんださん！	"},																			
"	41	":{"character":"	エビドリア！	","letter": "	Shrimp doria!	", "pinyin":"	えびどりあ！	"},																			
"	42	":{"character":"	パンダくん起きなさい！	","letter": "	Wake up, panda!	", "pinyin":"	ぱんだくんおきなさい！	"},																			
"	43	":{"character":"	たった週２回のバイトなのに	","letter": "	I'm only working two jobs a week.	", "pinyin":"	たったしゅう２かいのばいとなのに	"},																			
"	44	":{"character":"	朝から居眠りしないでよ	","letter": "	Don't doze off in the morning.	", "pinyin":"	あさからいねむりしないでよ	"},																			
"	45	":{"character":"	はいパンダだんご	","letter": "	Here you go, panda dumplings.	", "pinyin":"	はいぱんだだんご	"},																			
"	46	":{"character":"	いらない	","letter": "	I don't want it.	", "pinyin":"	いらない	"},																			
"	47	":{"character":"	えっ！？どうして？	","letter": "	What? Why not?	", "pinyin":"	えっ！？どうして？	"},																			
"	48	":{"character":"	今日からダイエットするの	","letter": "	I'm going on a diet today.	", "pinyin":"	きょうからだいえっとするの	"},																			
"	49	":{"character":"	ダイエット！？	","letter": "	Diet?	", "pinyin":"	だいえっと！？	"},																			
"	50	":{"character":"	へぇ…私なんかすっかりメタボだけど	","letter": "	Well...I'm a metabolic syndrome person, but...	", "pinyin":"	へぇ…わたしなんかすっかりめたぼだけど	"},																			
"	51	":{"character":"	なんにもしてないな	","letter": "	I haven't done anything.	", "pinyin":"	なんにもしてないな	"},																			
"	52	":{"character":"	昨日はすべり台を壊しちゃったしさ…	","letter": "	I broke the slide yesterday...	", "pinyin":"	きのうはすべりだいをこわしちゃったしさ…	"},																			
"	53	":{"character":"	ごめんごめん	","letter": "	Sorry, sorry.	", "pinyin":"	ごめんごめん	"},																			
"	54	":{"character":"	あれは柱がシロアリに食われてたからで	","letter": "	That was because the pillars were eaten by termites.	", "pinyin":"	あれははしらがしろありにくわれてたからで	"},																			
"	55	":{"character":"	パンダくんのせいじゃないから	","letter": "	It's not your fault.	", "pinyin":"	ぱんだくんのせいじゃないから	"},																			
"	56	":{"character":"	それにまだ若いのにおっさん体型だし…	","letter": "	And you're still young, but you're an old man...	", "pinyin":"	それにまだわかいのにおっさんたいけいだし…	"},																			
"	57	":{"character":"	でもそれが自然なパンダだし	","letter": "	But he's a natural panda.	", "pinyin":"	でもそれがしぜんなぱんだだし	"},																			
"	58	":{"character":"	そもそもパンダの名前の由来を知らないの？	","letter": "	You don't know where the name 'panda' comes from?	", "pinyin":"	そもそもぱんだのなまえのゆらいをしらないの？	"},																			
"	59	":{"character":"	えっ何？かわいいとか？	","letter": "	What? Cute?	", "pinyin":"	えっなに？かわいいとか？	"},																			
"	60	":{"character":"	まぁいろんな説があるんだけどさそのうちの一つは…	","letter": "	Well, there are many theories, but one of them is...	", "pinyin":"	まぁいろんなせつがあるんだけどさそのうちのひとつは…	"},																			
"	61	":{"character":"	むか～しむかし	","letter": "	Once upon a time...	", "pinyin":"	むか～しむかし	"},																			
"	62	":{"character":"	外国人が中国を探検していたときのこと…	","letter": "	A long time ago, when foreigners were exploring China...	", "pinyin":"	がいこくじんがちゅうごくをたんけんしていたときのこと…	"},																			
"	63	":{"character":"	ワオ！	","letter": "	Wow!	", "pinyin":"	わお！	"},																			
"	64	":{"character":"	あ～パンダ…	","letter": "	Panda...	", "pinyin":"	あ～ぱんだ…	"},																			
"	65	":{"character":"	こうして中国語の「太った」という意味のパンダが	","letter": "	And so the name 'panda,' which means 'fat' in Chinese...	", "pinyin":"	こうしてちゅうごくごの「ふとった」といういみのぱんだが	"},																			
"	66	":{"character":"	名前として広まったという説があるんだ	","letter": "	as the name of a panda.	", "pinyin":"	なまえとしてひろまったというせつがあるんだ	"},																			
"	67	":{"character":"	じゃあ僕って…	","letter": "	So I'm a...	", "pinyin":"	じゃあぼくって…	"},																			
"	68	":{"character":"	パンダパンダ	","letter": "	Panda-panda.	", "pinyin":"	ぱんだぱんだ	"},																			
"	69	":{"character":"	メタボーメタボー	","letter": "	Metabo, metabo, metabo...	", "pinyin":"	めたぼーめたぼー	"},																			
"	70	":{"character":"	なんかすごくへこんできた…	","letter": "	I feel so depressed...	", "pinyin":"	なんかすごくへこんできた…	"},																			
"	71	":{"character":"	世の中には知らないほうが幸せなこともあるよね	","letter": "	There are some things in this world you're better off not knowing.	", "pinyin":"	よのなかにはしらないほうがしあわせなこともあるよね	"},																			
"	72	":{"character":"	バイトのせいだよ	","letter": "	It's because of my part-time job.	", "pinyin":"	ばいとのせいだよ	"},																			
"	73	":{"character":"	超ヒマで	","letter": "	I'm super busy.	", "pinyin":"	ちょうひまで	"},																			
"	74	":{"character":"	おやつを食べてお昼寝するしかないから太っちゃったんだ	","letter": "	I've gained weight because I have to eat snacks and take naps.	", "pinyin":"	おやつをたべておひるねするしかないからふとっちゃったんだ	"},																			
"	75	":{"character":"	ヒマじゃないでしょう！	","letter": "	You're not busy!	", "pinyin":"	ひまじゃないでしょう！	"},																			
"	76	":{"character":"	ちゃんとお客さんにサービスしなさい！	","letter": "	You're supposed to be serving the customers!	", "pinyin":"	ちゃんとおきゃくさんにさーびすしなさい！	"},																			
"	77	":{"character":"	なんか最近マンネリでさ…	","letter": "	I've been in a rut lately...	", "pinyin":"	なんかさいきんまんねりでさ…	"},																			
"	78	":{"character":"	タイヤやすべり台で遊ぶのも飽きちゃって…	","letter": "	I'm tired of playing with tires and slides...	", "pinyin":"	たいややすべりだいであそぶのもあきちゃって…	"},																			
"	79	":{"character":"	お仕事でしょ！	","letter": "	You're working!	", "pinyin":"	おしごとでしょ！	"},																			
"	80	":{"character":"	ねぇフィットネスゲーム持ってきていい？	","letter": "	Hey, can I bring my fitness game?	", "pinyin":"	ねぇふぃっとねすげーむもってきていい？	"},																			
"	81	":{"character":"	ダメ！	","letter": "	No!	", "pinyin":"	だめ！	"},																			
"	82	":{"character":"	ゲルマニウム温浴作ってよ	","letter": "	Make me a Germanium bath.	", "pinyin":"	げるまにうむおんよくつくってよ	"},																			
"	83	":{"character":"	ダメです！	","letter": "	No!	", "pinyin":"	だめです！	"},																			
"	84	":{"character":"	エアロビのお姉さんを呼ぼうよ	","letter": "	Let's call the aerobics lady.	", "pinyin":"	えあろびのおねえさんをよぼうよ	"},																			
"	85	":{"character":"	ダメだってば！	","letter": "	No, you can't!	", "pinyin":"	だめだってば！	"},																			
"	86	":{"character":"	はぁ～あ…なんかきっかけさえあれば	","letter": "	If only there was some kind of a trigger...	", "pinyin":"	はぁ～あ…なんかきっかけさえあれば	"},																			
"	87	":{"character":"	もっとダイエットやる気になるのにな	","letter": "	I'd be more motivated to lose weight.	", "pinyin":"	もっとだいえっとやるきになるのにな	"},																			
"	88	":{"character":"	まぁダイエットしたいならしっかりとサービスに励みなさい	","letter": "	Well, if you want to lose weight, make sure you're in the service.	", "pinyin":"	まぁだいえっとしたいならしっかりとさーびすにはげみなさい	"},																			
"	89	":{"character":"	は～い任せて	","letter": "	I'll take care of it.	", "pinyin":"	は～いまかせて	"},																			
"	90	":{"character":"	僕ってやればできる子だから	","letter": "	I'm a can-do girl.	", "pinyin":"	ぼくってやればできるこだから	"},																			
"	91	":{"character":"	じゃあちゃんと頼むよ	","letter": "	Then take good care of me.	", "pinyin":"	じゃあちゃんとたのむよ	"},																			
"	92	":{"character":"	パンダさん起きて～！	","letter": "	Wake up, panda!	", "pinyin":"	ぱんださんおきて～！	"},																			
"	93	":{"character":"	パンダさんかわいい！	","letter": "	Panda, you're so cute!	", "pinyin":"	ぱんださんかわいい！	"},																			
"	94	":{"character":"	サービスサービス！	","letter": "	Service, service, service!	", "pinyin":"	さーびすさーびす！	"},																			
"	95	":{"character":"	サービスサービス！	","letter": "	Service, service, service!	", "pinyin":"	さーびすさーびす！	"},																			
"	96	":{"character":"	かわいいって言われたときだけ反応するね	","letter": "	I only respond when you call me cute.	", "pinyin":"	かわいいっていわれたときだけはんのうするね	"},																			
"	97	":{"character":"	サービスサービス！	","letter": "	Service, service, service!	", "pinyin":"	さーびすさーびす！	"},																			
"	98	":{"character":"	この下膨れ体型がかわいいんだよね	","letter": "	I think he's cute with this bulging bottom.	", "pinyin":"	このしもぶくれたいけいがかわいいんだよね	"},																			
"	99	":{"character":"	メタボパンダさんだね	","letter": "	You're a metabolic panda, aren't you?	", "pinyin":"	めたぼぱんださんだね	"},																			
"	100	":{"character":"	目指せドリームパンダ！	","letter": "	Aim for dream panda!	", "pinyin":"	めざせどりーむぱんだ！	"},																			
"	101	":{"character":"	パパンダーパパンパンパパンダー	","letter": "	Papander panda panda panda panda panda	", "pinyin":"	ぱぱんだーぱぱんぱんぱぱんだー	"},																			
"	102	":{"character":"	パパンダーパンパンパンパパンダー	","letter": "	Papandapandapandapandapandapandapandapandapandapandapandapandapandapandapandap!	", "pinyin":"	ぱぱんだーぱんぱんぱんぱぱんだー	"},																			
"	103	":{"character":"	ダイエット！	","letter": "	Diet!	", "pinyin":"	だいえっと！	"},																			
"	104	":{"character":"	ダイエット	","letter": "	Diet!	", "pinyin":"	だいえっと	"},																			
"	105	":{"character":"	ダイエット…	","letter": "	Diet...	", "pinyin":"	だいえっと…	"},																			
"	106	":{"character":"	パンダさ～ん！	","letter": "	Panda~!	", "pinyin":"	ぱんださ～ん！	"},																			
"	107	":{"character":"	ダイエットダイエット！	","letter": "	Diet, diet, diet!	", "pinyin":"	だいえっとだいえっと！	"},																			
"	108	":{"character":"	ダイエットダイエット！	","letter": "	Diet, diet, diet!	", "pinyin":"	だいえっとだいえっと！	"},																			
"	109	":{"character":"	ダイエットダイエット！	","letter": "	Diet, diet, diet!	", "pinyin":"	だいえっとだいえっと！	"},																			
"	110	":{"character":"	何だかドキドキするね	","letter": "	I'm kind of nervous.	", "pinyin":"	なんだかどきどきするね	"},																			
"	111	":{"character":"	大丈夫だよ	","letter": "	It's okay.	", "pinyin":"	だいじょうぶだよ	"},																			
"	112	":{"character":"	ここんとこずっと頑張ってたんだから	","letter": "	You've been working so hard these past few weeks.	", "pinyin":"	ここんとこずっとがんばってたんだから	"},																			
"	113	":{"character":"	目標とりあえず１３０キロ	","letter": "	My goal is 130 pounds for now.	", "pinyin":"	もくひょうとりあえず１３０きろ	"},																			
"	114	":{"character":"	やった！	","letter": "	Yes!	", "pinyin":"	やった！	"},																			
"	115	":{"character":"	おめでとうダイエット成功だね	","letter": "	Congrats on the diet!	", "pinyin":"	おめでとうだいえっとせいこうだね	"},																			
"	116	":{"character":"	僕もっと頑張ってスリムなドリームパンダになるよ	","letter": "	I'm going to work even harder to become a slim dream panda!	", "pinyin":"	ぼくもっとがんばってすりむなどりーむぱんだになるよ	"},																			
"	117	":{"character":"	いや～そこまでしなくていいから	","letter": "	No, you don't have to go that far.	", "pinyin":"	いや～そこまでしなくていいから	"},																			
"	118	":{"character":"	頑張ったパンダくんにご褒美があるよ	","letter": "	There's a reward for your hard work, panda!	", "pinyin":"	がんばったぱんだくんにごほうびがあるよ	"},																			
"	119	":{"character":"	えっ何？	","letter": "	What?	", "pinyin":"	えっなに？	"},																			
"	120	":{"character":"	楽しく滑れるように工夫してみたんだ	","letter": "	I've made it fun for you.	", "pinyin":"	たのしくすべれるようにくふうしてみたんだ	"},																			
"	121	":{"character":"	パンダくんがマンネリって言ってたからね	","letter": "	You said you were in a rut.	", "pinyin":"	ぱんだくんがまんねりっていってたからね	"},																			
"	122	":{"character":"	半田さんありがとう	","letter": "	Thank you, Mr. Handa.	", "pinyin":"	はんでんさんありがとう	"},																			
"	123	":{"character":"	待ってたよ一緒に初滑りしよう	","letter": "	I've been waiting for you... let's go skiing together for the first time!	", "pinyin":"	まってたよいっしょにはつすべりしよう	"},																			
"	124	":{"character":"	うん！	","letter": "	Yeah!	", "pinyin":"	うん！	"},																			
"	125	":{"character":"	ワーイ！	","letter": "	Yay!	", "pinyin":"	わーい！	"},																			
"	126	":{"character":"	ワーイ！	","letter": "	Yay!	", "pinyin":"	わーい！	"},																			
"	127	":{"character":"	あっ！どうしたんですか？	","letter": "	Oh! What's wrong?	", "pinyin":"	あっ！どうしたんですか？	"},																			
"	128	":{"character":"	あいや…お腹がつっかえて…	","letter": "	Oh, no... just a little tummy ache...	", "pinyin":"	あいや…おなかがつっかえて…	"},																			
"	129	":{"character":"	常勤パンダさんメタボ	","letter": "	Full-time panda, metabolic syndrome.	", "pinyin":"	じょうきんぱんださんめたぼ	"},																			
"	130	":{"character":"	ハァー作り直しかな…	","letter": "	I'll have to remake it...	", "pinyin":"	はぁーつくりなおしかな…	"},																			
"	131	":{"character":"	目指せ！ワイルドパンダ	","letter": "	Go for it! Wild Panda	", "pinyin":"	めざせ！わいるどぱんだ	"},																			
"	132	":{"character":"	いらっしゃい	","letter": "	Hello, there...	", "pinyin":"	いらっしゃい	"},																			
"	133	":{"character":"	こんにちは	","letter": "	Hello.	", "pinyin":"	こんにちは	"},																			
"	134	":{"character":"	何してるのパンダくん	","letter": "	What are you doing, panda?	", "pinyin":"	なにしてるのぱんだくん	"},																			
"	135	":{"character":"	どうしたのその格好	","letter": "	What's with the outfit?	", "pinyin":"	どうしたのそのかっこう	"},																			
"	136	":{"character":"	悪いヤツな気分になってみたくて	","letter": "	I'm just trying to feel like a badass.	", "pinyin":"	わるいやつなきぶんになってみたくて	"},																			
"	137	":{"character":"	ワルな人って憧れちゃうな	","letter": "	I've always wanted to be a badass.	", "pinyin":"	わるなひとってあこがれちゃうな	"},																			
"	138	":{"character":"	パンダくんいつもの？	","letter": "	Panda, is that your usual?	", "pinyin":"	ぱんだくんいつもの？	"},																			
"	139	":{"character":"	うんあいやストロングコーヒー	","letter": "	No, it's strong coffee.	", "pinyin":"	うんあいやすとろんぐこーひー	"},																			
"	140	":{"character":"	えっストロング？結構苦いよ	","letter": "	Strong coffee? It's pretty bitter.	", "pinyin":"	えっすとろんぐ？けっこうにがいよ	"},																			
"	141	":{"character":"	今日はワルの気分だから	","letter": "	I'm feeling badass today.	", "pinyin":"	きょうはわるのきぶんだから	"},																			
"	142	":{"character":"	はいストロング	","letter": "	Here you go, Strong.	", "pinyin":"	はいすとろんぐ	"},																			
"	143	":{"character":"	いただきます	","letter": "	Bon appétit!	", "pinyin":"	いただきます	"},																			
"	144	":{"character":"	外せば	","letter": "	Take it off.	", "pinyin":"	はずせば	"},																			
"	145	":{"character":"	ねぇワルのどこに憧れたの？	","letter": "	What is it about being a badass that you admire so much?	", "pinyin":"	ねぇわるのどこにあこがれたの？	"},																			
"	146	":{"character":"	ほら僕って優柔不断だから	","letter": "	Well, I'm indecisive.	", "pinyin":"	ほらぼくってゆうじゅうふだんだから	"},																			
"	147	":{"character":"	強気な人が羨ましくって	","letter": "	I envy people who can be tough.	", "pinyin":"	つよきなひとがうらやましくって	"},																			
"	148	":{"character":"	それワルとは関係ないでしょ	","letter": "	That has nothing to do with being a badass.	", "pinyin":"	それわるとはかんけいないでしょ	"},																			
"	149	":{"character":"	えっそう？	","letter": "	Oh, really?	", "pinyin":"	えっそう？	"},																			
"	150	":{"character":"	僕に足りないのはワイルドさだと思うんだ	","letter": "	I think what I lack is wildness.	", "pinyin":"	ぼくにたりないのはわいるどさだとおもうんだ	"},																			
"	151	":{"character":"	ワイルドねぇ…	","letter": "	Wild...	", "pinyin":"	わいるどねぇ…	"},																			
"	152	":{"character":"	うわ～苦っ！	","letter": "	Wow, that's bitter!	", "pinyin":"	うわ～くっ！	"},																			
"	153	":{"character":"	やっぱり…	","letter": "	I knew it...	", "pinyin":"	やっぱり…	"},																			
"	154	":{"character":"	マイルドなコーヒーね	","letter": "	Mild coffee.	", "pinyin":"	まいるどなこーひーね	"},																			
"	155	":{"character":"	いろいろビデオを見てワイルドなイメージを膨らませてみたの	","letter": "	I've been watching a lot of videos and trying to develop a wild image of it.	", "pinyin":"	いろいろびでおをみてわいるどないめーじをふくらませてみたの	"},																			
"	156	":{"character":"	ビデオ？	","letter": "	Videos?	", "pinyin":"	びでお？	"},																			
"	157	":{"character":"	うんとね…	","letter": "	Yeah...	", "pinyin":"	うんとね…	"},																			
"	158	":{"character":"	グフッグフフフッ…	","letter": "	Guffaw...	", "pinyin":"	ぐふっぐふふふっ…	"},																			
"	159	":{"character":"	山吹色のお菓子でございます	","letter": "	It's a wild yellow candy.	", "pinyin":"	やまぶきいろのおかしでございます	"},																			
"	160	":{"character":"	越後屋お主もワルよのう	","letter": "	Echigoya, you're a bad boy too.	", "pinyin":"	えちごやおぬしもわるよのう	"},																			
"	161	":{"character":"	ノーノー！	","letter": "	No no no!	", "pinyin":"	のーのー！	"},																			
"	162	":{"character":"	微妙にズレてない？それ	","letter": "	Aren't you slightly off? That...	", "pinyin":"	びみょうにずれてない？それ	"},																			
"	163	":{"character":"	イマイチ強気でワイルドなイメージがつかめなくて	","letter": "	I can't quite grasp the image of him being tough and wild.	", "pinyin":"	いまいちつよきでわいるどないめーじがつかめなくて	"},																			
"	164	":{"character":"	強気でワイルドですか	","letter": "	Bullish and wild?	", "pinyin":"	つよきでわいるどですか	"},																			
"	165	":{"character":"	グリズリーくんとかそうかも	","letter": "	Like a grizzly bear, maybe.	", "pinyin":"	ぐりずりーくんとかそうかも	"},																			
"	166	":{"character":"	えっ誰？誰？	","letter": "	Who? Who?	", "pinyin":"	えっだれ？だれ？	"},																			
"	167	":{"character":"	お店やってるから夜行ってみる？	","letter": "	He runs a store. You want to go there at night?	", "pinyin":"	おみせやってるからよるいってみる？	"},																			
"	168	":{"character":"	グリズリーさんのお店ってこの辺りなの？	","letter": "	Is Mr. Grizzly's store around here?	", "pinyin":"	ぐりずりーさんのおみせってこのあたりなの？	"},																			
"	169	":{"character":"	いやもっと先	","letter": "	No, it's a little further.	", "pinyin":"	いやもっとさき	"},																			
"	170	":{"character":"	ここを抜けるとすぐそこ	","letter": "	It's right through here.	", "pinyin":"	ここをぬけるとすぐそこ	"},																			
"	171	":{"character":"	着いたよここね	","letter": "	There we are.	", "pinyin":"	ついたよここね	"},																			
"	172	":{"character":"	パンダくんこっちこっち	","letter": "	Here we are. Come on, panda, come on.	", "pinyin":"	ぱんだくんこっちこっち	"},																			
"	173	":{"character":"	確かにワイルドなお店だね	","letter": "	This sure is a wild place.	", "pinyin":"	たしかにわいるどなおみせだね	"},																			
"	174	":{"character":"	猛獣館って感じ？	","letter": "	It's like a menagerie.	", "pinyin":"	もうじゅうかんってかんじ？	"},																			
"	175	":{"character":"	こんばんはグリズリーくん	","letter": "	Good evening, grizzly.	", "pinyin":"	こんばんはぐりずりーくん	"},																			
"	176	":{"character":"	よおシロクマ久しぶりじゃねえか	","letter": "	Hey, polar bear. It's been a long time.	", "pinyin":"	よおしろくまひさしぶりじゃねえか	"},																			
"	177	":{"character":"	本当にワイルドだ…	","letter": "	He's really wild...	", "pinyin":"	ほんとうにわいるどだ…	"},																			
"	178	":{"character":"	相変わらずなまっちろい野郎だぜこのシロクマ野郎	","letter": "	You're still the same old lazy bastard, you polar bear.	", "pinyin":"	あいかわらずなまっちろいやろうだぜこのしろくまやろう	"},																			
"	179	":{"character":"	ちょっと焼いてこいよ日サロで	","letter": "	Go get a tan at the tanning salon.	", "pinyin":"	ちょっとやいてこいよひさろで	"},																			
"	180	":{"character":"	いや…行ってもたぶん変わらない	","letter": "	No... it probably won't make a difference.	", "pinyin":"	いや…いってもたぶんかわらない	"},																			
"	181	":{"character":"	今日は友達を連れてきた	","letter": "	I brought a friend today.	", "pinyin":"	きょうはともだちをつれてきた	"},																			
"	182	":{"character":"	は…はじめまして	","letter": "	Nice to meet you.	", "pinyin":"	は…はじめまして	"},																			
"	183	":{"character":"	白いのか黒いのかはっきりしねえ野郎だな	","letter": "	You're a white or black bastard.	", "pinyin":"	しろいのかくろいのかはっきりしねえやろうだな	"},																			
"	184	":{"character":"	パンダだからね	","letter": "	He's a panda.	", "pinyin":"	ぱんだだからね	"},																			
"	185	":{"character":"	まあいいか座れ	","letter": "	Well, sit down.	", "pinyin":"	まあいいかすわれ	"},																			
"	186	":{"character":"	何にする？	","letter": "	What'll it be?	", "pinyin":"	なににする？	"},																			
"	187	":{"character":"	シングルモルト	","letter": "	Single malt.	", "pinyin":"	しんぐるもると	"},																			
"	188	":{"character":"	おいパンダ	","letter": "	Hey, panda.	", "pinyin":"	おいぱんだ	"},																			
"	189	":{"character":"	はい…	","letter": "	Yes, I'll have a...	", "pinyin":"	はい…	"},																			
"	190	":{"character":"	お前は？	","letter": "	What's yours?	", "pinyin":"	おまえは？	"},																			
"	191	":{"character":"	えっと…竹大盛り	","letter": "	Uh... a big bowl of bamboo.	", "pinyin":"	えっと…たけおおもり	"},																			
"	192	":{"character":"	悪いなヘルシーなものは置いてないんだ	","letter": "	Sorry, we don't have anything healthy.	", "pinyin":"	わるいなへるしーなものはおいてないんだ	"},																			
"	193	":{"character":"	じゃ…じゃあ…アイスコーヒーお願いします	","letter": "	Well... then... can I have an iced coffee, please?	", "pinyin":"	じゃ…じゃあ…あいすこーひーおねがいします	"},																			
"	194	":{"character":"	ソフトドリンクもないね	","letter": "	No soft drinks either.	", "pinyin":"	そふとどりんくもないね	"},																			
"	195	":{"character":"	じゃあ笹の入ったパフェをお願いします	","letter": "	Then I'll have a parfait with bamboo leaves.	", "pinyin":"	じゃあささのはいったぱふぇをおねがいします	"},																			
"	196	":{"character":"	ヘルシーなものはないっつってんだろ！！	","letter": "	I told you we don't have anything healthy!	", "pinyin":"	へるしーなものはないっつってんだろ！！	"},																			
"	197	":{"character":"	グリズリーくん	","letter": "	Grizzly.	", "pinyin":"	ぐりずりーくん	"},																			
"	198	":{"character":"	しようがねえな	","letter": "	I can't help it.	", "pinyin":"	しようがねえな	"},																			
"	199	":{"character":"	シロクマの友人だ特別にコーヒーいれてやるよ	","letter": "	I'm a friend of the polar bears, so I'll make you a special coffee.	", "pinyin":"	しろくまのゆうじんだとくべつにこーひーいれてやるよ	"},																			
"	200	":{"character":"	ミルクは？	","letter": "	Milk?	", "pinyin":"	みるくは？	"},																			
"	201	":{"character":"	なしで	","letter": "	No milk?	", "pinyin":"	なしで	"},																			
"	202	":{"character":"	あっいや…ありで	","letter": "	No, with milk.	", "pinyin":"	あっいや…ありで	"},																			
"	203	":{"character":"	あっやっぱなしで	","letter": "	No milk.	", "pinyin":"	あっやっぱなしで	"},																			
"	204	":{"character":"	白黒はっきりしろ！！	","letter": "	It's black and white!	", "pinyin":"	しろくろはっきりしろ！！	"},																			
"	205	":{"character":"	もう…相変わらず短気だな	","letter": "	You've got a temper as usual, don't you?	", "pinyin":"	もう…あいかわらずたんきだな	"},																			
"	206	":{"character":"	まあパンダが白黒はっきりしたら	","letter": "	If pandas were black and white.	", "pinyin":"	まあぱんだがしろくろはっきりしたら	"},																			
"	207	":{"character":"	シロクマかただのクマになっちまうよな	","letter": "	If pandas were black and white, they'd be polar bears or just bears.	", "pinyin":"	しろくまかただのくまになっちまうよな	"},																			
"	208	":{"character":"	ハハハハハハ！	","letter": "	Ha-ha-ha-ha-ha!	", "pinyin":"	はははははは！	"},																			
"	209	":{"character":"	グリズリーさんって怖い人だね	","letter": "	You're a scary grizzly, aren't you?	", "pinyin":"	ぐりずりーさんってこわいひとだね	"},																			
"	210	":{"character":"	そう？	","letter": "	Yeah?	", "pinyin":"	そう？	"},																			
"	211	":{"character":"	よう兄ちゃん	","letter": "	Hey, bro.	", "pinyin":"	ようにいちゃん	"},																			
"	212	":{"character":"	アンタ丸々と太っててうまそうだな	","letter": "	You look so fat and delicious.	", "pinyin":"	あんたまるまるとふとっててうまそうだな	"},																			
"	213	":{"character":"	どうやって食べるのがいいかな	","letter": "	How should I eat it?	", "pinyin":"	どうやってたべるのがいいかな	"},																			
"	214	":{"character":"	丸飲みとか	","letter": "	Swallow it whole.	", "pinyin":"	まるのみとか	"},																			
"	215	":{"character":"	ヤシの実とか	","letter": "	Or coconuts.	", "pinyin":"	やしのみとか	"},																			
"	216	":{"character":"	バーベキューとか	","letter": "	Barbecue.	", "pinyin":"	ばーべきゅーとか	"},																			
"	217	":{"character":"	もろきゅうとか	","letter": "	Morokyu.	", "pinyin":"	もろきゅうとか	"},																			
"	218	":{"character":"	活け作りとか	","letter": "	Live fish...	", "pinyin":"	いけづくりとか	"},																			
"	219	":{"character":"	若作りとか	","letter": "	Wakamaki...	", "pinyin":"	わかづくりとか	"},																			
"	220	":{"character":"	おいお前！	","letter": "	Hey, you!	", "pinyin":"	おいおまえ！	"},																			
"	221	":{"character":"	あんまり他の客を怖がらすんじゃねえよ	","letter": "	Don't scare the other customers!	", "pinyin":"	あんまりほかのきゃくをこわがらすんじゃねえよ	"},																			
"	222	":{"character":"	か…帰ります！	","letter": "	I'm leaving!	", "pinyin":"	か…かえります！	"},																			
"	223	":{"character":"	おいパンダ！	","letter": "	Hey, panda!	", "pinyin":"	おいぱんだ！	"},																			
"	224	":{"character":"	悪かったなほらよコーヒーだ	","letter": "	Here's your coffee.	", "pinyin":"	わるかったなほらよこーひーだ	"},																			
"	225	":{"character":"	グリズリーさんありがとう！	","letter": "	Here you go, coffee. Thank you, grizzly!	", "pinyin":"	ぐりずりーさんありがとう！	"},																			
"	226	":{"character":"	ねぇグリズリーさん	","letter": "	Hey, Mr. Grizzly.	", "pinyin":"	ねぇぐりずりーさん	"},																			
"	227	":{"character":"	何だ？	","letter": "	What's up?	", "pinyin":"	なんだ？	"},																			
"	228	":{"character":"	あの写真ってグリズリーさんだよね？	","letter": "	That's a grizzly in the picture, right?	", "pinyin":"	あのしゃしんってぐりずりーさんだよね？	"},																			
"	229	":{"character":"	うん？おおあれか	","letter": "	Yeah? Oh, that one.	", "pinyin":"	うん？おおあれか	"},																			
"	230	":{"character":"	愛車でアメリカを横断したときのやつさ	","letter": "	That's the one where he drove his car across America.	", "pinyin":"	あいしゃであめりかをおうだんしたときのやつさ	"},																			
"	231	":{"character":"	かっこいい！	","letter": "	Oh, my God, that's so cool!	", "pinyin":"	かっこいい！	"},																			
"	232	":{"character":"	よかったぜ地平線まで続く道をぶっ飛ばしてよ	","letter": "	That's great... blasting down the road to the horizon.	", "pinyin":"	よかったぜちへいせんまでつづくみちをぶっとばしてよ	"},																			
"	233	":{"character":"	わぁ～憧れちゃうな	","letter": "	Wow, I'd love to be a part of that.	", "pinyin":"	わぁ～あこがれちゃうな	"},																			
"	234	":{"character":"	どうせお前らはスローライフとかいってダラダラ暮らしてやがんだろ？	","letter": "	You guys live the slow life anyway, don't you?	", "pinyin":"	どうせおまえらはすろーらいふとかいってだらだらくらしてやがんだろ？	"},																			
"	235	":{"character":"	ロハスって言ってよ	","letter": "	Call it LOHAS.	", "pinyin":"	ろはすっていってよ	"},																			
"	236	":{"character":"	言い方変えただけだろ	","letter": "	It's just a different way of saying it.	", "pinyin":"	いいかたかえただけだろ	"},																			
"	237	":{"character":"	ゆっくりでもそんなに変わらないよ	","letter": "	Slowly isn't going to change much.	", "pinyin":"	ゆっくりでもそんなにかわらないよ	"},																			
"	238	":{"character":"	昔からマイペースだよなお前は	","letter": "	You've always taken things at your own pace.	", "pinyin":"	むかしからまいぺーすだよなおまえは	"},																			
"	239	":{"character":"	人生は一度きりだぜ	","letter": "	You only live once.	", "pinyin":"	じんせいはいちどきりだぜ	"},																			
"	240	":{"character":"	熱くぶっ飛ばさなきゃな	","letter": "	You gotta go out with a bang.	", "pinyin":"	あつくぶっとばさなきゃな	"},																			
"	241	":{"character":"	グリズリーさんすごくかっこいいね	","letter": "	You're so cool, grizzly.	", "pinyin":"	ぐりずりーさんすごくかっこいいね	"},																			
"	242	":{"character":"	僕そういうの大好き！	","letter": "	I love it!	", "pinyin":"	ぼくそういうのだいすき！	"},																			
"	243	":{"character":"	おっ？シロクマの知り合いにしちゃあ	","letter": "	What? For a guy who knows polar bears.	", "pinyin":"	おっ？しろくまのしりあいにしちゃあ	"},																			
"	244	":{"character":"	話のわかるヤツじゃないか	","letter": "	You know, for a guy who knows polar bears, you sure know what you're talking about.	", "pinyin":"	はなしのわかるやつじゃないか	"},																			
"	245	":{"character":"	ほら冷めちまうぞ飲めよ	","letter": "	Here, drink up, it's getting cold.	", "pinyin":"	ほらさめちまうぞのめよ	"},																			
"	246	":{"character":"	うん！	","letter": "	Drink up.	", "pinyin":"	うん！	"},																			
"	247	":{"character":"	どうだ？アイリッシュコーヒーにしてみたんだ	","letter": "	What do you think? I made you an Irish coffee.	", "pinyin":"	どうだ？あいりっしゅこーひーにしてみたんだ	"},																			
"	248	":{"character":"	まっコーヒーよりウイスキーのほうが多かったかもな	","letter": "	Well, it was more whiskey than coffee.	", "pinyin":"	まっこーひーよりういすきーのほうがおおかったかもな	"},																			
"	249	":{"character":"	えっ？それは…	","letter": "	What? That's...	", "pinyin":"	えっ？それは…	"},																			
"	250	":{"character":"	バルルルル…グフッフフフ	","letter": "	Barlle-lulu... guffaw.	", "pinyin":"	ばるるるる…ぐふっふふふ	"},																			
"	251	":{"character":"	またソイツと来いよ	","letter": "	Come again with him.	", "pinyin":"	またそいつとこいよ	"},																			
"	252	":{"character":"	今度はインスタントじゃないコーヒーをいれてやるから	","letter": "	I'll make you a coffee that's not instant this time.	", "pinyin":"	こんどはいんすたんとじゃないこーひーをいれてやるから	"},																			
"	253	":{"character":"	うんマイルドでよろしくね	","letter": "	Mild coffee, please.	", "pinyin":"	うんまいるどでよろしくね	"},																			
"	254	":{"character":"	あれ？	","letter": "	What?	", "pinyin":"	あれ？	"},																			
"	255	":{"character":"	目が覚めた？	","letter": "	You're awake?	", "pinyin":"	めがさめた？	"},																			
"	256	":{"character":"	シロクマくん運んでくれたんだね	","letter": "	Polar bear, you brought me here.	", "pinyin":"	しろくまくんはこんでくれたんだね	"},																			
"	257	":{"character":"	うん	","letter": "	Yeah, I did.	", "pinyin":"	うん	"},																			
"	258	":{"character":"	ありがとう	","letter": "	Thank you.	", "pinyin":"	ありがとう	"},																			
"	259	":{"character":"	いいよ別に	","letter": "	No problem.	", "pinyin":"	いいよべつに	"},																			
"	260	":{"character":"	それともうひとつありがとう	","letter": "	And thanks for the other thing.	", "pinyin":"	それともうひとつありがとう	"},																			
"	261	":{"character":"	えっ？	","letter": "	What?	", "pinyin":"	えっ？	"},																			
"	262	":{"character":"	僕だいぶワイルドってのがわかった気がするよ	","letter": "	I think I'm starting to understand wild.	", "pinyin":"	ぼくだいぶわいるどってのがわかったきがするよ	"},																			
"	263	":{"character":"	そうそれならよかった	","letter": "	Well, that's good.	", "pinyin":"	そうそれならよかった	"},																			
"	264	":{"character":"	シロクマくんどう？これ	","letter": "	What do you think, Polar Bear? What do you think, Polar Bear?	", "pinyin":"	しろくまくんどう？これ	"},																			
"	265	":{"character":"	ワイルド？	","letter": "	Wild?	", "pinyin":"	わいるど？	"},																			
"	266	":{"character":"	いやぁマイルドかな	","letter": "	Mild.	", "pinyin":"	いやぁまいるどかな	"},																			
"	267	":{"character":"	じゃあ！	","letter": "	Okay, then.	", "pinyin":"	じゃあ！	"},																			
"	268	":{"character":"	あれ？パンダくんどこ行くの？	","letter": "	What's that? Where are you going, panda?	", "pinyin":"	あれ？ぱんだくんどこいくの？	"},																			
"	269	":{"character":"	ワルは後ろを振り返らない	","letter": "	Badass never looks back.	", "pinyin":"	わるはうしろをふりかえらない	"},																			
"	270	":{"character":"	あっそう…	","letter": "	Oh, yeah...	", "pinyin":"	あっそう…	"},																			
"	271	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguins! Penguins!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	272	":{"character":"	どうしたのパンダ君	","letter": "	What's wrong, Mr. Panda?	", "pinyin":"	どうしたのぱんだくん	"},																			
"	273	":{"character":"	ペンギンさんってどうしてみんなに嫌われてるんだっけ	","letter": "	Why does everyone hate Mr. Penguin?	", "pinyin":"	ぺんぎんさんってどうしてみんなにきらわれてるんだっけ	"},																			
"	274	":{"character":"	そんな事実ないでしょう	","letter": "	That's not true.	", "pinyin":"	そんなじじつないでしょう	"},																			
"	275	":{"character":"	人気ものだよ僕は	","letter": "	I'm popular.	", "pinyin":"	にんきものだよぼくは	"},																			
"	276	":{"character":"	どっちでもいいじゃない	","letter": "	I don't care.	", "pinyin":"	どっちでもいいじゃない	"},																			
"	277	":{"character":"	次回のしろくまカフェは	","letter": "	Next time at the Shirokuma Cafe...	", "pinyin":"	じかいのしろくまかふぇは	"},																			
"	278	":{"character":"	鉛筆書きでお送りします	","letter": "	I'll send you a pencil drawing.	", "pinyin":"	えんぴつがきでおおくりします	"},																			
"	279	":{"character":"	塗ります	","letter": "	I'll paint.	", "pinyin":"	ぬります	"},																			
"	280	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
																									
}