obj = {
"	1	":{"character":"	笹子さんくいすぎ	","letter": "	Sasago-san eats too much	", "pinyin":"	ささごさんくいすぎ	"},																			
"	2	":{"character":"	あ動きます	","letter": "	Oh, I'll move.	", "pinyin":"	あうごきます	"},																			
"	3	":{"character":"	白熊君張切る	","letter": "	Polar bear, I'm going to cut you off!	", "pinyin":"	しろくまくんはりきる	"},																			
"	4	":{"character":"	どうしたのパンダ君溜息なんかついて	","letter": "	Panda, what's wrong with your sigh?	", "pinyin":"	どうしたのぱんだくんためいきなんかついて	"},																			
"	5	":{"character":"	バイト行きたくないよ	","letter": "	I don't want to go to work.	", "pinyin":"	ばいといきたくないよ	"},																			
"	6	":{"character":"	またそれ	","letter": "	There you go again.	", "pinyin":"	またそれ	"},																			
"	7	":{"character":"	本当に何もすることなくて超退屈なんだもん	","letter": "	I'm really bored because there's nothing to do.	", "pinyin":"	ほんとうになにもすることなくてちょうたいくつなんだもん	"},																			
"	8	":{"character":"	常勤パンダさんとあっち向いてほいとかしても	","letter": "	I'm bored to death.	", "pinyin":"	じょうきんぱんださんとあっちむいてほいとかしても	"},																			
"	9	":{"character":"	十五分ぐらい厭きるし	","letter": "	I'm bored for about 15 minutes.	", "pinyin":"	じゅうごふんぐらいあきるし	"},																			
"	10	":{"character":"	よく十五分もできるね	","letter": "	How can you do that for 15 minutes?	", "pinyin":"	よくじゅうごふんもできるね	"},																			
"	11	":{"character":"	十五秒で厭きるよ	","letter": "	I get bored after 15 seconds.	", "pinyin":"	じゅうごびょうであきるよ	"},																			
"	12	":{"character":"	ペンギンさん時間潰すのって大変だよ	","letter": "	Penguin, it's hard to kill time.	", "pinyin":"	ぺんぎんさんじかんつぶすのってたいへんだよ	"},																			
"	13	":{"character":"	仕方ないからいっぱいお昼寝してたら	","letter": "	I had no choice but to take a lot of naps.	", "pinyin":"	しかたないからいっぱいおひるねしてたら	"},																			
"	14	":{"character":"	寝違えって首回らなくなっちゃうし	","letter": "	I'll get a headache.	", "pinyin":"	ねちがえってくびまわらなくなっちゃうし	"},																			
"	15	":{"character":"	ぶーくりおやつ食べてもちょっびとの時間しか経たないし	","letter": "	I only have a little time to eat my snacks.	", "pinyin":"	ぶーくりおやつたべてもちょっびとのじかんしかたたないし	"},																			
"	16	":{"character":"	パンダのバイト始めてからおやつの食べ過ぎで太っちゃった	","letter": "	I've gained weight from eating too many snacks since I started working as a panda	", "pinyin":"	ぱんだのばいとはじめてからおやつのたべすぎでふとっちゃった	"},																			
"	17	":{"character":"	また	","letter": "	Also...	", "pinyin":"	また	"},																			
"	18	":{"character":"	バイトのせいだよ	","letter": "	It's because of the part-time job.	", "pinyin":"	ばいとのせいだよ	"},																			
"	19	":{"character":"	それだけが理由かな	","letter": "	Is that the only reason?	", "pinyin":"	それだけがりゆうかな	"},																			
"	20	":{"character":"	そうだよバイトしてるから太るんだよ	","letter": "	That's right... my part-time job is making me fat.	", "pinyin":"	そうだよばいとしてるからふとるんだよ	"},																			
"	21	":{"character":"	パンダ君のバイトって週二日だよね	","letter": "	Panda, you work two days a week, right?	", "pinyin":"	ぱんだくんのばいとってしゅうふつかだよね	"},																			
"	22	":{"character":"	週二日で文句言わないでよ	","letter": "	Don't complain about two days a week.	", "pinyin":"	しゅうふつかでもんくいわないでよ	"},																			
"	23	":{"character":"	むしろ毎日行こうよ	","letter": "	I'd rather go every day.	", "pinyin":"	むしろまいにちいこうよ	"},																			
"	24	":{"character":"	そうだね	","letter": "	I agree.	", "pinyin":"	そうだね	"},																			
"	25	":{"character":"	そうだよ	","letter": "	Yeah, I agree.	", "pinyin":"	そうだよ	"},																			
"	26	":{"character":"	週一日にしようかな	","letter": "	I'll go one day a week.	", "pinyin":"	しゅういちにちにしようかな	"},																			
"	27	":{"character":"	減らすの	","letter": "	Less.	", "pinyin":"	へらすの	"},																			
"	28	":{"character":"	いいな僕は仕事忙しくてもう少し暇になりたい	","letter": "	I've got a lot of work to do, and I'd like to have a little more free time.	", "pinyin":"	いいなぼくはしごといそがしくてもうすこしひまになりたい	"},																			
"	29	":{"character":"	そうなの	","letter": "	Yeah.	", "pinyin":"	そうなの	"},																			
"	30	":{"character":"	偶には気分転換したいね	","letter": "	I'd like a change of scenery once in a while.	", "pinyin":"	たまにはきぶんてんかんしたいね	"},																			
"	31	":{"character":"	お店忙しいですもんね	","letter": "	You're a busy man, aren't you?	", "pinyin":"	おみせいそがしいですもんね	"},																			
"	32	":{"character":"	あいいなぁ忙しいの	","letter": "	I'd love to be busy.	", "pinyin":"	あいいなぁいそがしいの	"},																			
"	33	":{"character":"	パンダ君になってゴロゴロしたい	","letter": "	I'd like to be a panda and just relax.	", "pinyin":"	ぱんだくんになってごろごろしたい	"},																			
"	34	":{"character":"	もう二人ともないもの強請りなんだから	","letter": "	You're both begging for things you don't have.	", "pinyin":"	もうふたりともないものねだりなんだから	"},																			
"	35	":{"character":"	笹子さん何か言ってやってよ	","letter": "	Sasako, say something to him.	", "pinyin":"	ささごさんなにかいってやってよ	"},																			
"	36	":{"character":"	そう言われても…	","letter": "	I don't know...	", "pinyin":"	そういわれても…	"},																			
"	37	":{"character":"	いい事思いついちゃった	","letter": "	I've got an idea.	", "pinyin":"	いいことおもいついちゃった	"},																			
"	38	":{"character":"	何ですか	","letter": "	What is it?	", "pinyin":"	なんですか	"},																			
"	39	":{"character":"	パンダ君一日だけ入れ替わってみない？	","letter": "	Panda... why don't you switch places for a day?	", "pinyin":"	ぱんだくんいちにちだけいれかわってみない？	"},																			
"	40	":{"character":"	僕が動物園へパンダのバイトに行くから	","letter": "	I'll go to the zoo and work as a panda.	", "pinyin":"	ぼくがどうぶつえんへぱんだのばいとにいくから	"},																			
"	41	":{"character":"	パンダ君は白熊カフェでマスターするの	","letter": "	I'll go to the zoo to work as a panda, and you go to the Polar Bear Cafe to be a master.	", "pinyin":"	ぱんだくんはしろくまかふぇでますたーするの	"},																			
"	42	":{"character":"	いやいや無理でしょ	","letter": "	No, no, no, no, no, no, no, no, no, no, no, no, no.	", "pinyin":"	いやいやむりでしょ	"},																			
"	43	":{"character":"	いいなぁ	","letter": "	I'd love to.	", "pinyin":"	いいなぁ	"},																			
"	44	":{"character":"	白熊君ってかっこいいから一回やってみたっかたんだ	","letter": "	Polar bears are so cool, I've always wanted to try one.	", "pinyin":"	しろくまくんってかっこいいからいっかいやってみたっかたんだ	"},																			
"	45	":{"character":"	いや無理でしょ	","letter": "	No, you can't.	", "pinyin":"	いやむりでしょ	"},																			
"	46	":{"character":"	へぇそうかな	","letter": "	Oh, really?	", "pinyin":"	へぇそうかな	"},																			
"	47	":{"character":"	白熊君変なこと言わないでよ	","letter": "	Don't say weird things about me, polar bear.	", "pinyin":"	しろくまくんへんなこといわないでよ	"},																			
"	48	":{"character":"	あおはようパンダ君	","letter": "	Good morning, panda.	", "pinyin":"	あおはようぱんだくん	"},																			
"	49	":{"character":"	…じゃないですよね	","letter": "	I'm not a...	", "pinyin":"	…じゃないですよね	"},																			
"	50	":{"character":"	パンダで~す	","letter": "	I'm a panda.	", "pinyin":"	ぱんだで~す	"},																			
"	51	":{"character":"	パンダコーナーってこっちだっけ？	","letter": "	Panda Corner is this way?	", "pinyin":"	ぱんだこーなーってこっちだっけ？	"},																			
"	52	":{"character":"	ちょっと待ってよ！白熊君でしょ？	","letter": "	Wait a minute! You're a polar bear, right?	", "pinyin":"	ちょっとまってよ！しろくまくんでしょ？	"},																			
"	53	":{"character":"	あればれちゃった	","letter": "	I've been spotted.	", "pinyin":"	あればれちゃった	"},																			
"	54	":{"character":"	半田さん平気平気	","letter": "	Don't worry, Mr. Handa.	", "pinyin":"	はんでんさんへいきへいき	"},																			
"	55	":{"character":"	お客さんには熊の区別なんてつかないから	","letter": "	The customers can't tell the difference between a bear and a polar bear.	", "pinyin":"	おきゃくさんにはくまのくべつなんてつかないから	"},																			
"	56	":{"character":"	何言ってるの	","letter": "	What are you talking about?	", "pinyin":"	なにいってるの	"},																			
"	57	":{"character":"	白熊君なの物分りだよ	","letter": "	It's a polar bear. I know what it is.	", "pinyin":"	しろくまくんなのものわかりだよ	"},																			
"	58	":{"character":"	帰って帰って	","letter": "	Go home.	", "pinyin":"	かえってかえって	"},																			
"	59	":{"character":"	待ってください先輩	","letter": "	Wait, sir!	", "pinyin":"	まってくださいせんぱい	"},																			
"	60	":{"character":"	何だ桐野	","letter": "	What is it, Kirino?	", "pinyin":"	なんだきりの	"},																			
"	61	":{"character":"	今日は常勤パンダさんが有給休暇で休みですよ	","letter": "	Today's the day off for the full-time panda.	", "pinyin":"	きょうはじょうきんぱんださんがゆうきゅうきゅうかでやすみですよ	"},																			
"	62	":{"character":"	そうなると…	","letter": "	That means...	", "pinyin":"	そうなると…	"},																			
"	63	":{"character":"	ママパンダさんいないよ	","letter": "	Mama Panda's not here.	", "pinyin":"	ままぱんださんいないよ	"},																			
"	64	":{"character":"	白熊君パンダ君は？	","letter": "	Where's Mr. Panda, Polar Bear?	", "pinyin":"	しろくまくんぱんだくんは？	"},																			
"	65	":{"character":"	今日は来ないよ	","letter": "	He's not coming today.	", "pinyin":"	きょうはこないよ	"},																			
"	66	":{"character":"	今すぐ呼んで！	","letter": "	Call him now!	", "pinyin":"	いますぐよんで！	"},																			
"	67	":{"character":"	今から呼んでも間に合わないよ	","letter": "	If we call him now, he'll never get here in time.	", "pinyin":"	いまからよんでもまにあわないよ	"},																			
"	68	":{"character":"	大丈夫任せて	","letter": "	Don't worry, I'll take care of it.	", "pinyin":"	だいじょうぶまかせて	"},																			
"	69	":{"character":"	な…なるべく目立たないようにお願いします	","letter": "	Please be as inconspicuous as possible.	", "pinyin":"	な…なるべくめだたないようにおねがいします	"},																			
"	70	":{"character":"	は～い～頑張ります	","letter": "	I'll do my best.	", "pinyin":"	は～い～がんばります	"},																			
"	71	":{"character":"	パンダ君美味しそうな笹が手に入ったから	","letter": "	Panda, I got some delicious looking bamboo grass.	", "pinyin":"	ぱんだくんおいしそうなささがてにはいったから	"},																			
"	72	":{"character":"	差し入れだ…よっ	","letter": "	I brought you some...	", "pinyin":"	さしいれだ…よっ	"},																			
"	73	":{"character":"	パンダで～す	","letter": "	I'm a panda!	", "pinyin":"	ぱんだで～す	"},																			
"	74	":{"character":"	気になって見に来ちゃったよ	","letter": "	I was curious... so I came to see.	", "pinyin":"	きになってみにきちゃったよ	"},																			
"	75	":{"character":"	パンダだよ	","letter": "	It's a panda!	", "pinyin":"	ぱんだだよ	"},																			
"	76	":{"character":"	何だか熱があるみたいだ	","letter": "	You seem to have a fever.	", "pinyin":"	なんだかねつがあるみたいだ	"},																			
"	77	":{"character":"	あれ？可愛くない？	","letter": "	What? Isn't he cute?	", "pinyin":"	あれ？かわいくない？	"},																			
"	78	":{"character":"	変だなぁ…	","letter": "	That's weird.	", "pinyin":"	へんだなぁ…	"},																			
"	79	":{"character":"	やっぱり無理だよ全然違うよ	","letter": "	I can't believe it, it's not even close.	", "pinyin":"	やっぱりむりだよぜんぜんちがうよ	"},																			
"	80	":{"character":"	あれがパンダ？	","letter": "	Is that a panda?	", "pinyin":"	あれがぱんだ？	"},																			
"	81	":{"character":"	何が違くねぇ？長すぎるっていうかでか過ぎねぇ？	","letter": "	What's wrong? It's too long or too big or something.	", "pinyin":"	なにがたがいくねぇ？ながすぎるっていうかでかすぎねぇ？	"},																			
"	82	":{"character":"	でも俺ら生パンダ見るの始めてたし	","letter": "	But we've never seen a live panda before.	", "pinyin":"	でもおれらなまぱんだみるのはじめてたし	"},																			
"	83	":{"character":"	ああいうのかも	","letter": "	Maybe it's like that.	", "pinyin":"	ああいうのかも	"},																			
"	84	":{"character":"	そうだけどうさぁ…	","letter": "	Yeah, but...	", "pinyin":"	そうだけどうさぁ…	"},																			
"	85	":{"character":"	なんかあのシルエットは白熊じゃねぇ？	","letter": "	That silhouette looks like a polar bear.	", "pinyin":"	なんかあのしるえっとはしろくまじゃねぇ？	"},																			
"	86	":{"character":"	おっといけない	","letter": "	Oh, no!	", "pinyin":"	おっといけない	"},																			
"	87	":{"character":"	アイテム装備	","letter": "	I'm going to equip myself with the item.	", "pinyin":"	あいてむそうび	"},																			
"	88	":{"character":"	そうして技を使う	","letter": "	Then I'll do the trick.	", "pinyin":"	そうしてわざをつかう	"},																			
"	89	":{"character":"	ほらやっぱりパンダだよ	","letter": "	I'm a panda!	", "pinyin":"	ほらやっぱりぱんだだよ	"},																			
"	90	":{"character":"	あはは本当だ	","letter": "	I'm right!	", "pinyin":"	あははほんとうだ	"},																			
"	91	":{"character":"	パンダさん	","letter": "	A panda.	", "pinyin":"	ぱんださん	"},																			
"	92	":{"character":"	でけぇ	","letter": "	He's so big!	", "pinyin":"	でけぇ	"},																			
"	93	":{"character":"	白熊君グッドジョブ	","letter": "	Good job, polar bear.	", "pinyin":"	しろくまくんぐっどじょぶ	"},																			
"	94	":{"character":"	かしこまりました	","letter": "	Yes, sir.	", "pinyin":"	かしこまりました	"},																			
"	95	":{"character":"	すみません	","letter": "	Excuse me, sir.	", "pinyin":"	すみません	"},																			
"	96	":{"character":"	はいただいま	","letter": "	I'm home.	", "pinyin":"	はいただいま	"},																			
"	97	":{"character":"	確かに暇な仕事だ	","letter": "	You're right, it's a slow job.	", "pinyin":"	たしかにひまなしごとだ	"},																			
"	98	":{"character":"	あんまり動かないなぁ	","letter": "	I don't move around much.	", "pinyin":"	あんまりうごかないなぁ	"},																			
"	99	":{"character":"	パンダだもん仕方ないよ	","letter": "	Well, it's just pandas, that's all.	", "pinyin":"	ぱんだだもんしかたないよ	"},																			
"	100	":{"character":"	おっとサービスサービス	","letter": "	Service, service, service.	", "pinyin":"	おっとさーびすさーびす	"},																			
"	101	":{"character":"	あれタイヤでどうやって遊べばいいんだっけ	","letter": "	I don't know how to play with those tires.	", "pinyin":"	あれたいやでどうやってあそべばいいんだっけ	"},																			
"	102	":{"character":"	困ってねぇ	","letter": "	I'm stumped.	", "pinyin":"	こまってねぇ	"},																			
"	103	":{"character":"	パンダさんどうしたの	","letter": "	What's wrong with the panda?	", "pinyin":"	ぱんださんどうしたの	"},																			
"	104	":{"character":"	どうしよう皆怪しんでるよ	","letter": "	Oh, my God... people are getting suspicious.	", "pinyin":"	どうしようみんなあやしんでるよ	"},																			
"	105	":{"character":"	おほ遊んでる遊んでる	","letter": "	Oh, they're playing, they're playing, they're playing.	", "pinyin":"	おほあそんでるあそんでる	"},																			
"	106	":{"character":"	何だ今の	","letter": "	What was that?	", "pinyin":"	なんだいまの	"},																			
"	107	":{"character":"	もう白熊君がありえない動きするから	","letter": "	What's that? A polar bear is making unbelievable moves.	", "pinyin":"	もうしろくまくんがありえないうごきするから	"},																			
"	108	":{"character":"	生パンダはやっぱ違うなぁ	","letter": "	I've never seen a live panda.	", "pinyin":"	なまぱんだはやっぱちがうなぁ	"},																			
"	109	":{"character":"	セーフ	","letter": "	Safe.	", "pinyin":"	せーふ	"},																			
"	110	":{"character":"	よしもっとサービスしよう	","letter": "	All right, let's serve him some more.	", "pinyin":"	よしもっとさーびすしよう	"},																			
"	111	":{"character":"	うわっ白熊だ	","letter": "	Oh, it's a polar bear.	", "pinyin":"	うわっしろくまだ	"},																			
"	112	":{"character":"	うぉっパンダだ	","letter": "	A panda!	", "pinyin":"	うぉっぱんだだ	"},																			
"	113	":{"character":"	うわっ白熊だ	","letter": "	It's a polar bear!	", "pinyin":"	うわっしろくまだ	"},																			
"	114	":{"character":"	うぉっパンダだ	","letter": "	It's a panda!	", "pinyin":"	うぉっぱんだだ	"},																			
"	115	":{"character":"	うわっ白熊だ	","letter": "	Oh, it's a polar bear!	", "pinyin":"	うわっしろくまだ	"},																			
"	116	":{"character":"	うわっパンダだ	","letter": "	It's a panda!	", "pinyin":"	うわっぱんだだ	"},																			
"	117	":{"character":"	ちょっちょっちょっ白熊君	","letter": "	Hey, hey, hey, hey, Mr. White Bear!	", "pinyin":"	ちょっちょっちょっしろくまくん	"},																			
"	118	":{"character":"	（パンダ白熊パンダ白熊……）	","letter": "	(Panda polar bear panda polar bear ......)	", "pinyin":"	（ぱんだしろくまぱんだしろくま……）	"},																			
"	119	":{"character":"	パンダがいないとまずい	","letter": "	It's bad without pandas	", "pinyin":"	ぱんだがいないとまずい	"},																			
"	120	":{"character":"	白熊パンダがばれてもやばすぎる	","letter": "	It's too bad if they find out about the polar bear panda	", "pinyin":"	しろくまぱんだがばれてもやばすぎる	"},																			
"	121	":{"character":"	はぁ…始末書の用意しといたほうがいいかな	","letter": "	I'd better prepare a letter of explanation...	", "pinyin":"	はぁ…しまつしょのよういしといたほうがいいかな	"},																			
"	122	":{"character":"	半田さん大変です	","letter": "	Mr. Handa is in trouble!	", "pinyin":"	はんでんさんたいへんです	"},																			
"	123	":{"character":"	あ！ついに来た！ついにばれた	","letter": "	Ah! Finally! They finally found out!	", "pinyin":"	あ！ついにきた！ついにばれた	"},																			
"	124	":{"character":"	パンダ君が大人気ですよ	","letter": "	Mr. Panda is very popular.	", "pinyin":"	ぱんだくんがだいにんきですよ	"},																			
"	125	":{"character":"	どうしよう！え？	","letter": "	Oh, my God! What?	", "pinyin":"	どうしよう！え？	"},																			
"	126	":{"character":"	よし	","letter": "	Okay, okay.	", "pinyin":"	よし	"},																			
"	127	":{"character":"	すげぇーあの距離を沈めたぞ	","letter": "	Wow, he sank it from that distance!	", "pinyin":"	すげぇーあのきょりをしずめたぞ	"},																			
"	128	":{"character":"	マスタスでられじゃねぇ？	","letter": "	I think we're gonna get it from Mastas.	", "pinyin":"	ますたすでられじゃねぇ？	"},																			
"	129	":{"character":"	どうもどうも	","letter": "	Thank you, thank you, thank you.	", "pinyin":"	どうもどうも	"},																			
"	130	":{"character":"	パンダさんかっこいい	","letter": "	Pandas are so cool!	", "pinyin":"	ぱんださんかっこいい	"},																			
"	131	":{"character":"	パンダグッズも飛ぶように売れてます	","letter": "	Panda merchandise is selling like hotcakes.	", "pinyin":"	ぱんだぐっずもとぶようにうれてます	"},																			
"	132	":{"character":"	このパンダティシャツください	","letter": "	I want this panda tee shirt.	", "pinyin":"	このぱんだてぃしゃつください	"},																			
"	133	":{"character":"	パンダバッグ三色全部	","letter": "	Panda bags in all three colors!	", "pinyin":"	ぱんだばっぐさんしょくぜんぶ	"},																			
"	134	":{"character":"	半田さん大成功でしょ	","letter": "	Mr. Handa, you're a big success, aren't you?	", "pinyin":"	はんでんさんだいせいこうでしょ	"},																			
"	135	":{"character":"	そういえばあっちはどうなったかな	","letter": "	Oh, by the way, what happened to the other one?	", "pinyin":"	そういえばあっちはどうなったかな	"},																			
"	136	":{"character":"	こんにちは	","letter": "	Hello.	", "pinyin":"	こんにちは	"},																			
"	137	":{"character":"	いらっしゃいませ	","letter": "	Welcome.	", "pinyin":"	いらっしゃいませ	"},																			
"	138	":{"character":"	なにしようかなえっと	","letter": "	What can I do for you?	", "pinyin":"	なにしようかなえっと	"},																			
"	139	":{"character":"	いやその白熊にしてはちょっと小さいというか	","letter": "	Well, you're a little small for a polar bear, aren't you?	", "pinyin":"	いやそのしろくまにしてはちょっとちいさいというか	"},																			
"	140	":{"character":"	パンダ君だよね	","letter": "	You're a panda, right?	", "pinyin":"	ぱんだくんだよね	"},																			
"	141	":{"character":"	いいえ白熊ですよ	","letter": "	No, it's a polar bear.	", "pinyin":"	いいえしろくまですよ	"},																			
"	142	":{"character":"	白熊君どこ行ったの	","letter": "	Hey, polar bear, where'd you go?	", "pinyin":"	しろくまくんどこいったの	"},																			
"	143	":{"character":"	ここにいますよ	","letter": "	I'm right here.	", "pinyin":"	ここにいますよ	"},																			
"	144	":{"character":"	ばればれだね	","letter": "	I know, I know.	", "pinyin":"	ばればれだね	"},																			
"	145	":{"character":"	ですね	","letter": "	I know.	", "pinyin":"	ですね	"},																			
"	146	":{"character":"	海に行こう	","letter": "	Let's go to the beach.	", "pinyin":"	うみにいこう	"},																			
"	147	":{"character":"	いらっしゃいませ	","letter": "	Welcome to the beach!	", "pinyin":"	いらっしゃいませ	"},																			
"	148	":{"character":"	あれ今日白熊君は	","letter": "	Where's Mr. Polar Bear?	", "pinyin":"	あれきょうしろくまくんは	"},																			
"	149	":{"character":"	お出かけなんですよ	","letter": "	Mr. Polar Bear is going out today.	", "pinyin":"	おでかけなんですよ	"},																			
"	150	":{"character":"	やってきました海	","letter": "	Here we are at the beach.	", "pinyin":"	やってきましたうみ	"},																			
"	151	":{"character":"	海	","letter": "	The ocean!	", "pinyin":"	うみ	"},																			
"	152	":{"character":"	夏は海だよね	","letter": "	Summer is for the sea, right?	", "pinyin":"	なつはうみだよね	"},																			
"	153	":{"character":"	ペンギンさんどうこのシャツおニュウなんだ	","letter": "	Penguin, how do you like this shirt?	", "pinyin":"	ぺんぎんさんどうこのしゃつおにゅうなんだ	"},																			
"	154	":{"character":"	パンダ君普段何にも着てないのに	","letter": "	Panda, you're not usually wearing anything	", "pinyin":"	ぱんだくんふだんなんにもきてないのに	"},																			
"	155	":{"character":"	シーンにあわせた装い	","letter": "	I'm dressed for the scene	", "pinyin":"	しーんにあわせたよそおい	"},																			
"	156	":{"character":"	何のシーンなんだか	","letter": "	I don't know what the scene is	", "pinyin":"	なにのしーんなんだか	"},																			
"	157	":{"character":"	早く着替えて泳ごう	","letter": "	Let's get changed and go for a swim!	", "pinyin":"	はやくきがえておよごう	"},																			
"	158	":{"character":"	ええもっとゆっくりしようよ白熊君	","letter": "	Yeah, let's take it slow, polar bear.	", "pinyin":"	ええもっとゆっくりしようよしろくまくん	"},																			
"	159	":{"character":"	あれパンダや	","letter": "	That's a panda!	", "pinyin":"	あれぱんだや	"},																			
"	160	":{"character":"	ほんまや海にパンダがいてるわ	","letter": "	Oh, yeah, there's a panda in the ocean.	", "pinyin":"	ほんまやうみにぱんだがいてるわ	"},																			
"	161	":{"character":"	アロハ着て可愛らしいな	","letter": "	You look so cute in your aloha.	", "pinyin":"	あろはきてかわいらしいな	"},																			
"	162	":{"character":"	これからどこ行くん	","letter": "	Where are you going?	", "pinyin":"	これからどこいくん	"},																			
"	163	":{"character":"	飴ちゃあげようか	","letter": "	Where are you going?	", "pinyin":"	あめちゃあげようか	"},																			
"	164	":{"character":"	ありがとう	","letter": "	Thanks, I'll give you a candy bar.	", "pinyin":"	ありがとう	"},																			
"	165	":{"character":"	ほなな気ィつけてな	","letter": "	You take care of yourself.	", "pinyin":"	ほななきぃつけてな	"},																			
"	166	":{"character":"	モテモテだよ	","letter": "	You're a hit with the ladies.	", "pinyin":"	もてもてだよ	"},																			
"	167	":{"character":"	あれ白熊君は	","letter": "	Hey, where's Polar Bear?	", "pinyin":"	あれしろくまくんは	"},																			
"	168	":{"character":"	あっち	","letter": "	Over there.	", "pinyin":"	あっち	"},																			
"	169	":{"character":"	素敵	","letter": "	Nice.	", "pinyin":"	すてき	"},																			
"	170	":{"character":"	かっこいい	","letter": "	He's so cool.	", "pinyin":"	かっこいい	"},																			
"	171	":{"character":"	モテモテだね	","letter": "	You're irresistible.	", "pinyin":"	もてもてだね	"},																			
"	172	":{"character":"	白熊君早く行かないと日が暮れちゃうよ	","letter": "	Polar Bear, we've got to get going, it's getting dark.	", "pinyin":"	しろくまくんはやくいかないとひがくれちゃうよ	"},																			
"	173	":{"character":"	さっきまでゆっくりしようって言ってたのに	","letter": "	We were just talking about taking it easy.	", "pinyin":"	さっきまでゆっくりしようっていってたのに	"},																			
"	174	":{"character":"	やっぱり着替えるんだ	","letter": "	I knew you'd change.	", "pinyin":"	やっぱりきがえるんだ	"},																			
"	175	":{"character":"	ペンギンさんこそいつも同じで飽きないの	","letter": "	You penguins never get tired of doing the same thing all the time.	", "pinyin":"	ぺんぎんさんこそいつもおなじであきないの	"},																			
"	176	":{"character":"	パンダ君だっていつもは大体同じじゃない	","letter": "	You're always the same, panda.	", "pinyin":"	ぱんだくんだっていつもはだいたいおなじじゃない	"},																			
"	177	":{"character":"	まず何しようか	","letter": "	What shall we do first?	", "pinyin":"	まずなにしようか	"},																			
"	178	":{"character":"	僕魚とりに行く	","letter": "	I'm going fishing.	", "pinyin":"	ぼくさかなとりにいく	"},																			
"	179	":{"character":"	僕はお昼寝	","letter": "	I'm going to take a nap.	", "pinyin":"	ぼくはおひるね	"},																			
"	180	":{"character":"	いい波だね	","letter": "	Nice waves, huh?	", "pinyin":"	いいなみだね	"},																			
"	181	":{"character":"	皆ばらばらだな	","letter": "	Everyone's so scattered.	", "pinyin":"	みんなばらばらだな	"},																			
"	182	":{"character":"	せっかく皆で来てるんだからさ	","letter": "	We're all here together.	", "pinyin":"	せっかくみんなできてるんだからさ	"},																			
"	183	":{"character":"	一緒になんかやろうよ	","letter": "	Let's do something together.	", "pinyin":"	いっしょになんかやろうよ	"},																			
"	184	":{"character":"	あっちでシーカヤックを貸してくれるらしいよ	","letter": "	They rent sea kayaks over there.	", "pinyin":"	あっちでしーかやっくをかしてくれるらしいよ	"},																			
"	185	":{"character":"	何それ	","letter": "	What's that?	", "pinyin":"	なにそれ	"},																			
"	186	":{"character":"	知らないけどやりたい	","letter": "	I don't know, but I want to.	", "pinyin":"	しらないけどやりたい	"},																			
"	187	":{"character":"	うん見渡す限りの水平線気持ちがいいね	","letter": "	Yeah, the horizon as far as the eye can see.	", "pinyin":"	うんみわたすかぎりのすいへいせんきもちがいいね	"},																			
"	188	":{"character":"	難しいよ白熊君どうやるの	","letter": "	It's hard, polar bear, how do you do it?	", "pinyin":"	むずかしいよしろくまくんどうやるの	"},																			
"	189	":{"character":"	水面深くまでパドルを入れないで	","letter": "	Don't let the paddle go too deep into the water.	", "pinyin":"	すいめんふかくまでぱどるをいれないで	"},																			
"	190	":{"character":"	利き手側のブレード引き押せたら同時に反対側を押し出す	","letter": "	When you get the dominant side of the blade down, you push the other side out at the same time.	", "pinyin":"	ききてがわのぶれーどびきおせたらどうじにはんたいがわをおしだす	"},																			
"	191	":{"character":"	両肩のラインよりひじが回らないように	","letter": "	Don't let your elbows go beyond your shoulder line.	", "pinyin":"	りょうかたのらいんよりひじがまわらないように	"},																			
"	192	":{"character":"	むしろ腰を回転…	","letter": "	Instead, rotate your hips...	", "pinyin":"	むしろこしをかいてん…	"},																			
"	193	":{"character":"	もっと簡単に言ってくれる	","letter": "	You make it sound so much easier than it is.	", "pinyin":"	もっとかんたんにいってくれる	"},																			
"	194	":{"character":"	ペンギンさんがいつも泳ぐときみたいに	","letter": "	Like penguins always do when they swim.	", "pinyin":"	ぺんぎんさんがいつもおよぐときみたいに	"},																			
"	195	":{"character":"	よーし	","letter": "	Okay.	", "pinyin":"	よーし	"},																			
"	196	":{"character":"	ね見たパンダ君	","letter": "	Hey, look, Mr. Panda...	", "pinyin":"	ねみたぱんだくん	"},																			
"	197	":{"character":"	飽きたよ	","letter": "	I'm bored.	", "pinyin":"	あきたよ	"},																			
"	198	":{"character":"	はやっ	","letter": "	No, no, no, no, no, no, no, no, no, no, no, no, no.	", "pinyin":"	はやっ	"},																			
"	199	":{"character":"	海しか見えないし動かないよ	","letter": "	All I can see is the ocean, and it's not moving.	", "pinyin":"	うみしかみえないしうごかないよ	"},																			
"	200	":{"character":"	海に来てるんだし漕いでないから当たり前じゃない	","letter": "	Well, we're on the ocean, and we're not paddling, so why should we?	", "pinyin":"	うみにきてるんだしこいでないからあたりまえじゃない	"},																			
"	201	":{"character":"	こがなくていいやつ乗る	","letter": "	I'll take the one that doesn't require paddling.	", "pinyin":"	こがなくていいやつのる	"},																			
"	202	":{"character":"	次は何しようか	","letter": "	What shall we do next?	", "pinyin":"	つぎはなにしようか	"},																			
"	203	":{"character":"	やっぱり砂浜でまったりがいいよ	","letter": "	I think we should just sit on the beach.	", "pinyin":"	やっぱりすなはまでまったりがいいよ	"},																			
"	204	":{"character":"	のんびり干物作り	","letter": "	I'm going to make some dried fish.	", "pinyin":"	のんびりひものづくり	"},																			
"	205	":{"character":"	ウクレレ弾こうっと	","letter": "	I'm going to play the ukulele.	", "pinyin":"	うくれれひこうっと	"},																			
"	206	":{"character":"	ねえ僕の体を作ってよ	","letter": "	Hey, will you build me a body?	", "pinyin":"	ねえぼくのからだをつくってよ	"},																			
"	207	":{"character":"	どんなの	","letter": "	What kind of body?	", "pinyin":"	どんなの	"},																			
"	208	":{"character":"	マッチョでねセクシーな感じがいいな	","letter": "	I want to be macho... and sexy.	", "pinyin":"	まっちょでねせくしーなかんじがいいな	"},																			
"	209	":{"character":"	前に言ってた逆三角形の足の長いやつ	","letter": "	You know, that inverted triangle you were talking about... with long legs.	", "pinyin":"	まえにいってたぎゃくさんかくけいのあしのながいやつ	"},																			
"	210	":{"character":"	呼ばれて飛び出たドリームパンダ	","letter": "	The dream panda that jumped out at the call.	", "pinyin":"	よばれてとびでたどりーむぱんだ	"},																			
"	211	":{"character":"	あれよりごつい感じ	","letter": "	I want it to be more burly than that.	", "pinyin":"	あれよりごついかんじ	"},																			
"	212	":{"character":"	でもむきむきすぎないの	","letter": "	But not too peek-a-boo.	", "pinyin":"	でもむきむきすぎないの	"},																			
"	213	":{"character":"	注文多いな	","letter": "	That's a lot of orders.	", "pinyin":"	ちゅうもんおおいな	"},																			
"	214	":{"character":"	任せて	","letter": "	I'm on it.	", "pinyin":"	まかせて	"},																			
"	215	":{"character":"	どう	","letter": "	How's he doing?	", "pinyin":"	どう	"},																			
"	216	":{"character":"	お相撲さんだね	","letter": "	You're a sumo wrestler.	", "pinyin":"	おすもうさんだね	"},																			
"	217	":{"character":"	ごつくてむきむきすぎない	","letter": "	Big and not too mushy.	", "pinyin":"	ごつくてむきむきすぎない	"},																			
"	218	":{"character":"	やだ	","letter": "	I don't like it.	", "pinyin":"	やだ	"},																			
"	219	":{"character":"	任せて	","letter": "	I got it.	", "pinyin":"	まかせて	"},																			
"	220	":{"character":"	ごつ過ぎるよ	","letter": "	It's too big.	", "pinyin":"	ごつすぎるよ	"},																			
"	221	":{"character":"	もっとかっこいいのがいいな	","letter": "	I want something cooler.	", "pinyin":"	もっとかっこいいのがいいな	"},																			
"	222	":{"character":"	任せて	","letter": "	I got it.	", "pinyin":"	まかせて	"},																			
"	223	":{"character":"	かっこいいけど違う	","letter": "	It's cool, but it's not.	", "pinyin":"	かっこいいけどちがう	"},																			
"	224	":{"character":"	モテモテがいい	","letter": "	I want something irresistible.	", "pinyin":"	もてもてがいい	"},																			
"	225	":{"character":"	任せて	","letter": "	I got it.	", "pinyin":"	まかせて	"},																			
"	226	":{"character":"	これってモテモテ	","letter": "	This is irresistible.	", "pinyin":"	これってもてもて	"},																			
"	227	":{"character":"	うん皆でお祝いしてるし	","letter": "	Yeah, and we're all celebrating.	", "pinyin":"	うんみんなでおいわいしてるし	"},																			
"	228	":{"character":"	僕必要	","letter": "	You need me.	", "pinyin":"	ぼくひつよう	"},																			
"	229	":{"character":"	次は何しようか	","letter": "	What should we do next?	", "pinyin":"	つぎはなにしようか	"},																			
"	230	":{"character":"	誰がやる	","letter": "	Who's up for it?	", "pinyin":"	だれがやる	"},																			
"	231	":{"character":"	白熊君やりなよ	","letter": "	Polar bear, you should do it.	", "pinyin":"	しろくまくんやりなよ	"},																			
"	232	":{"character":"	いいの	","letter": "	I'll do it.	", "pinyin":"	いいの	"},																			
"	233	":{"character":"	何遠慮してるの	","letter": "	What are you waiting for?	", "pinyin":"	なにえんりょしてるの	"},																			
"	234	":{"character":"	そうじゃなくて	","letter": "	No, I'm not.	", "pinyin":"	そうじゃなくて	"},																			
"	235	":{"character":"	目隠ししても分かっちゃうんだよ	","letter": "	I can see through the blindfold.	", "pinyin":"	めかくししてもわかっちゃうんだよ	"},																			
"	236	":{"character":"	鼻がいいから	","letter": "	You have a great nose.	", "pinyin":"	はながいいから	"},																			
"	237	":{"character":"	じゃあパンダ君	","letter": "	Okay, Mr. Panda.	", "pinyin":"	じゃあぱんだくん	"},																			
"	238	":{"character":"	よーし	","letter": "	Okay.	", "pinyin":"	よーし	"},																			
"	239	":{"character":"	パンダ君寝てる	","letter": "	Panda, you're sleeping.	", "pinyin":"	ぱんだくんねてる	"},																			
"	240	":{"character":"	パンダ君に目隠しはダメだね	","letter": "	You can't blindfold a panda.	", "pinyin":"	ぱんだくんにめかくしはだめだね	"},																			
"	241	":{"character":"	右だよペンギンさん	","letter": "	To the right, Mr. Penguin.	", "pinyin":"	みぎだよぺんぎんさん	"},																			
"	242	":{"character":"	右ってどれぐらい	","letter": "	How far to the right?	", "pinyin":"	みぎってどれぐらい	"},																			
"	243	":{"character":"	上半身を30度右にねじって僅かに前傾姿勢をとる	","letter": "	Twist your upper body 30 degrees to the right and lean forward slightly.	", "pinyin":"	じょうはんしんを30どみぎにねじってわずかにぜんけいしせいをとる	"},																			
"	244	":{"character":"	そして腕を目の高さに当てて…	","letter": "	And place your arms at eye level...	", "pinyin":"	そしてうでをめのたかさにあてて…	"},																			
"	245	":{"character":"	もっと簡単に言ってくれる	","letter": "	That's easier said than done.	", "pinyin":"	もっとかんたんにいってくれる	"},																			
"	246	":{"character":"	真ん前	","letter": "	Right in front of you.	", "pinyin":"	まんまえ	"},																			
"	247	":{"character":"	そこだよペンギンさん	","letter": "	Right there, Mr. Penguin.	", "pinyin":"	そこだよぺんぎんさん	"},																			
"	248	":{"character":"	ホント	","letter": "	Really.	", "pinyin":"	ほんと	"},																			
"	249	":{"character":"	ペン子さんにアタックするつもりで	","letter": "	I was going to attack Mr. Penko.	", "pinyin":"	ぺんごさんにあたっくするつもりで	"},																			
"	250	":{"character":"	ペン子さん	","letter": "	Mr. Penko?	", "pinyin":"	ぺんごさん	"},																			
"	251	":{"character":"	あのえペン子さん干物がお好きですか	","letter": "	Do you like dried fish?	", "pinyin":"	あのえぺんごさんひものがおすきですか	"},																			
"	252	":{"character":"	僕は好きです	","letter": "	I do	", "pinyin":"	ぼくはすきです	"},																			
"	253	":{"character":"	あの干物が好きというかペン子さんもいいえ	","letter": "	I like dried fish, and you like dried fish?	", "pinyin":"	あのひものがすきというかぺんごさんもいいえ	"},																			
"	254	":{"character":"	ペン子さんがあ	","letter": "	Penko san...	", "pinyin":"	ぺんごさんがあ	"},																			
"	255	":{"character":"	ぺぺぺぺぺペン子さん	","letter": "	Pepe pepe, Penko san	", "pinyin":"	ぺぺぺぺぺぺんごさん	"},																			
"	256	":{"character":"	ペン子さん聞いてくれますか	","letter": "	Penko-san, will you listen to me?	", "pinyin":"	ぺんごさんきいてくれますか	"},																			
"	257	":{"character":"	ペン子さんペン子さん	","letter": "	Penko-san, Penko-san	", "pinyin":"	ぺんごさんぺんごさん	"},																			
"	258	":{"character":"	お幸せに	","letter": "	I wish you happiness	", "pinyin":"	おしあわせに	"},																			
"	259	":{"character":"	ペン子さんペン子さん	","letter": "	Penko-san Penko-san	", "pinyin":"	ぺんごさんぺんごさん	"},																			
"	260	":{"character":"	ご注文はお決まりですか	","letter": "	Have you decided on your order?	", "pinyin":"	ごちゅうもんはおきまりですか	"},																			
"	261	":{"character":"	竹大盛り	","letter": "	A large serving of bamboo	", "pinyin":"	たけおおもり	"},																			
"	262	":{"character":"	ありません	","letter": "	No, I don't have any.	", "pinyin":"	ありません	"},																			
"	263	":{"character":"	じゃあ普通盛りでいいんです	","letter": "	Then I'll just have a normal portion.	", "pinyin":"	じゃあふつうざかりでいいんです	"},																			
"	264	":{"character":"	すみませんどっちもありません	","letter": "	Sorry, we don't have either.	", "pinyin":"	すみませんどっちもありません	"},																			
"	265	":{"character":"	海の家名物竹大盛り	","letter": "	The 'Bamboo' bowl is a specialty of the beach house.	", "pinyin":"	うみのかめいぶつたけおおもり	"},																			
"	266	":{"character":"	絶対人気出るよ	","letter": "	I'm sure it'll be a hit.	", "pinyin":"	ぜったいにんきでるよ	"},																			
"	267	":{"character":"	パンダ君にだけでしょ	","letter": "	Only for you, panda.	", "pinyin":"	ぱんだくんにだけでしょ	"},																			
"	268	":{"character":"	僕このサーモンの軽いスモークミキュイソースクレソニエール	","letter": "	I'll have the lightly smoked salmon with a light mikuey sauce and cressonnière.	", "pinyin":"	ぼくこのさーもんのかるいすもーくみきゅいそーすくれそにえーる	"},																			
"	269	":{"character":"	違うでしょ	","letter": "	No, you're not.	", "pinyin":"	ちがうでしょ	"},																			
"	270	":{"character":"	じゃあ僕もトッピング竹で	","letter": "	I'll have the bamboo topping, too.	", "pinyin":"	じゃあぼくもとっぴんぐたけで	"},																			
"	271	":{"character":"	ないからそのトッピング	","letter": "	I don't have that topping.	", "pinyin":"	ないからそのとっぴんぐ	"},																			
"	272	":{"character":"	ペンギンさんは	","letter": "	You get the penguins...	", "pinyin":"	ぺんぎんさんは	"},																			
"	273	":{"character":"	僕はシーフードラーメン	","letter": "	I'll have the seafood ramen.	", "pinyin":"	ぼくはしーふーどらーめん	"},																			
"	274	":{"character":"	あつっあつあつあつ	","letter": "	Hot, hot, hot!	", "pinyin":"	あつっあつあつあつ	"},																			
"	275	":{"character":"	ペンギンさんいつも生魚だもんね	","letter": "	You always eat raw fish, don't you, Penguin?	", "pinyin":"	ぺんぎんさんいつもせいぎょだもんね	"},																			
"	276	":{"character":"	ペンギン舌だね	","letter": "	You have penguin tongue!	", "pinyin":"	ぺんぎんしただね	"},																			
"	277	":{"character":"	なにそれ	","letter": "	What's that?	", "pinyin":"	なにそれ	"},																			
"	278	":{"character":"	猫舌のペンギン版	","letter": "	It's the penguin version of cat tongue.	", "pinyin":"	ねこじたのぺんぎんばん	"},																			
"	279	":{"character":"	普通に猫舌でいいよ	","letter": "	I'm fine with cat's tongue.	", "pinyin":"	ふつうにねこじたでいいよ	"},																			
"	280	":{"character":"	頑張ってシーフードがペンギンさんを待ってるよ	","letter": "	Good luck with the seafood. The penguins are waiting for you.	", "pinyin":"	がんばってしーふーどがぺんぎんさんをまってるよ	"},																			
"	281	":{"character":"	あつあつ	","letter": "	Hot and humid!	", "pinyin":"	あつあつ	"},																			
"	282	":{"character":"	シーフードなら海で食べればいいのに	","letter": "	If you want seafood, why don't you just eat it in the ocean?	", "pinyin":"	しーふーどならかいでたべればいいのに	"},																			
"	283	":{"character":"	もっともなこと言わないでくれる	","letter": "	You don't have to be so rude.	", "pinyin":"	もっともなこといわないでくれる	"},																			
"	284	":{"character":"	ああもう行儀悪いな	","letter": "	Oh, my God, you're so rude.	", "pinyin":"	ああもうぎょうぎわるいな	"},																			
"	285	":{"character":"	女の子に嫌われちゃうよ	","letter": "	The girls won't like you.	", "pinyin":"	おんなのこにきらわれちゃうよ	"},																			
"	286	":{"character":"	ほら	","letter": "	Look.	", "pinyin":"	ほら	"},																			
"	287	":{"character":"	パンダさんが焼き蕎麦食べてる	","letter": "	A panda is eating buckwheat noodles.	", "pinyin":"	ぱんださんがやきそばたべてる	"},																			
"	288	":{"character":"	可愛い	","letter": "	He's cute.	", "pinyin":"	かわいい	"},																			
"	289	":{"character":"	高評価だね	","letter": "	That's high praise.	", "pinyin":"	こうひょうかだね	"},																			
"	290	":{"character":"	何で	","letter": "	Why?	", "pinyin":"	なんで	"},																			
"	291	":{"character":"	シーンに合わせたふるまい	","letter": "	It's a very appropriate behavior for the scene.	", "pinyin":"	しーんにあわせたふるまい	"},																			
"	292	":{"character":"	僕だってラーメン食べてるのに	","letter": "	I'm eating ramen too!	", "pinyin":"	ぼくだってらーめんたべてるのに	"},																			
"	293	":{"character":"	ペンギンがラーメン食べてる	","letter": "	Penguins eating ramen!	", "pinyin":"	ぺんぎんがらーめんたべてる	"},																			
"	294	":{"character":"	何だあれ珍しい	","letter": "	What the hell is that?	", "pinyin":"	なんだあれめずらしい	"},																			
"	295	":{"character":"	低評価だね	","letter": "	That's a low rating.	", "pinyin":"	ていひょうかだね	"},																			
"	296	":{"character":"	何で	","letter": "	Why?	", "pinyin":"	なんで	"},																			
"	297	":{"character":"	おいしいね	","letter": "	It's delicious.	", "pinyin":"	おいしいね	"},																			
"	298	":{"character":"	やっぱりおいしく感じるシーンっていうのがあるのかもね	","letter": "	Maybe there's a certain scene that makes them taste good.	", "pinyin":"	やっぱりおいしくかんじるしーんっていうのがあるのかもね	"},																			
"	299	":{"character":"	皆と一緒に風を感じながら	","letter": "	I'm feeling the wind with the others.	", "pinyin":"	みんなといっしょにかぜをかんじながら	"},																			
"	300	":{"character":"	次はかき氷食べよう	","letter": "	Let's have shaved ice next time.	", "pinyin":"	つぎはかきごおりたべよう	"},																			
"	301	":{"character":"	僕イチゴ味がいいな	","letter": "	I want strawberry.	", "pinyin":"	ぼくいちごあじがいいな	"},																			
"	302	":{"character":"	せっかくいいこと言ったのに	","letter": "	I just said something nice.	", "pinyin":"	せっかくいいこといったのに	"},																			
"	303	":{"character":"	もう皆ばらばらだよ	","letter": "	But now we're all scattered.	", "pinyin":"	もうみんなばらばらだよ	"},																			
"	304	":{"character":"	ホント自分勝手っていうかチームワークがないっていうか	","letter": "	It's like we're all selfish... and there's no teamwork.	", "pinyin":"	ほんとじぶんかってっていうかちーむわーくがないっていうか	"},																			
"	305	":{"character":"	ばらばらだよ	","letter": "	We're all so scattered.	", "pinyin":"	ばらばらだよ	"},																			
"	306	":{"character":"	楽しかったね	","letter": "	It was fun, wasn't it?	", "pinyin":"	たのしかったね	"},																			
"	307	":{"character":"	そうだね干物も作れたし	","letter": "	Yeah, and we got to make dried fish.	", "pinyin":"	そうだねひものもつくれたし	"},																			
"	308	":{"character":"	海っていいよね	","letter": "	The ocean's great, isn't it?	", "pinyin":"	うみっていいよね	"},																			
"	309	":{"character":"	本日の列車は運行を終了しました	","letter": "	No more trains today.	", "pinyin":"	ほんじつのれっしゃはうんこうをしゅうりょうしました	"},																			
"	310	":{"character":"	寝過ごした	","letter": "	I overslept.	", "pinyin":"	ねすごした	"},																			
"	311	":{"character":"	山もいいよね	","letter": "	Mountains are nice, aren't they?	", "pinyin":"	やまもいいよね	"},																			
"	312	":{"character":"	次は何する	","letter": "	What'll we do next?	", "pinyin":"	つぎはなにする	"},																			
"	313	":{"character":"	干物食べる	","letter": "	Eat dried fish	", "pinyin":"	ひものたべる	"},																			
"	314	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguins, penguins, penguins	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	315	":{"character":"	なにパンダ君	","letter": "	What's up, panda?	", "pinyin":"	なにぱんだくん	"},																			
"	316	":{"character":"	本当に興味がない相手と喋る時って話題が思いつかないもんだね	","letter": "	When you're talking to someone you're not really interested in, it's hard to come up with a topic.	", "pinyin":"	ほんとうにきょうみがないあいてとしゃべるときってわだいがおもいつかないもんだね	"},																			
"	317	":{"character":"	それ僕に発表しないでくれる	","letter": "	Don't announce that to me.	", "pinyin":"	それぼくにはっぴょうしないでくれる	"},																			
"	318	":{"character":"	じゃ得意な白熊君の物まね見せてよ	","letter": "	Then show us your best polar bear impersonation.	", "pinyin":"	じゃとくいなしろくまくんのものまねみせてよ	"},																			
"	319	":{"character":"	次回の白熊カフェは…	","letter": "	Next time at the Polar Bear Cafe...	", "pinyin":"	じかいのしろくまかふぇは…	"},																			
"	320	":{"character":"	白熊君終わろう	","letter": "	Polar Bear, let's finish up.	", "pinyin":"	しろくまくんおわろう	"},																			
"	321	":{"character":"	次回の白熊カフェは朝の五時半からお送りします	","letter": "	The next edition of the White Bear Cafe will begin at 5:30 in the morning.	", "pinyin":"	じかいのしろくまかふぇはあさのごじはんからおおくりします	"},																			
"	322	":{"character":"	夕方！夕方の五時半！	","letter": "	Evening! 5:30 in the evening!	", "pinyin":"	ゆうがた！ゆうがたのごじはん！	"},																			
"	323	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}