obj = {
"	1	":{"character":"	ペンギンさんの失恋	","letter": "	Penguin's broken heart	", "pinyin":"	ぺんぎんさんのしつれん	"},																			
"	2	":{"character":"	はい	","letter": "	Yes, ma'am.	", "pinyin":"	はい	"},																			
"	3	":{"character":"	頼んでないよ	","letter": "	I didn't order anything.	", "pinyin":"	たのんでないよ	"},																			
"	4	":{"character":"	新メニューのホットケーキ味見してみて	","letter": "	Taste the new pancakes on the menu.	", "pinyin":"	しんめにゅーのほっとけーきあじみしてみて	"},																			
"	5	":{"character":"	笹が入ってないよ	","letter": "	There's no bamboo grass in them.	", "pinyin":"	ささがはいってないよ	"},																			
"	6	":{"character":"	普通入れないから	","letter": "	I don't usually put it in.	", "pinyin":"	ふつういれないから	"},																			
"	7	":{"character":"	なんかしょっぱい	","letter": "	It's too salty.	", "pinyin":"	なんかしょっぱい	"},																			
"	8	":{"character":"	シャケ入れてみた	","letter": "	I added salmon.	", "pinyin":"	しゃけいれてみた	"},																			
"	9	":{"character":"	笹子さんも食べてみてよ	","letter": "	Try some, Sasago!	", "pinyin":"	ささごさんもたべてみてよ	"},																			
"	10	":{"character":"	あ…はい	","letter": "	Yes...	", "pinyin":"	あ…はい	"},																			
"	11	":{"character":"	やっぱりしょっぱいです	","letter": "	It's still too salty.	", "pinyin":"	やっぱりしょっぱいです	"},																			
"	12	":{"character":"	はぁ…	","letter": "	Oh, no...	", "pinyin":"	はぁ…	"},																			
"	13	":{"character":"	あれ？ペンギンさんいつからいたの？	","letter": "	Huh? How long have you been here, Penguin?	", "pinyin":"	あれ？ぺんぎんさんいつからいたの？	"},																			
"	14	":{"character":"	ずっといるでしょ！	","letter": "	You've been here all along!	", "pinyin":"	ずっといるでしょ！	"},																			
"	15	":{"character":"	ちゃんと気づいてたよ	","letter": "	I've noticed.	", "pinyin":"	ちゃんときづいてたよ	"},																			
"	16	":{"character":"	でも何か話しかけちゃいけないのかと思って	","letter": "	But I thought I shouldn't talk to you.	", "pinyin":"	でもなにかはなしかけちゃいけないのかとおもって	"},																			
"	17	":{"character":"	話しかけてよ！	","letter": "	Talk to me!	", "pinyin":"	はなしかけてよ！	"},																			
"	18	":{"character":"	シャケ入りホットケーキ食べる？	","letter": "	Do you want some pancakes with salmon?	", "pinyin":"	しゃけいりほっとけーきたべる？	"},																			
"	19	":{"character":"	僕は今食欲なんかないの	","letter": "	I don't have much of an appetite right now.	", "pinyin":"	ぼくはいましょくよくなんかないの	"},																			
"	20	":{"character":"	どうしたんですか？	","letter": "	What's the matter?	", "pinyin":"	どうしたんですか？	"},																			
"	21	":{"character":"	見てわからない？	","letter": "	Can't you see?	", "pinyin":"	みてわからない？	"},																			
"	22	":{"character":"	わかんないよ	","letter": "	I don't know.	", "pinyin":"	わかんないよ	"},																			
"	23	":{"character":"	僕はね…僕はね…	","letter": "	I'm...	", "pinyin":"	ぼくはね…ぼくはね…	"},																			
"	24	":{"character":"	失恋したんだよ！	","letter": "	I'm heartbroken!	", "pinyin":"	しつれんしたんだよ！	"},																			
"	25	":{"character":"	失恋？	","letter": "	Heartbroken?	", "pinyin":"	しつれん？	"},																			
"	26	":{"character":"	それは七輪！	","letter": "	That's a tricycle!	", "pinyin":"	それはしちりん！	"},																			
"	27	":{"character":"	それは一輪車！	","letter": "	That's a unicycle!	", "pinyin":"	それはいちりんしゃ！	"},																			
"	28	":{"character":"	それは三輪車！	","letter": "	That's a tricycle!	", "pinyin":"	それはさんりんしゃ！	"},																			
"	29	":{"character":"	だから僕は失恋してツッコむ気力もないの！	","letter": "	That's why I'm so heartbroken, I don't even have the energy to pick up a finger!	", "pinyin":"	だからぼくはしつれんしてつっこむきりょくもないの！	"},																			
"	30	":{"character":"	ツッコんでるじゃない	","letter": "	You're playing with it!	", "pinyin":"	つっこんでるじゃない	"},																			
"	31	":{"character":"	失恋ってペン子さん？	","letter": "	Heartbroken, Penko?	", "pinyin":"	しつれんってぺんごさん？	"},																			
"	32	":{"character":"	決まってるじゃない！	","letter": "	Of course!	", "pinyin":"	きまってるじゃない！	"},																			
"	33	":{"character":"	あ…あの…なんて言ったらいいか…	","letter": "	Um... um, I don't know what to say...	", "pinyin":"	あ…あの…なんていったらいいか…	"},																			
"	34	":{"character":"	何も言わないでほっておいてよ	","letter": "	Don't say anything, just leave me alone	", "pinyin":"	なにもいわないでほっておいてよ	"},																			
"	35	":{"character":"	パンダくん駅前のベーグル屋さんおいしいらしいよ	","letter": "	Panda, I heard the bagel shop in front of the station is delicious	", "pinyin":"	ぱんだくんえきまえのべーぐるやさんおいしいらしいよ	"},																			
"	36	":{"character":"	聞いてよ！	","letter": "	Listen to me!	", "pinyin":"	きいてよ！	"},																			
"	37	":{"character":"	聞いてほしいんですか？	","letter": "	You want me to listen?	", "pinyin":"	きいてほしいんですか？	"},																			
"	38	":{"character":"	当たり前じゃない！	","letter": "	Of course I do!	", "pinyin":"	あたりまえじゃない！	"},																			
"	39	":{"character":"	話せば楽になるぞ	","letter": "	It'll be easier if you just talk to me.	", "pinyin":"	はなせばらくになるぞ	"},																			
"	40	":{"character":"	刑事さん実は…	","letter": "	Detective, actually...	", "pinyin":"	けいじさんじつは…	"},																			
"	41	":{"character":"	って…僕は犯人じゃないから！	","letter": "	I'm not the murderer!	", "pinyin":"	って…ぼくははんにんじゃないから！	"},																			
"	42	":{"character":"	で…どうしたの？	","letter": "	So... what happened?	", "pinyin":"	で…どうしたの？	"},																			
"	43	":{"character":"	見ちゃったんだよ	","letter": "	I saw it.	", "pinyin":"	みちゃったんだよ	"},																			
"	44	":{"character":"	何を？	","letter": "	Saw what?	", "pinyin":"	なにを？	"},																			
"	45	":{"character":"	ペン子さんがデートしてるところ…	","letter": "	I saw Penko-san on a date...	", "pinyin":"	ぺんごさんがでーとしてるところ…	"},																			
"	46	":{"character":"	だ…誰とですか？	","letter": "	With who?	", "pinyin":"	だ…だれとですか？	"},																			
"	47	":{"character":"	それがなんと驚いたことに…	","letter": "	And to my surprise...	", "pinyin":"	それがなんとおどろいたことに…	"},																			
"	48	":{"character":"	絶対にありえない相手で…	","letter": "	It was with someone absolutely impossible...	", "pinyin":"	ぜったいにありえないあいてで…	"},																			
"	49	":{"character":"	本当に信じられない…	","letter": "	I really can't believe it...	", "pinyin":"	ほんとうにしんじられない…	"},																			
"	50	":{"character":"	誰なんですか？	","letter": "	Who is it?	", "pinyin":"	だれなんですか？	"},																			
"	51	":{"character":"	まさかと思うくらいの…	","letter": "	I can't believe it...	", "pinyin":"	まさかとおもうくらいの…	"},																			
"	52	":{"character":"	いいから早く吐け	","letter": "	Just tell me, just tell me!	", "pinyin":"	いいからはやくはけ	"},																			
"	53	":{"character":"	って…僕犯人じゃないから！	","letter": "	I'm not the murderer!	", "pinyin":"	って…ぼくはんにんじゃないから！	"},																			
"	54	":{"character":"	さっき公園で目撃しちゃったんだ	","letter": "	I just saw him in the park.	", "pinyin":"	さっきこうえんでもくげきしちゃったんだ	"},																			
"	55	":{"character":"	ペン子さん！	","letter": "	Penko!	", "pinyin":"	ぺんごさん！	"},																			
"	56	":{"character":"	こんなところでめぐり会うなんて	","letter": "	I can't believe we ran into each other here.	", "pinyin":"	こんなところでめぐりあうなんて	"},																			
"	57	":{"character":"	運命感じちゃうな！	","letter": "	I feel like it's fate	", "pinyin":"	うんめいかんじちゃうな！	"},																			
"	58	":{"character":"	やぁ！偶然ですねペン…	","letter": "	Hey! What a coincidence...	", "pinyin":"	やぁ！ぐうぜんですねぺん…	"},																			
"	59	":{"character":"	お待たせ～	","letter": "	Here you go.	", "pinyin":"	おまたせ～	"},																			
"	60	":{"character":"	じゃあ行きましょう	","letter": "	Let's go.	", "pinyin":"	じゃあいきましょう	"},																			
"	61	":{"character":"	ゾウガメさん？	","letter": "	Mr. Elephant Turtle?	", "pinyin":"	ぞうがめさん？	"},																			
"	62	":{"character":"	本当に？	","letter": "	Really?	", "pinyin":"	ほんとうに？	"},																			
"	63	":{"character":"	ゾウガメさんが？	","letter": "	Mr. giant tortoise?	", "pinyin":"	ぞうがめさんが？	"},																			
"	64	":{"character":"	そう…ペン子さんと待ち合わせてデートしてたんだ	","letter": "	Yes... she met up with Penko and had a date.	", "pinyin":"	そう…ぺんごさんとまちあわせてでーとしてたんだ	"},																			
"	65	":{"character":"	ステキなカフェですね	","letter": "	This is a nice cafe.	", "pinyin":"	すてきなかふぇですね	"},																			
"	66	":{"character":"	僕…ここに甲羅干しに来るんです～	","letter": "	I... come here to dry my shell.	", "pinyin":"	ぼく…ここにこうらぼしにくるんです～	"},																			
"	67	":{"character":"	まぁ！	","letter": "	Oh, my!	", "pinyin":"	まぁ！	"},																			
"	68	":{"character":"	僕も食べたいな～	","letter": "	I want some too!	", "pinyin":"	ぼくもたべたいな～	"},																			
"	69	":{"character":"	はい	","letter": "	I'd love to eat it too!	", "pinyin":"	はい	"},																			
"	70	":{"character":"	いい天気	","letter": "	It's a beautiful day.	", "pinyin":"	いいてんき	"},																			
"	71	":{"character":"	だね～	","letter": "	It's a beautiful day.	", "pinyin":"	だね～	"},																			
"	72	":{"character":"	２人で楽しそうにお茶飲んだり	","letter": "	They were having a nice cup of tea.	", "pinyin":"	２にんでたのしそうにおちゃのんだり	"},																			
"	73	":{"character":"	あ～んってしたりボートに乗ってたんだよ！	","letter": "	They were having a cup of tea, oohing and ahhing, and going on a boat ride!	", "pinyin":"	あ～んってしたりぼーとにのってたんだよ！	"},																			
"	74	":{"character":"	それどこで聞いてたの？	","letter": "	Where did you hear that?	", "pinyin":"	それどこできいてたの？	"},																			
"	75	":{"character":"	そりゃ…	","letter": "	That's...	", "pinyin":"	そりゃ…	"},																			
"	76	":{"character":"	なんだか涙ぐましいね	","letter": "	That's kind of tearful.	", "pinyin":"	なんだかなみだぐましいね	"},																			
"	77	":{"character":"	でもそれだけじゃ	","letter": "	But that's not enough to tell if they're lovers or not.	", "pinyin":"	でもそれだけじゃ	"},																			
"	78	":{"character":"	恋人同士かどうかわかんないんじゃない？	","letter": "	I don't know if they're lovers or not.	", "pinyin":"	こいびとどうしかどうかわかんないんじゃない？	"},																			
"	79	":{"character":"	それが決定的なことに…	","letter": "	That's the deciding factor...	", "pinyin":"	それがけっていてきなことに…	"},																			
"	80	":{"character":"	私…大好きなんですよね	","letter": "	I... love them.	", "pinyin":"	わたし…だいすきなんですよね	"},																			
"	81	":{"character":"	カメ…	","letter": "	Turtle...	", "pinyin":"	かめ…	"},																			
"	82	":{"character":"	そんな～っ！	","letter": "	Oh no!	", "pinyin":"	そんな～っ！	"},																			
"	83	":{"character":"	知らなかった…ペン子さんカメが大好きだったなんて…	","letter": "	I didn't know... that Penko-san loves turtles...	", "pinyin":"	しらなかった…ぺんごさんかめがだいすきだったなんて…	"},																			
"	84	":{"character":"	カメのどこがいいんだろう？	","letter": "	What do I like about turtles?	", "pinyin":"	かめのどこがいいんだろう？	"},																			
"	85	":{"character":"	ねぇどこがいいんだと思う？	","letter": "	What do you think is so good about turtles?	", "pinyin":"	ねぇどこがいいんだとおもう？	"},																			
"	86	":{"character":"	はっきり言ってよ！	","letter": "	Speak up!	", "pinyin":"	はっきりいってよ！	"},																			
"	87	":{"character":"	こ…甲羅があるとこですかね？	","letter": "	Is it the shell?	", "pinyin":"	こ…こうらがあるとこですかね？	"},																			
"	88	":{"character":"	首とか手足が引っ込むところもキュートかも	","letter": "	Or the way its neck and arms and legs tuck in?	", "pinyin":"	くびとかてあしがひっこむところもきゅーとかも	"},																			
"	89	":{"character":"	千年生きるのはすごいよね	","letter": "	It's amazing that they live for 1,000 years.	", "pinyin":"	せんねんいきるのはすごいよね	"},																			
"	90	":{"character":"	ペ…ペンギンにだっていいとこあるでしょ？	","letter": "	Penguins have their good points, too, don't they?	", "pinyin":"	ぺ…ぺんぎんにだっていいとこあるでしょ？	"},																			
"	91	":{"character":"	ないの！？	","letter": "	No!	", "pinyin":"	ないの！？	"},																			
"	92	":{"character":"	負けてる…完璧に負けてるよ	","letter": "	You're losing... you're totally losing.	", "pinyin":"	まけてる…かんぺきにまけてるよ	"},																			
"	93	":{"character":"	僕はどうしてペンギンに生まれたんだろう	","letter": "	Why was I born a penguin?	", "pinyin":"	ぼくはどうしてぺんぎんにうまれたんだろう	"},																			
"	94	":{"character":"	お母さん！どうして僕をカメに生んでくれなかったの！？	","letter": "	Mom! Why didn't you make me a turtle?	", "pinyin":"	おかあさん！どうしてぼくをかめにうんでくれなかったの！？	"},																			
"	95	":{"character":"	ペンギンさんあのね	","letter": "	Penguins... you know what?	", "pinyin":"	ぺんぎんさんあのね	"},																			
"	96	":{"character":"	ペンギンからカメは生まれないんだよ	","letter": "	Penguins don't make turtles.	", "pinyin":"	ぺんぎんからかめはうまれないんだよ	"},																			
"	97	":{"character":"	わかってるよ！	","letter": "	I know!	", "pinyin":"	わかってるよ！	"},																			
"	98	":{"character":"	あ～あ…こんなことなら思い切って	","letter": "	If it's going to be like this, I should've gone out on a limb and asked	", "pinyin":"	あ～あ…こんなことならおもいきって	"},																			
"	99	":{"character":"	ペン子さんをドライブに誘っとくんだった	","letter": "	I should have taken Penko-san for a drive!	", "pinyin":"	ぺんごさんをどらいぶにさそっとくんだった	"},																			
"	100	":{"character":"	い…今からでも遅くないですよ	","letter": "	It's not too late...	", "pinyin":"	い…いまからでもおそくないですよ	"},																			
"	101	":{"character":"	せっかく免許も取ったんだし…	","letter": "	I just got my driver's license...	", "pinyin":"	せっかくめんきょもとったんだし…	"},																			
"	102	":{"character":"	そ…そうだよね！	","letter": "	That's right!	", "pinyin":"	そ…そうだよね！	"},																			
"	103	":{"character":"	ペン子さんカメ好きなら	","letter": "	If you like turtles...	", "pinyin":"	ぺんごさんかめすきなら	"},																			
"	104	":{"character":"	速い乗り物は好きじゃないかもね	","letter": "	Maybe you don't like fast rides	", "pinyin":"	はやいのりものはすきじゃないかもね	"},																			
"	105	":{"character":"	ゆっくりじゃないとダメなのか～！	","letter": "	It's got to be slow!	", "pinyin":"	ゆっくりじゃないとだめなのか～！	"},																			
"	106	":{"character":"	やっぱダメだ…	","letter": "	I can't do it...	", "pinyin":"	やっぱだめだ…	"},																			
"	107	":{"character":"	もうきっぱりペン子さんのことは諦めよう	","letter": "	Let's give up on Penko once and for all	", "pinyin":"	もうきっぱりぺんごさんのことはあきらめよう	"},																			
"	108	":{"character":"	そうですね	","letter": "	I agree.	", "pinyin":"	そうですね	"},																			
"	109	":{"character":"	またステキな子が現れるよ	","letter": "	There'll be another nice girl.	", "pinyin":"	またすてきなこがあらわれるよ	"},																			
"	110	":{"character":"	そうだよねいつまでも引きずってちゃダメだよね	","letter": "	That's right... we can't keep dragging it out forever.	", "pinyin":"	そうだよねいつまでもひきずってちゃだめだよね	"},																			
"	111	":{"character":"	そうですよ	","letter": "	That's right.	", "pinyin":"	そうですよ	"},																			
"	112	":{"character":"	やっぱ諦めちゃダメでしょ！	","letter": "	You can't give up on her after all!	", "pinyin":"	やっぱあきらめちゃだめでしょ！	"},																			
"	113	":{"character":"	どっちなの？	","letter": "	Which is it?	", "pinyin":"	どっちなの？	"},																			
"	114	":{"character":"	でもペン子さんにはゾウガメさんが…	","letter": "	But Penko-san has a giant tortoise...	", "pinyin":"	でもぺんごさんにはぞうがめさんが…	"},																			
"	115	":{"character":"	ペンギンがゾウガメなんかに負けてたまるか～っ！	","letter": "	Penguins can't lose to a giant tortoise!	", "pinyin":"	ぺんぎんがぞうがめなんかにまけてたまるか～っ！	"},																			
"	116	":{"character":"	あっゾウガメさん	","letter": "	Ah, Mr. Tortoise!	", "pinyin":"	あっぞうがめさん	"},																			
"	117	":{"character":"	こんにちは～	","letter": "	Hello!	", "pinyin":"	こんにちは～	"},																			
"	118	":{"character":"	ライバル登場だよ	","letter": "	Here comes the rival!	", "pinyin":"	らいばるとうじょうだよ	"},																			
"	119	":{"character":"	ペン子さんの彼氏来た	","letter": "	Penko's boyfriend's here!	", "pinyin":"	ぺんごさんのかれしきた	"},																			
"	120	":{"character":"	ダメだよそんなこと言っちゃ	","letter": "	Don't say that!	", "pinyin":"	だめだよそんなこといっちゃ	"},																			
"	121	":{"character":"	これから決闘するの？	","letter": "	Are you going to duel?	", "pinyin":"	これからけっとうするの？	"},																			
"	122	":{"character":"	しないよ	","letter": "	No, we're not.	", "pinyin":"	しないよ	"},																			
"	123	":{"character":"	えっとこういうのたしか…	","letter": "	I mean...	", "pinyin":"	えっとこういうのたしか…	"},																			
"	124	":{"character":"	シャバダバ？	","letter": "	Shabadaba?	", "pinyin":"	しゃばだば？	"},																			
"	125	":{"character":"	修羅場だよ	","letter": "	It's a battlefield.	", "pinyin":"	しゅらばだよ	"},																			
"	126	":{"character":"	ちょっと黙っててよ！	","letter": "	Shut up!	", "pinyin":"	ちょっとだまっててよ！	"},																			
"	127	":{"character":"	とにかくペン子さんとどういうおつきあいなのか	","letter": "	Anyway, what kind of a relationship do you have with Penko?	", "pinyin":"	とにかくぺんごさんとどういうおつきあいなのか	"},																			
"	128	":{"character":"	はっきりさせないと	","letter": "	I need to know what kind of a relationship you have with Penko.	", "pinyin":"	はっきりさせないと	"},																			
"	129	":{"character":"	ゾ…ゾウガメ君！	","letter": "	Zo... zoogame!	", "pinyin":"	ぞ…ぞうがめくん！	"},																			
"	130	":{"character":"	なに～？	","letter": "	What?	", "pinyin":"	なに～？	"},																			
"	131	":{"character":"	あ…いや…	","letter": "	It's a... no...	", "pinyin":"	あ…いや…	"},																			
"	132	":{"character":"	いい天気だね	","letter": "	It's a beautiful day.	", "pinyin":"	いいてんきだね	"},																			
"	133	":{"character":"	ペンギンさんはっきりさせるんじゃなかったの？	","letter": "	Penguin, I thought we were clear.	", "pinyin":"	ぺんぎんさんはっきりさせるんじゃなかったの？	"},																			
"	134	":{"character":"	わかってるよ！	","letter": "	I know, I know!	", "pinyin":"	わかってるよ！	"},																			
"	135	":{"character":"	どうかした～？	","letter": "	What's wrong?	", "pinyin":"	どうかした～？	"},																			
"	136	":{"character":"	あ…いや…あのさ！この間さ公園で…	","letter": "	Uh... no... you know what? The other day at the park...	", "pinyin":"	あ…いや…あのさ！このあいださこうえんで…	"},																			
"	137	":{"character":"	すごくおいしいマイワシを食べたんだよね～	","letter": "	I ate some really tasty sardines in the park.	", "pinyin":"	すごくおいしいまいわしをたべたんだよね～	"},																			
"	138	":{"character":"	おいしかった～	","letter": "	It was delicious!	", "pinyin":"	おいしかった～	"},																			
"	139	":{"character":"	違うでしょ？	","letter": "	It wasn't, was it?	", "pinyin":"	ちがうでしょ？	"},																			
"	140	":{"character":"	わかってるよ！	","letter": "	I know!	", "pinyin":"	わかってるよ！	"},																			
"	141	":{"character":"	話には順序ってものが…	","letter": "	There's an order to things...	", "pinyin":"	はなしにはじゅんじょってものが…	"},																			
"	142	":{"character":"	そういえばあの公園でさ	","letter": "	Oh, by the way, at the park...	", "pinyin":"	そういえばあのこうえんでさ	"},																			
"	143	":{"character":"	女の子のペンギンと一緒にいたじゃない？	","letter": "	You know, the one with the little penguins?	", "pinyin":"	おんなのこのぺんぎんといっしょにいたじゃない？	"},																			
"	144	":{"character":"	あの公園気持いいよね	","letter": "	It's so nice there, isn't it?	", "pinyin":"	あのこうえんきもちいいよね	"},																			
"	145	":{"character":"	でゾウガメさんとペン子さんはどういう関係？	","letter": "	So, what's the story with the elephant tortoise and the penguins?	", "pinyin":"	でぞうがめさんとぺんごさんはどういうかんけい？	"},																			
"	146	":{"character":"	あからさまに聞かないでよ！	","letter": "	Don't ask so bluntly!	", "pinyin":"	あからさまにきかないでよ！	"},																			
"	147	":{"character":"	それでゾウガメさんはどうして一緒に？	","letter": "	So, how did you get together with Mr. Tortoise?	", "pinyin":"	それでぞうがめさんはどうしていっしょに？	"},																			
"	148	":{"character":"	笹子さんまで！？	","letter": "	Even Sasago-san!	", "pinyin":"	ささごさんまで！？	"},																			
"	149	":{"character":"	なんで公園に一緒にいたの？	","letter": "	Why were you in the park together?	", "pinyin":"	なんでこうえんにいっしょにいたの？	"},																			
"	150	":{"character":"	誘われて～	","letter": "	I was invited...	", "pinyin":"	さそわれて～	"},																			
"	151	":{"character":"	ペン子さんに誘われた！？	","letter": "	Penko-san asked me out!	", "pinyin":"	ぺんごさんにさそわれた！？	"},																			
"	152	":{"character":"	好きだって～	","letter": "	She said she likes me~!	", "pinyin":"	すきだって～	"},																			
"	153	":{"character":"	カ…メ…	","letter": "	Ka...me...	", "pinyin":"	か…め…	"},																			
"	154	":{"character":"	ゾウガメさんペン子さんとお幸せに！うわ～ん！	","letter": "	I wish you and Penko-san all the best, Mr. Elephant Tortoise! Woah~!	", "pinyin":"	ぞうがめさんぺんごさんとおしあわせに！うわ～ん！	"},																			
"	155	":{"character":"	ラ…	","letter": "	La...	", "pinyin":"	ら…	"},																			
"	156	":{"character":"	ラ？	","letter": "	La?	", "pinyin":"	ら？	"},																			
"	157	":{"character":"	いや待てよ	","letter": "	No, wait!	", "pinyin":"	いやまてよ	"},																			
"	158	":{"character":"	ペン子さんがそんなにカメ好きなら…	","letter": "	If Penko-san likes turtles so much...	", "pinyin":"	ぺんごさんがそんなにかめすきなら…	"},																			
"	159	":{"character":"	いらっしゃい	","letter": "	Welcome.	", "pinyin":"	いらっしゃい	"},																			
"	160	":{"character":"	こんにちは	","letter": "	Hello.	", "pinyin":"	こんにちは	"},																			
"	161	":{"character":"	何やってるのペンギンさん	","letter": "	What are you doing here, Penguin?	", "pinyin":"	なにやってるのぺんぎんさん	"},																			
"	162	":{"character":"	どこから持ってきたんですか？その甲羅	","letter": "	Where did you get that from? That shell	", "pinyin":"	どこからもってきたんですか？そのこうら	"},																			
"	163	":{"character":"	かたい	","letter": "	It's so hard!	", "pinyin":"	かたい	"},																			
"	164	":{"character":"	ペン子さんはカメが大好き	","letter": "	Penko-san loves turtles	", "pinyin":"	ぺんごさんはかめがだいすき	"},																			
"	165	":{"character":"	ああペン子さんはね	","letter": "	Yes, Penko-san does.	", "pinyin":"	ああぺんごさんはね	"},																			
"	166	":{"character":"	カメじゃなくて	","letter": "	Not turtles.	", "pinyin":"	かめじゃなくて	"},																			
"	167	":{"character":"	大好きなのはカメラ	","letter": "	What he loves is cameras	", "pinyin":"	だいすきなのはかめら	"},																			
"	168	":{"character":"	最近カメラが趣味らしいよ	","letter": "	He's been into cameras lately.	", "pinyin":"	さいきんかめらがしゅみらしいよ	"},																			
"	169	":{"character":"	ゾウガメさんも同じ趣味みたいで	","letter": "	Mr. Elephant Tortoise seems to have the same hobby.	", "pinyin":"	ぞうがめさんもおなじしゅみみたいで	"},																			
"	170	":{"character":"	大好きなのはねカメじゃなくてカメラだよ	","letter": "	I love cameras, not turtles.	", "pinyin":"	だいすきなのはねかめじゃなくてかめらだよ	"},																			
"	171	":{"character":"	出直してきます	","letter": "	I'll come back later.	", "pinyin":"	でなおしてきます	"},																			
"	172	":{"character":"	パンダくんの夜遊び	","letter": "	Panda's night out	", "pinyin":"	ぱんだくんのよあそび	"},																			
"	173	":{"character":"	お疲れさまでした	","letter": "	Thank you for your hard work.	", "pinyin":"	おつかれさまでした	"},																			
"	174	":{"character":"	お疲れさま	","letter": "	Thank you.	", "pinyin":"	おつかれさま	"},																			
"	175	":{"character":"	パンダくん閉店なんだけど	","letter": "	Panda, we're closed.	", "pinyin":"	ぱんだくんへいてんなんだけど	"},																			
"	176	":{"character":"	パンダくん？	","letter": "	Panda?	", "pinyin":"	ぱんだくん？	"},																			
"	177	":{"character":"	ああおはよう	","letter": "	Good morning.	", "pinyin":"	ああおはよう	"},																			
"	178	":{"character":"	もう夜だよ	","letter": "	It's almost night.	", "pinyin":"	もうよるだよ	"},																			
"	179	":{"character":"	グリズリーくん	","letter": "	Hey, grizzly.	", "pinyin":"	ぐりずりーくん	"},																			
"	180	":{"character":"	ようちょっと遊びに行こうぜ	","letter": "	Hey, let's go have a little fun.	", "pinyin":"	ようちょっとあそびにいこうぜ	"},																			
"	181	":{"character":"	いいよ	","letter": "	Yeah, sure.	", "pinyin":"	いいよ	"},																			
"	182	":{"character":"	遊びに行くの？	","letter": "	You wanna go hang out?	", "pinyin":"	あそびにいくの？	"},																			
"	183	":{"character":"	僕も行きたい！	","letter": "	I want to go, too!	", "pinyin":"	ぼくもいきたい！	"},																			
"	184	":{"character":"	ガキの行くところじゃねぇんだよ	","letter": "	It's not for kids.	", "pinyin":"	がきのいくところじゃねぇんだよ	"},																			
"	185	":{"character":"	大人の夜遊びだ	","letter": "	It's a night out for adults.	", "pinyin":"	おとなのよあそびだ	"},																			
"	186	":{"character":"	夜遊び？	","letter": "	Nightlife?	", "pinyin":"	よあそび？	"},																			
"	187	":{"character":"	なんかすごくおもしろそう	","letter": "	Sounds like a lot of fun.	", "pinyin":"	なんかすごくおもしろそう	"},																			
"	188	":{"character":"	何でついてくるんだよ	","letter": "	Why are you following me?	", "pinyin":"	なんでついてくるんだよ	"},																			
"	189	":{"character":"	グリズリーくんが誘ったんじゃない	","letter": "	Mr. Grizzly didn't ask me to go out with him.	", "pinyin":"	ぐりずりーくんがさそったんじゃない	"},																			
"	190	":{"character":"	お前じゃねぇよ	","letter": "	It wasn't you.	", "pinyin":"	おまえじゃねぇよ	"},																			
"	191	":{"character":"	コイツだよ	","letter": "	It's him.	", "pinyin":"	こいつだよ	"},																			
"	192	":{"character":"	どこ行くの？	","letter": "	Where are you going?	", "pinyin":"	どこいくの？	"},																			
"	193	":{"character":"	というわけでパンダくん	","letter": "	So, Mr. Panda.	", "pinyin":"	というわけでぱんだくん	"},																			
"	194	":{"character":"	今日は残念だけど中止だから帰ろう	","letter": "	I'm sorry, but we're cancelling today. Let's go home.	", "pinyin":"	きょうはざんねんだけどちゅうしだからかえろう	"},																			
"	195	":{"character":"	残念	","letter": "	Too bad.	", "pinyin":"	ざんねん	"},																			
"	196	":{"character":"	何でそうなるんだ！	","letter": "	What the hell is wrong with you?	", "pinyin":"	なんでそうなるんだ！	"},																			
"	197	":{"character":"	ちょっと待て！	","letter": "	Wait a minute!	", "pinyin":"	ちょっとまて！	"},																			
"	198	":{"character":"	やっぱり行くの？	","letter": "	Are you still going?	", "pinyin":"	やっぱりいくの？	"},																			
"	199	":{"character":"	行くに決まってんだろ！	","letter": "	Of course we're going!	", "pinyin":"	いくにきまってんだろ！	"},																			
"	200	":{"character":"	すごいここ何？	","letter": "	What is this place?	", "pinyin":"	すごいここなに？	"},																			
"	201	":{"character":"	バッティングセンター	","letter": "	What is this place? The batting cage.	", "pinyin":"	ばってぃんぐせんたー	"},																			
"	202	":{"character":"	来たことねぇのか	","letter": "	You've never been here before?	", "pinyin":"	きたことねぇのか	"},																			
"	203	":{"character":"	何やってんだよ！	","letter": "	What the hell are you doing?	", "pinyin":"	なにやってんだよ！	"},																			
"	204	":{"character":"	ぶら下がって遊ぶとこじゃねぇんだよ！	","letter": "	This is not a place to hang out!	", "pinyin":"	ぶらさがってあそぶとこじゃねぇんだよ！	"},																			
"	205	":{"character":"	そうなの？	","letter": "	Is that so?	", "pinyin":"	そうなの？	"},																			
"	206	":{"character":"	ったく…	","letter": "	Oh, man...	", "pinyin":"	ったく…	"},																			
"	207	":{"character":"	これ気持いいね	","letter": "	This feels good.	", "pinyin":"	これきもちいいね	"},																			
"	208	":{"character":"	だからそうじゃねぇんだよ	","letter": "	That's not what I meant.	", "pinyin":"	だからそうじゃねぇんだよ	"},																			
"	209	":{"character":"	結構凝りがほぐれるね	","letter": "	It loosens me up a lot.	", "pinyin":"	けっこうこりがほぐれるね	"},																			
"	210	":{"character":"	お前までやってんじゃねぇ！	","letter": "	Don't do it to me, too!	", "pinyin":"	おまえまでやってんじゃねぇ！	"},																			
"	211	":{"character":"	じゃあここで何して遊ぶの？	","letter": "	What do you do here?	", "pinyin":"	じゃあここでなにしてあそぶの？	"},																			
"	212	":{"character":"	向こうから来た球を打ち返すんだよ	","letter": "	You hit the ball back from the other side.	", "pinyin":"	むこうからきたたまをうちかえすんだよ	"},																			
"	213	":{"character":"	こうやるんだ	","letter": "	Like this.	", "pinyin":"	こうやるんだ	"},																			
"	214	":{"character":"	ナイスキャッチ	","letter": "	Nice catch!	", "pinyin":"	ないすきゃっち	"},																			
"	215	":{"character":"	シロクマくんすご～い！	","letter": "	That's great, Polar Bear!	", "pinyin":"	しろくまくんすご～い！	"},																			
"	216	":{"character":"	ピッチャーライナーだね	","letter": "	That's a pitcher's liner.	", "pinyin":"	ぴっちゃーらいなーだね	"},																			
"	217	":{"character":"	何やってんだよ！！	","letter": "	What are you doing?	", "pinyin":"	なにやってんだよ！！	"},																			
"	218	":{"character":"	僕もやる	","letter": "	I'll do it too.	", "pinyin":"	ぼくもやる	"},																			
"	219	":{"character":"	やらなくていいんだよ！	","letter": "	You don't have to!	", "pinyin":"	やらなくていいんだよ！	"},																			
"	220	":{"character":"	大当たり！	","letter": "	You hit the jackpot!	", "pinyin":"	おおあたり！	"},																			
"	221	":{"character":"	グリズリーさんやったね！	","letter": "	You did it, Grizzly!	", "pinyin":"	ぐりずりーさんやったね！	"},																			
"	222	":{"character":"	なんかもうやる気なくなったぜ	","letter": "	I don't feel like doing it anymore.	", "pinyin":"	なんかもうやるきなくなったぜ	"},																			
"	223	":{"character":"	じゃあ僕がお手本を	","letter": "	I'll set the example.	", "pinyin":"	じゃあぼくがおてほんを	"},																			
"	224	":{"character":"	さあ来い！	","letter": "	Come on!	", "pinyin":"	さあこい！	"},																			
"	225	":{"character":"	バット持ちすぎだろう！	","letter": "	You're holding the bat too high!	", "pinyin":"	ばっともちすぎだろう！	"},																			
"	226	":{"character":"	じゃあ改めてお手本を	","letter": "	Well, let me show you how it's done.	", "pinyin":"	じゃああらためておてほんを	"},																			
"	227	":{"character":"	バット使えよ！	","letter": "	Use the bat!	", "pinyin":"	ばっとつかえよ！	"},																			
"	228	":{"character":"	もういい…パンダとにかくやってみろ	","letter": "	All right, Panda, just do it.	", "pinyin":"	もういい…ぱんだとにかくやってみろ	"},																			
"	229	":{"character":"	パンダくんバットを構えてよ～く球を見るんだよ	","letter": "	Panda, hold up the bat and look at the ball.	", "pinyin":"	ぱんだくんばっとをかまえてよ～くたまをみるんだよ	"},																			
"	230	":{"character":"	いやそうじゃなくてな…	","letter": "	No, no, no, I mean...	", "pinyin":"	いやそうじゃなくてな…	"},																			
"	231	":{"character":"	ボールをしっかり見て	","letter": "	Watch the ball.	", "pinyin":"	ぼーるをしっかりみて	"},																			
"	232	":{"character":"	じ～～～	","letter": "	Look at the ball.	", "pinyin":"	じ～～～	"},																			
"	233	":{"character":"	こう？	","letter": "	Like this?	", "pinyin":"	こう？	"},																			
"	234	":{"character":"	打てよ	","letter": "	Hit it.	", "pinyin":"	うてよ	"},																			
"	235	":{"character":"	やっぱり？	","letter": "	Like I knew it?	", "pinyin":"	やっぱり？	"},																			
"	236	":{"character":"	やっぱりじゃねぇ！バットで当てろ！！	","letter": "	I knew it! Hit it with the bat!	", "pinyin":"	やっぱりじゃねぇ！ばっとであてろ！！	"},																			
"	237	":{"character":"	ナイスショット	","letter": "	Nice shot.	", "pinyin":"	ないすしょっと	"},																			
"	238	":{"character":"	やったぁ！	","letter": "	Yeah!	", "pinyin":"	やったぁ！	"},																			
"	239	":{"character":"	ゴルフじゃねぇ！！	","letter": "	This ain't golf!	", "pinyin":"	ごるふじゃねぇ！！	"},																			
"	240	":{"character":"	積み木じゃねぇ！	","letter": "	It's not a block!	", "pinyin":"	つみきじゃねぇ！	"},																			
"	241	":{"character":"	ビリヤードじゃねぇ！	","letter": "	It's not billiards!	", "pinyin":"	びりやーどじゃねぇ！	"},																			
"	242	":{"character":"	ああおもしろかった	","letter": "	Yeah, it was fun.	", "pinyin":"	ああおもしろかった	"},																			
"	243	":{"character":"	全然バッティングしてねぇけどな	","letter": "	We're not batting at all, though.	", "pinyin":"	ぜんぜんばってぃんぐしてねぇけどな	"},																			
"	244	":{"character":"	次いくぞ	","letter": "	Let's go next time.	", "pinyin":"	つぎいくぞ	"},																			
"	245	":{"character":"	またどこか行くの？	","letter": "	Are we going somewhere else?	", "pinyin":"	またどこかいくの？	"},																			
"	246	":{"character":"	夜はこれからだからな	","letter": "	We're going on a night out.	", "pinyin":"	よるはこれからだからな	"},																			
"	247	":{"character":"	これからなんだ…	","letter": "	We're just getting started...	", "pinyin":"	これからなんだ…	"},																			
"	248	":{"character":"	次はどこかな？	","letter": "	Where's next?	", "pinyin":"	つぎはどこかな？	"},																			
"	249	":{"character":"	風呂だ！	","letter": "	Bathroom!	", "pinyin":"	ふろだ！	"},																			
"	250	":{"character":"	広い！	","letter": "	It's huge!	", "pinyin":"	ひろい！	"},																			
"	251	":{"character":"	すごいね！	","letter": "	Oh, my God!	", "pinyin":"	すごいね！	"},																			
"	252	":{"character":"	すげぇだろう？	","letter": "	Isn't it amazing?	", "pinyin":"	すげぇだろう？	"},																			
"	253	":{"character":"	本当だ！	","letter": "	It is!	", "pinyin":"	ほんとうだ！	"},																			
"	254	":{"character":"	すごいよ！！	","letter": "	It's awesome!	", "pinyin":"	すごいよ！！	"},																			
"	255	":{"character":"	そういうすげぇじゃねぇんだけどな…	","letter": "	It's not that awesome...	", "pinyin":"	そういうすげぇじゃねぇんだけどな…	"},																			
"	256	":{"character":"	ほらほら	","letter": "	Come on, come on, come on.	", "pinyin":"	ほらほら	"},																			
"	257	":{"character":"	まずはちゃんと体洗えよ	","letter": "	Wash yourself first.	", "pinyin":"	まずはちゃんとからだあらえよ	"},																			
"	258	":{"character":"	背中流してあげようか？	","letter": "	Do you want me to wash your back?	", "pinyin":"	せなかながしてあげようか？	"},																			
"	259	":{"character":"	うん頼むよ	","letter": "	Yes, please.	", "pinyin":"	うんたのむよ	"},																			
"	260	":{"character":"	背中流してあげようか？	","letter": "	Do you want me to wash your back?	", "pinyin":"	せなかながしてあげようか？	"},																			
"	261	":{"character":"	おうお前もちったぁ気が利くじゃねぇか	","letter": "	Oh, you're so thoughtful.	", "pinyin":"	おうおまえもちったぁきがきくじゃねぇか	"},																			
"	262	":{"character":"	やめろ何かこそばゆいぞ	","letter": "	Stop it, you're making me nervous.	", "pinyin":"	やめろなにかこそばゆいぞ	"},																			
"	263	":{"character":"	パンダくんもっと強くこするんだよ	","letter": "	Panda, rub harder.	", "pinyin":"	ぱんだくんもっとつよくこするんだよ	"},																			
"	264	":{"character":"	イテーッ！！ツメ立てんなツメ！	","letter": "	Ouch! Don't get your claws in my face!	", "pinyin":"	いてーっ！！つめたてんなつめ！	"},																			
"	265	":{"character":"	あっごめん	","letter": "	Oh, I'm sorry.	", "pinyin":"	あっごめん	"},																			
"	266	":{"character":"	目に染みるよ	","letter": "	It's stinging my eyes.	", "pinyin":"	めにしみるよ	"},																			
"	267	":{"character":"	早く流せ	","letter": "	Get it out of my eyes.	", "pinyin":"	はやくながせ	"},																			
"	268	":{"character":"	グリズリーさん…	","letter": "	Mr. Grizzly...	", "pinyin":"	ぐりずりーさん…	"},																			
"	269	":{"character":"	誰？	","letter": "	Who's there?	", "pinyin":"	だれ？	"},																			
"	270	":{"character":"	ハア…すっきり	","letter": "	Oh, that's so refreshing.	", "pinyin":"	はあ…すっきり	"},																			
"	271	":{"character":"	グリズリーさんも流してあげるよ	","letter": "	I'll flush you, too, Mr. Grizzly.	", "pinyin":"	ぐりずりーさんもながしてあげるよ	"},																			
"	272	":{"character":"	おう頼むぜ	","letter": "	Oh, come on.	", "pinyin":"	おうたのむぜ	"},																			
"	273	":{"character":"	アチーッ！！熱いじゃねえか！	","letter": "	Atch! That's hot!	", "pinyin":"	あちーっ！！あついじゃねえか！	"},																			
"	274	":{"character":"	ごめんなさい…	","letter": "	I'm sorry...	", "pinyin":"	ごめんなさい…	"},																			
"	275	":{"character":"	赤いほうを回すとお湯で	","letter": "	You turn the red one, it's hot water.	", "pinyin":"	あかいほうをまわすとおゆで	"},																			
"	276	":{"character":"	青いほうが水だからな	","letter": "	The blue one is water.	", "pinyin":"	あおいほうがみずだからな	"},																			
"	277	":{"character":"	わかった	","letter": "	I get it.	", "pinyin":"	わかった	"},																			
"	278	":{"character":"	冷てぇ！！ちゃんと調節しろよ！	","letter": "	It's cold! You've got to adjust the settings!	", "pinyin":"	ひやてぇ！！ちゃんとちょうせつしろよ！	"},																			
"	279	":{"character":"	ごめんなさい…	","letter": "	I'm sorry, I'm sorry, I'm sorry.	", "pinyin":"	ごめんなさい…	"},																			
"	280	":{"character":"	アチーッ！！	","letter": "	Aah!	", "pinyin":"	あちーっ！！	"},																			
"	281	":{"character":"	冷てぇ！！	","letter": "	It's cold!	", "pinyin":"	ひやてぇ！！	"},																			
"	282	":{"character":"	アチーッ！！	","letter": "	Achy!	", "pinyin":"	あちーっ！！	"},																			
"	283	":{"character":"	冷てぇ！！	","letter": "	It's cold!	", "pinyin":"	ひやてぇ！！	"},																			
"	284	":{"character":"	えっと…えっと…	","letter": "	Uh... uh...	", "pinyin":"	えっと…えっと…	"},																			
"	285	":{"character":"	パンダ…もういい気持だけもらっとく	","letter": "	Panda... just take the good feelings already.	", "pinyin":"	ぱんだ…もういいきもちだけもらっとく	"},																			
"	286	":{"character":"	いいニオイになったね	","letter": "	You got a nice smell now.	", "pinyin":"	いいにおいになったね	"},																			
"	287	":{"character":"	何の香りだ？ここのシャンプー	","letter": "	What's that smell? Shampoo.	", "pinyin":"	なにのかおりだ？ここのしゃんぷー	"},																			
"	288	":{"character":"	うんすごくおいしそうなニオイ	","letter": "	It smells so good.	", "pinyin":"	うんすごくおいしそうなにおい	"},																			
"	289	":{"character":"	これ	","letter": "	Here.	", "pinyin":"	これ	"},																			
"	290	":{"character":"	クマザサシャンプーだね	","letter": "	Kumazasa shampoo.	", "pinyin":"	くまざさしゃんぷーだね	"},																			
"	291	":{"character":"	飲めないかな？	","letter": "	Can I drink it?	", "pinyin":"	のめないかな？	"},																			
"	292	":{"character":"	飲むんじゃねぇぞ	","letter": "	Don't drink it!	", "pinyin":"	のむんじゃねぇぞ	"},																			
"	293	":{"character":"	というわけでパンダくんお風呂に入れてみよう	","letter": "	So, let's give him a bath, panda.	", "pinyin":"	というわけでぱんだくんおふろにいれてみよう	"},																			
"	294	":{"character":"	いいね	","letter": "	That's good.	", "pinyin":"	いいね	"},																			
"	295	":{"character":"	よくねぇやめろ	","letter": "	No, no, no, no, no, no, no, no, no, no, no, no, no.	", "pinyin":"	よくねぇやめろ	"},																			
"	296	":{"character":"	わ～い！わ～い飛んだ飛んだ！	","letter": "	Oh, wow! Yay, it flew!	", "pinyin":"	わ～い！わ～いとんだとんだ！	"},																			
"	297	":{"character":"	そうそううまいうまい	","letter": "	Oh, yeah, that's good, that's good, that's good, that's good.	", "pinyin":"	そうそううまいうまい	"},																			
"	298	":{"character":"	あれどうやるの？	","letter": "	How do you do that?	", "pinyin":"	あれどうやるの？	"},																			
"	299	":{"character":"	こうだよ	","letter": "	Like this.	", "pinyin":"	こうだよ	"},																			
"	300	":{"character":"	やめろ！	","letter": "	Stop it!	", "pinyin":"	やめろ！	"},																			
"	301	":{"character":"	ったく！	","letter": "	Oh, shit!	", "pinyin":"	ったく！	"},																			
"	302	":{"character":"	どこ行くの？	","letter": "	Where are you going?	", "pinyin":"	どこいくの？	"},																			
"	303	":{"character":"	俺はサウナが好きなんだ	","letter": "	I like saunas.	", "pinyin":"	おれはさうながすきなんだ	"},																			
"	304	":{"character":"	それは魚！	","letter": "	That's a fish!	", "pinyin":"	それはさかな！	"},																			
"	305	":{"character":"	それはアンテナ！	","letter": "	It's an antenna!	", "pinyin":"	それはあんてな！	"},																			
"	306	":{"character":"	それは手品！	","letter": "	It's a magic trick!	", "pinyin":"	それはてじな！	"},																			
"	307	":{"character":"	サウナって何？	","letter": "	What's a sauna?	", "pinyin":"	さうなってなに？	"},																			
"	308	":{"character":"	ふぅ～なんかすごい汗出るよ	","letter": "	It makes you sweat like crazy.	", "pinyin":"	ふぅ～なんかすごいあせでるよ	"},																			
"	309	":{"character":"	それがサウナのいいところだ	","letter": "	That's the beauty of a sauna.	", "pinyin":"	それがさうなのいいところだ	"},																			
"	310	":{"character":"	蒸されてる感じ	","letter": "	It's like being steamed.	", "pinyin":"	むされてるかんじ	"},																			
"	311	":{"character":"	これが体にいいんだよ！	","letter": "	It's good for you!	", "pinyin":"	これがからだにいいんだよ！	"},																			
"	312	":{"character":"	もう限界…	","letter": "	I'm at my limit...	", "pinyin":"	もうげんかい…	"},																			
"	313	":{"character":"	情けねぇな	","letter": "	I'm so pathetic...	", "pinyin":"	なさけねぇな	"},																			
"	314	":{"character":"	僕ももうダメ…	","letter": "	I can't take it anymore either...	", "pinyin":"	ぼくももうだめ…	"},																			
"	315	":{"character":"	辛抱が足りねぇな	","letter": "	I'm running out of patience.	", "pinyin":"	しんぼうがたりねぇな	"},																			
"	316	":{"character":"	今日はやけに時間が長く感じるぜ	","letter": "	Time seems to be taking longer than usual today...	", "pinyin":"	きょうはやけにじかんがながくかんじるぜ	"},																			
"	317	":{"character":"	俺ももう限界…	","letter": "	I'm at my limit too...	", "pinyin":"	おれももうげんかい…	"},																			
"	318	":{"character":"	出よう	","letter": "	Let's get out of here.	", "pinyin":"	でよう	"},																			
"	319	":{"character":"	テメエらの仕業か！	","letter": "	You did this to me!	", "pinyin":"	てめえらのしぎょうか！	"},																			
"	320	":{"character":"	おもしろかった！	","letter": "	That was fun.	", "pinyin":"	おもしろかった！	"},																			
"	321	":{"character":"	夜遊びっておもしろいね	","letter": "	The nightlife is fun.	", "pinyin":"	よあそびっておもしろいね	"},																			
"	322	":{"character":"	小腹も空いたしちょっと一杯やってくか	","letter": "	I'm feeling a little hungry. I think I'm gonna grab a drink.	", "pinyin":"	こばらもあいたしちょっといっぱいやってくか	"},																			
"	323	":{"character":"	いいね	","letter": "	Yeah, that sounds good.	", "pinyin":"	いいね	"},																			
"	324	":{"character":"	えっ？なになに？	","letter": "	What? What is it?	", "pinyin":"	えっ？なになに？	"},																			
"	325	":{"character":"	へいらっしゃい！	","letter": "	Come here!	", "pinyin":"	へいらっしゃい！	"},																			
"	326	":{"character":"	おや今日は新顔さんもご一緒で	","letter": "	Well, we have a newcomer with us today.	", "pinyin":"	おやきょうはしんがおさんもごいっしょで	"},																			
"	327	":{"character":"	親父とりあえず生２つ	","letter": "	Dad, I'll just have two drafts for now.	", "pinyin":"	おやじとりあえずなま２つ	"},																			
"	328	":{"character":"	あとアイスコーヒーください	","letter": "	And an iced coffee, please.	", "pinyin":"	あとあいすこーひーください	"},																			
"	329	":{"character":"	カフェじゃねぇんだぞ	","letter": "	This ain't no cafe!	", "pinyin":"	かふぇじゃねぇんだぞ	"},																			
"	330	":{"character":"	ああおいしそう！	","letter": "	Looks delicious!	", "pinyin":"	ああおいしそう！	"},																			
"	331	":{"character":"	串ごと食うなよ	","letter": "	Don't eat the whole skewer!	", "pinyin":"	くしごとくうなよ	"},																			
"	332	":{"character":"	おいしい！	","letter": "	Delicious!	", "pinyin":"	おいしい！	"},																			
"	333	":{"character":"	まぁぐいっと！	","letter": "	Take a big gulp!	", "pinyin":"	まぁぐいっと！	"},																			
"	334	":{"character":"	ああすみません	","letter": "	Oh, I'm sorry.	", "pinyin":"	ああすみません	"},																			
"	335	":{"character":"	夜遊びって最高だね！	","letter": "	I love a good night out!	", "pinyin":"	よあそびってさいこうだね！	"},																			
"	336	":{"character":"	だろ！	","letter": "	It's great!	", "pinyin":"	だろ！	"},																			
"	337	":{"character":"	人生はな昼もあれば夜もある	","letter": "	There's day and there's night.	", "pinyin":"	じんせいはなひるもあればよるもある	"},																			
"	338	":{"character":"	明るいときもあれば暗いときもある	","letter": "	There are light times and dark times.	", "pinyin":"	あかるいときもあればくらいときもある	"},																			
"	339	":{"character":"	暗いときにも楽しいことはたくさんあるんだよ	","letter": "	There's a lot of fun in the dark times, too.	", "pinyin":"	くらいときにもたのしいことはたくさんあるんだよ	"},																			
"	340	":{"character":"	どっちもあるからいいんだよね	","letter": "	It's good to have both, isn't it?	", "pinyin":"	どっちもあるからいいんだよね	"},																			
"	341	":{"character":"	お客さん深いね	","letter": "	You're a deep customer.	", "pinyin":"	おきゃくさんふかいね	"},																			
"	342	":{"character":"	そうだよね	","letter": "	That's right.	", "pinyin":"	そうだよね	"},																			
"	343	":{"character":"	パンダも白いとこと黒いとこ両方あるからいいんだもんね	","letter": "	Pandas are good because they have both white and black parts.	", "pinyin":"	ぱんだもしろいとことくろいとこりょうほうあるからいいんだもんね	"},																			
"	344	":{"character":"	おおそうだな！そのとおりだ！	","letter": "	Oh, yes! That's right!	", "pinyin":"	おおそうだな！そのとおりだ！	"},																			
"	345	":{"character":"	だね	","letter": "	That's right.	", "pinyin":"	だね	"},																			
"	346	":{"character":"	グリズリーくん	","letter": "	Grizzly bear.	", "pinyin":"	ぐりずりーくん	"},																			
"	347	":{"character":"	すっかり寝ちゃったねパンダくん	","letter": "	You're all tuckered out, panda.	", "pinyin":"	すっかりねちゃったねぱんだくん	"},																			
"	348	":{"character":"	なんで俺がコイツをおぶって帰んなきゃなんねぇんだよ	","letter": "	Why do I have to carry him home?	", "pinyin":"	なんでおれがこいつをおぶってかえんなきゃなんねぇんだよ	"},																			
"	349	":{"character":"	楽しかった…	","letter": "	It was fun...	", "pinyin":"	たのしかった…	"},																			
"	350	":{"character":"	楽しかったって	","letter": "	It was fun...	", "pinyin":"	たのしかったって	"},																			
"	351	":{"character":"	まっまた連れてきてやってもいいかな	","letter": "	I'll bring him back again.	", "pinyin":"	まっまたつれてきてやってもいいかな	"},																			
"	352	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguin! Penguin!	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	353	":{"character":"	何？パンダ君	","letter": "	What? Mr. Panda.	", "pinyin":"	なに？ぱんだくん	"},																			
"	354	":{"character":"	自分が格好いいなと思った瞬間の話して	","letter": "	Tell me about a moment when you thought you were cool.	", "pinyin":"	じぶんがかっこいいなとおもったしゅんかんのはなして	"},																			
"	355	":{"character":"	そうだなぁ	","letter": "	I don't know.	", "pinyin":"	そうだなぁ	"},																			
"	356	":{"character":"	ないならいいよ	","letter": "	If you don't have one, that's okay.	", "pinyin":"	ないならいいよ	"},																			
"	357	":{"character":"	二秒も考えさせてもらえないんだね	","letter": "	You're not gonna give me two seconds to think about it.	", "pinyin":"	にびょうもかんがえさせてもらえないんだね	"},																			
"	358	":{"character":"	ないならいいよ	","letter": "	If you don't have one, that's okay.	", "pinyin":"	ないならいいよ	"},																			
"	359	":{"character":"	探したかったな	","letter": "	I wish I could have found it.	", "pinyin":"	さがしたかったな	"},																			
"	360	":{"character":"	ないならいいよ	","letter": "	If you don't have it, it's fine.	", "pinyin":"	ないならいいよ	"},																			
"	361	":{"character":"	白熊君頼んだ	","letter": "	Polar Bear, you're on.	", "pinyin":"	しろくまくんたのんだ	"},																			
"	362	":{"character":"	次回しろくまカフェ	","letter": "	Next time at the Shirokuma Cafe.	", "pinyin":"	じかいしろくまかふぇ	"},																			
"	363	":{"character":"	生放送でお送りします	","letter": "	We'll be broadcasting live.	", "pinyin":"	なまほうそうでおおくりします	"},																			
"	364	":{"character":"	いつもどおりやるよ	","letter": "	We'll be doing what we always do.	", "pinyin":"	いつもどおりやるよ	"},																			
"	365	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	お楽しみに	"},																			
}