const koreanIntegratedKoreanSrsData = {
    "1학년": { "letter": "freshman", "srsData": { "state": "old", "date": 1641502353923 } },
    "2학년": { "letter": "sophomore", "srsData": { "state": "old", "date": 1641502219325 } },
    "3학년": { "letter": "junior", "srsData": { "state": "old", "date": 1641502382011 } },
    "4학년": { "letter": "senior", "srsData": { "state": "old", "date": 1641502350095 } },
    "과": { "letter": "lesson, chapter", "srsData": { "state": "old", "date": 1641502507138 } },
    "대학생": { "letter": "college student", "srsData": { "state": "old", "date": 1641502215637 } },
    "미국": { "letter": "the United States", "srsData": { "state": "old", "date": 1641502383956 } },
    "사람": { "letter": "person, people", "srsData": { "state": "old", "date": 1641502139148 } },
    "인사": { "letter": "greeting", "srsData": { "state": "old", "date": 1641502716777 } },
    "학년": { "letter": "school year", "srsData": { "state": "old", "date": 1641502142733 } },
    "학생": { "letter": "student", "srsData": { "state": "old", "date": 1641502352362 } },
    "한국": { "letter": "Korea", "srsData": { "state": "old", "date": 1641502145761 } },
    "나": { "letter": "I (plain)", "srsData": { "state": "old", "date": 1641502490914 } },
    "저": { "letter": "that (over there)", "srsData": { "state": "fresh", "date": 1641331351408 } },
    "나는": { "letter": "as for me (plain)", "srsData": { "state": "old", "date": 1641502510719 } },
    "저는": { "letter": "as for me (humble)", "srsData": { "state": "old", "date": 1641502631904 } },
    "나도": { "letter": "I also (plain)", "srsData": { "state": "old", "date": 1641502673897 } },
    "저도": { "letter": "I also (humble)", "srsData": { "state": "old", "date": 1641502613176 } },
    "일": { "letter": "day", "srsData": { "state": "average", "date": 1641339489425 } },
    "이": { "letter": "this", "srsData": { "state": "old", "date": 1641502329722 } },
    "안녕하다 (안녕하세요)": { "letter": "to be well ('Hi', 'Hello', 'How are you?')", "srsData": { "state": "old", "date": 1641502236685 } },
    "이다 (이에요, 여요)": { "letter": "to be (equation)", "srsData": { "state": "old", "date": 1641502212018 } },
    "도": { "letter": "also, too", "srsData": { "state": "old", "date": 1641502337531 } },
    "은": { "letter": "topic particle ('as for')", "srsData": { "state": "old", "date": 1641502273076 } },
    "는": { "letter": "topic particle ('as for')", "srsData": { "state": "old", "date": 1641502423332 } },
    "선생님": { "letter": "teacher", "srsData": { "state": "old", "date": 1641502654469 } },
    "씨": { "letter": "(attached to a person's name for courtesy)", "srsData": { "state": "old", "date": 1641502217577 } },
    "영국": { "letter": "United Kingdom", "srsData": { "state": "old", "date": 1641502373151 } },
    "영어": { "letter": "the English language", "srsData": { "state": "old", "date": 1641502336046 } },
    "이름": { "letter": "name", "srsData": { "state": "old", "date": 1641502692660 } },
    "일본": { "letter": "Japan", "srsData": { "state": "old", "date": 1641502430448 } },
    "중국": { "letter": "China", "srsData": { "state": "old", "date": 1641502689564 } },
    "클래스": { "letter": "class", "srsData": { "state": "old", "date": 1641502364040 } },
    "한국어": { "letter": "the Korean language", "srsData": { "state": "old", "date": 1641502370952 } },
    "한국말": { "letter": "the Korean language", "srsData": { "state": "old", "date": 1641502360647 } },
    "네": { "letter": "yes, I see, okay", "srsData": { "state": "old", "date": 1641502380635 } },
    "아니요": { "letter": "no", "srsData": { "state": "old", "date": 1641502478800 } },
    "가": { "letter": "(subject particle)", "srsData": { "state": "old", "date": 1641502310141 } },
    "그렇다 (그래요)": { "letter": "to be so ('Is that right?')", "srsData": { "state": "average", "date": 1641339253248 } },
    "반갑다 (반갑습니다)": { "letter": "to be glad ('Glad to meet you')", "srsData": { "state": "old", "date": 1641502393074 } },
    "아니다 (아니에요)": { "letter": "to not be (negative equation)", "srsData": { "state": "old", "date": 1641502160368 } },
    "뭐": { "letter": "what", "srsData": { "state": "old", "date": 1641502265016 } },
    "무넛": { "letter": "what", "srsData": { "state": "old", "date": 1641502408080 } },
    "아": { "letter": "oh", "srsData": { "state": "old", "date": 1641502449142 } },
    "프랑스": { "letter": "France", "srsData": { "state": "old", "date": 1641502603493 } },
    "스페인": { "letter": "Spain", "srsData": { "state": "old", "date": 1641502225278 } },
    "러시아": { "letter": "Russia", "srsData": { "state": "old", "date": 1641502307206 } },
    "일본어": { "letter": "Japanese (language)", "srsData": { "state": "old", "date": 1641502343329 } },
    "일어": { "letter": "Japanese (language)", "srsData": { "state": "average", "date": 1641339149259 } },
    "중국어": { "letter": "Chinese (language)", "srsData": { "state": "old", "date": 1641502609938 } },
    "프랑스어": { "letter": "French (language)", "srsData": { "state": "old", "date": 1641502286682 } },
    "스페인어": { "letter": "Spanish (language)", "srsData": { "state": "old", "date": 1641502538649 } },
    "러시아어": { "letter": "Russian (language)", "srsData": { "state": "old", "date": 1641502648753 } },
    "한국사람": { "letter": "Korean (person)", "srsData": { "state": "old", "date": 1641502250761 } },
    "미국사람": { "letter": "American (person)", "srsData": { "state": "old", "date": 1641502476416 } },
    "영국사람": { "letter": "British (person)", "srsData": { "state": "old", "date": 1641502177355 } },
    "일본사람": { "letter": "Japanese (person)", "srsData": { "state": "old", "date": 1641502318681 } },
    "중국사람": { "letter": "Chinese (person)", "srsData": { "state": "old", "date": 1641502439133 } },
    "프랑스사람": { "letter": "French (person)", "srsData": { "state": "old", "date": 1641502660842 } },
    "스페인사람": { "letter": "Spanish (person)", "srsData": { "state": "old", "date": 1641502678777 } },
    "러시아사람": { "letter": "Russian (person)", "srsData": { "state": "old", "date": 1641502434657 } },
    "가방": { "letter": "bag", "srsData": { "state": "old", "date": 1641502445874 } },
    "기숙사": { "letter": "dormitory", "srsData": { "state": "old", "date": 1641502705766 } },
    "대학교": { "letter": "college, university", "srsData": { "state": "old", "date": 1641502453023 } },
    "도서관": { "letter": "library", "srsData": { "state": "old", "date": 1641502270751 } },
    "유니온빌딩": { "letter": "Union Building", "srsData": { "state": "old", "date": 1641502670995 } },
    "시계": { "letter": "clock, watch", "srsData": { "state": "old", "date": 1641502623619 } },
    "식당": { "letter": "restaurant", "srsData": { "state": "old", "date": 1641502619589 } },
    "학교식당": { "letter": "school cafeteria", "srsData": { "state": "old", "date": 1641502260555 } },
    "안": { "letter": "do not", "srsData": { "state": "old", "date": 1641502732195 } },
    "앞": { "letter": "the front", "srsData": { "state": "old", "date": 1641502400791 } },
    "뒤": { "letter": "the back, behind", "srsData": { "state": "old", "date": 1641502253036 } },
    "옆": { "letter": "the side, beside", "srsData": { "state": "old", "date": 1641502229645 } },
    "어디": { "letter": "what place, where (question word)", "srsData": { "state": "old", "date": 1641502472760 } },
    "우체국": { "letter": "post office", "srsData": { "state": "old", "date": 1641502636569 } },
    "위": { "letter": "the top side, above", "srsData": { "state": "old", "date": 1641502665988 } },
    "밑": { "letter": "the bottom, below", "srsData": { "state": "old", "date": 1641502442938 } },
    "의자": { "letter": "chair", "srsData": { "state": "old", "date": 1641502427044 } },
    "책": { "letter": "book", "srsData": { "state": "old", "date": 1641502243745 } },
    "책방": { "letter": "bookstore", "srsData": { "state": "old", "date": 1641502542872 } },
    "첵상": { "letter": "desk", "srsData": { "state": "old", "date": 1641598265450 } },
    "캠퍼스": { "letter": "campus", "srsData": { "state": "old", "date": 1641502348558 } },
    "학교": { "letter": "school", "srsData": { "state": "old", "date": 1641502302868 } },
    "학생회관": { "letter": "student center", "srsData": { "state": "old", "date": 1641502198859 } },
    "층": { "letter": "floor, layer", "srsData": { "state": "old", "date": 1641502488157 } },
    "있다 (있어요)": { "letter": "to have", "srsData": { "state": "old", "date": 1641502340200 } },
    "저어": { "letter": "uh (expression of hesitation)", "srsData": { "state": "old", "date": 1641502327549 } },
    "에": { "letter": "at, in, on (time)", "srsData": { "state": "old", "date": 1641502497295 } },
    "숙제": { "letter": "homework", "srsData": { "state": "old", "date": 1641598673468 } },
    "숙제하다": { "letter": "to do homework", "srsData": { "state": "old", "date": 1641502240990 } },
    "아침": { "letter": "breakfast; morning", "srsData": { "state": "old", "date": 1641676762611 } },
    "음식": { "letter": "food", "srsData": { "state": "old", "date": 1641502357201 } },
    "커피": { "letter": "coffee", "srsData": { "state": "old", "date": 1641502367404 } },
    "괜찮다 (괜찮아요)": { "letter": "to be all right, to be okay", "srsData": { "state": "old", "date": 1641502398038 } },
    "넓다": { "letter": "to be spacious, to be wide", "srsData": { "state": "old", "date": 1641502299660 } },
    "많다": { "letter": "to be many, to be much", "srsData": { "state": "old", "date": 1641502527665 } },
    "맛있다 (맛있어요)": { "letter": "to be delicious", "srsData": { "state": "old", "date": 1641502456520 } },
    "싸다 (싸요)": { "letter": "to be cheap", "srsData": { "state": "old", "date": 1641598207831 } },
    "어떻다 (어때요)": { "letter": "to be how", "srsData": { "state": "old", "date": 1641502323080 } },
    "좋다 (좋아요)": { "letter": "to be good, to be nice", "srsData": { "state": "old", "date": 1641502482022 } },
    "크다": { "letter": "to be big", "srsData": { "state": "old", "date": 1641598492158 } },
    "아주": { "letter": "very, really", "srsData": { "state": "old", "date": 1641598676785 } },
    "참": { "letter": "by the way", "srsData": { "state": "old", "date": 1641598334769 } },
    "가다": { "letter": "to go", "srsData": { "state": "old", "date": 1641598214221 } },
    "먹다 (먹어요)": { "letter": "to eat", "srsData": { "state": "old", "date": 1641598685876 } },
    "앉다": { "letter": "to sit", "srsData": { "state": "old", "date": 1641598693195 } },
    "알다": { "letter": "to know", "srsData": { "state": "old", "date": 1641676782748 } },
    "하다 (해요)": { "letter": "to do", "srsData": { "state": "old", "date": 1641598258569 } },
    "어": { "letter": "oh", "srsData": { "state": "old", "date": 1641598204520 } },
    "~어요": { "letter": "(polite ending)", "srsData": { "state": "old", "date": 1641598687446 } },
    "~아요": { "letter": "(polite ending)", "srsData": { "state": "old", "date": 1641598503937 } },
    "그리고": { "letter": "and", "srsData": { "state": "old", "date": 1641598648595 } },
    "경제학": { "letter": "economics", "srsData": { "state": "old", "date": 1641598721057 } },
    "교과서": { "letter": "textbook", "srsData": { "state": "average", "date": 1641339024766 } },
    "교실": { "letter": "classroom", "srsData": { "state": "average", "date": 1641339278393 } },
    "내일": { "letter": "tomorrow", "srsData": { "state": "old", "date": 1641598486087 } },
    "반": { "letter": "class", "srsData": { "state": "old", "date": 1641598482383 } },
    "사질": { "letter": "dictionary", "srsData": { "state": "old", "date": 1641598298663 } },
    "수업": { "letter": "course; class", "srsData": { "state": "old", "date": 1641598465269 } },
    "시간": { "letter": "hour (duration)", "srsData": { "state": "old", "date": 1641676857355 } },
    "여자": { "letter": "woman", "srsData": { "state": "old", "date": 1641598294258 } },
    "오늘": { "letter": "today", "srsData": { "state": "average", "date": 1641339138462 } },
    "우산": { "letter": "umbrella", "srsData": { "state": "old", "date": 1641598639276 } },
    "질문": { "letter": "question", "srsData": { "state": "average", "date": 1641417570927 } },
    "집": { "letter": "home; house", "srsData": { "state": "old", "date": 1641598267412 } },
    "친구": { "letter": "friend", "srsData": { "state": "old", "date": 1641598716352 } },
    "컴퓨터": { "letter": "computer", "srsData": { "state": "old", "date": 1641598275261 } },
    "누구": { "letter": "who", "srsData": { "state": "old", "date": 1641598727857 } },
    "인사하다": { "letter": "to greet", "srsData": { "state": "old", "date": 1641598321404 } },
    "읽다": { "letter": "to read", "srsData": { "state": "old", "date": 1641598330899 } },
    "없다 (없어요)": { "letter": "to not be (existence), to not have", "srsData": { "state": "old", "date": 1641598249075 } },
    "재미있다 (재미있어요)": { "letter": "to be interesting, fun", "srsData": { "state": "old", "date": 1641598456520 } },
    "그런데": { "letter": "by the way", "srsData": { "state": "old", "date": 1641598218141 } },
    "~(으)세요": { "letter": "(honorific polite ending)", "srsData": { "state": "old", "date": 1641598702296 } },
    "어제": { "letter": "yesterday", "srsData": { "state": "old", "date": 1641598428449 } },
    "공부 (하다)": { "letter": "study", "srsData": { "state": "old", "date": 1641598301949 } },
    "남자": { "letter": "man", "srsData": { "state": "old", "date": 1641598271367 } },
    "시험": { "letter": "test; exam", "srsData": { "state": "old", "date": 1641598287208 } },
    "역사": { "letter": "history", "srsData": { "state": "average", "date": 1641417738118 } },
    "주스": { "letter": "juice", "srsData": { "state": "old", "date": 1641598710704 } },
    "텔레비전": { "letter": "television", "srsData": { "state": "old", "date": 1641598253530 } },
    "마시다": { "letter": "to drink", "srsData": { "state": "old", "date": 1641598473019 } },
    "만나다": { "letter": "to meet", "srsData": { "state": "old", "date": 1641598282678 } },
    "보다 (보세요)": { "letter": "to see, to look, to watch", "srsData": { "state": "old", "date": 1641598443671 } },
    "지내다 (지내세요)": { "letter": "to get along", "srsData": { "state": "old", "date": 1641598611865 } },
    "그래서": { "letter": "so, therefore", "srsData": { "state": "average", "date": 1641417679112 } },
    "그럼": { "letter": "(if so) then", "srsData": { "state": "old", "date": 1641598665031 } },
    "매일": { "letter": "every day", "srsData": { "state": "old", "date": 1641598278432 } },
    "어떻게": { "letter": "how", "srsData": { "state": "old", "date": 1641598733580 } },
    "열심히": { "letter": "diligently", "srsData": { "state": "old", "date": 1641598469484 } },
    "요즘": { "letter": "these days", "srsData": { "state": "fresh", "date": 1641331366256 } },
    "잘": { "letter": "well", "srsData": { "state": "old", "date": 1641676860566 } },
    "지금": { "letter": "now", "srsData": { "state": "old", "date": 1641676873881 } },
    "들": { "letter": "(plural particle)", "srsData": { "state": "old", "date": 1641676839678 } },
    "을": { "letter": "(object particle)", "srsData": { "state": "old", "date": 1641676862869 } },
    "를": { "letter": "(object particle)", "srsData": { "state": "old", "date": 1641676880862 } },
    "밋없다": { "letter": "to be tasteless, not delicious", "srsData": { "state": "fresh", "date": 1641331358049 } },
    "재미없다": { "letter": "to be uninteresting", "srsData": { "state": "old", "date": 1641676776591 } },
    "바빠요": { "letter": "I'm busy", "srsData": { "state": "old", "date": 1641676746510 } },
    "그저그래요": { "letter": "Just so-so", "srsData": { "state": "old", "date": 1641676832669 } },
    "괜찮아요": { "letter": "I'm all right, Not too bad", "srsData": { "state": "old", "date": 1641676811079 } },
    "좋아요": { "letter": "I'm fine", "srsData": { "state": "old", "date": 1641676866514 } },
    "잘지내요": { "letter": "I'm doing well", "srsData": { "state": "old", "date": 1641676907225 } },
    "동양학": { "letter": "Asian studies", "srsData": { "state": "old", "date": 1641676680572 } },
    "물리학": { "letter": "physics", "srsData": { "state": "old", "date": 1641676767759 } },
    "기계공학": { "letter": "mechanical engineering", "srsData": { "state": "old", "date": 1641676942772 } },
    "음악": { "letter": "music", "srsData": { "state": "average", "date": 1641417721691 } },
    "건축학": { "letter": "architecture", "srsData": { "state": "old", "date": 1641676896432 } },
    "언어학": { "letter": "linguistics", "srsData": { "state": "old", "date": 1641676848246 } },
    "교육학": { "letter": "education", "srsData": { "state": "old", "date": 1641676671551 } },
    "생물학": { "letter": "biology", "srsData": { "state": "average", "date": 1641339039584 } },
    "전기공학": { "letter": "electrical engineering", "srsData": { "state": "average", "date": 1641339457724 } },
    "피아노": { "letter": "piano", "srsData": { "state": "average", "date": 1641339468470 } },
    "펍학": { "letter": "law", "srsData": { "state": "average", "date": 1641339238516 } },
    "개": { "letter": "item", "srsData": { "state": "average", "date": 1641339027227 } },
    "고등학생": { "letter": "high school student", "srsData": { "state": "average", "date": 1641339444600 } },
    "남동생": { "letter": "younger brother", "srsData": { "state": "average", "date": 1641339422267 } },
    "대학원생": { "letter": "graduate student", "srsData": { "state": "average", "date": 1641339144613 } },
    "동생": { "letter": "younger sibling", "srsData": { "state": "average", "date": 1641339288987 } },
    "보스톤": { "letter": "Boston", "srsData": { "state": "average", "date": 1641339241443 } },
    "부모님": { "letter": "parents", "srsData": { "state": "average", "date": 1641339261123 } },
    "아버지": { "letter": "father", "srsData": { "state": "average", "date": 1641339426030 } },
    "어머니": { "letter": "mother", "srsData": { "state": "average", "date": 1641339434131 } },
    "여동생": { "letter": "younger sister", "srsData": { "state": "average", "date": 1641339302220 } },
    "오빠": { "letter": "the older brother of a female", "srsData": { "state": "average", "date": 1641339505331 } },
    "형": { "letter": "the older brother of a male", "srsData": { "state": "average", "date": 1641417637647 } },
    "홍콩": { "letter": "Hong Kong", "srsData": { "state": "average", "date": 1641339043594 } },
    "몇": { "letter": "how many; what (with a counter)", "srsData": { "state": "average", "date": 1641339034356 } },
    "관": { "letter": "volume", "srsData": { "state": "average", "date": 1641339524104 } },
    "년": { "letter": "year", "srsData": { "state": "average", "date": 1641417595355 } },
    "달": { "letter": "month", "srsData": { "state": "average", "date": 1641417549964 } },
    "달러": { "letter": "dollar", "srsData": { "state": "average", "date": 1641417614299 } },
    "마리": { "letter": "animal", "srsData": { "state": "average", "date": 1641417686678 } },
    "명": { "letter": "people", "srsData": { "state": "average", "date": 1641417579655 } },
    "원": { "letter": "won (Korean currency)", "srsData": { "state": "average", "date": 1641417552559 } },
    "월": { "letter": "month", "srsData": { "state": "average", "date": 1641417539571 } },
    "두": { "letter": "(with counter) two", "srsData": { "state": "average", "date": 1641417474456 } },
    "한": { "letter": "(with counter) one", "srsData": { "state": "average", "date": 1641417642847 } },
    "계시다": { "letter": "to be (existence); stay (hom.)", "srsData": { "state": "fresh", "date": 1641331368578 } },
    "하고": { "letter": "with", "srsData": { "state": "average", "date": 1641417618303 } },
    "거": { "letter": "thing (contraction of 것)", "srsData": { "state": "fresh", "date": 1641331361343 } },
    "누나": { "letter": "the older sister of a male", "srsData": { "state": "average", "date": 1641417490888 } },
    "뉴욕": { "letter": "New York", "srsData": { "state": "average", "date": 1641417586669 } },
    "룸메이트": { "letter": "roommate", "srsData": { "state": "average", "date": 1641417486605 } },
    "방": { "letter": "room", "srsData": { "state": "fresh", "date": 1641331363221 } },
    "사이": { "letter": "relationship; between", "srsData": { "state": "average", "date": 1641417591364 } },
    "아파트": { "letter": "apartment", "srsData": { "state": "average", "date": 1641417710104 } },
    "언니": { "letter": "the older sister of a female", "srsData": { "state": "average", "date": 1641417653751 } },
    "로스앤젤레스": { "letter": "Los Angeles (L.A.)", "srsData": { "state": "average", "date": 1641417731218 } },
    "하와이": { "letter": "Hawai'i", "srsData": { "state": "average", "date": 1641417600985 } },
    "만": { "letter": "only", "srsData": { "state": "fresh", "date": 1641330984403 } },
    "의": { "letter": "of", "srsData": { "state": "fresh", "date": 1641330986102 } },
    "고맙다": { "letter": "to be thankful", "srsData": { "state": "fresh", "date": 1641330992223 } },
    "나쁘다": { "letter": "to be bad", "srsData": { "state": "fresh", "date": 1641330995302 } },
    "비싸다": { "letter": "to be expensive", "srsData": { "state": "fresh", "date": 1641330999835 } },
    "예쁘다": { "letter": "to be pretty", "srsData": { "state": "fresh", "date": 1641331005930 } },
    "작다": { "letter": "to be small (in size)", "srsData": { "state": "fresh", "date": 1641331012631 } },
    "배우다": { "letter": "to learn", "srsData": { "state": "fresh", "date": 1641331348447 } },
    "오다": { "letter": "to come", "srsData": { "state": "fresh", "date": 1641331020781 } },
    "자다": { "letter": "to sleep", "srsData": { "state": "fresh", "date": 1641331023007 } },
    "주다": { "letter": "to give", "srsData": { "state": "fresh", "date": 1641331027518 } },
    "저희": { "letter": "we; us; our (humble)", "srsData": { "state": "fresh", "date": 1641331034029 } },
    "우리": { "letter": "we; us; our (plain)", "srsData": { "state": "fresh", "date": 1641331036171 } },
    "이거": { "letter": "this (=이갓)", "srsData": { "state": "fresh", "date": 1641331040452 } },
    "내": { "letter": "my (plain)", "srsData": { "state": "fresh", "date": 1641331043471 } },
    "재": { "letter": "my (humble)", "srsData": { "state": "fresh", "date": 1641331045998 } },
    "공원": { "letter": "park", "srsData": { "state": "fresh", "date": 1641331048667 } },
    "랩": { "letter": "lab", "srsData": { "state": "fresh", "date": 1641331050553 } },
    "백화점": { "letter": "department store", "srsData": { "state": "fresh", "date": 1641331057705 } },
    "생일": { "letter": "birthday", "srsData": { "state": "fresh", "date": 1641331060557 } },
    "서점": { "letter": "bookstore (= 책방)" },
    "선물(하다)": { "letter": "present, gift" },
    "쇼핑(하다)": { "letter": "shopping" },
    "연습(하다)": { "letter": "practice" },
    "오래간만": { "letter": "after a long time" },
    "운동(하다)": { "letter": "exercise" },
    "일(하다)": { "letter": "work" },
    "저녁": { "letter": "evening; dinner" },
    "점심": { "letter": "lunch" },
    "커피숍": { "letter": "coffee shop, cafe" },
    "테니스": { "letter": "tennis" },
    "햄버거": { "letter": "hamburger" },
    "가르치다": { "letter": "to teach" },
    "사다": { "letter": "to buy" },
    "치다": { "letter": "to play (tennis)" },
    "에서": { "letter": "from (location)" },
    "안녕히": { "letter": "in peace" },
    "가게": { "letter": "store" },
    "오전": { "letter": "morning, a.m" },
    "오후": { "letter": "afternoon, p.m" },
    "옷": { "letter": "clothes" },
    "월요일": { "letter": "Monday" },
    "화요일": { "letter": "Tuesday" },
    "수요일": { "letter": "Wednesday" },
    "목요일": { "letter": "Thursday" },
    "금요일": { "letter": "Friday" },
    "토요일": { "letter": "Saturday" },
    "일요일": { "letter": "Sunday" },
    "정치학": { "letter": "political science" },
    "이번": { "letter": "this time" },
    "학기": { "letter": "semester, academic term" },
    "걷다": { "letter": "to walk" },
    "듣다(들어러)": { "letter": "to listen, to take a course" },
    "좋아하다": { "letter": "to like" },
    "과목": { "letter": "course, subject" },
    "분": { "letter": "minute" },
    "시": { "letter": "hour, o'clock" },
    "같이": { "letter": "together" },
    "언제": { "letter": "when" },
    "(으)러": { "letter": "in order to" },
    "날씨": { "letter": "weather" },
    "말(하다)": { "letter": "speech, words" },
    "버스": { "letter": "bus" },
    "볼펜": { "letter": "ball point pen" },
    "비행기": { "letter": "airplane" },
    "연필": { "letter": "pencil" },
    "자전거": { "letter": "bicycle" },
    "지하철": { "letter": "subway" },
    "자동차": { "letter": "car" },
    "하루": { "letter": "(one) day" },
    "한국타운": { "letter": "Korea town" },
    "까지": { "letter": "up to (location)" },
    "으로": { "letter": "toward, to" },
    "쯤": { "letter": "about, around" },
    "걸리다": { "letter": "to take (time)" },
    "살다": { "letter": "to live" },
    "쓰다": { "letter": "to write" },
    "가깝다": { "letter": "to be close, to be near" },
    "덥다": { "letter": "to be hot" },
    "멀다": { "letter": "to be far" },
    "쉽다": { "letter": "to be easy" },
    "어렵다": { "letter": "to be difficult" },
    "춥다": { "letter": "to be cold" },
    "좁다": { "letter": "to be narrow" },
    "보통": { "letter": "usually" },
    "얼마다; 얼마": { "letter": "how long, how much" },
    "조금": { "letter": "a little" },
    "뛰다": { "letter": "to run" },
    "운전하다": { "letter": "to drive" },
    "수영(하다)": { "letter": "swimming" },
    "수영장": { "letter": "swimming pool" },
    "전화(하다)": { "letter": "telephone" },
    "주말": { "letter": "weekend" },
    "테니스장": { "letter": "tennis court" },
    "파티": { "letter": "party" },
    "모르다": { "letter": "to not know, to be unaware of" },
    "일어나다": { "letter": "to get up" },
    "바쁘다": { "letter": "to be busy" },
    "너무": { "letter": "too much" },
    "못": { "letter": "cannot" },
    "왜": { "letter": "why" },
    "지난": { "letter": "last, past" },
    "았; 었; ㅆ": { "letter": "(past tense)" },
    "계절": { "letter": "season" },
    "꽃": { "letter": "flower" },
    "극장": { "letter": "movie theater" },
    "나라": { "letter": "country" },
    "내년": { "letter": "next year" },
    "다음": { "letter": "next; following" },
    "대학원": { "letter": "graduate school" },
    "방학": { "letter": "school vacation" },
    "브로드웨이 극장": { "letter": "Broadway theater" },
    "약속": { "letter": "engagement; promise" },
    "액션 영화": { "letter": "action movie" },
    "여름": { "letter": "summer" },
    "여행": { "letter": "travel" },
    "영화": { "letter": "movie" },
    "이스트 홀": { "letter": "East Hall" },
    "코미디": { "letter": "comedy" },
    "받다": { "letter": "to receive" },
    "아마": { "letter": "probably; perhaps" },
    "자주": { "letter": "often; frequently" },
    "정말": { "letter": "really" },
    "무슨": { "letter": "what; what kind of" },
    "어느": { "letter": "which" },
    "(으)ㄹ 거예요": { "letter": "(probability)" },
    "지난월요일": { "letter": "last Monday" },
    "이번월요일": { "letter": "this Monday" },
    "다음월요일": { "letter": "next Monday" },
    "지난토요일": { "letter": "last Saturday" },
    "이번토요일": { "letter": "this Saturday" },
    "다음토요일": { "letter": "next Saturday" },
    "지난주말": { "letter": "last weekend" },
    "이번주말": { "letter": "this weekend" },
    "다음주말": { "letter": "next weekend" },
    "지난주": { "letter": "last week" },
    "이번주": { "letter": "this week" },
    "다음주": { "letter": "next week" },
    "지난달": { "letter": "last month" },
    "이(번)달": { "letter": "this month" },
    "다음달": { "letter": "next month" },
    "적년": { "letter": "last year" },
    "올해": { "letter": "this year" },
    "가을": { "letter": "autumn, fall" },
    "겨울": { "letter": "winter" },
    "마켓": { "letter": "market" },
    "봄": { "letter": "spring" },
    "설거지": { "letter": "dishwashing" },
    "신문": { "letter": "newspaper" },
    "심리학": { "letter": "psychology" },
    "이야기": { "letter": "talk, chat (= 에가)" },
    "전공": { "letter": "major" },
    "주": { "letter": "week" },
    "준비": { "letter": "preparation" },
    "청소": { "letter": "cleaning" },
    "크리스마스": { "letter": "Christmas" },
    "흐리다": { "letter": "to be cloudy" },
    "보내다": { "letter": "to spend time" },
    "장(을) 보다": { "letter": "to buy one's groceries" },
    "가끔": { "letter": "sometimes, occasionally" },
    "많이": { "letter": "each other" },
    "~고": { "letter": "and (clausal connective)" },
    "가운데": { "letter": "the middle, the center" },
    "건너편": { "letter": "the other side" },
    "교회": { "letter": "church" },
    "꽃짐": { "letter": "flower shop" },
    "동네": { "letter": "neighborhood" },
    "서울": { "letter": "Seoul" },
    "슈퍼": { "letter": "supermarket" },
    "약국": { "letter": "drugstore" },
    "지도": { "letter": "map" },
    "쪽": { "letter": "side; direction" },
    "초등학교": { "letter": "elementary school" },
    "군데": { "letter": "place; spot" },
    "번": { "letter": "number" },
    "지요": { "letter": "isn't it? (seeking agreement)" },
    "여기": { "letter": "here" },
    "거기": { "letter": "there" },
    "저기": { "letter": "over there" },
    "내리다": { "letter": "to get off" },
    "타다": { "letter": "to get in or on; ride" },
    "깨끗하다": { "letter": "to be clean" },
    "따뜻하다": { "letter": "to be warm" },
    "조용하다": { "letter": "to be quiet" },
    "여러": { "letter": "many, several" },
    "그": { "letter": "that" },
    "근처": { "letter": "nearby; vicinity" },
    "마씀": { "letter": "speech; words (honorific)" },
    "말": { "letter": "speech; words (plain)" },
    "시천": { "letter": "city hall" },
    "역": { "letter": "station" },
    "오른쪽": { "letter": "right side" },
    "왼쪽": { "letter": "left side" },
    "우표": { "letter": "stamp" },
    "은행": { "letter": "bank" },
    "의사": { "letter": "doctor" },
    "처음": { "letter": "the first time" },
    "호선": { "letter": "subway line" },
    "좀": { "letter": "a little (contraction of 조금)" },
    "쭉": { "letter": "straight" },
    "돌다": { "letter": "to turn" },
    "팔다": { "letter": "to sell" },
    "묻다": { "letter": "to ask" },
    "보이다": { "letter": "to be seen; visible" },
    "뵙다": { "letter": "to see (humble)" },
    "보다": { "letter": "to see (plain)" },
    "감사하다": { "letter": "to be thankful" },
    "미안하다": { "letter": "to be sorry" },
    "습나다": { "letter": "(deferential ending for a statement)" },
    "습니까": { "letter": "(deferential ending for a question)" }
}
const koreanIntegratedKoreanSrsNextDate = "1641330984403"
const koreanIntegratedKoreanSrsNumber = "20"
const koreanIntegratedKoreanSrsProgress = { "timeStamp": "04/01/2022", "newItemsArray": ["서점", "선물(하다)", "쇼핑(하다)", "연습(하다)", "오래간만", "운동(하다)", "일(하다)", "저녁", "점심", "커피숍", "테니스", "햄버거", "가르치다", "사다", "치다", "에서", "안녕히", "가게", "오전", "오후", "옷", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일", "정치학", "이번", "학기", "걷다", "듣다(들어러)", "좋아하다", "과목", "분", "시", "같이", "언제", "(으)러", "날씨", "말(하다)", "버스", "볼펜", "비행기", "연필", "자전거", "지하철", "자동차", "하루", "한국타운", "까지", "으로", "쯤", "걸리다", "살다", "쓰다", "가깝다", "덥다", "멀다", "쉽다", "어렵다", "춥다", "좁다", "보통", "얼마다; 얼마", "조금", "뛰다", "운전하다", "수영(하다)", "수영장", "전화(하다)", "주말", "테니스장", "파티", "모르다", "일어나다", "바쁘다", "너무", "못", "왜", "지난", "았; 었; ㅆ", "계절", "꽃", "극장", "나라", "내년", "다음", "대학원", "방학", "브로드웨이 극장", "약속", "액션 영화", "여름", "여행", "영화", "이스트 홀", "코미디", "받다", "아마", "자주", "정말", "무슨", "어느", "(으)ㄹ 거예요", "지난월요일", "이번월요일", "다음월요일", "지난토요일", "이번토요일", "다음토요일", "지난주말", "이번주말", "다음주말", "지난주", "이번주", "다음주", "지난달", "이(번)달", "다음달", "적년", "올해", "가을", "겨울", "마켓", "봄", "설거지", "신문", "심리학", "이야기", "전공", "주", "준비", "청소", "크리스마스", "흐리다", "보내다", "장(을) 보다", "가끔", "많이", "~고", "가운데", "건너편", "교회", "꽃짐", "동네", "서울", "슈퍼", "약국", "지도", "쪽", "초등학교", "군데", "번", "지요", "여기", "거기", "저기", "내리다", "타다", "깨끗하다", "따뜻하다", "조용하다", "여러", "그", "근처", "마씀", "말", "시천", "역", "오른쪽", "왼쪽", "우표", "은행", "의사", "처음", "호선", "좀", "쭉", "돌다", "팔다", "묻다", "보이다", "뵙다", "보다", "감사하다", "미안하다", "습나다", "습니까"], "completedItemsArray": [], "dueTodayItemsArray": ["저", "일", "그렇다 (그래요)", "일어", "교과서", "교실", "오늘", "요즘", "밋없다", "생물학", "전기공학", "피아노", "펍학", "개", "고등학생", "남동생", "대학원생", "동생", "보스톤", "부모님", "아버지", "어머니", "여동생", "오빠", "홍콩", "몇", "관", "계시다", "거", "방", "만", "의", "고맙다", "나쁘다", "비싸다", "예쁘다", "작다", "배우다", "오다", "자다", "주다", "저희", "우리", "이거", "내", "재", "공원", "랩", "백화점", "생일"], "allNewCards": ["서점", "선물(하다)", "쇼핑(하다)", "연습(하다)", "오래간만", "운동(하다)", "일(하다)", "저녁", "점심", "커피숍", "테니스", "햄버거", "가르치다", "사다", "치다", "에서", "안녕히", "가게", "오전", "오후", "의", "몇", "대학원생", "작다", "자다", "나쁘다", "비싸다", "피아노", "공원", "펍학", "개", "고맙다", "오다", "요즘", "교실", "오빠", "저", "어머니", "관", "보스톤", "계시다", "예쁘다", "고등학생", "일어", "여동생", "생일", "동생", "주다", "저희", "내", "밋없다", "배우다", "방", "우리", "일", "그렇다 (그래요)", "교과서", "오늘", "아버지", "생물학", "백화점", "이거", "부모님", "전기공학", "만", "재", "남동생", "랩", "홍콩", "거"] }