obj = {	
"	1	":{"character":"	雑誌取材がやってきた	","letter": "	A magazine interview came in.	", "pinyin":"	ざっししゅざいがやってきた	"},																			
"	2	":{"character":"	なんでうまくいかないんだろう…	","letter": "	I don't know why it didn't work out...	", "pinyin":"	なんでうまくいかないんだろう…	"},																			
"	3	":{"character":"	えっ？なに？	","letter": "	What? What?	", "pinyin":"	えっ？なに？	"},																			
"	4	":{"character":"	あっあれ？縦列駐車？	","letter": "	Oh, that? Parallel parking?	", "pinyin":"	あっあれ？じゅうれつちゅうしゃ？	"},																			
"	5	":{"character":"	違うよ！	","letter": "	No!	", "pinyin":"	ちがうよ！	"},																			
"	6	":{"character":"	じゃあできるようになったの？	","letter": "	So you can do it now?	", "pinyin":"	じゃあできるようになったの？	"},																			
"	7	":{"character":"	まだちゃんとできてないけど…違うってば！	","letter": "	I haven't quite got it right yet, but... no!	", "pinyin":"	まだちゃんとできてないけど…ちがうってば！	"},																			
"	8	":{"character":"	僕が言いたいのはデートだよデートのお誘いだよ	","letter": "	What I'm trying to say is that I want to go on a date with you.	", "pinyin":"	ぼくがいいたいのはでーとだよでーとのおさそいだよ	"},																			
"	9	":{"character":"	会って言えばいいんじゃないの？	","letter": "	Why don't you just meet her and tell her?	", "pinyin":"	あっていえばいいんじゃないの？	"},																			
"	10	":{"character":"	それができないから困ってるんだよ	","letter": "	I can't do that. That's why I'm in trouble.	", "pinyin":"	それができないからこまってるんだよ	"},																			
"	11	":{"character":"	なんで？	","letter": "	Why not?	", "pinyin":"	なんで？	"},																			
"	12	":{"character":"	もういい…パンダくんに相談するんじゃなかった	","letter": "	I shouldn't have talked to you, Panda.	", "pinyin":"	もういい…ぱんだくんにそうだんするんじゃなかった	"},																			
"	13	":{"character":"	シロクマさん！	","letter": "	Polar bear!	", "pinyin":"	しろくまさん！	"},																			
"	14	":{"character":"	すみません遅くなりました	","letter": "	Sorry I'm late.	", "pinyin":"	すみませんおそくなりました	"},																			
"	15	":{"character":"	どなたですか？	","letter": "	Who's this?	", "pinyin":"	どなたですか？	"},																			
"	16	":{"character":"	取材の人ですよ	","letter": "	I'm the interviewer.	", "pinyin":"	しゅざいのひとですよ	"},																			
"	17	":{"character":"	取材？	","letter": "	You're the interviewer?	", "pinyin":"	しゅざい？	"},																			
"	18	":{"character":"	昨日言ったじゃないですか	","letter": "	I told you yesterday.	", "pinyin":"	きのういったじゃないですか	"},																			
"	19	":{"character":"	うん知ってる	","letter": "	Yes, I know who you are.	", "pinyin":"	うんしってる	"},																			
"	20	":{"character":"	『月刊フラフラウォーカー』のライター大崎と申します	","letter": "	I'm Osaki, a writer for Hula Hula Walker.	", "pinyin":"	『げっかんふらふらうぉーかー』のらいたーおおさきともうします	"},																			
"	21	":{"character":"	よろしくね	","letter": "	Nice to meet you.	", "pinyin":"	よろしくね	"},																			
"	22	":{"character":"	何か？	","letter": "	What's up?	", "pinyin":"	なにか？	"},																			
"	23	":{"character":"	あの…編集長が先に来ているはずなんですが	","letter": "	Um... the editor-in-chief is supposed to be here first.	", "pinyin":"	あの…へんしゅうちょうがさきにきているはずなんですが	"},																			
"	24	":{"character":"	編集長？そういう方はまだお見えではないですね	","letter": "	Editor-in-Chief? That person hasn't shown up yet.	", "pinyin":"	へんしゅうちょう？そういうほうはまだおみえではないですね	"},																			
"	25	":{"character":"	そうですか…どうしたんだろう？	","letter": "	I see...what's going on?	", "pinyin":"	そうですか…どうしたんだろう？	"},																			
"	26	":{"character":"	実はこちらのしろくまカフエを絶対取り上げようって言ったのは	","letter": "	Actually, it was our editor-in-chief who said we should definitely feature Shirokuma Kafue here.	", "pinyin":"	じつはこちらのしろくまかふえをぜったいとりあげようっていったのは	"},																			
"	27	":{"character":"	うちの編集長なんですよ	","letter": "	It was our editor-in-chief who said we should definitely feature Shirokuma Kafue.	", "pinyin":"	うちのへんしゅうちょうなんですよ	"},																			
"	28	":{"character":"	知る人ぞ知る隠れ処カフェや	","letter": "	He has a great intuition for finding hidden cafes and open cafes	", "pinyin":"	しるひとぞしるかくれがかふぇや	"},																			
"	29	":{"character":"	オープンカフェを見つける勘がとても鋭くて	","letter": "	He has a keen intuition for finding hidden cafes and open cafes that are well known to those in the know.	", "pinyin":"	おーぷんかふぇをみつけるかんがとてもするどくて	"},																			
"	30	":{"character":"	うちの雑誌は編集長のセンスに支えられているようなものです	","letter": "	Our magazine is supported by his sense of taste.	", "pinyin":"	うちのざっしはへんしゅうちょうのせんすにささえられているようなものです	"},																			
"	31	":{"character":"	聞いた？	","letter": "	Did you hear?	", "pinyin":"	きいた？	"},																			
"	32	":{"character":"	雑誌の取材だって	","letter": "	She's doing an interview for a magazine.	", "pinyin":"	ざっしのしゅざいだって	"},																			
"	33	":{"character":"	取材？	","letter": "	Interviews?	", "pinyin":"	しゅざい？	"},																			
"	34	":{"character":"	いろいろインタビューしたり写真撮ったりするんじゃない？	","letter": "	Isn't he supposed to do interviews and take pictures?	", "pinyin":"	いろいろいんたびゅーしたりしゃしんとったりするんじゃない？	"},																			
"	35	":{"character":"	インタビュー？写真？	","letter": "	Interviews? Photographs?	", "pinyin":"	いんたびゅー？しゃしん？	"},																			
"	36	":{"character":"	ファンレターとか届いたりして	","letter": "	Fan letters and stuff.	", "pinyin":"	ふぁんれたーとかとどいたりして	"},																			
"	37	":{"character":"	パンダくんの取材じゃないよ	","letter": "	I'm not interviewing pandas.	", "pinyin":"	ぱんだくんのしゅざいじゃないよ	"},																			
"	38	":{"character":"	お客さんにインタビューしたら雑誌に写真載るよ	","letter": "	If I interview a client, I'll have my picture in a magazine.	", "pinyin":"	おきゃくさんにいんたびゅーしたらざっしにしゃしんのるよ	"},																			
"	39	":{"character":"	えっ！？それは困るよ！	","letter": "	What? That's not good!	", "pinyin":"	えっ！？それはこまるよ！	"},																			
"	40	":{"character":"	僕写真写り自信ないんだよああ…	","letter": "	I'm not confident about my picture...	", "pinyin":"	ぼくしゃしんうつりじしんないんだよああ…	"},																			
"	41	":{"character":"	じゃあとりあえず取材を始めさせていただきますね	","letter": "	Well then, I'll start the interview anyway.	", "pinyin":"	じゃあとりあえずしゅざいをはじめさせていただきますね	"},																			
"	42	":{"character":"	まずはシロクマさんに	","letter": "	First of all, I'd like to ask Mr. Polar Bear	", "pinyin":"	まずはしろくまさんに	"},																			
"	43	":{"character":"	カフェを始めたいきさつなんかをお聞きしたいんですが	","letter": "	I'd like to ask you how you started the cafe.	", "pinyin":"	かふぇをはじめたいきさつなんかをおききしたいんですが	"},																			
"	44	":{"character":"	いきさつ…	","letter": "	How did you...	", "pinyin":"	いきさつ…	"},																			
"	45	":{"character":"	それは力作	","letter": "	That's a good work.	", "pinyin":"	それはりきさく	"},																			
"	46	":{"character":"	それは印刷	","letter": "	That's printing.	", "pinyin":"	それはいんさつ	"},																			
"	47	":{"character":"	それは警察	","letter": "	That's the police.	", "pinyin":"	それはけいさつ	"},																			
"	48	":{"character":"	それは改札	","letter": "	It's a ticket gate.	", "pinyin":"	それはかいさつ	"},																			
"	49	":{"character":"	あ…えっと…そのダジャレは…	","letter": "	Oh... um... that pun...	", "pinyin":"	あ…えっと…そのだじゃれは…	"},																			
"	50	":{"character":"	それは挨拶！！	","letter": "	That's a greeting!	", "pinyin":"	それはあいさつ！！	"},																			
"	51	":{"character":"	かぶせてきましたね編集長	","letter": "	You've got it covered, Mr. Editor.	", "pinyin":"	かぶせてきましたねへんしゅうちょう	"},																			
"	52	":{"character":"	マスターはダジャレが得意なナイスガイ…と	","letter": "	Master is a nice guy who is good at puns...	", "pinyin":"	ますたーはだじゃれがとくいなないすがい…と	"},																			
"	53	":{"character":"	編集長？	","letter": "	Mr. Editor-in-Chief?	", "pinyin":"	へんしゅうちょう？	"},																			
"	54	":{"character":"	はいうちの編集長ハシビロコウさんです	","letter": "	Yes, our editor-in-chief, Mr. Shoebill.	", "pinyin":"	はいうちのへんしゅうちょうはしびろこうさんです	"},																			
"	55	":{"character":"	ですよね！ホント今回大当たりです	","letter": "	Of course! We really hit the jackpot this time!	", "pinyin":"	ですよね！ほんとこんかいおおあたりです	"},																			
"	56	":{"character":"	編集長が本当にここはすばらしいカフェだと	","letter": "	Our editor-in-chief says this is really a wonderful cafe.	", "pinyin":"	へんしゅうちょうがほんとうにここはすばらしいかふぇだと	"},																			
"	57	":{"character":"	あっそう	","letter": "	Oh, yes!	", "pinyin":"	あっそう	"},																			
"	58	":{"character":"	それでは改めまして	","letter": "	Well then, let me begin.	", "pinyin":"	それではあらためまして	"},																			
"	59	":{"character":"	挨拶ならぬカフェを始めたいきさつですが	","letter": "	How did you start the café?	", "pinyin":"	あいさつならぬかふぇをはじめたいきさつですが	"},																			
"	60	":{"character":"	やっぱ聞いちゃうんだそれ	","letter": "	I knew you'd ask.	", "pinyin":"	やっぱきいちゃうんだそれ	"},																			
"	61	":{"character":"	なんで？	","letter": "	Why?	", "pinyin":"	なんで？	"},																			
"	62	":{"character":"	話せば長くなるんだけど	","letter": "	It's a long story.	", "pinyin":"	はなせばながくなるんだけど	"},																			
"	63	":{"character":"	僕はカナダのハドソン湾で生まれたの	","letter": "	I was born in Hudson Bay, Canada.	", "pinyin":"	ぼくはかなだのはどそんわんでうまれたの	"},																			
"	64	":{"character":"	僕は三つ子のいちばん下でいちばん体が小さかった	","letter": "	I was the youngest of triplets and the smallest.	", "pinyin":"	ぼくはみつごのいちばんしたでいちばんからだがちいさかった	"},																			
"	65	":{"character":"	お母さんが食べ物を探して歩くと	","letter": "	Whenever my mother walked around looking for food.	", "pinyin":"	おかあさんがたべものをさがしてあるくと	"},																			
"	66	":{"character":"	いつも僕だけ遅れてしまった	","letter": "	I was always late.	", "pinyin":"	いつもぼくだけおくれてしまった	"},																			
"	67	":{"character":"	そしてある吹雪の日	","letter": "	Then one day during a snowstorm	", "pinyin":"	そしてあるふぶきのひ	"},																			
"	68	":{"character":"	僕はとうとうお母さんたちとはぐれてしまった	","letter": "	I finally got separated from my mom and dad.	", "pinyin":"	ぼくはとうとうおかあさんたちとはぐれてしまった	"},																			
"	69	":{"character":"	吹雪がやむと…	","letter": "	When the blizzard stopped...	", "pinyin":"	ふぶきがやむと…	"},																			
"	70	":{"character":"	お母さんたちの姿はどこにもなかった	","letter": "	They were nowhere to be found	", "pinyin":"	おかあさんたちのすがたはどこにもなかった	"},																			
"	71	":{"character":"	一生懸命呼んだけど応えはない	","letter": "	I tried calling out to them, but there was no answer	", "pinyin":"	いっしょうけんめいよんだけどこたえはない	"},																			
"	72	":{"character":"	そのうち気づいた	","letter": "	Eventually I realized	", "pinyin":"	そのうちきづいた	"},																			
"	73	":{"character":"	僕のいる氷は沖へ流されてる	","letter": "	The ice I was on was drifting out to sea	", "pinyin":"	ぼくのいるこおりはおきへながされてる	"},																			
"	74	":{"character":"	僕はひとりぼっちで海の上を漂流していった	","letter": "	I drifted out to sea all alone	", "pinyin":"	ぼくはひとりぼっちでうみのうえをひょうりゅうしていった	"},																			
"	75	":{"character":"	何日も何日も…	","letter": "	For days and days...	", "pinyin":"	なんにちもなんにちも…	"},																			
"	76	":{"character":"	そ…それでどうなったの？	","letter": "	And then what happened?	", "pinyin":"	そ…それでどうなったの？	"},																			
"	77	":{"character":"	お腹が減ってついに動けなくなったとき	","letter": "	When I finally got so hungry that I couldn't move.	", "pinyin":"	おなかがへってついにうごけなくなったとき	"},																			
"	78	":{"character":"	僕は通りがかった猟師の人に助けられたんだ	","letter": "	I was saved by a passing hunter.	", "pinyin":"	ぼくはとおりがかったりょうしのひとにたすけられたんだ	"},																			
"	79	":{"character":"	それから僕は助けてくれた人の両親に預けられた	","letter": "	Then my rescuer's parents took me in.	", "pinyin":"	それからぼくはたすけてくれたひとのりょうしんにあずけられた	"},																			
"	80	":{"character":"	そこは小さな食堂をやっていて	","letter": "	They had a small diner.	", "pinyin":"	そこはちいさなしょくどうをやっていて	"},																			
"	81	":{"character":"	店を手伝ううちに	","letter": "	I started to like cooking.	", "pinyin":"	みせをてつだううちに	"},																			
"	82	":{"character":"	僕は料理が好きになった	","letter": "	I started to like cooking.	", "pinyin":"	ぼくはりょうりがすきになった	"},																			
"	83	":{"character":"	でもそんな生活も長くは続かなかったよ	","letter": "	But that life didn't last long.	", "pinyin":"	でもそんなせいかつもながくはつづかなかったよ	"},																			
"	84	":{"character":"	僕は大きくなりすぎて	","letter": "	I got too big.	", "pinyin":"	ぼくはおおきくなりすぎて	"},																			
"	85	":{"character":"	おじいさんとおばあさんの家にいられなくなってしまったんだ	","letter": "	I couldn't stay with my grandma and grandpa.	", "pinyin":"	おじいさんとおばあさんのいえにいられなくなってしまったんだ	"},																			
"	86	":{"character":"	それで家を出て	","letter": "	So I left.	", "pinyin":"	それでいえをでて	"},																			
"	87	":{"character":"	カフェを始めた	","letter": "	I opened a cafe.	", "pinyin":"	かふぇをはじめた	"},																			
"	88	":{"character":"	お店をやっていたらいつか話が伝わって	","letter": "	I thought if I ran the store, maybe someday they'd hear about me.	", "pinyin":"	おみせをやっていたらいつかはなしがつたわって	"},																			
"	89	":{"character":"	お母さんたちに会えるかもしれないから	","letter": "	I might get to meet your mothers.	", "pinyin":"	おかあさんたちにあえるかもしれないから	"},																			
"	90	":{"character":"	なに！？	","letter": "	What?	", "pinyin":"	なに！？	"},																			
"	91	":{"character":"	わかります編集長	","letter": "	I understand, Mr. Editor-in-Chief.	", "pinyin":"	わかりますへんしゅうちょう	"},																			
"	92	":{"character":"	シロクマさんの大変さを思うと…	","letter": "	When I think of how hard it is for Polar Bear...	", "pinyin":"	しろくまさんのたいへんさをおもうと…	"},																			
"	93	":{"character":"	シロクマくん	","letter": "	Polar bear.	", "pinyin":"	しろくまくん	"},																			
"	94	":{"character":"	大変だったんだね	","letter": "	I'm sorry you've had such a hard time.	", "pinyin":"	たいへんだったんだね	"},																			
"	95	":{"character":"	お母さんたちにはまだ会えないの？	","letter": "	Have you been able to see your mom and dad yet?	", "pinyin":"	おかあさんたちにはまだあえないの？	"},																			
"	96	":{"character":"	うん今のところ	","letter": "	No, not yet.	", "pinyin":"	うんいまのところ	"},																			
"	97	":{"character":"	あれ？私この前は建設会社を脱サラして	","letter": "	Huh? I heard you quit your job at a construction company	", "pinyin":"	あれ？わたしこのまえはけんせつがいしゃをだつさらして	"},																			
"	98	":{"character":"	カフェを始めたって聞いたんですけど…	","letter": "	I heard you quit your job as a construction worker and started a café...	", "pinyin":"	かふぇをはじめたってきいたんですけど…	"},																			
"	99	":{"character":"	ああ…そういうバージョンもあるね	","letter": "	Yeah... that's one version.	", "pinyin":"	ああ…そういうばーじょんもあるね	"},																			
"	100	":{"character":"	作り話ですか	","letter": "	You're making that up?	", "pinyin":"	つくりばなしですか	"},																			
"	101	":{"character":"	だから言ったのに	","letter": "	I told you so.	", "pinyin":"	だからいったのに	"},																			
"	102	":{"character":"	ははぁ真相はお好みってことですね	","letter": "	The truth is your choice.	", "pinyin":"	ははぁしんそうはおこのみってことですね	"},																			
"	103	":{"character":"	さすがナイスガイ	","letter": "	Nice guy.	", "pinyin":"	さすがないすがい	"},																			
"	104	":{"character":"	じゃあ次の質問ですが…	","letter": "	Okay, next question...	", "pinyin":"	じゃあつぎのしつもんですが…	"},																			
"	105	":{"character":"	どうしました！？編集長！	","letter": "	What's wrong? Mr. Editor!	", "pinyin":"	どうしました！？へんしゅうちょう！	"},																			
"	106	":{"character":"	ああそのお花ですね	","letter": "	Oh, those flowers.	", "pinyin":"	ああそのおはなですね	"},																			
"	107	":{"character":"	このステキなアレンジメントはどなたが？	","letter": "	Who made this beautiful arrangement?	", "pinyin":"	このすてきなあれんじめんとはどなたが？	"},																			
"	108	":{"character":"	近くの花屋さんにお願いしてるんです	","letter": "	I hired a florist nearby.	", "pinyin":"	ちかくのはなやさんにおねがいしてるんです	"},																			
"	109	":{"character":"	編集長？	","letter": "	Mr. Editor?	", "pinyin":"	へんしゅうちょう？	"},																			
"	110	":{"character":"	編集長！	","letter": "	Editor-in-Chief!	", "pinyin":"	へんしゅうちょう！	"},																			
"	111	":{"character":"	編集長！	","letter": "	Editor-in-Chief!	", "pinyin":"	へんしゅうちょう！	"},																			
"	112	":{"character":"	編集…	","letter": "	Editor-in-Chief...	", "pinyin":"	へんしゅう…	"},																			
"	113	":{"character":"	これは！	","letter": "	This is it!	", "pinyin":"	これは！	"},																			
"	114	":{"character":"	自家菜園です	","letter": "	It's our vegetable garden.	", "pinyin":"	じかさいえんです	"},																			
"	115	":{"character":"	お店で使う野菜やハーブを育てているんですよ	","letter": "	We grow the vegetables and herbs we use in the restaurant!	", "pinyin":"	おみせでつかうやさいやはーぶをそだてているんですよ	"},																			
"	116	":{"character":"	さすが編集長！どんなことも見逃しませんね	","letter": "	That's our editor-in-chief! You never miss anything!	", "pinyin":"	さすがへんしゅうちょう！どんなこともみのがしませんね	"},																			
"	117	":{"character":"	こだわりの食材	","letter": "	The ingredients are carefully selected.	", "pinyin":"	こだわりのしょくざい	"},																			
"	118	":{"character":"	景色も良好	","letter": "	Great view!	", "pinyin":"	けしきもりょうこう	"},																			
"	119	":{"character":"	客席も充実	","letter": "	Plenty of seating	", "pinyin":"	きゃくせきもじゅうじつ	"},																			
"	120	":{"character":"	洗練された外観	","letter": "	Sophisticated exterior	", "pinyin":"	せんれんされたがいかん	"},																			
"	121	":{"character":"	そんなステキなしろくまカフェさんなんですが	","letter": "	Shirokuma Cafe is such a wonderful place.	", "pinyin":"	そんなすてきなしろくまかふぇさんなんですが	"},																			
"	122	":{"character":"	オススメがあればぜひ紹介していただけますか？	","letter": "	If you have any recommendations, could you introduce them to us?	", "pinyin":"	おすすめがあればぜひしょうかいしていただけますか？	"},																			
"	123	":{"character":"	笹大盛りがオススメだよ！	","letter": "	I recommend the large bowl of bamboo grass!	", "pinyin":"	ささおおもりがおすすめだよ！	"},																			
"	124	":{"character":"	それ料理じゃなくて素材だよね	","letter": "	That's not a dish, it's an ingredient.	", "pinyin":"	それりょうりじゃなくてそざいだよね	"},																			
"	125	":{"character":"	あぁ家の隣にあってすぐ来られるのもオススメ	","letter": "	Oh, and it's right next to my house, so I recommend coming here right away!	", "pinyin":"	あぁいえのとなりにあってすぐこられるのもおすすめ	"},																			
"	126	":{"character":"	パンダくんだけでしょ	","letter": "	Only for pandas, right?	", "pinyin":"	ぱんだくんだけでしょ	"},																			
"	127	":{"character":"	素材と立地が抜群と…	","letter": "	I think the ingredients and the location are excellent...	", "pinyin":"	そざいとりっちがばつぐんと…	"},																			
"	128	":{"character":"	その他は？	","letter": "	What else?	", "pinyin":"	そのほかは？	"},																			
"	129	":{"character":"	ランチパスタが人気ですね	","letter": "	Lunch pasta is popular.	", "pinyin":"	らんちぱすたがにんきですね	"},																			
"	130	":{"character":"	うんうん…アンチョビの入ったやつね	","letter": "	The one with anchovies.	", "pinyin":"	うんうん…あんちょびのはいったやつね	"},																			
"	131	":{"character":"	春野菜もいいよね	","letter": "	Spring greens are good, too.	", "pinyin":"	はるやさいもいいよね	"},																			
"	132	":{"character":"	せっかくだから食べてもらったらどうでしょう？	","letter": "	Since we're here, why don't you let them try it?	", "pinyin":"	せっかくだからたべてもらったらどうでしょう？	"},																			
"	133	":{"character":"	どうですか？編集長	","letter": "	What do you think? Editor-in-Chief.	", "pinyin":"	どうですか？へんしゅうちょう	"},																			
"	134	":{"character":"	パスタ嫌いなのかな？	","letter": "	You don't like pasta?	", "pinyin":"	ぱすたきらいなのかな？	"},																			
"	135	":{"character":"	意外とダイナミックだよね	","letter": "	It's surprisingly dynamic.	", "pinyin":"	いがいとだいなみっくだよね	"},																			
"	136	":{"character":"	そうですか！とってもおいしいそうです	","letter": "	I see! I hear it's very tasty!	", "pinyin":"	そうですか！とってもおいしいそうです	"},																			
"	137	":{"character":"	あぁそう	","letter": "	Ah, yes.	", "pinyin":"	あぁそう	"},																			
"	138	":{"character":"	えっ！？この間の雑誌もう出たの？	","letter": "	What? Did you get the magazine the other day?	", "pinyin":"	えっ！？このあいだのざっしもうでたの？	"},																			
"	139	":{"character":"	うんサンプルが来てる	","letter": "	Yes, samples are here.	", "pinyin":"	うんさんぷるがきてる	"},																			
"	140	":{"character":"	見せて見せて！	","letter": "	Let me see! Let me see!	", "pinyin":"	みせてみせて！	"},																			
"	141	":{"character":"	あっ！これだね	","letter": "	Oh! This is it.	", "pinyin":"	あっ！これだね	"},																			
"	142	":{"character":"	写ってない…	","letter": "	It's not in the picture...	", "pinyin":"	うつってない…	"},																			
"	143	":{"character":"	写ってる…	","letter": "	It's in the...	", "pinyin":"	うつってる…	"},																			
"	144	":{"character":"	ですね	","letter": "	Yes, it is.	", "pinyin":"	ですね	"},																			
"	145	":{"character":"	サケハンターグリズリーさん	","letter": "	Mr. Grizzly the Salmon Hunter.	", "pinyin":"	さけはんたーぐりずりーさん	"},																			
"	146	":{"character":"	おはよう	","letter": "	Good morning, Mr. Grizzly.	", "pinyin":"	おはよう	"},																			
"	147	":{"character":"	おはようパンダくん	","letter": "	Good morning, Mr. Panda.	", "pinyin":"	おはようぱんだくん	"},																			
"	148	":{"character":"	あれ！？これなんの荷物？	","letter": "	What's that? What's all this stuff?	", "pinyin":"	あれ！？これなんのにもつ？	"},																			
"	149	":{"character":"	お出かけの準備	","letter": "	Preparing to go out.	", "pinyin":"	おでかけのじゅんび	"},																			
"	150	":{"character":"	えっ！？出かけちゃうの？カフェは？	","letter": "	What? You're going out? Where's the cafe?	", "pinyin":"	えっ！？でかけちゃうの？かふぇは？	"},																			
"	151	":{"character":"	今日はお休み	","letter": "	No, I'm closed today.	", "pinyin":"	きょうはおやすみ	"},																			
"	152	":{"character":"	せっかく早起きできたからモーニング食べようと思ったのに	","letter": "	I woke up early and thought I'd have morning breakfast.	", "pinyin":"	せっかくはやおきできたからもーにんぐたべようとおもったのに	"},																			
"	153	":{"character":"	ごめんね	","letter": "	Sorry.	", "pinyin":"	ごめんね	"},																			
"	154	":{"character":"	どこ行くの？	","letter": "	Where are you going?	", "pinyin":"	どこいくの？	"},																			
"	155	":{"character":"	今日はね…	","letter": "	Today...	", "pinyin":"	こんにちはね…	"},																			
"	156	":{"character":"	シロクマ！用意はできてんだろうな？	","letter": "	Polar bear! You're ready, right?	", "pinyin":"	しろくま！よういはできてんだろうな？	"},																			
"	157	":{"character":"	荷物はこれで全部か？	","letter": "	Is this all your stuff?	", "pinyin":"	にもつはこれでぜんぶか？	"},																			
"	158	":{"character":"	うん	","letter": "	Yeah.	", "pinyin":"	うん	"},																			
"	159	":{"character":"	グリズリーさんおはよう	","letter": "	Good morning, grizzly.	", "pinyin":"	ぐりずりーさんおはよう	"},																			
"	160	":{"character":"	おう	","letter": "	Good morning, Mr. Grizzly.	", "pinyin":"	おう	"},																			
"	161	":{"character":"	シロクマくんとどこ行くの？	","letter": "	Where are you and Polar Bear going?	", "pinyin":"	しろくまくんとどこいくの？	"},																			
"	162	":{"character":"	うん？あぁちょっと食材をな	","letter": "	Yeah, I'm just getting some groceries. Oh, just to pick up a few ingredients.	", "pinyin":"	うん？あぁちょっとしょくざいをな	"},																			
"	163	":{"character":"	料理の材料を発掘しに	","letter": "	I'm going to dig up some ingredients for a dish.	", "pinyin":"	りょうりのざいりょうをはっくつしに	"},																			
"	164	":{"character":"	発掘？楽しそう！	","letter": "	Digging? Sounds fun!	", "pinyin":"	はっくつ？たのしそう！	"},																			
"	165	":{"character":"	僕も行きたい…	","letter": "	I want to go, too.	", "pinyin":"	ぼくもいきたい…	"},																			
"	166	":{"character":"	遊びじゃねえんだよ！	","letter": "	It's not a game!	", "pinyin":"	あそびじゃねえんだよ！	"},																			
"	167	":{"character":"	まぁでも遠足みたいなものかな	","letter": "	Well, it's like a field trip.	", "pinyin":"	まぁでもえんそくみたいなものかな	"},																			
"	168	":{"character":"	遠足？	","letter": "	Field trip?	", "pinyin":"	えんそく？	"},																			
"	169	":{"character":"	笹はおやつに入る？ごはんかな？	","letter": "	Do you think bamboos count as a snack? Or a meal?	", "pinyin":"	ささはおやつにはいる？ごはんかな？	"},																			
"	170	":{"character":"	う～ん…難しいね	","letter": "	Hmmm... that's a tough one.	", "pinyin":"	う～ん…むずかしいね	"},																			
"	171	":{"character":"	アザラシはごはんだけど…	","letter": "	Seals are food, but...	", "pinyin":"	あざらしはごはんだけど…	"},																			
"	172	":{"character":"	おやつは？	","letter": "	What about snacks?	", "pinyin":"	おやつは？	"},																			
"	173	":{"character":"	セイウチかな	","letter": "	Maybe walruses.	", "pinyin":"	せいうちかな	"},																			
"	174	":{"character":"	何ダラダラとくっちゃべってんだよ！	","letter": "	What are you two whispering about?	", "pinyin":"	なにだらだらとくっちゃべってんだよ！	"},																			
"	175	":{"character":"	行くぞ早く乗れ	","letter": "	Come on, let's go!	", "pinyin":"	いくぞはやくのれ	"},																			
"	176	":{"character":"	おいシロクマ	","letter": "	Hey, polar bear.	", "pinyin":"	おいしろくま	"},																			
"	177	":{"character":"	何？グリズリーくん	","letter": "	What? Grizzly bear.	", "pinyin":"	なに？ぐりずりーくん	"},																			
"	178	":{"character":"	なんでアイツがいるんだよ？	","letter": "	Why is he here?	", "pinyin":"	なんであいつがいるんだよ？	"},																			
"	179	":{"character":"	グリズリーくんが乗れって言ったんじゃない	","letter": "	Mr. Grizzly didn't tell us to get in.	", "pinyin":"	ぐりずりーくんがのれっていったんじゃない	"},																			
"	180	":{"character":"	そうじゃなくてよ！	","letter": "	No, he didn't!	", "pinyin":"	そうじゃなくてよ！	"},																			
"	181	":{"character":"	まぁいいじゃない	","letter": "	Well, that's okay.	", "pinyin":"	まぁいいじゃない	"},																			
"	182	":{"character":"	ねぇどこ行くの？	","letter": "	Hey, where are we going?	", "pinyin":"	ねぇどこいくの？	"},																			
"	183	":{"character":"	山？それとも海？	","letter": "	The mountains? The mountains or the ocean?	", "pinyin":"	やま？それともうみ？	"},																			
"	184	":{"character":"	山はおいしい笹がいっぱい生えてるし…	","letter": "	The mountains are full of delicious bamboo grass...	", "pinyin":"	やまはおいしいささがいっぱいはえてるし…	"},																			
"	185	":{"character":"	海はかわいい女の子がいっぱいいるよね	","letter": "	The ocean is full of cute girls.	", "pinyin":"	うみはかわいいおんなのこがいっぱいいるよね	"},																			
"	186	":{"character":"	川だよ	","letter": "	The river.	", "pinyin":"	かわだよ	"},																			
"	187	":{"character":"	お前は店で出す分が欲しいんだろ？	","letter": "	You want some for your restaurant, right?	", "pinyin":"	おまえはみせでだすぶんがほしいんだろ？	"},																			
"	188	":{"character":"	うんいっぱい獲れるといいな	","letter": "	I hope you catch a lot.	", "pinyin":"	うんいっぱいえれるといいな	"},																			
"	189	":{"character":"	結構いそうな感じだぜ	","letter": "	Looks like there's plenty to go around.	", "pinyin":"	けっこういそうなかんじだぜ	"},																			
"	190	":{"character":"	あっ魚！	","letter": "	Fish!	", "pinyin":"	あっさかな！	"},																			
"	191	":{"character":"	あれが俺たちの獲物だ	","letter": "	That's our catch.	", "pinyin":"	あれがおれたちのえものだ	"},																			
"	192	":{"character":"	え…あれが？	","letter": "	That's... that's what we got?	", "pinyin":"	え…あれが？	"},																			
"	193	":{"character":"	そうだサケだ	","letter": "	Yeah, that's a salmon.	", "pinyin":"	そうださけだ	"},																			
"	194	":{"character":"	なんだよ？	","letter": "	What?	", "pinyin":"	なんだよ？	"},																			
"	195	":{"character":"	もっとタケノコ的なものを想像してたのに…	","letter": "	I was expecting something more like a bamboo shoot...	", "pinyin":"	もっとたけのこてきなものをそうぞうしてたのに…	"},																			
"	196	":{"character":"	イヤなら帰れ！	","letter": "	If you don't like it, go home!	", "pinyin":"	いやならかえれ！	"},																			
"	197	":{"character":"	なんだ…発掘じゃないじゃない	","letter": "	What... it's not an excavation.	", "pinyin":"	なんだ…はっくつじゃないじゃない	"},																			
"	198	":{"character":"	似たようなもんでしょ	","letter": "	It's just like that.	", "pinyin":"	にたようなもんでしょ	"},																			
"	199	":{"character":"	そうかなぁ…	","letter": "	I don't know...	", "pinyin":"	そうかなぁ…	"},																			
"	200	":{"character":"	頑張ってよ	","letter": "	Good luck with that.	", "pinyin":"	がんばってよ	"},																			
"	201	":{"character":"	明日からのしろくまカフェのランチ	","letter": "	Tomorrow's lunch at the Shirokuma Cafe	", "pinyin":"	あしたからのしろくまかふぇのらんち	"},																			
"	202	":{"character":"	グリズリー君にかかってるんだから	","letter": "	It's up to you, grizzly.	", "pinyin":"	ぐりずりーくんにかかってるんだから	"},																			
"	203	":{"character":"	まったく…他力本願なヤツめ	","letter": "	What a selfish guy.	", "pinyin":"	まったく…たりきほんがんなやつめ	"},																			
"	204	":{"character":"	えっどうやって獲るの？	","letter": "	How are you going to catch it?	", "pinyin":"	えっどうやってえるの？	"},																			
"	205	":{"character":"	シッ！	","letter": "	Shoo!	", "pinyin":"	しっ！	"},																			
"	206	":{"character":"	オラァッ！	","letter": "	Hey!	", "pinyin":"	おらぁっ！	"},																			
"	207	":{"character":"	オラ１匹目！	","letter": "	That's the first one!	", "pinyin":"	おら１ひきめ！	"},																			
"	208	":{"character":"	２匹目！３匹４匹！	","letter": "	Two, three, four!	", "pinyin":"	２ひきめ！３ひき４ひき！	"},																			
"	209	":{"character":"	まぁ俺の手にかかりゃこんなもんよ	","letter": "	Well, that's what I get.	", "pinyin":"	まぁおれのてにかかりゃこんなもんよ	"},																			
"	210	":{"character":"	さすが！	","letter": "	That's what I'm talking about!	", "pinyin":"	さすが！	"},																			
"	211	":{"character":"	わぁ…ピチピチしてる	","letter": "	Wow... you're spunky.	", "pinyin":"	わぁ…ぴちぴちしてる	"},																			
"	212	":{"character":"	ん？このシチュエーションガキの頃にもあったぞ…	","letter": "	What? I had this situation when I was a kid...	", "pinyin":"	ん？このしちゅえーしょんがきのころにもあったぞ…	"},																			
"	213	":{"character":"	あれ？	","letter": "	What?	", "pinyin":"	あれ？	"},																			
"	214	":{"character":"	全然獲れねえ…	","letter": "	I can't catch anything...	", "pinyin":"	ぜんぜんえれねえ…	"},																			
"	215	":{"character":"	なんだシロクマ！テメエ！笑って見てんじゃねえ！	","letter": "	What a polar bear! You! Don't you dare laugh at me!	", "pinyin":"	なんだしろくま！てめえ！わらってみてんじゃねえ！	"},																			
"	216	":{"character":"	え？笑ってないよ？	","letter": "	What? I'm not laughing.	", "pinyin":"	え？わらってないよ？	"},																			
"	217	":{"character":"	笑ってるだろうが口がよ！	","letter": "	You're smiling, you're smiling!	", "pinyin":"	わらってるだろうがくちがよ！	"},																			
"	218	":{"character":"	口の下が黒いだけだよ	","letter": "	It's just that the bottom of your mouth is black.	", "pinyin":"	くちのしたがくろいだけだよ	"},																			
"	219	":{"character":"	ホントだ口閉じてる	","letter": "	You're right, my mouth is closed.	", "pinyin":"	ほんとだくちとじてる	"},																			
"	220	":{"character":"	ね？	","letter": "	See?	", "pinyin":"	ね？	"},																			
"	221	":{"character":"	まぎらわしいヤツだな！	","letter": "	You're a fucking liar!	", "pinyin":"	まぎらわしいやつだな！	"},																			
"	222	":{"character":"	うおりゃ～っ！	","letter": "	Oooooh!	", "pinyin":"	うおりゃ～っ！	"},																			
"	223	":{"character":"	イテッ	","letter": "	Ouch.	", "pinyin":"	いてっ	"},																			
"	224	":{"character":"	やっぱ笑ってんじゃねえか！	","letter": "	I knew he was smiling!	", "pinyin":"	やっぱわらってんじゃねえか！	"},																			
"	225	":{"character":"	思わず…	","letter": "	I couldn't help it...	", "pinyin":"	おもわず…	"},																			
"	226	":{"character":"	アイツに笑われてた俺も	","letter": "	He used to laugh at me.	", "pinyin":"	あいつにわらわれてたおれも	"},																			
"	227	":{"character":"	今じゃ立派にサケが獲れるようになったんだぜ	","letter": "	But now I can catch salmon with pride.	", "pinyin":"	いまじゃりっぱにさけがえれるようになったんだぜ	"},																			
"	228	":{"character":"	あっ…って何やってんだ	","letter": "	What are you doing?	", "pinyin":"	あっ…ってなにやってんだ	"},																			
"	229	":{"character":"	えっ？ピクニックの準備	","letter": "	What? Preparing a picnic.	", "pinyin":"	えっ？ぴくにっくのじゅんび	"},																			
"	230	":{"character":"	俺が働いてるときに何だそりゃ！	","letter": "	What are you doing while I'm working?	", "pinyin":"	おれがはたらいてるときになんだそりゃ！	"},																			
"	231	":{"character":"	まぁまぁグリズリーくんがサケ獲ってお腹が空いたら	","letter": "	Well, well, well, well. If Mr. Grizzly catches a salmon and gets hungry...	", "pinyin":"	まぁまぁぐりずりーくんがさけとっておなかがあいたら	"},																			
"	232	":{"character":"	ランチができてるってわけ	","letter": "	Lunch is ready.	", "pinyin":"	らんちができてるってわけ	"},																			
"	233	":{"character":"	なかなかいいでしょ	","letter": "	That's not bad.	", "pinyin":"	なかなかいいでしょ	"},																			
"	234	":{"character":"	腹にたまるもんを頼むぜ	","letter": "	Get me something to fill me up.	", "pinyin":"	はらにたまるもんをたのむぜ	"},																			
"	235	":{"character":"	ん？サケがいねえ	","letter": "	What? There's no salmon.	", "pinyin":"	ん？さけがいねえ	"},																			
"	236	":{"character":"	何やってんだ！	","letter": "	What the hell are you doing?	", "pinyin":"	なにやってんだ！	"},																			
"	237	":{"character":"	なかなかグリズリーさんみたいにはいかないね	","letter": "	You're not as good as Mr. Grizzly.	", "pinyin":"	なかなかぐりずりーさんみたいにはいかないね	"},																			
"	238	":{"character":"	誰でもできそうに見えたのにな	","letter": "	You looked like you could do it.	", "pinyin":"	だれでもできそうにみえたのにな	"},																			
"	239	":{"character":"	いいかよく見てろ	","letter": "	Watch it, watch it, watch it.	", "pinyin":"	いいかよくみてろ	"},																			
"	240	":{"character":"	もういいや笹食べよっと	","letter": "	I'm going to eat some bamboo shoots.	", "pinyin":"	もういいやささたべよっと	"},																			
"	241	":{"character":"	そんな簡単に諦めんな！	","letter": "	Don't give up so easily!	", "pinyin":"	そんなかんたんにあきらめんな！	"},																			
"	242	":{"character":"	えっ？でも疲れちゃったしお腹空いたし…	","letter": "	What? But I'm tired and hungry...	", "pinyin":"	えっ？でもつかれちゃったしおなかあいたし…	"},																			
"	243	":{"character":"	そういう問題じゃねえ！	","letter": "	That's not the point!	", "pinyin":"	そういうもんだいじゃねえ！	"},																			
"	244	":{"character":"	同じクマとしてシロクマ！お前もコイツに何か言ってやれ！	","letter": "	As a fellow bear, Polar bear! You should say something to him too!	", "pinyin":"	おなじくまとしてしろくま！おまえもこいつになにかいってやれ！	"},																			
"	245	":{"character":"	パンダくんは竹と笹があれば満足だから	","letter": "	Panda is happy with bamboo and bamboo grass.	", "pinyin":"	ぱんだくんはたけとささがあればまんぞくだから	"},																			
"	246	":{"character":"	うん	","letter": "	Yeah...	", "pinyin":"	うん	"},																			
"	247	":{"character":"	何だと？	","letter": "	What?	", "pinyin":"	なんだと？	"},																			
"	248	":{"character":"	クマは狩りだろ狩ってこそのクマだろ！	","letter": "	Bears are meant to hunt!	", "pinyin":"	くまはかりだろかってこそのくまだろ！	"},																			
"	249	":{"character":"	タケノコだ！	","letter": "	Bamboo shoots!	", "pinyin":"	たけのこだ！	"},																			
"	250	":{"character":"	ちょっとそこでとってきた	","letter": "	I got them right there.	", "pinyin":"	ちょっとそこでとってきた	"},																			
"	251	":{"character":"	これだったらパンダくんも狩りをする気になるでしょ	","letter": "	I'm sure that'll get Panda to start hunting, too.	", "pinyin":"	これだったらぱんだくんもかりをするきになるでしょ	"},																			
"	252	":{"character":"	なるほどな	","letter": "	I see.	", "pinyin":"	なるほどな	"},																			
"	253	":{"character":"	えっサケってタケノコ食べるの？	","letter": "	Salmon eat bamboo shoots?	", "pinyin":"	えっさけってたけのこたべるの？	"},																			
"	254	":{"character":"	違う	","letter": "	No.	", "pinyin":"	ちがう	"},																			
"	255	":{"character":"	お前が食うんだよパンダ	","letter": "	You eat them, panda.	", "pinyin":"	おまえがくうんだよぱんだ	"},																			
"	256	":{"character":"	パンダくん	","letter": "	Panda.	", "pinyin":"	ぱんだくん	"},																			
"	257	":{"character":"	グリズリーくんが狩りのお手本見せてくれるって	","letter": "	Mr. Grizzly is going to show me how to hunt.	", "pinyin":"	ぐりずりーくんがかりのおてほんみせてくれるって	"},																			
"	258	":{"character":"	狩りをしてこそのクマだもんね	","letter": "	Hunting is what makes a bear a bear, right?	", "pinyin":"	かりをしてこそのくまだもんね	"},																			
"	259	":{"character":"	おおうよく見てろよパンダ	","letter": "	Oh, watch where you're going, panda.	", "pinyin":"	おおうよくみてろよぱんだ	"},																			
"	260	":{"character":"	まずは標的を見つける	","letter": "	First, I'm gonna find my target.	", "pinyin":"	まずはひょうてきをみつける	"},																			
"	261	":{"character":"	絶対に目を離さない	","letter": "	And you never take your eyes off of it.	", "pinyin":"	ぜったいにめをはなさない	"},																			
"	262	":{"character":"	獲物の動きを予測する	","letter": "	Anticipate your prey's movements.	", "pinyin":"	えもののうごきをよそくする	"},																			
"	263	":{"character":"	どうだやってみろ	","letter": "	Try it.	", "pinyin":"	どうだやってみろ	"},																			
"	264	":{"character":"	おいしいね	","letter": "	It's delicious.	", "pinyin":"	おいしいね	"},																			
"	265	":{"character":"	って食ってんじゃねえ！	","letter": "	Don't just eat it!	", "pinyin":"	ってくってんじゃねえ！	"},																			
"	266	":{"character":"	ちゃんと泳いでるタケノコをとれ	","letter": "	Get the bamboo shoots that are swimming.	", "pinyin":"	ちゃんとおよいでるたけのこをとれ	"},																			
"	267	":{"character":"	タケノコは泳がないよ	","letter": "	Bamboo shoots don't swim.	", "pinyin":"	たけのこはおよがないよ	"},																			
"	268	":{"character":"	だよね	","letter": "	Right, right.	", "pinyin":"	だよね	"},																			
"	269	":{"character":"	んなの知ってる！	","letter": "	I know that!	", "pinyin":"	んなのしってる！	"},																			
"	270	":{"character":"	イライラしないでグリズリーさん	","letter": "	Don't get upset, Mr. Grizzly.	", "pinyin":"	いらいらしないでぐりずりーさん	"},																			
"	271	":{"character":"	僕のとっておきの笹あげるから	","letter": "	I'll give you my best bamboo grass.	", "pinyin":"	ぼくのとっておきのささあげるから	"},																			
"	272	":{"character":"	笹は健康にもいいんだよ	","letter": "	Bamboos are good for your health.	", "pinyin":"	ささはけんこうにもいいんだよ	"},																			
"	273	":{"character":"	お前も食わず嫌いしてないで	","letter": "	Don't be so picky.	", "pinyin":"	おまえもくわずぎらいしてないで	"},																			
"	274	":{"character":"	サケくらい食ってみろよ	","letter": "	You should at least try some salmon.	", "pinyin":"	さけくらいくってみろよ	"},																			
"	275	":{"character":"	うんわかった	","letter": "	I'll try it.	", "pinyin":"	うんわかった	"},																			
"	276	":{"character":"	笹どう？	","letter": "	How's the bamboo?	", "pinyin":"	ささどう？	"},																			
"	277	":{"character":"	あんましうまくねえ	","letter": "	Not so good!	", "pinyin":"	あんましうまくねえ	"},																			
"	278	":{"character":"	サケのほうがうまいだろ	","letter": "	Salmon's better.	", "pinyin":"	さけのほうがうまいだろ	"},																			
"	279	":{"character":"	ん～あんまり	","letter": "	Not so much.	", "pinyin":"	ん～あんまり	"},																			
"	280	":{"character":"	いいニオイ！	","letter": "	Smells good!	", "pinyin":"	いいにおい！	"},																			
"	281	":{"character":"	コーヒー入ったよ	","letter": "	Coffee's ready.	", "pinyin":"	こーひーはいったよ	"},																			
"	282	":{"character":"	おうありがてえ	","letter": "	Oh, thank you.	", "pinyin":"	おうありがてえ	"},																			
"	283	":{"character":"	おいしいね	","letter": "	It's good.	", "pinyin":"	おいしいね	"},																			
"	284	":{"character":"	ああ	","letter": "	Yeah, it's good.	", "pinyin":"	ああ	"},																			
"	285	":{"character":"	いっぱいとれてよかったね	","letter": "	I'm glad you got a lot of coffee.	", "pinyin":"	いっぱいとれてよかったね	"},																			
"	286	":{"character":"	お前もな	","letter": "	You too.	", "pinyin":"	おまえもな	"},																			
"	287	":{"character":"	おいパンダ！こっちだ	","letter": "	Hey, panda! Come here, come here.	", "pinyin":"	おいぱんだ！こっちだ	"},																			
"	288	":{"character":"	いらっしゃい	","letter": "	Come on in.	", "pinyin":"	いらっしゃい	"},																			
"	289	":{"character":"	おかげさまで大人気ですよランチパスタ	","letter": "	Thanks to you, we're very popular. Pasta for lunch.	", "pinyin":"	おかげさまでだいにんきですよらんちぱすた	"},																			
"	290	":{"character":"	これって…	","letter": "	What's this?	", "pinyin":"	これって…	"},																			
"	291	":{"character":"	サケと…	","letter": "	Salmon and...	", "pinyin":"	さけと…	"},																			
"	292	":{"character":"	タケノコ？	","letter": "	Bamboo shoots?	", "pinyin":"	たけのこ？	"},																			
"	293	":{"character":"	昨日のお礼ね	","letter": "	For yesterday.	", "pinyin":"	きのうのおれいね	"},																			
"	294	":{"character":"	おいパンダ俺のタケノコお前にやる	","letter": "	Hey, Panda, you can have my bamboo shoots.	", "pinyin":"	おいぱんだおれのたけのこおまえにやる	"},																			
"	295	":{"character":"	グリズリーさん僕のサケあげるね	","letter": "	Grizzly, you can have my salmon.	", "pinyin":"	ぐりずりーさんぼくのさけあげるね	"},																			
"	296	":{"character":"	あ好き嫌いはダメですよ	","letter": "	Oh, and don't be picky.	", "pinyin":"	あすききらいはだめですよ	"},																			
"	297	":{"character":"	細かいこと気にするなよ	","letter": "	Don't worry about the details.	", "pinyin":"	こまかいこときにするなよ	"},																			
"	298	":{"character":"	そうそう	","letter": "	Oh, yeah.	", "pinyin":"	そうそう	"},																			
"	299	":{"character":"	もう	","letter": "	Oh, my God.	", "pinyin":"	もう	"},																			
"	300	":{"character":"	まぁいいじゃない	","letter": "	Oh, come on.	", "pinyin":"	まぁいいじゃない	"},																			
"	301	":{"character":"	ペンギンさんペンギンさん	","letter": "	Penguin, Penguin, Penguin.	", "pinyin":"	ぺんぎんさんぺんぎんさん	"},																			
"	302	":{"character":"	何？パンダ君	","letter": "	What? Mr. Panda.	", "pinyin":"	なに？ぱんだくん	"},																			
"	303	":{"character":"	ペンギンさんが今まで学んだ人生の知恵を教えてよ	","letter": "	Tell us what life wisdom you've learned so far, Mr. Penguin.	", "pinyin":"	ぺんぎんさんがいままでまなんだじんせいのちえをおしえてよ	"},																			
"	304	":{"character":"	飲み会で最後に残った一個を食べる時は	","letter": "	When you're at a bar and you're eating the last piece of leftover food.	", "pinyin":"	のみかいでさいごにのこったいっこをたべるときは	"},																			
"	305	":{"character":"	お皿を下げてもらうどさくさで食べちゃえば	","letter": "When you eat the last piece of leftover food at a drinking party...", "pinyin":"	おさらをさげてもらうどさくさでたべちゃえば	"},																			
"	306	":{"character":"	幾分気まずくないよ	","letter": "	It's a little less awkward.	", "pinyin":"	いくぶんきまずくないよ	"},																			
"	307	":{"character":"	心の底から小さい知恵だね	","letter": "	Small wisdom from the bottom of my heart.	", "pinyin":"	こころのそこからちいさいちえだね	"},																			
"	308	":{"character":"	白熊君終わろ	","letter": "	Shirokuma, finish up.	", "pinyin":"	しろくまくんおわろ	"},																			
"	309	":{"character":"	次回しろくまカフェ「Z」	","letter": "	Next time at the Shirokuma Cafe. 'Z'	", "pinyin":"	じかいしろくまかふぇ「Z」	"},																			
"	310	":{"character":"	「Z」つけないで	","letter": "	Don't put a Z' in there.	", "pinyin":"	「Z」つけないで	"},																			
"	311	":{"character":"	お楽しみに	","letter": "	Enjoy!	", "pinyin":"	おたのしみに	"},																			
}